### ISSUE TITLE
Wrong font width (maximum advance freetype2 value)

### ISSUE THREAD

**Issue by avivace** [jwilm/alacritty#1020]
debian Sid, x11

`maximum advance` via freetype2 is too wide for some fonts.

Same issue as #902 and #990 and I'm still unable to solve this.
I've tried the [workaround](https://gist.github.com/mikoim/498dfcdd39439316e3eb9b8897914302) proposed but the patch is unapplicable. I've reproduced the same modifications and applied [this](https://gist.github.com/avivace/9d3fddcb43e853d53cadbca4ed11d27e) patch. Still nothing. 

Narrow fonts like Iosevka or Pragmata Pro have this issue:
![image](https://user-images.githubusercontent.com/14352721/34877642-269e270e-f7a7-11e7-950e-bf443c7d1be5.png)

I'm currently just setting offset x to -8.0 and it looks pretty good, almost identical to my other terminal emulator.

Offsetting by `-8.0` however, causes a strange behaviour on the dimensions column  value (I have to set `1000` to see ~80 colums)

Still, what's the status of this?

**Comment by rkanati** [comment]
I'm not exactly having this problem, but when I switched to Alacritty, I noticed it seemed to make cells wider than other terminals.

For reference: this could be fixed by making the FreeType loader compute cell width like the CoreText loader currently does, i.e. the advance width of a '0'.
Or, perhaps more robustly: use the average advance width of every printable in Latin-1. libVTE more-or-less does this.
