### ISSUE TITLE
main thread panicked

### ISSUE THREAD

**Issue by scampi** [jwilm/alacritty#1039]
rust: rustc 1.23.0 (766bd11c8 2018-01-01)

```
1 ❯ RUST_BACKTRACE=1 alacritty
thread 'main' panicked at 'unhandled pixel mode: LcdV', font/src/ft/mod.rs:481:24
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: __libc_start_main
  11: <unknown>
```

Which operating system does the issue occur on?

arch linux

If on linux, are you using X11 or Wayland?

X11

**Comment by chrisduerr** [comment]
Are you using a vertical display?

**Comment by scampi** [comment]
no

**Comment by jwilm** [comment]
This is because we haven't implemented support for unpacking vertically decimated subpixel rasters from FreeType: https://github.com/jwilm/alacritty/blob/692cdef9e3104aa0d0df21608499f70e36a8b846/font/src/ft/mod.rs#L481

@scampi does your display have vertically decimated RGB sections? If not, you might want to fix your fontconfig to use `lcd` instead of `lcdv`.

**Comment by scampi** [comment]
I added this to alacritty.yml but still no change.

```
font:
  options:
    antialias: lcd
    hinting: lcd
```

@jwilm was this what you meant ?

> does your display have vertically decimated RGB sections?

No idea how to check that.
