### ISSUE TITLE
Cannot find binaries (brew, nvim, ...) after install

### ISSUE THREAD

**Issue by marco-fp** [jwilm/alacritty#1050]
Which operating system does the issue occur on?
macOS High Sierra 10.13.2 

1. Installed Alacritty and created the desktop application.
2. Opened Alacritty and found that no binaries are recongnized: brew, nvim, vim, ...

Am I missing something? Is it not loading the proper path for the binaries?

**Comment by fcvarela** [comment]
This is because it ignores /etc/paths

**Comment by marco-fp** [comment]
Thanks for the reply. Any easy fix-guide on how to solve it?

**Comment by sandersantema** [comment]
As far as I know alacritty doesn't do anything with these binaries. I believe it's handled by your shell, which reads from the $PATH variable. However you can set a default shell in the Alacritty config. ~/.config/alacritty/alacritty.yml

For instance:
`
shell:
  program: /usr/local/bin/fish
  args:
    - --login
`

If you use fish, otherwise you can figure out where your shell is located by using `which <name of shell>` don't include <>

**Comment by marco-fp** [comment]
That should do it, thank you :+1:
