### ISSUE TITLE
Different versions of ZSH being reported between the packaged app and running the binary

### ISSUE THREAD

**Issue by Andy-Bell** [jwilm/alacritty#1070]
Which operating system does the issue occur on? OS X 10.13.2

(Using alacritty built from master: commit 53a5a96fdd49975b4eb8072380a5573d8dd62263 )

When running `which -a zsh` on a non-alacritty terminal, it will report:
```
/usr/local/bin/zsh
/bin/zsh
```

To reproduce (assuming the above is true):

1. In non-alacritty terminal, start instance of alacritty
2. In this alacritty window, run `which -a zsh`
3. Check it matches the above result
4. Close alacritty window
5. Open alacritty via the 'spotlight search'
6. In this new window, run `which -a zsh`
7. Output should read only `/bin/zsh`

Somehow alacritty is using a different shell in the bundled form than when being ran as a binary. I think this is the key behind several issues I am encountering with this terminal (not respecting fonts/ unable to run certain programs/ etc.) and if it is resolvable should clear up the other issues.

**Comment by JamesDunne** [comment]
See https://github.com/jwilm/alacritty/issues/1071 that I just reported which I think is a more general cause of this issue; solution included. It appears `alacritty` by default directly spawns `bash` instead of using `login` but you can amend your config file to specify the terminal process as `login` instead.

**Comment by Andy-Bell** [comment]
Thanks @JamesDunne that has fixed this issue, closing here in favour of #1071
