### ISSUE TITLE
Support "True" (24-bit) color

### ISSUE THREAD

**Issue by abstiles** [jwilm/alacritty#109]
Many modern terminal emulators these days do better than 16 or 256 colors. Full 24-bit color would simplify color scheme configuration when working with multiple terminal applications simultaneously (as with Tmux+Vim).

It's not clear whether this is already supported or already planned.

**Comment by jwilm** [comment]
24-bit color is supported. You may need to add something like this to your vimrc:

```viml
execute "set t_8f=\e[38;2;%lu;%lu;%lum"
execute "set t_8b=\e[48;2;%lu;%lu;%lum"
```

**Comment by polyzen** [comment]
@jwilm, I'm also having this issue.

Shot with alacritty on left: https://ptpb.pw/SuMX.png

Relevant vimrc lines: https://github.com/polyzen/dotfiles/blob/desktop/.vim/vimrc#L19-L21

Commit: 8d3f5f4e179b6fe55617dc72fe60fa1bdfd9b014

**Comment by fantastic16** [comment]
More thorough details here:
`~/.tmux.conf`:
```tmux
set -g default-terminal 'screen-256color'
set -ga terminal-overrides ',*256col*:Tc'
```

`~/.vim/vimrc` (or `~/.vimrc`):
```vim
if exists('+termguicolors')
  let &t_8f="\<Esc>[38;2;%lu;%lu;%lum"
  let &t_8b="\<Esc>[48;2;%lu;%lu;%lum"
  set termguicolors
endif
```

**Comment by elquimista** [comment]
More thorough details here:
`~/.tmux.conf`:
```tmux
set -g default-terminal 'screen-256color'
set -ga terminal-overrides ',*256col*:Tc'
```

`~/.vim/vimrc` (or `~/.vimrc`):
```vim
if exists('+termguicolors')
  let &t_8f="\<Esc>[38;2;%lu;%lu;%lum"
  let &t_8b="\<Esc>[48;2;%lu;%lu;%lum"
  set termguicolors
endif
```

**Comment by sakhnik** [comment]
This doesn't work for me anymore in Arch Linux. The current version is 0.2.9. I tried in 0.2.8 too, didn't work.
True color is rendered just fine without tmux, but fails when tmux is launched. What's the advised configuration currently?

**Comment by codebam** [comment]
I'd argue this is still an issue, however it might not be an issue with Alacritty? When TERM is set to `alacritty` because the terminfo file is installed you don't get 24 bit color in tmux. Changing your TERM to xterm-256color in `alacritty.yml` fixes this but then you lose out on whatever alacritty specific features/formatting options that terminfo file gives you.

**Comment by m-wells** [comment]
I'm also on Arch Linux.

Adding the following to your `bashrc` (or the equivalent statement to your specific `*rc` file)
```
alias tmux='TERM=screen-256color tmux'
```
preserves `TERM=alacritty` outside of `tmux` and enables true color inside.
`.tmux.conf` should contain
```
set -g default-terminal 'screen-256color'
set -ga terminal-overrides ',*256col*:Tc'
```

**Comment by SicariusNoctis** [comment]
This post is for those who are looking for *RGB color*.

Set your `tmux.conf` as follows: 

```tmux
set  -g default-terminal "tmux-256color"
set -ag terminal-overrides ",alacritty:RGB"
```

**Restart tmux.**

This test script should now output nice smooth gradients:

```bash
curl -s https://gist.githubusercontent.com/lifepillar/09a44b8cf0f9397465614e622979107f/raw/24-bit-color.sh >24-bit-color.sh
bash 24-bit-color.sh
```

![](https://i.imgur.com/0coRgxd.png)

----

**Optional:**

If you want your tmux configuration to work with other terminal emulators, you can add this to `alacritty.yml`:

```bash
env:
  TERM: xterm-256color
```

...though you might lose some features. (I believe `terminfo` will no longer tell applications about all the great features alacritty has.)

**Comment by Julian** [comment]
The last comment mostly worked for me, with 2 differences --

Firstly that I was surprised that the Homebrew cask didn't itself install the terminfo file, though that appears documented [in the readme](https://github.com/jwilm/alacritty#macos). Instead of running it with `sudo` I ran it with my own user and that seems to also work.

Second, using `set  -g default-terminal "tmux-256color"` was causing `git diff` to complain that "terminal is not fully functional" for me, so I went back to `screen-256color", and now I appear to properly have 24-bit color both inside and outside of Alacritty using that bash script above.

**Comment by NilsIrl** [comment]
> _RGB color_

What's the difference between RGB and TrueColor? Which one should I choose?

**Comment by kchibisov** [comment]
`Tc` is a tmux extension, `RGB` is +- standard thing.

**Comment by NilsIrl** [comment]
> `Tc` is a tmux extension, `RGB` is +- standard thing.

since

```
set -ga terminal-overrides ",alacritty:RGB"
```
and 
```
set -ga terminal-overrides ",alacritty:Tc"
```

give the same result (to my eyes), would `RBG` be better?

**Comment by kchibisov** [comment]
https://github.com/tmux/tmux/wiki/FAQ read `How do I use RGB`. So they are equal tbh.

**Comment by uunnxx** [comment]
> > _RGB color_
> 
> What's the difference between RGB and TrueColor (Tc)? Which one should I choose?

(TrueColor === RGB)

TrueColor is 24 bit ->  ~16M colors
RGB is 24 bit too ->    ~16M colors
000000 (rgb: black) color is 24 bit:

red color:      00(hex) -> 8 bit
green color:  00(hex) -> 8 bit
blue color:    00(hex) -> 8 bit
-------------------------------------- 24 bit

**Comment by rpearce** [comment]
> More thorough details here:
> `~/.tmux.conf`:
> 
> ```shell
> set -g default-terminal 'screen-256color'
> set -ga terminal-overrides ',*256col*:Tc'
> ```
> 
> `~/.vim/vimrc` (or `~/.vimrc`):
> 
> ```viml
> if exists('+termguicolors')
>   let &t_8f="\<Esc>[38;2;%lu;%lu;%lum"
>   let &t_8b="\<Esc>[48;2;%lu;%lu;%lum"
>   set termguicolors
> endif
> ```

elquimista's tmux & vimrc termguicolors info fixed this for me. Everything's looking great now with Dracula in neovim!

**Comment by jpcirrus** [comment]
All I had to do to get this to work with Alacritty 0.10.1 and tmux 3.3a (with: `set-option -s default-terminal tmux-256color`) was to change the value of `TERM` in  `alacritty.yml`:

```yaml
env:
    TERM: alacritty-direct
```

**Comment by pabloab** [comment]
I tested Alacritty 0.10.1 with [this _test-drive_](https://hellricer.github.io/2019/10/05/test-drive-your-terminal.html). A lot of features lacking but some are issues related to tmux, like this one or making font _italic_:

- 24-bit (true-color): Tune tmux [Supported](https://github.com/alacritty/alacritty/issues/109#issuecomment-271021919)
- text decorations
  
  
  - italic: Supported (tune tmux)
  
  
  - double underline: [Supported since v0.11.0](https://github.com/alacritty/alacritty/issues/4142#issuecomment-682318799)
  - this is also double underline: To be tested
  - curly underline: **Not supported**. No issue opened?
  - colored underline: **Not supported** ([but will](https://github.com/alacritty/alacritty/pull/4660#issuecomment-1069322394))
  
  
  
  
  - overline: **Not supported** ([but will](https://github.com/alacritty/alacritty/pull/6123))
- bitmap emojis
  - 😃😱😵: **Not supported** No issue opened?
- right-to-left ('w' symbol should be at right side)
    - [**Not supported**](https://github.com/alacritty/alacritty/issues/663)

![image](https://user-images.githubusercontent.com/657836/193739679-899f04d2-9545-4dbb-89d0-4d17fdd87d83.png)

**Comment by kchibisov** [comment]
@pabloab most of the things you've mentioned here are supported.

Some of them are explicitly rejected though.

![picture](https://user-images.githubusercontent.com/27620401/193745019-837cb34c-7f22-4a87-9dc0-3fd95d32aff3.png)


For example text decorations won't change, since all sort of standard escapes we support. RTL is also an unlikely to happen I guess and sixel is also questionable.

**Comment by hasufell** [comment]
I tried all of the suggestions, including the ones here: https://stackoverflow.com/questions/10158508/lose-vim-colorscheme-in-tmux-mode

Not a single one worked.
