### ISSUE TITLE
Create twitter handle for updates and changes.

### ISSUE THREAD

**Issue by 00imvj00** [jwilm/alacritty#1103]
This less of an issue and more of a request.

I am really interested in `Alacritty`, but lack of information update whats new and new updates and stuff is kinda making me not to use. because i am always waiting for the stable version. So, if possible, please create twitter handle for `alacritty` to provide updates about project and production use cases and some `config` tricks. 

sorry, for raising the issue, but I couldn't find any other place to put this request.

**Comment by chrisduerr** [comment]
I'm not a fan of this proposal, I think a twitter handle would have little benefit. It's always possible to subscribe to certain issues if you want to keep track of them.

However once a more steady release cycle is reached, it might be useful to create a changelog and keep that updated.

**Comment by chrisduerr** [comment]
I think the new CHANGELOG file should resolve problems with not knowing exactly what changed in the recent versions of Alacritty.

New releases should also advertise new versions on github, see #80 for tracking that.

Jwilm has also created two blog posts already for the major Alacritty updates, you can find it on jwilm.io and it also links to his twitter handle, where you should be able to see when new blogs are released.

The subreddit /r/alacritty exists, however it is not active. However if you want to see more activity there, feel free to contribute.

If you want to discuss Alacritty, ask questions and follow the current development, the #alacritty IRC channel is also available and always active.

I think all these channels should provide sufficient means to stay up-to-date with Alacritty. Also please note that any additional channels always introduce additional work which can't be put into improving Alacritty itself. I'm not active on Twitter at all for example, so that wouldn't be an option for me. However I think that the channels Alacritty provides are sufficient for getting informations about all important changes.
