### ISSUE TITLE
Fails to build with incremental compilation turned on

### ISSUE THREAD

**Issue by jonathandturner** [jwilm/alacritty#1115]
Which operating system does the issue occur on?

macOS

```
Jonathans-MacBook-Pro:alacritty jonathanturner$ cargo build --release
   Compiling alacritty v0.1.0 (file:///Users/jonathanturner/Source/alacritty)
error: can't perform LTO when compiling incrementally
```

That's with CARGO_INCREMENTAL="1".  Since incremental compilation will likely be the default in the future, this is probably worth fixing.  (of course, I might have something wrong in my own configuration that's causing it...)

**Comment by chrisduerr** [comment]
This is probably due to the `lto = true` in the `Cargo.toml` file under release settings. I'd say that for a release profile `lto` is more important than incremental compilation though. Especially when we're shipping binaries in the future.

If you want to disable `lto` to make use of incremental compilation, it should be simple to edit the config file for that.

**Comment by jonathandturner** [comment]
Right - being able to configure it is definitely important.  I noted at the bottom that incremental will soon be the default at least for Debug (and maybe also Release?).  If that happens, alacritty may end up having issues compiling with more recent nightlies.  

I guess this issue is more of a heads up more than anything.  Thanks for the tip.

**Comment by chrisduerr** [comment]
Yeah if anything should actually break, the builds will show that and we can just act upon it. Right now I don't see much reason to act.

**Comment by peddermaster2** [comment]
Sry for my comment on this closed issue. But with the most recent rust nightly I have this problem now. I did not set `CARGO_INCREMENTAL="1"` so it must be the default by now.  
Maybe it is time to act now.

**Comment by chrisduerr** [comment]
@peddermaster2 I would have thought they'd change this to automatically imply `incremental = false` once this lands for releases, but looks like that's not the case for nightly? Which is odd since this would qualify as a breaking change imho.

I've written a PR to fix it here: https://github.com/jwilm/alacritty/pull/2081.

No matter what happens in stable, this should keep us on the safe side.
