### ISSUE TITLE
How to install with snap

### ISSUE THREAD

**Issue by variadico** [jwilm/alacritty#1121]
I noticed you have a `snapcraft.yaml` file in your repo.

But, searching in the terminal for alacritty shows this.

```
$ snap search alacritty
No matching snaps for "alacritty"
```

Is a snap install supported?

**Comment by chrisduerr** [comment]
I don't think installing through snap works right now. This might change with #927.

**Comment by BobbyWibowo** [comment]
From what I can see, the snap isn't being actively updated? `snap info alacritty` gave me 0.2.0 in stable channel (oddly 0.1.0 in edge), but latest release in this repo was already 0.2.4.

**Comment by chrisduerr** [comment]
@BobbyWibowo I am not aware of who's maintaining that snap. So it's that third party you'd have to contact if there's any problems with it I believe.

**Comment by simos** [comment]
First all all, there is a issue with snapcraft that does not allow to build the snap package at the moment, https://bugs.launchpad.net/snapcraft/+bug/1809259
This means that I cannot test at the moment.

Second, there is this (in the works?) policy for snap packages, https://github.com/Lin-Buo-Ren/snapcrafters-template-plus
This means that either the maintainer manages the releases of alacritty, or someone else does it from the snapcraft community.
Actually, nowdays it's quite simple to manage the snap package releases because there is a build server at https://build.snapcraft.io You can setup alacritty to build automatically the snap packages. 
Then, you can release through https://snapcraft.io (there is a snap package manager).

**Comment by chrisduerr** [comment]
There currently is no intention to maintain an official Alacritty snap.
