### ISSUE TITLE
URL recognition

### ISSUE THREAD

**Issue by spikebike** [jwilm/alacritty#113]
Other popular linux terminals often have a feature when you mouse over a URL it highlights and you can right click to open them in a browser.  I believe this is often referred to as "dingus click".  I find it a very handy feature.

**Comment by lord-re** [comment]
a left click on an url to open it in a configured browser would be very nice.

**Comment by casey** [comment]
It would be interesting to implement this by allowing the user to supply a series of rules consisting of a pattern and an action.

For example:

```yaml
rules:
  'https://[^\s]+': firefox {0}
  '([-_0-9a-zA-Z/]+):([0-9]+)': some-ide {1} --line {2}
```

The key for a rule is a regex to match under the cursor, and the value of the rule shows the command line to run when it matches, with {N} representing capture groups of the matched regex to substitute into the command.

This is roughly how the the Plan 9 plumber works, so no credit due to me for this idea:

https://en.wikipedia.org/wiki/Plumber_(program)
http://man.cat-v.org/plan_9/6/plumb
http://doc.cat-v.org/plan_9/4th_edition/papers/plumb

It seems like there are probably many useful features of the form "When I click on text that looks like this, do something specific." of which clickable URLs are a special case, so solving this in a general way may be advantageous.

**Comment by casey** [comment]
Some other ideas:

- Go to github issue or pull request when clicking on something of the form '#[0-9]+'
- Open a commit in a gitk / some other repo viewer when clicking a commit hash '[a-f0-9]{40}'

**Comment by trqx** [comment]
could also be dealt with external pipe?
see this st patch http://st.suckless.org/patches/externalpipe

**Comment by shawncplus** [comment]
As someone that uses irssi inside tmux as a chat client this a pretty big missing feature. Every time I want to click on a link I have to detach my tmux session, open gnome terminal, reattach, click the link then detatch gnome terminal, reattach in alacritty.

**Comment by Flat** [comment]
Is there a reason you can't just copy the link in irssi and paste it into your browser for the time being? That work flow seems a little convoluted.

**Comment by jwilm** [comment]
@Flat that's my strategy for the time being :)

**Comment by shawncplus** [comment]
@Flat When using tmux the mouse controls are taken over so selecting text selects it for tmux selection mode, not to the system clipboard.

**Comment by Flat** [comment]
@shawncplus you can set tmux to copy to the system clipboard for example `bind-key -n -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe 'xclip -i -sel p -f | xclip -i -sel c'` in your .tmux.conf I'm pretty sure holding shift also works for alacritty.

**Comment by casey** [comment]
Here's an interesting crate for finding URLs in text:

https://github.com/robinst/linkify

**Comment by P4Cu** [comment]
I guess that should have a lable : "T - enhancement"

**Comment by guiniol** [comment]
If I may, I would really like that feature to be accessible through a keyboard shortcut rather than the mouse.
There are two workflows which work for this:
- one urxvt extension does this by: you press a key combination, it highlights the latest url, you can press up/down (or j/k) to select other urls, and enter to open it (or y to copy it)
- termite does that by: you press a key combination, termite creates annotates each url with a number and there is a prompt, you type the number into the prompt and enter to open (there's another key combination to start the copy mode instead).

**Comment by maximbaz** [comment]
To add to your list, there is also a tmux plugin for this: https://github.com/tmux-plugins/tmux-copycat

Although, unfortunately it broke with the release of tmux 2.4+ and [still hasn't been fixed](https://github.com/tmux-plugins/tmux-copycat/issues/109), so it is not a viable solution at this moment 😞

**Comment by guiniol** [comment]
I didn't know about this plugin (I was using an older one), but I don't use tmux on my local box usually, so I'd rather have it in the terminal.

**Comment by ibrokemypie** [comment]
Any progress?

**Comment by chrisduerr** [comment]
I've created #1617 as an initial implementation of this feature. To keep the github issues small and concise, I've marked the PR to close this issue and created #1618 for further work on this topic.

**Comment by chrisduerr** [comment]
@sudo-nice There's this issue which seems to provide similar functionality: https://github.com/jwilm/alacritty/issues/1615.

However there have been several discussions about making it possible to use the keyboard more to search the buffer or select text, I believe there are already issues open for these (like #262).

**Comment by noobymcnoob** [comment]
localhost doesn't seem to be recognized afaict.
