### ISSUE TITLE
Investigate `update_lines` performance optimizations

### ISSUE THREAD

**Issue by jwilm** [jwilm/alacritty#114]
http://github.com/libcg/vcat
https://twitter.com/libcg/status/817507201291980801

**Comment by lord-re** [comment]
Using **mpv -vo tct** will output something watchable (especially with a tiny font) and with sound.
You can see if drops frame or not while playing.

**Comment by chrisduerr** [comment]
I've tested this using mpv and vcat and ran perf on mpv with a movie at a font size of 5 for a while. This font size was just readable enough for me to make out that Alacritty dropped some frames, however things still were reasonably smooth and it shouldn't be too tough on mpv.

Looking at the output, mpv itself was certainly working hard already, but the result provided some interesting insights into things that could be optimized at small font sizes (or large grid sizes).

Some things standing out to me were that one of the hottest regions was the following:
https://github.com/jwilm/alacritty/blob/master/src/display.rs#L446-L452

While the `render_cells` call here makes a lot of sense as something that will take a huge part of the load, the `update_lines` call isn't in the greatest place here and optimizations to it might be beneficial.

**Comment by chrisduerr** [comment]
Something worth noting should be that `mpv` probably isn't the best thing to test this, since it needs to do a lot of work itself.

The cacafire program is something I've used before that seems to really stress Alacritty at smaller fonts and its implementation should be a little more straight-forward. So looking into that could provide some more insights.
