### ISSUE TITLE
Should be able to set scrollback history to zero to disable it.

### ISSUE THREAD

**Issue by jwilm** [jwilm/alacritty#1150]
I am not sure if this works, but it should certainly be tested and fixed as needed.

**Comment by chrisduerr** [comment]
I've manually tested it and it seems to work just fine.

**Comment by chrisduerr** [comment]
Actually after playing with one of my scrollback branches it consistently crashed for me with 0 scroll history. So I probably did something wrong when testing it and it worked.

**Comment by chrisduerr** [comment]
This actually breaks for values bigger than 0 too. With my tested screen size I had to at least have a history size of 3 to make it work.

**Comment by jwilm** [comment]
> This actually breaks for values bigger than 0 too. With my tested screen size I had to at least have a history size of 3 to make it work.

That's not surprising. Hopefully we can find an elegant implementation that satisfies all values of scrollback length.

**Comment by chrisduerr** [comment]
Well we can definitely find an unelegant solution (setting the scrollback history to always at least 100 and then just disabling scrolling), but yeah there should be a way to actually solve these issues.

**Comment by jwilm** [comment]
hah, that would certainly get it out the door sooner :P

**Comment by chrisduerr** [comment]
Currently it seems like the scrollback history size is based on the initial window size plus the initial history size, so when the history length is set to 100 in the config and the initial window is 24 lines high the history will always be 124 lines long.

This is currently causing the issue with setting the scrollback to 0, when fixing the initial negative usize panic, the error that you will run into looks like this:
![Bug](https://u.teknik.io/ShAHt.png)

Having what I said initially in mind, this makes sense. The scrollback history is based on the initial size of the terminal + the scrollback size, so since the scrollback size is 0, the size of the grid will be set to the initial window size. Since the grid is smaller than the window now, the terminal is "repeated" at the top.

This will probably also break `live-config-reload` because based on my testing it does not seem like it is possible to change the scrollback size at runtime.

At this point I'm not entirely sure how to fix this so I thought I'd just write this out first. It will probably require some changes to how scrollback history size works. I'll keep playing around with this though, so if I can find out any more and make this work I'll send a PR, but if someone else has an idea this might help getting you started.
