### ISSUE TITLE
Doesn't build on osx. 

### ISSUE THREAD

**Issue by davidawad** [jwilm/alacritty#1212]
Which operating system does the issue occur on?
using latest macosx, 2017 13 inch macbook pro with out the touchbar. 
fish shell.
rust version
```
rustc 1.24.1 
```

I compiled the repo following the instructions in the readme and the result looks like this when running the application. 

<img width="1440" alt="screen shot 2018-03-29 at 11 21 46 am" src="https://user-images.githubusercontent.com/4019054/38097601-cd3c32a4-3343-11e8-83fe-971b2b396c7f.png">

**Comment by sodiumjoe** [comment]
using default `.alacritty.yml`? Any output from doing `cargo run` or  failing that, from `RUST_LOG=alacritty=debug cargo run`?

**Comment by chrisduerr** [comment]
Since there has been no feedback on this issue and it does work on multiple macOS versions, I'm closing this as resolved.

If you should still run into this problem, please make sure that you have the latest Rust version installed (ideally with `rustup`). And if you run macOS 10.12 or lower, please try running https://github.com/jwilm/alacritty/pull/1605 instead.
