### ISSUE TITLE
Scrollback memory pre-allocation and optimization

### ISSUE THREAD

**Issue by maximbaz** [jwilm/alacritty#1236]
Arch Linux, X11

Please see this message by @mpe: https://github.com/jwilm/alacritty/issues/241#issuecomment-379426780

> @maximbaz thanks for looking at it.
>
> Measuring memory usage is complicated, because of shared pages etc. But your measurement using RES - SHR is probably better than mine which was just looking at RSS.
>
> I'm also running with scrollback enabled, and it seems I actually had 20,000 lines configured.
>
> So in that case I see RES ~= 130MB and SHR ~= 20MB for 90MB in total.
>
> **It's the scrollback size which accounts for most of the memory usage.**
>
> If I reduce scrollback to 100 lines, I see numbers that more or less match yours in htop.
>
> So the question is why is scrollback using so much memory? If I compare a few values (all at startup):
>
> ```
> Lines   RES  SHR
> 100,000	535M 19M
>  20,000	131M 19M
>  10,000	 82M 19M
>   1,000	 36M 19M
>     100	 32M 19M
> ```
>
> Each extra line of (empty) scrollback is using ~5K of memory?

I did my own measurements too:

* alacritty master, tmux with 20,000 lines of history configured:

    ```
    When               What         RES      SHR
    On startup         tmux         4248     3120
    After `$ tree /`   tmux         33964    3120
    ```

* alacritty scrollback, with 20,000 lines of history configured:

    ```
    When               What         RES      SHR
    On startup         alacritty    191M     20856
    After `$ tree /`   alacritty    191M     20856
    ```

My summary:

1. Tmux starts very light, while alacritty pre-allocates huge amount of memory. Can this pre-allocation be avoided? I start many instances of alacritty often, most of them will not have huge scrollback history.
1. Tmux consumes 34MB with 20k lines of history, alacritty eats 191MB for the same size. Can this be optimized?

**Comment by chrisduerr** [comment]
This is because the complete scrollback buffer is allocated at startup and filled with empty lines.

You can see the code which does this here:
https://github.com/jwilm/alacritty/blob/scrollback/src/grid/mod.rs#L117-L126

**Comment by maximbaz** [comment]
Aha, there is even a `TODO` for implementing a delayed allocation - good! And now we have a ticket tracking that `TODO` 😉 

But I'm also curious about the memory size, how come tmux can fit the same amount of history in less than 20% of what alacritty needs? Tmux additionally allocates `34-4=30MB` of memory for the scrollback of `20,000` lines, while alacritty allocates `192-32=160MB` of additional memory.

**Comment by chrisduerr** [comment]
I don't think the current version of alacritty is super optimized on memory usage. I haven't profiled it myself but I'm sure there could be some improvements made.

As far as I know alacritty stores an empty cell for every LinexColumn in the terminal right now, so it's gonna allocate a lot of "useless" information that the user can't see.

**Comment by matrixik** [comment]
Just one more data point (I'm not using alacritty now). I have scrollbar set to 1 000 000 lines now because I hit 100 000 too frequently in at last one terminal. I works mostly with logs and metrics.

**Comment by chrisduerr** [comment]
It's always dangerous to call a workflow "incorrect", but I wonder if there's a better solution for handling a usecase where the history frequently fills up with such a large number of lines.

With log files for example I'd recommend using something like `less`. It would probably allow easier navigation and search too, since Alacritty's scrollback buffer currently isn't searchable.

I think the situation of large scrollback buffers can definitely be improved in the future, but even if the memory is dynamically allocated, if the 1 million lines are completely filled, that will not make any difference. Offloading to a file would be a potential solution for something like that, but it would introduce a lot of additional complexity and require synchronization. So that's probably far, far in the future, or potentially completely out of scope.

Reducing the actual storage size by trimming down on things like the cell or row size would always be an option, with a million lines even a difference like u64 vs u32 for every row can already cause a memory consumption of multiple megabytes. If this affects every cell there's definitely going to be a large impact. However Alacritty definitely isn't completely wasteful in this area, so it's not a super simple optimization to make.

At the end of the day Alacritty's goal is still performance though, so when offloading more stuff into memory significantly improves performance, but makes large history buffers less feasible, Alacritty's choice would probably be the performance improvement. Hopefully there's going to be a solution that helps out everyone, but that's not always simple.

It's always appreciated if people with different workflows and experiences are available to test out changes though. So if there's any updates or potential PRs to improve this situation, I'll add a comment here.

**Comment by nixpulvis** [comment]
> I wonder if there's a better solution for handling a usecase where the history frequently fills up with such a large number of lines.

As I see it there's only one, reasonable way to limit the size of the history buffer, and that's by setting the line limit to something within your liking (0 turns scrollback off). Otherwise it's just a matter of time before my history will be full. **I think what you're saying is that people should probably set their scrollback length smaller than they might otherwise want, and instead use things like `less` for cases where they need more.**

I think (as with everything) there are plenty of ways we can avoid the memory footprint as @chrisduerr touched on already, though generally there's contention between speed and space. I'm curious how other terminals handle these kinds of things.

**Comment by haarp** [comment]
Why compromise?

In my use case, I have plenty of short-lived terminal sessions. It makes no sense to allocate hundreds of MB whenever one of them starts. But when I *do* end up having lots of log, I want to be able to review that, and not have to go back, increase the buffer, then restart my command.

In short, I want to have my cake and eat it too. Which is exactly why dynamic allocation would be the best. On top of other possible optimizations, as already mentioned in this bug.


Come to think of it, would it be possible and/or make sense to keep the scrollback buffer in video memory?

**Comment by haarp** [comment]
Heh, well, if it gets to the point that you're dealing with millions of lines, you're really better off finding another way. I can't even imagine dealing with that in a terminal emulator. Maybe an upper limit of 100k lines would be sensible?

**Comment by chrisduerr** [comment]
Yeah, up to 100k should not be a problem and based on my testing it shouldn't mess anything up. However @matrixik was explicitly talking about how 100k wasn't enough and he usually uses 1 million lines. So my comment was specifically aimed at that usecase, for everything up to 100k I think we can find a solution where you get to have your cake and eat it too. :)

**Comment by haarp** [comment]
Thank you! Some quick initial tests show that the commit makes a difference. Memory usage per fresh terminal is down to around 30MB and startup time noticeably improved.

**Comment by McUsr** [comment]
Hello.

Thanks for a great terminal emulator.

Apologies in advance, for probably asking the question in the wrong place, but this thread popped up when asking the question in Google:

I'm just curious, is there a way to save the scrollback buffer to a file, so I can open it with less, or is it some other way to open the scrollback buffer with less?

Thanks.

**Comment by kchibisov** [comment]
What you want is https://github.com/alacritty/alacritty/issues/1615
