### ISSUE TITLE
Empty titlebar option

### ISSUE THREAD

**Issue by voider1** [jwilm/alacritty#1255]
I'd like there to be an option for the titlebar to be empty. I'm going to open a PR for this myself pretty soon. Just letting everyone know.

**Comment by jwilm** [comment]
Could this be accomplished with `dynamic_title: false` in the config and passing `--title ""` for the program arguments?

**Comment by sodiumjoe** [comment]
@jwilm I just tested and yes it does work at least from `cargo run -- --title=''` on macos. It's not clear to me how to do that from the packaged app binary though.

**Comment by voider1** [comment]
@jwilm Like @sodiumjoe said, it's not really clear how to do it from the packaged app. Also when you're going to distribute binaries no one will be running Alacritty with Cargo. We all just want to point and click. So I think having an option in the config is useful.

**Comment by chrisduerr** [comment]
At least in the Linux `.desktop` it should be absolutely trivial to change the command line parameters. I'm sure it's also possible in the app file. You don't need to run `cargo` to pass the `--title ''` flag, it's part of alacritty's command line arguments.

**Comment by voider1** [comment]
It is. @jwilm Thoughts?

**Comment by chrisduerr** [comment]
It has been mentioned before that it would be nice to override config settings from the command line, would be possible to use something like `--option "window.padding.x" "3"` or similar.

We could then remove flags like `--live-config-reload` because it's already a config option and could be overwritten using that.

The only thing that should only me command line parameter are probably `--ref-test`, `--help`, `--version` and `--config-file`.

Maybe this can be further discussed in an RFC?

**Comment by chrisduerr** [comment]
Since there seems to be a "reasonable" way to get this working I'm closing this issue.

Further comments about moving the `--title` option into the configuration file can be shared in the RFC: 1258.
