### ISSUE TITLE
Remove "Error: target STRING not available" message

### ISSUE THREAD

**Issue by AlmightyFloppyFish** [jwilm/alacritty#1299]
Which operating system does the issue occur on?
Arch x64

If on linux, are you using X11 or Wayland?
X11

If you paste in terminal without having anything copied it automatically pastes this overly long message instead. It's just anoying and serves no purpose. Make it just paste "?" or nothing at all like all other terminal emulators.

**Comment by chrisduerr** [comment]
I don't think this is something which is directly setup in Alacritty, at least I can't find anywhere in the codebase that would specify a string like that. Might come from our pasting dependency.

How does that even happen though? In which case do you have nothing in your selection clipboard?

**Comment by jwilm** [comment]
This will be easy to resolve when we don't exec `xclip`.

**Comment by AlmightyFloppyFish** [comment]
> In which case do you have nothing in your selection clipboard?
After you've booted the OS up untill the point where you copy something.

You're right, it's probably from xclip and not from alacritty itself.

**Comment by francesca64** [comment]
So Alacritty just uses `xclip` under the hood? That sounds pretty sketchy. Adding clipboard handling to winit shouldn't be hard at all (on X11, it's implemented the same way as drag and drop, so it would probably only take me a matter of hours; I'd also expect other platforms to be simpler than X11). It's just that no one's designed an API for it.

**Comment by jwilm** [comment]
@francesca64 indeed it is. We actually have [an old PR](https://github.com/jwilm/alacritty/pull/522) which adds real X11 clipboard support via `xcb`, but it never landed due to some minor differences in behavior.

I have put a little bit of thought into a clipboard API for `winit`. Reader beware, the following discussion is opinionated!

Starting with prior art, `GLFW` offers a limited clipboard API:

```c
void glfwSetClipboardString (GLFWwindow *window, const char *string);
void glfwGetClipboardString (GLFWwindow *window);
```

My minimal research suggests there is no support for copy or paste events, just an API for manipulating the clipboard string. This API would not be sufficient for Alacritty since on X11 we access both the _primary selection_ buffer and the _clipboard_ buffer. Other applications may not care about that.

One additional wrinkle is that it would be nice to have built-in support for the `Copy` and `Paste` menu items on platforms like macOS. Paste in that case could presumably be supported as an event variant with data, and copy could invoke some callback. Many applications enable or disable copy and paste modally and grey out the menu items under certain conditions.

I get the feeling that supporting the system copy/paste menu and actions is quite a rabbit hole -- at least for now. Assuming `winit`wants to avoid that for now, that puts the discussion at a point of "how does winit support a basic clipboard access API, and should it?"

I don't have an answer for what a winit API should look like, but I can offer what Alacritty's [`copypasta` API](https://jwilm.io/docs/copypasta/copypasta/) provides. Should winit offer a clipboard API? I have mixed feelings about this. On one hand, it means consumers don't need to pull in another dependency. On the other hand, it adds to the scope of winit something that can easily be outsourced to another crate. Couple this with the fact that `winit` may not want to immediately provide any deeper clipboard integrations as discussed above and my opinion moves firmly into "no it shouldn't" territory.

One thing I haven't considered is Wayland support which may make for a compelling reason to include the API in winit, but I don't know enough to comment either way.

For now, this project is happy to continue using a library in addition to `winit` to get clipboard support (really need to fix that xclip dependency, though).

**Comment by francesca64** [comment]
I think it's a good idea not to make winit the one true source of platform glue, though I'd need to split out winit's X11 util module into its own library for that to be practical. I've already thought of what I'd name the crate, so the hardest part is taken care of.

**Comment by nixpulvis** [comment]
FWIW, I'm in favor of fixing this issue (as title describes) before diving deep into a better solution for copy/paste. It's a bit confusing if you don't know that it's a bug.

**Comment by ddevault** [comment]
It should be easier to handle the clipboard properly on Wayland, for what it's worth.

**Comment by bendik** [comment]
For anyone who just want this to "work" https://github.com/brunelli/wl-clipboard-x11
