### ISSUE TITLE
Performance: Kitty is on par without sacrificing things like tabs & modern features

### ISSUE THREAD

**Issue by anirudhb** [jwilm/alacritty#1309]
### *important(maybe):* system specs
-------

Arch Linux (VirtualBox) 4GB ram
i3 + polybar

-------

Usually, Alacritty was about ~0.5 sec faster than Kitty, but Kitty provided scroll back and ligatures, tabs & windows, image protocol, mouse protocol, extensibility, etc.
Given this, it does seem Alacritty is the fastest terminal, but Kitty provides much more for a small performance cost.

**Comment by chrisduerr** [comment]
Disregarding the benchmarks you've run, I don't see how this is relevant. If you feel like the goals of Kitty are more aligned with your personal preferences, why not support Kitty, it's a great terminal emulator.

Alacritty is still in an ***alpha*** state and some things like scrollback will come without any question. Other things like ligatures will potentially be added if once someone gets around to implemeting them. I don't quite see what "modern features" are for you, but other things like tabs are often just better done by other applications, even when there might be an implementation that does not affect speed/resource usage at all, it's still code and complexity that has to be added and maintained. So I think a lot of people that use alacritty are simply not looking for some of these features and would rather see the development focus in other aspects of the terminal emulator.

This is just my personal opinion, maybe @jwilm thinks differently about this, but I don't see why alacritty should just pick up the goals of a different terminal emulator in an attempt to outplay it at their own game. It seems like a healthier competition when alacritty instead goes for their own goals instead of copying others.

**Comment by jwilm** [comment]
@chrisduerr :100: 

This is exactly right. And just to reiterate the main point, things like tabs/windows/etc are just not in scope for this project. We are planning to offer an embedding API for applications which wish to take advantage of Alacritty's focus on simplicity and performance to build derivatives with whatever additional features they please.

**Comment by anirudhb** [comment]
OK. Thanks for clarifying!

**Comment by quininer** [comment]
Kitty doesn't even support System IME.
