### ISSUE TITLE
Decoration free windows can't be resized after glutin 0.16

### ISSUE THREAD

**Issue by cconger** [jwilm/alacritty#1345]
Which operating system does the issue occur on?
MacOS 10.12.6 (16G1314)

After updating building and launching the release build after the glutin update I am unable to resize the window either through conventional edge grabbing nor through window management tools.

Reverting to the build immediately prior to the glutin update resolved the problem.

I understand this might be a regression in an upstream library.

**Comment by pappasam** [comment]
Which operating system does the issue occur on?
Linux Mint 18.3
Dell XPS 15
GPU Driver: Nvidia-387

I have a similar issue related to decoration-free windows with the latest master. When resizing my window using Super+Arrow Keys, the window would randomly turn transparent. Additionally, if I type "AA" at my bash prompt, only the first A will show up; input seems to be disappearing somewhere.

Things seem to work fine by setting window: { decorations: true }

**Comment by francesca64** [comment]
@cconger 

Hm, this is unfortunate; since Alacritty jumped forward by like 5 winit versions at once, it's hard to say exactly when that broke. @sodiumjoe do you know when I broke this?

@pappasam
> When resizing my window using Super+Arrow Keys, the window would randomly turn transparent (eg, any opacity would decrease to pretty much transparent).

That's an unfortunate regression that happened at some point on glutin (*not* winit). With transparency disabled, it turns black instead; it seems that any downscaling that happens before the framebuf resizes ends up producing `[0.0, 0.0, 0.0, 0.0]`. This doesn't seem to be specific to resizing though, i.e. using the zoom functionality of my image viewer creates an increasingly transparent hole in my window.

> Additionally, if I type "AA" at my bash prompt, only the first A will show up; input seems to be disappearing somewhere.

You know, I tend to always have some winit apps running in the background, and I've had problems in Thunar, `pamac-manager`, etc. with keypresses getting eaten. I've been secretly afraid it was my fault somehow, but you say it only happens with decorations disabled?

I know for a fact that the resize flickering problem also happens with decorations on (tomaka/glutin#1019).

**Comment by chrisduerr** [comment]
The resize flickering problem has been reported before and is indeed an issue with glutin. There are actually quite a few issues that are caused by transparency, which is why I opened a PR to spawn a window without transparency enabled if the opacity is set to 1.0 in the configuration file.

Some of the issues related to this: #969 #1077 #1279.

**Comment by cconger** [comment]
@francesca64 I'm peeking around in change logs and this change in Winit for version 0.14 seems like it might be the culprit. https://github.com/tomaka/winit/pull/488/files

I think perhaps Alacritty should swap to using hidden menubar instead of decoration free, so that it can be given the `NSResizableWindowMask`.

I can play around with some options this weekend. Thanks for following up.

**Comment by cconger** [comment]
The cheap solution of just affording the ResizeableWindowMask was not enough to resolve it.  Something in the winit subclassing might be off but I was not able to allocate as much time to it this weekend as I intended.

**Comment by francesca64** [comment]
I can confirm that this was broken by tomaka/winit#408. I'll investigate this, if you're not attached to doing it yourself.

**Comment by cconger** [comment]
Please look into it, did not mean to block, was just happy to investigate as well. 👀

**Comment by francesca64** [comment]
Are you sure adding `NSResizableWindowMask` doesn't work? It works great for me!

**Comment by cconger** [comment]
My rust-fu is weak so I may not have been linking my local crates properly.

**Comment by francesca64** [comment]
Great! Here's the PR: tomaka/winit#553

**Comment by felixrabe** [comment]
Is this solved? If not, would upgrading glutin to 0.17 (be possible and) solve this?

**Comment by chrisduerr** [comment]
Yes, #1403 should solve this.
