### ISSUE TITLE
Change font size by half-steps with `Increase-/DecreaseFontSize` bindings

### ISSUE THREAD

**Issue by NickeZ** [jwilm/alacritty#1353]
(extracted from https://github.com/jwilm/alacritty/issues/1339)

Which operating system does the issue occur on?
Ubuntu 18.04 LTS

If on linux, are you using X11 or Wayland?
X11

I noticed that if I set font size to 7.5 it reports `Size(15)` in the console. And by using the shortcuts to resize the font I can only achieve odd numbers until I go all the way down to 2. I think this means that I cannot step through all font sizes.

```
$ alacritty -v
Welcome to Alacritty.
Configuration loaded from /home/niklas/.config/alacritty.yml
device_pixel_ratio: 1.6666666
width: 636, height: 1032
Initializing glyph cache
Finished initializing glyph cache in 0.040205583
width: 804, height: 460
Cell Size: (10 x 19)
PTY Dimensions: Line(24) x Column(80)
Font size changed: Size(15)
width: 636, height: 1032
Font size changed: Size(17)
width: 636, height: 1032
Font size changed: Size(19)
width: 636, height: 1032
Font size changed: Size(21)
width: 636, height: 1032
Font size changed: Size(19)
width: 636, height: 1032
Font size changed: Size(17)
width: 636, height: 1032
Font size changed: Size(15)
width: 636, height: 1032
Font size changed: Size(13)
width: 636, height: 1032
Font size changed: Size(11)
width: 636, height: 1032
Font size changed: Size(9)
width: 636, height: 1032
Font size changed: Size(7)
width: 636, height: 1032
Font size changed: Size(5)
width: 636, height: 1032
Font size changed: Size(3)
width: 636, height: 1032
Font size changed: Size(2)
width: 636, height: 1032
Font size changed: Size(4)
width: 636, height: 1032
Font size changed: Size(6)
width: 636, height: 1032
Font size changed: Size(8)
width: 636, height: 1032
Font size changed: Size(10)
width: 636, height: 1032
Font size changed: Size(12)
width: 636, height: 1032
Font size changed: Size(14)
width: 636, height: 1032
Font size changed: Size(16)
width: 636, height: 1032
Font size changed: Size(18)
width: 636, height: 1032
Font size changed: Size(20)
width: 636, height: 1032
Font size changed: Size(22)
width: 636, height: 1032
```

**Comment by chrisduerr** [comment]
I've mentioned this is #1339 but it has probably gotten lost in all the information. As jwilm has mentioned that is intended and shouldn't cause any issues.

**Comment by chrisduerr** [comment]
You do not. It's not possible to increment/decrement by `0.5` using the shortcut. But I agree that it would probably make sense to do that.

**Comment by NickeZ** [comment]
Will you reopen this issue as a request for `IncreaseFontSize` to increase the font by the smallest step possible? Since Alacritty became DPR/DPI aware I would really like to be able to single step the fonts in different terminals.

**Comment by chrisduerr** [comment]
I'm fine with changing it to step by the `.5` instead of `1.`, so I've reopened this issue. If @jwilm disagrees with this or thinks this is unnecessary, I guess he can just close this issue again. :)

**Comment by jwilm** [comment]
sounds good to me. Not sure why we don't do this already

**Comment by felippemr** [comment]
Hey, I'm new around here but I've been using alacritty and also trying to learn some rust. How can I help with this issue?

**Comment by chrisduerr** [comment]
Hi, this should be a fairly simple issue, if you want to have a go at it, here are some basic instructions:

The code where font sizes are increased/decreased is here:
https://github.com/jwilm/alacritty/blob/master/src/input.rs#L229-L234

To make the desired change, these would need to be changed to increase/decrease by `(-)0.5` instead of `(-)1`.

This will lead to a few issues with types, because the `change_font_size` method needs to take an `f32` instead of an `i8` now, this has to be changed in the `input.rs` and `event.rs` file. Changing just https://github.com/jwilm/alacritty/blob/master/src/input.rs#L65 should allow the compiler to throw errors and tell you all the different places where things need to be changed.

Finally the method in `term/mod.rs` has to be switched, this is where the actual font size change happens:
https://github.com/jwilm/alacritty/blob/master/src/term/mod.rs#L844

Here you just need to change the type of `delta` to `f32` and then replace the `f32::from(data)` part with just `data`.

I hope this should get you going if you want to tackle this issue @felippemr. If you want to give it a try just let me know and I'll assign this to you. If you have any further questions feel free to just respond to this issue or ask on irc (freenode/#alacritty). I'll answer as quickly as possible. :)

**Comment by felippemr** [comment]
Nice, thanks for the help! I'll give it a shot later today and will let you know if I have any problems.

**Comment by felippemr** [comment]
I'm working on it, can you assign it to me?

**Comment by chrisduerr** [comment]
I actually can not, I'm not sure why. But this should suffice as a record that someone else is currently working on it.

**Comment by felippemr** [comment]
I created a pull request. Would you be able to take a look?

**Comment by chrisduerr** [comment]
Sure! :)

**Comment by felippemr** [comment]
@NickeZ the pr with this change has been merged.
