### ISSUE TITLE
Logo design proposal

### ISSUE THREAD

**Issue by Tobaloidee** [jwilm/alacritty#1363]
Good day Sir @jwilm , I'm a graphics designer and I want to contribute to your good project by proposing a logo design. I'll be doing it for free as a gift to your project. If you will permit me I will start immediately and post here after. 

Thanks and best regards!

-[Tobaloidee](https://github.com/Tobaloidee)

**Comment by chrisduerr** [comment]
@Tobaloidee Hello, first of all thanks a lot for even proposing this.

There have been previous threads regarding an official logo (see #285, #863, #967). If you look at those you'll notice that we've already had a round of design proposals and decided on the icon that fits the project best, however the original designer of that hasn't responded in over 6 months.

I think moving forward it would be great to maybe have a few more icon designs, allowing anyone to chime in again if they are able to do so. Then we could select the best fitting one and hopefully sort out the licensing issues with the original author still around.

I'm not sure how @jwilm feels about this, since he has already decided on the icon from @net, so I'm not entirely sure how long we should give @net before we just dismiss that (admittedly awesome) icon and go for a different one. However if you want to design a new icon, I'm sure it can't hurt, I just wouldn't want to guarantee anything.

Generally regarding the direction the icon should go it would probably make sense to read through the previous discussions, but I don't think going into a completely different direction would be great too. The main things that came up the last time was that it would be cool if the icon somehow represents the "speed" of alacritty, without putting the language Alacritty is written in (Rust) into the logo as a primary selling point.

**Comment by net** [comment]
Hi, I’m still around and can make a PR this weekend. Apologies for the inactivity, been busy.

I’m not against going down a different path if that’s what we want to do though.

**Comment by chrisduerr** [comment]
@net Awesome to hear from you again! I'm still a big fan of the logo you've designed. As mentioned in #967 we'd need to at least have the SVG to move forward. I'd love to play around with it a bit myself to see if I can figure out a border that would make sense (I'm not much of a designer, but I can try).

If @Tobaloidee still wants to add a different proposal, I don't think anyone would stop him, but I wouldn't want anyone to waste his time. Do you think you could provide the SVG @net and give permission to use and alter the logo?

**Comment by Tobaloidee** [comment]
Oh I didn't know it has already been sorted out already. :)  @net 's design was great! and it was a great choice @chrisduerr.  Anyways, thank you for the feedback Sir. Best regards!

**Comment by chrisduerr** [comment]
Thanks again for making the proposal and also for getting us back in contact with @net. :)

**Comment by chrisduerr** [comment]
Closing this in favor of #967.
