### ISSUE TITLE
Selection misses first character

### ISSUE THREAD

**Issue by jrouleau** [jwilm/alacritty#1366]
Selecting in alacritty often misses the first character. Other terminals (such as urxvt and xterm) always include the first character in the selection even if only part of it is selected.

Edit: I should add that this was tested on scrollback@4631ca4

Alacritty:
![alacritty_selection](https://user-images.githubusercontent.com/11533746/41203662-c6730ec4-6cc9-11e8-8bc7-17063ada0a63.gif)

Urxvt
![urxvt_selection](https://user-images.githubusercontent.com/11533746/41203932-76730916-6ccd-11e8-8411-eb5b864c4065.gif)

**Comment by chrisduerr** [comment]
This was an intentional design decision and I'm not sure if there's any intention to change it.

As far as I'm concerned I think it's the proper behavior to select a cell only if most of it is inside the selection.

**Comment by jrouleau** [comment]
Perhaps it isn't what I thought. Fiddling with text selection in chrome, I see similar behaviour where it only includes the character beneath the cursor if more than half of it is selected. This logically makes sense; however, in practice, alacritty is consistently failing to select as expected.

Though I am now noticing another issue that may be the root cause of this. The start of the selection does not seem to be tied to where the mouse down event happened. You can click on a cell, wait, and then move the mouse quickly to start selecting and if you moved fast enough, the first cell of the selection will not be where you first clicked.

![alacritty_fast_selection](https://user-images.githubusercontent.com/11533746/41206251-db244258-6cf0-11e8-949e-a823315400ff.gif)

**Comment by chrisduerr** [comment]
I'm not able to reproduce this, could you provide some additional system information?

**Comment by jrouleau** [comment]
Hardware: Asus UX430UA
OS: Arch Linux x64
Kernel: 4.13.12-1-ARCH
GPU: Intel UHD Graphics 620
GPU Driver: i915
Window Manager: I3

Let me know if you need any more specifics.

At some point in the next week I should be able to run some tests in more generic environments

**Comment by chrisduerr** [comment]
I've tried this on a slower machine and there I'm able to reproduce this issue. I'm not quite sure what's going on here but it seems like a bug. It's potentially possible that this is caused by winit but I'd say it's unlikely, once the mouse down event is received alacritty should know the start position, so it's likely that there's some kind of problem in alacritty.

Now the only question left is if this is also present on the scrollback branch. I'll try to test this whenever I've got the time, but if you want to test this on your machine too @jrouleau it would be much appreciated.

**Comment by nixpulvis** [comment]
I have this issue on my laptops as well, and I can confirm that it also happens on the master branch. It should be noted that this issue doesn't seem to be caused by a selection starting just in the middle, you can drag your cursor over almost the whole letter and have it missed. Further, if you click, and very slowly drag after a short pause it works as intended pretty reliably.

**Comment by jrouleau** [comment]
@chrisduerr I use and discovered the issue on the scrollback branch so it is definitely present there too.

**Comment by chrisduerr** [comment]
Thanks for looking into this! I'll take a peek at the code when I've got some time. Sounds like it's either a super simple fix or some really painful racing condition or something like that. :D

**Comment by chrisduerr** [comment]
I've opened a PR which should fix this (#1389). I don't think there are going to be any issues with this, but testing is still always welcome! :)
