### ISSUE TITLE
Trailing colour when scrolling below initially rendered area in Vim

### ISSUE THREAD

**Issue by ArniDagur** [jwilm/alacritty#1376]
**System:** Arch Linux using X11
**Alacritty:** scrollback branch, latest version

I think it's best for you to look at the following video: https://www.youtube.com/watch?v=_wm4nhb3TFc&feature=youtu.be

On the left is uxterm, and on the right is Alacritty, both configured in approximately the same manner. Open on both terminal emulators is Vim with the Dracula Colorscheme and vim-airline. In Alacritty, you can see that when I scroll below the initially rendered area on the top, some of the colours (pink in this case) of vim-airline seem to trail downwards as the cursor moves.

I have done the same with Termite, and I have no problems there either.

Any ideas?

**Comment by chrisduerr** [comment]
Huh that's very interesting, I've never seen that happen before. I'm not quite sure what the cause of this could be.

Maybe this is in some way related to #1317, but I don't think it is because I can't see any zero-width characters in use here. You could try to remove all unicode characters from your airline but that's all I've got.

Does this only happen inside of vim? Does this happen on the latest master too? If this only happens inside of vim, can you provide a minimal vimrc for reproducing the issue? I'd imagine just using airline should be enough to reproduce for you?

**Comment by ArniDagur** [comment]
I have been investigating when this bug pops its head up using a minimized vimrc, and resizing the window seems to be one of them ([video demonstration](https://youtu.be/sHp4O2BPqdw)).

A previous session's colour trail also seems to stick around after disabling vim-airline and restarting vim, until alacritty + vim is restarted again: ([video](https://www.youtube.com/watch?v=JODfO20e9D8))

Could it be that I'm wrong about this being an alacritty bug?

I will try the master branch and report back.

**Comment by ArniDagur** [comment]
To the best of my testing, this only seems to happen on the scrollback branch.

**Comment by ArniDagur** [comment]
I do, however, get the following when I exit Vim on master:

![Screenshot](https://image.ibb.co/hCa8AJ/output.png)

The other problem seems to go away when using master.

**Comment by chrisduerr** [comment]
Okay, I've found a way I can always reproduce it with 100% accuracy. Here are the steps to follow for reproducing this issue:

 - Create a new alacritty window
 - Open vim
 - Increase window width
 - Go to the alt screen buffer (`printf '\e[1049h`)
 - Print lines until issue appears (for example `for i in {1000..2}; do echo $i; done`)

Using this method I was able to verify that this issue is not present on the latest `master`, so I'm going to tag this as scrollback.

**Comment by chrisduerr** [comment]
So I've already kinda expected this, but I've just confirmed that this is related to the `template` set on the `Term` struct. Apparently this is what's going on behind the scenes:

 - Grid is initialized
 - Template row is set to vim's statusline
 - Upon growing the empty lines are initialized to vim's statusline color using the template
 - When entering alt-screen again the alt screen's template row is loaded
 - When new lines are printed, the template cells are used to fill the grown area

This is probably not 100% how things are going down, but I think that's pretty much the gist of it.

I'd be interested in knowing under which circumstances we'd need a template cell at all, from my testing it seems like just replacing this with `Cell::default()` doesn't introduce any regressions. Could you enlighten me @jwilm? I'm sure there's a good reason for this, but the way it's currently implemented doesn't look optimal to me.

**Comment by jwilm** [comment]
> I'd be interested in knowing under which circumstances we'd need a template cell at all, from my testing it seems like just replacing this with Cell::default() doesn't introduce any regressions.

The template cell is where the current state of the cursor is stored. Take `back_color_erase` feature for instance. This is how applications like `htop` draw the color background for header lines and the bottom line -- set background color, issue clear line to right command. I believe we recorded some `vttest` runs for this feature that should catch any problems, but I may be mistaken.

As for using a template for scrolling, it might be worth looking through some of the git history there. We've made a lot of changes to it over time to fix various bugs, and there might be some insightful commit messages. I'm not sure off the top of my head what the right behavior is.

**Comment by chrisduerr** [comment]
I've looked through the commit history regarding the `grow_cols` function and could not find any specific detail explaining why the template cell is used here instead of `Cell::default()`. [This](https://github.com/jwilm/alacritty/commit/7f1c1efe474851a129e4a2e5bc012d9b76ed2ed0) is the commit which introduced this change.

I understand that things like `back_color_erase` require a template cell/row, however when the terminal is resized, shouldn't the initial state be equal to the default terminal cell state? If an application then wishes to handle that resize they could still do so at any time.

Similar thoughts might also apply to the `grow_lines` function, however I'm not aware of a bug caused by using the template cell here.

Just to clarify, since it sounded like I want to get rid of the template cell/row completely in my previous comment. This is the change I would propose which fixes this bug:
```diff
diff --git a/src/term/mod.rs b/src/term/mod.rs
index 3cdd5ff..ca3b502 100644
--- a/src/term/mod.rs
+++ b/src/term/mod.rs
@@ -1138,8 +1138,8 @@ impl Term {
         debug!("num_cols, num_lines = {}, {}", num_cols, num_lines);
 
         // Resize grids to new size
-        self.grid.resize(num_lines, num_cols, &self.cursor.template);
-        self.alt_grid.resize(num_lines, num_cols, &self.cursor_save_alt.template);
+        self.grid.resize(num_lines, num_cols, &Cell::default());
+        self.alt_grid.resize(num_lines, num_cols, &Cell::default());
 
         // Reset scrolling region to new size
         self.scroll_region = Line(0)..self.grid.num_lines();
```

Note that our testing should cover this at least partially and with this diff, there are no test failures. I've also done some manual testing with `htop` and `vim`, which do not have any problems with resizing with this patch applied.

**Comment by chrisduerr** [comment]
I've opened a PR with these changes [here](https://github.com/jwilm/alacritty/pull/1469), I haven't run into any issue with this so far, but since jwilm has mentioned some concerns, I'm going to run this branch myself for a while.

If someone wants to help out with testing, it would be much appreciated.
