### ISSUE TITLE
Font size rescales when dragged into a bigger monitor

### ISSUE THREAD

**Issue by Khalian** [jwilm/alacritty#1416]
Which operating system does the issue occur on?

Mac

The experience is very jarring. It would be nicer if alacritty consistently spawns in the same monitor screen it already is at, but that does not happen.

**Comment by Khalian** [comment]
While I was able to use this : https://github.com/jwilm/alacritty/pull/625 to work around it, i still think the resizing experience needs a fix.

**Comment by chrisduerr** [comment]
This sounds like you're missing the feature of DPI scaling on monitor change. Please see #1346, #1362 and #1403 for the current work on this topic.

Once these PRs are merged the font size will automatically change whenever the Alacritty window is moved from one screen to another.

**Comment by chrisduerr** [comment]
Also if this is really the issue you're running into, please close this issue and subscribe to the issues mentioned in the different PRs to keep track of this, to reduce the number of duplicate issues to keep track of.

**Comment by Khalian** [comment]
Launching alacritty with https://github.com/jwilm/alacritty/pull/625 is giving me an error as well.

**Comment by chrisduerr** [comment]
#625 is part of the master branch, if you are able to build the latest master, the changes introduced in this PR are unlikely to cause any issues.

**Comment by Khalian** [comment]
So couple of things 

1. https://github.com/jwilm/alacritty/blob/master/alacritty.yml#L300 does not actually show up when i installed alacritty (and I literally installed it yesterday). I have ~/.config/alacritty/alacritty.yml

2. So I added those lines manually, and then ran alacritty from iterm2

I got 

alacritty                                                                                                                                                                                                                                                                                                      
problem with config: Custom("Invalid value: invalid value for Action")

**Comment by chrisduerr** [comment]
What does `git log --oneline | head -n 1` give you when you execute it in the alacritty directory?

**Comment by Khalian** [comment]
╭─arunavs@f45c89bd4dd3  /Volumes/Unix/workspace/arunavs/third_party/alacritty ‹› ‹master›
╰─$ git log --oneline | head -n 1
68b3d8a Remove outdated comment about NixOS

**Comment by chrisduerr** [comment]
Okay, I'm going to assume here that you've installed Alacritty for the first time before and you've never built any other branch. If this is not the case please make sure that you clean up the project completely and rebuild it just to make absolutely sure.

Since the config file is baked into Alacritty at compile time, you should try deleting (create backup if necessary) the configuration file and then start Alacritty gain. This will create a new configuration file and since the branch you've mentioned makes use of the latest config file in the git repo, it should put a config on your system in `~/.config/alacritty/alacritty.yml` which contains the button mappings for increasing and decreasing font size.

**Comment by Khalian** [comment]
I think i figured out the issue. The homebrew formula for alacritty is referring to an outdated version. The correct one is put into Applications.
