### ISSUE TITLE
Missing alacritty-completions.zsh file in aur alacritty-git package

### ISSUE THREAD

**Issue by Fandekasp** [jwilm/alacritty#1434]
Which operating system does the issue occur on?
Arch Linux

If on linux, are you using X11 or Wayland?
X11 (i3 WM)

```
$ yay -Ql alacritty-git   
alacritty-git /usr/
alacritty-git /usr/bin/
alacritty-git /usr/bin/alacritty
alacritty-git /usr/share/
alacritty-git /usr/share/applications/
alacritty-git /usr/share/applications/alacritty.desktop
alacritty-git /usr/share/bash-completion/
alacritty-git /usr/share/bash-completion/completions/
alacritty-git /usr/share/bash-completion/completions/alacritty
alacritty-git /usr/share/fish/
alacritty-git /usr/share/fish/completions/
alacritty-git /usr/share/fish/completions/alacritty.fish
alacritty-git /usr/share/man/
alacritty-git /usr/share/man/man1/
alacritty-git /usr/share/man/man1/alacritty.1.gz
alacritty-git /usr/share/zsh/
alacritty-git /usr/share/zsh/site-functions/
alacritty-git /usr/share/zsh/site-functions/_alacritty
```

~Alacritty isn't working out of the box when installing on linux (window opened but prompt hangs forever). Will create other issues if I can figure it out~
EDIT: fixed by modifying the font in alacritty.yml

**Comment by chrisduerr** [comment]
If an aur package doesn't properly install the application, you should probably complain to the author of the aur package rather than Alacritty, since there's nothing we can do about this.

However, looking at the output, zsh completions for Alacritty are installed:
`alacritty-git /usr/share/zsh/site-functions/_alacritty`

I'm going to close this issue. If you have problems making completions work I'd recommend a zsh-related IRC or similar to help you out. From Alacritty's point of view there's nothing that can be done here, since we do provide completions and they do work properly when manually installed.
