### ISSUE TITLE
Small interval in responsivness

### ISSUE THREAD

**Issue by BigfootN** [jwilm/alacritty#1466]
Hello,

I've noticed that when using neovim (I don't know about any other contexts) when moving the cursor to the bottom or up, when releasing the movement key, it takes a small amount of time before the cursor really stops. Is this the normal behaviour ?

Other than this everything is really smooth.

Some information:

OS: `archlinux`
kernel version: `4.17.6-1-ARCH`
alacritty version: `0.1.0`

I am using `X11`.

Thank you very much in advance

**Comment by BigfootN** [comment]
Hello,

Thank you for your answer. I never managed to record a good quality video (I suppose because I needed something like `screenkey`).

To be more precise, what I meant is that when the (for example) bottom arrow is pressed for a certain amount of time, when releasing it the cursor keeps moving. It doesn't stop immediately, it only stops after some time.

Thank you very much in advance, hoping I was clearer.

**Comment by chrisduerr** [comment]
Unfortunately I can't reproduce this, it almost sounds like there's a build-up of events and Alacritty is unable to keep up.

Could you give me some more information about your system? GPU/CPU etc, just to judge if your computer is ancient or not. :D

**Comment by BigfootN** [comment]
Hello,

Thank you for your response.

So to answer your question, I am not using any gpu, only my `i7-8700k`.
Other than that, I am using `gnome-shell` as my `DE`.

Thank you very much in advance.

**Comment by chrisduerr** [comment]
Hmm okay, so Intel integrated graphics. I don't think your system's too slow, it sounds like plenty of horsepower to me.

Could you share a screen recording with `alacritty -vvv`? Like that there shouldn't be any need for something like `screenkey`.

**Comment by BigfootN** [comment]
Hello,

So I managed to get a [video](https://imgur.com/odQKGXg). I hope it's okay.

Thank you very much in advance.

**Comment by chrisduerr** [comment]
Is this reproducable with the default nvim config? You can test that using `nvim -u NONE`.

**Comment by phddoom** [comment]
I think I am having the same / similar issue. I think it is related to handling keyboard input since I can't seem to reproduce with something that produces a lot of output.

![output](https://user-images.githubusercontent.com/189922/43267427-edd608d4-90bb-11e8-84aa-d41fa248e710.gif)

Notice the jump in input towards the end of the gif.

I have a better quality video, but github only allows gifs ...

Let me know if there is other info I can provide to help.

**Comment by chrisduerr** [comment]
I'd be interested in seeing if you can reproduce this with `glutin` itself.

For anyone interested in testing this, here are some instructions:
 * Clone https://github.com/tomaka/glutin
 * Change into the `glutin` directory and run `cargo run --example window`
 * Wait for compilation :clock1030: 
 * Once the window opens, press lotta keys/hold keys

If this issue is related to glutin, I'd expect that the output in the window you ran this from would keep going after you stopped typing. I personally can't reproduce this issue, so for me the behavior when testing this is that as soon as I stop typing, there are no more events printed in the console.

If however glutin should stop spouting event messages as soon as you stop typing, this issue might actually be related to Alacritty itself.

**Comment by BigfootN** [comment]
Hello,

Sorry for the late response. So, even with `nvim -u NONE`, the problem persists.

I haven't tried yet with `glutin`.

Thank you very much in advance.

**Comment by BigfootN** [comment]
Hello,

I had the chance to test it with `glutin`, and it seems to be indeed coming from `glutin`. I am under the impression that output keeps going on even though I stopped typing.

Can anyone confirm this ?

Thank you very much in advance.

**Comment by chrisduerr** [comment]
If this is a problem with glutin, it probably makes sense to report it [upstream](https://github.com/tomaka/glutin) .

**Comment by BigfootN** [comment]
Thank you very much for your help, I opened an [issue](https://github.com/tomaka/glutin/issues/1054) on the `glutin` repository.

**Comment by yesacs** [comment]
I was originally posting in #2514 about something similar and just wanted to post my initial findings here. I'm on a late 2018 MacBook Pro @ 10.14.5

I cloned both `winit` and `glutin` masters and tried `cargo run --example window` on both. `winit` did not seem to exhibit the same problems with key repeats that I was seeing in `alacritty`. Unfortunately, I can't get the `glutin` example to run on my machine:

```thread 'main' panicked at 'gles2 function was not loaded', /Users/casey/Sites/glutin/target/debug/build/glutin_examples-f84a4408dcde85c4/out/gl_bindings.rs:1158:13```

Hope this helps. Like I said in the other comment I started noticing this after upgrading from macOS 10.13 to 10.14.

**Comment by for-coursera** [comment]
My 5 cents (macOS 10.11.6): was experiencing the same issue (e.g., in Vim, characters were continuing to be typed in even after I stop physically entering them) with alacritty 0.3.3 1067fa6 (to add some timeline, I cloned and built it on the 13th of September). 

Updating to the currently latest version (alacritty 0.3.3 3475e44) *almost* solved the issue: some practically unnoticeable lag is still present (comparing with Terminal.app, for example) but the improvements are significant.

**Comment by chrisduerr** [comment]
@for-coursera Could you try compiling the latest master from source? Looking at things, the upstream issue marks this as resolved, so I think if there are more problems it should be handled separately.

**Comment by for-coursera** [comment]
The latest master is 3475e44, which is the one I compiled (as I said in my comment above). Or am I missing something? :)

**Comment by chrisduerr** [comment]
Oh, I completely overlooked the hash and thought you were talking about 0.3.3 since you mentioned that version explicitly, sorry.

I still think the original underlying issue is resolved, though if you still can notice this there might be other stuff involved. The upstream bug was strictly about X11, so there might be some weirdness going on with macOS too.

So just to clarify, if you hold down a key (let's say `e`), it will output at least one more `e` after you've already released the key, right? Even on the latest master (compiled in release mode). I'm asking since you've used the word "lag", just to make sure you're not talking about characters not streaming in consistently.

**Comment by for-coursera** [comment]
> So just to clarify, if you hold down a key (let's say `e`), it will output at least one more `e` after you've already released the key, right?

That was my initial impression. But now after some additional testing I'm not really sure :) So, may be everything actually IS all right, and I was just a bit blind previously :)

**Comment by chrisduerr** [comment]
It's obviously hard for me to judge since I'm not looking at it, but if you're saying that it has significantly improved on master, likely even resolved, then I don't think there's any further reason to take action.

If you notice any more problems, please just open a separate issue and we can investigate it separately, otherwise it's just going to be buried here forever.

**Comment by for-coursera** [comment]
> then I don't think there's any further reason to take action.

Agreed. I was posting my initial comment more like a reference than an actual report (and since the issue was still open). 

Thanks for your help, and sorry for this confusion :)

**Comment by chrisduerr** [comment]
No worries, thanks for the feedback. Wouldn't have noticed that this could be closed without you.
