### ISSUE TITLE
Support clearing scroll-back buffer

### ISSUE THREAD

**Issue by saulshanabrook** [jwilm/alacritty#1480]
It would be helpful to have a command that clears the scroll-back buffer (which was implemented in https://github.com/jwilm/alacritty/pull/1147) so you could associate it with a keybinding. On Mac, in Terminal and iTerm this is bound to CMD-K by default.

**Comment by chrisduerr** [comment]
Thanks for opening this issue. This should be fairly straight-forward to implement, since the scrollback buffer itself already supports efficient clearing without any big overhead. [This](https://github.com/jwilm/alacritty/blob/23601fbefcab5ba08884dd87c6a3d2f4347166a2/src/grid/storage.rs#L36) allows setting the size of the scrollback buffer without actually modifying the maximum size or cleaning the cells in the scrollback buffer. So changing this should remove all content from the scrollback history without any other side-effects.

The implementation of key actions is done in `config.rs` and `input.rs`, there should already be examples for how to do this with things like `ScrollToBottom`. Since these already interact with the grid, a fairly similar approach should allow getting things up and running fairly quickly. Calling the `update_history` method in `storage.rs` from `grid/mod.rs` should do the job here.

**Comment by nixpulvis** [comment]
This feature is currently implemented in #1500, which should be ready to merge.
