### ISSUE TITLE
Upgrade winit to 0.17.0 and smithay-client-toolkit to 0.3.0

### ISSUE THREAD

**Issue by SirCmpwn** [jwilm/alacritty#1510]
I was going to send a patch but I don't really grok Rust or Cargo and quickly got lost.

**Comment by chrisduerr** [comment]
Thanks for opening this issue.

Usually with patches before 1.0 or minors after 1.0 it should be possible to just run `cargo update`, however since `smithay-client-toolkit` is pre-1.0 we can't just pull an update ourselves. We pull this crate through our dependency `winit`, so we have no control over the version which is used.

It looks like there's a PR for `winit` which will already require 0.3.0 [here](https://github.com/tomaka/winit/pull/628). Once that patch lands it should be possible to update `winit` again which then will pull 0.3.0 of `smithay-client-toolkit`. Alternatively if this takes too long I'm open to sending a PR to `winit` which just bumps the `smithay-client-toolkit` version without touching anything else, since this update does not cause any issues.

The `winit` version is already updated to 0.17.0 in the PR #1403, but it's likely that the inclusion of the latest `smithay-client-toolkit` will require another update to this PR once version 0.3.0 is supported.

So right now there's not much Alacritty can do about this, other than supporting upstream to include the latest version of the `smithay-client-toolkit`, however once that is done it should be easy to update Alacritty.

**Comment by SirCmpwn** [comment]
Sweet, thanks for the info.

**Comment by SirCmpwn** [comment]
The new winit release (0.17.2) is out with the necessary transitive update as well.

**Comment by SirCmpwn** [comment]
Looks like winit is itself a transitive dep - we need to update glutin here. I tried to do this, but it looks like there are some backwards-incompatible changes.

**Comment by chrisduerr** [comment]
@SirCmpwn No worries the #1403 PR already takes care of this. The new winit release is already part of the lockfile, so it's all ready once the PR is in a good shape.

This was quite a big change in glutin, so it takes a bit of time to polish things out. But it should pull in the latest version off all direct and transitive updates.

Thanks for looking into this though.

**Comment by dvergeylen** [comment]
As #1403 PR has been merged and tomaka/winit/pull/628 as well (3 months ago), isn't this issue solved by now? 😇

**Comment by chrisduerr** [comment]
@dvergeylen You're correct, this issue is resolved now. Thanks for the notice.
