### ISSUE TITLE
F16-F19 keys not working properly.

### ISSUE THREAD

**Issue by overlazy** [jwilm/alacritty#1525]
Which operating system does the issue occur on? macOs 10.14 public beta 7

My config for F keys:
![screenshot 2018-08-27 at 19 58 32](https://user-images.githubusercontent.com/27620401/44674341-e4001780-aa35-11e8-9279-232b1a0335cb.png)

Screen cast in alacritty ( I'm pressing keys from F13 to F19)
TERM: xterm-256color

![ezgif-2-846e274177](https://user-images.githubusercontent.com/27620401/44674607-b8c9f800-aa36-11e8-8a83-b49d31d21dd7.gif)

Screen cast in iterm2 ( I'm pressing keys from F13 to F19)
TERM: xterm-256color

![ezgif-2-bd5af78a1b](https://user-images.githubusercontent.com/27620401/44674635-d4350300-aa36-11e8-906b-0976055637f5.gif)

**Comment by jwilm** [comment]
Can you please run alacritty with `--print-events` and record the output? My guess is that winit doesn't know what those keys are so they are not triggering a key binding.

**Comment by overlazy** [comment]
"After some F15" I pressed F16-F19 and then again F15

[log.txt](https://github.com/jwilm/alacritty/files/2325205/log.txt)

**Comment by chrisduerr** [comment]
All the available key combinations can be seen [here](https://docs.rs/glutin/0.18.0/glutin/enum.VirtualKeyCode.html#variant.F12). Since Glutin/Winit do not provide bindings beyond F15, it's currently not possible to add them to Alacritty.

To make these work it would be necessary to add them to `winit` first. And as soon as they are added there, they should automatically start working in Alacritty.

I'd assume that adding these bindings is fairly simple, so the quickest way to get this working would probably be to send a PR to `winit`.
