### ISSUE TITLE
KDE + tmux: transparent and glitched background

### ISSUE THREAD

**Issue by nukeop** [jwilm/alacritty#1536]
Linux, X11, KDE.

On detaching from tmux session and switching from maximized to smaller size window (and vice versa) the background becomes completely transparent, sometimes with severe rendering artifacts present as well.

Unable to demonstrate this effect on a screenshot, because taking it immediately restores the window back to normal. It looks like there's a texture that does not initialize its memory and displays garbage.

Steps to reproduce:
1. Launch alacritty
2. run `tmux a` or createa new session
2. Detach from session (C-b d)
3. Maximize the window
4. The rendering bug should occur until the window is re-rendered.

**Comment by trimental** [comment]
I think that https://github.com/jwilm/alacritty/pull/1518 has a high chance of solving your problem considering it changes the way alacritty clears and renders the screen and fixes quite a few similar issues with rendering that are fixed on a re-render

**Comment by chrisduerr** [comment]
Besides trying #1518, it has been mentioned in numerous other issues that using transparency can mess up some things. Which is why I created a PR to disable transparency hot-reloading here: #1279.

The issue #1268 also includes a smaller patch you can apply to permanently disable transparency. This should completely solve all transparency related issues.

**Comment by trimental** [comment]
@chrisduerr I might of interpreted the original issue wrong but I think he might be saying that the transparency is an effect of the issue and not expected behaviour (ie he might not have it in the config). When I run alacritty without #1518 the same weird transparent gitching occurs when resizing (at least on wayland).

**Comment by chrisduerr** [comment]
@trimental I don't know about wayland, but there have been several issues before where the window would become transparent when resizing.

This is because transparency is always enabled as a window setting, however a background is just drawn above the transparent window when the opacity is set to 1.0. That's why disabling transparancy completely (in the source code) can help out.

**Comment by nukeop** [comment]
The bug occurs whether or not I have transparency in the config. Although I realise that internally it may not matter.

**Comment by chrisduerr** [comment]
I recommend giving the PR @trimental sent a shot. Maybe that will solve it.

**Comment by nukeop** [comment]
Yeah I no longer have this problem. Thanks.
