### ISSUE TITLE
Add to readme. on ubuntu 18.04 need to install xclip package.

### ISSUE THREAD

**Issue by Dustver** [jwilm/alacritty#1541]
_Which operating system does the issue occur on?_ -> Linux 4.15.0-34-generic #37-Ubuntu18.04 SMP Mon Aug 27 15:21:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

_If on linux, are you using X11 or Wayland?_ -> X11

after "cargo deb --install" installation has aborted with error "xclip package not installed".
add to readme line "sudo apt install xclip"

**Comment by chrisduerr** [comment]
The `.deb` has `xclip` as a dependency, so it should be okay. In the manual installation instructions `xclip` is also listed as a depedency.

I'm not super familiar with how `.deb`s work since I do not make use of them, but [this](https://github.com/jwilm/alacritty/blob/master/Cargo.toml#L72) looks like it lists everything that is required.

**Comment by chrisduerr** [comment]
The .deb build instructions should be moved to the INSTALL.md, since all dependencies are required to build it.

That should resolve this issue too.
