### ISSUE TITLE
Touch ID sudo doesn't work on MacOS

### ISSUE THREAD

**Issue by meunierd** [jwilm/alacritty#1549]
With the following `/etc/pam.d/sudo` contents:

```
# sudo: auth account password session
auth       sufficient     pam_tid.so
auth       sufficient     pam_smartcard.so
auth       required       pam_opendirectory.so
account    required       pam_permit.so
password   required       pam_deny.so
session    required       pam_permit.so
```

I'm able to `sudo` with Touch ID in Terminal.app but not Alacritty.

**Comment by dominiklohmann** [comment]
[pam_reattach](https://github.com/fabianishere/pam_reattach) should be able to work around this limitation. It is, however, not a good idea to ask users to install a third party PAM, since it's quite easy to get locked out doing so.

I found this PR for tmux discussing the issue as well: [Reattach to per-session namespace on OS X 10.10+](tmux/tmux#1434). 

There is some work to be done here and it's not just Alacritty having this issue. The version of `screen` shipped with macOS works just fine for example, just like iTerm2 and Terminal do.

**Comment by meunierd** [comment]
Closing this as it's actually just a tmux issue.
