### ISSUE TITLE
Selecting large amounts of text makes highlight disappear

### ISSUE THREAD

**Issue by haarp** [jwilm/alacritty#1557]
> Which operating system does the issue occur on?

Linux X11

When selecting text and scrolling at the same time using the new scrolling->history feature, there is a visual bug concering the selected text.

When more text is selected than fits on the viewport, and the viewport is scrolled so that **only** selected text is visible, the selection marker (inverted colors) disappears. If the viewport is scrolled so that only parts of its contents are selected, the selection marker shows up fine.

**Comment by chrisduerr** [comment]
Thanks for the report! I believe that nobody actually ever tested selection while scrolling, since it's a bit awkward to do with a mouse.

Currently it seems like the selection only updates during mouse movement, not when scrolling. But since scrolling changes the text under the cursor, it should also update the selection. I believe implementing this should work around the issue of selection disappearing and it should provide the added benefit that selection during scroll feels more responsive.

**Comment by chrisduerr** [comment]
Okay, so it turns out my original comment on this issue was a bit misguided. The selection not updating when scrolling and the issue reported here are entirely separate.
