### ISSUE TITLE
Colors don't look as they should

### ISSUE THREAD

**Issue by orium** [jwilm/alacritty#1561]
I don't know if this is duplicate of other issue, but the colors in alacritty don't seem right.  Here's a screenshot with alacritty on the left and urxvt on the right:

![screenshot-20180919-004206](https://user-images.githubusercontent.com/4107683/45722612-16201780-bba5-11e8-8224-a0c6f62390ea.png)

Running v0.2 in Arch Linux (installed from the official repos) with x.org.

**Comment by jwilm** [comment]
Do you have some sort of alpha channel configured in urxvt? It sort of looks like everything over there is low contrast.

This can all be updated through the alacritty config file. Alacritty doesn't pull from xrdb.

**Comment by orium** [comment]
> Do you have some sort of alpha channel configured in urxvt? It sort of looks like everything over there is low contrast.

No.  The urxvt window is a bit faded because the focus is on the other window.

**Comment by jwilm** [comment]
Have you verified that the colors in your alacritty.yml match how your urxvt is configured?

**Comment by orium** [comment]
I left them both with the default values.  Aparently the defaults are poor.  The default green is `0xb9ca4a` which is actually yellow.  I think it would be a good idea to copy the default colors from urxvt.

**Comment by orium** [comment]
> No, you should not open an issue to review the default colors. Your entitled behavior has no place in this project or its issue tracker.

I don't understand why you think my behavior is entitled.  I genuinely thought it was a bug because the colors didn't look right to me, in the sense that some of them don't match what is expected from their name.  I still think that because the colors are distant from their expected neutral form this makes it a poor default theme.

In any case, I don't think your response if fair.  Assuming good faith (which was certainly the case) and avoiding personal attacks are vital for a heathy community, specially one that is based on non face-to-face communications where intentions can easily be misjudged.

**Comment by jwilm** [comment]
@orium 

> I don't understand why you think my behavior is entitled

Then let me break it down for you.

* The initial issue description basically said "the colors are wrong" with no description of what specifically is wrong, what you've tried (if anything), and a non-representative screenshot where your "expected" results are being skewed by the non-focused window dimming. You put the onus on *us* to engage and poke at your problem to find out what you actually want.
* The defaults don't match your urxvt installation, and because they don't match _your_ previous terminal, you insist they are somehow wrong.
* "Aparently the defaults are poor" - attacking a decision based on your personal bias without consideration for why things are the way they are or that others may actually **enjoy** the defaults
* "I think it would be a good idea to copy the default colors from urxvt." - this is basically saying the same as above but with more emphasis on expecting the project to change for and accomodate you.
* "Should I open an issue to review the default colors?" - A harmless question by itself, but with context from previous comments, this is again expecting the project to change for you.

> I still think that because the colors are distant from their expected neutral form this makes it a poor default theme.

Now we are getting somewhere. This is an argument with some amount of objectivity rather than "hey, this isn't what **I** want".

> avoiding personal attacks are vital for a heathy community

So is preventing maintainers from getting burnt-out. One of, if not the biggest, contributor to maintainer burnout is battling entitlement, and that's why I attempt to stamp it out as soon as it arises.

> where intentions can easily be misjudged.

This is an important point, and it underscores why we should all be mindful of how our comments may be perceived by others.

**Comment by dcasella** [comment]
Not discussing the default color scheme choice;

> The default green is `0xb9ca4a` [which is actually yellow](https://www.color-hex.com/color/b9ca4a).

From the URL you linked (and I agree):
> Color #b9ca4a contains mainly GREEN color.

**Comment by jwilm** [comment]
Hey @dcasella, thanks for the feedback. I'm a little unclear on what you are saying, though; are you saying that you agree it's yellow or with the link saying it seems green?

The primary goal with the color choices was having high contrast for accessibility and aesthetics second. If there's an issue around this, it may be worth revisiting.

**Comment by dcasella** [comment]
> Hey @dcasella, thanks for the feedback. I'm a little unclear on what you are saying, though; are you saying that you agree it's yellow or with the link saying it seems green?

Sorry, "I agree" (with the website); it looks green to me.

**Comment by orium** [comment]
> The initial issue description basically said "the colors are wrong" with no description of what specifically is wrong, what you've tried (if anything), and a non-representative screenshot where your "expected" results are being skewed by the non-focused window dimming.

I wasn't specific because I didn't know exactly how to describe it.  I tried to search for other issues that could be related, but since I didn't know much about what to search except "color" I decided to open an issue (I even say that I don't if it was a duplicate).  Because of the lack of a good description I included a screenshot.  I didn't noticed that in the screenshot the urxvt window was dimmed.  I could have done a better job at describing things, but I assumed the screenshot would be the best way to expose what I meant.

> The defaults don't match your urxvt installation, and because they don't match your previous terminal, you insist they are somehow wrong.

It is not about my previous terminal.  It is about the expectation I have for colors.  I would argue that my expectations for colors are aligned with the general public.

> "Aparently the defaults are poor" - attacking a decision based on your personal bias without consideration for why things are the way they are or that others may actually enjoy the defaults.

I don't think disliking or points potential flaws in something is "attacking a decision".

I'm sure a lot of people enjoy that theme, but that doesn't necessarily make it a good default.  It what makes something a good default IMO is something that makes the majority of people reasonably happy with it.  I think the default colors are too off from the name they represent to be that.

> "I think it would be a good idea to copy the default colors from urxvt." - this is basically saying the same as above but with more emphasis on expecting the project to change for and accomodate you.

Once again, it is not about urxvt.  I should have written "I think it would be good to have a color scheme that better aligns with the natural expectation of the colors.  Urxvt is a good example.".  I wasn't as clear as I should, hence my point on "assuming good faith" (because it is generally true).

Also, it is not about accommodating me.  Independently of the fact that changing the theme was possible (which I didn't know was possible when I opened the issue), I think that a more neutral theme gives a better impression on new users and is closer to what most people would want.  I honestly thought the colors were being rendered incorrectly when I opened the issue.

> "Should I open an issue to review the default colors?" - A harmless question by itself, but with context from previous comments, this is again expecting the project to change for you.

I found weird that the issue was closed without any comment.

**Comment by orium** [comment]
@dcasella It is true that it is mostly green, but just by a bit.  You will notice that the red component (in RGB) is close to the green one.  A pure yellow is precisely represented by having both those components to the maximum value.

But looking at the representation of a color in RGB it not an easy way to evaluate it.  I think it is better to look at what people think of when they call something green or yellow and compare it.  You can do this in many ways (for instance checking google images for a color name and see what comes up).  For instance, if you go to wikipedia and check the [yellow](https://en.wikipedia.org/wiki/Yellow) and [green](https://en.wikipedia.org/wiki/Green) colors and put them side-by-side with the #B9CA4A in the middle you get this:

![color](https://user-images.githubusercontent.com/4107683/45773728-f808f480-bc42-11e8-9ca5-66d50415655c.png)

It seems clear that #B9CA4A is far from the "neutral green", and I would even say it is closer to yellow.

**Comment by chrisduerr** [comment]
Hey @orium, the default Alacritty theme is actually a lot more sensible than what other terminal emulators provide by default in my experience. And I've heard only good things about Alacritty's default colorscheme so far. It's also a pretty popular theme outside of Alacritty, so I'd say the statement that your "expectations for colors are aligned with the general public" are questionable.

We're happy to discuss any factual issues with this application, however calling something as subjective as color choices a bug or wrong, isn't going to help anyone.

If you're not happy with the default Alacritty colorscheme, I'd recommend taking a look at the alternatives [here](https://github.com/jwilm/alacritty/wiki/Color-schemes). I personally would recommend **everyone** to change the defaults, since it's a great way to make a terminal emulator your own.

Since it seems like the Alacritty project can't agree with the proposed resolution to this issue, I'll mark it as wontfix, so people that might look into this in the future know what's going on.

If you have any other questions or issues to report, please feel free to open a different issue. However I'd like to request that it is done in an appropriate manner. :)
