### ISSUE TITLE
ScrollPageUp and ScrollPageDown actions behave not as expected

### ISSUE THREAD

**Issue by scampi** [jwilm/alacritty#1593]
- linux with X11
- alacritty 0.2.0.911.g63a40df

Scrolling with the mouse wheel behaves as expected, however it does not when scrolling with the page up/down keys.

With the mapping bellow, the terminal is scrolled 1 page up when pressing `Shift + PageUp` but doesn't continue on additional key presses (it stays at the same position). See the [events log](https://github.com/jwilm/alacritty/files/2423000/alacritty.log.txt).

As for the `Shift + PageDown` combination, I have the following:
- go to the top with `Shift + Home`
- pressing `Shitft + PageDown` brings me to the bottom, although I would expect to have scrolled on page down only.

```yaml
  - { key: PageUp,   mods: Shift,   action: ScrollPageUp   }
  - { key: PageDown, mods: Shift,   action: ScrollPageDown }
  - { key: End,      mods: Shift,   action: ScrollToBottom }
  - { key: Home,     mods: Shift,   action: ScrollToTop    }
```

**Comment by chrisduerr** [comment]
Alacritty already has bindings for Shift+PageUp and Shift+PageDown. As a result of that, every time you invoke this action, an escape sequence is written to the terminal and then the output is scrolled by one page. The issue with this is that writing escape sequences will scroll the terminal emulator to the bottom, so with every invocation you first scroll to the bottom again and then scroll a page up. Which is why it doesn't seem to have any effect.

You can see the mappings in question here:
https://github.com/jwilm/alacritty/blob/master/alacritty.yml#L385-L390

**Comment by scampi** [comment]
thanks @chrisduerr ! Commenting out those existing mapping fixed my problem

**Comment by SicariusNoctis** [comment]
It appears you can get both behaviors by writing them in the following order:

```yaml
  - { key: PageUp,   mods: Shift,   chars: "\x1b[5;2~"                   }
  - { key: PageUp,   mods: Shift,   action: ScrollPageUp                 }
  - { key: PageDown, mods: Shift,   chars: "\x1b[6;2~"                   }
  - { key: PageDown, mods: Shift,   action: ScrollPageDown               }
```

**Comment by SicariusNoctis** [comment]
Is there any way to maintain sending `x1b[5;2~` during `Shift+PageUp` to tmux?
