### ISSUE TITLE
Quick question regarding alacritty.yml vs alacritty_macos.yml

### ISSUE THREAD

**Issue by jonleopard** [jwilm/alacritty#1626]
Hellol everyone,

Not having any issues here, I'm just curious what the differences are between the alacritty.yml config file, and the alacritty_macos.yml file are. I'm on a mac, and I've been using the default alacritty.yml file.

Can anyone explain what the differences are between these two files? At a glance, they look almost identical.

Cheers!

**Comment by jonleopard** [comment]
Thanks a lot for the info! Another quick question, since I'm new to Rust applications.

I run `git pull` whenever I see changes committed to master. Do I need to recompile once I do this? My normal process is:

`$ git pull`
`$ rustup override set stable`
`$ rustup update stable`
`$ cargo build --release`
`$ make app`
and finally, `cp -r target/release/osx/Alacritty.app /Applications/` since I'm on a Mac. 

I noticed that my symlinked config file won't pull in any of the latest changes, so I normally have to copy from master, and re-apply all my config params. Is there a better way to do this? I'm most likely butchering the whole update process.

Thanks again for all the info :)

**Comment by chrisduerr** [comment]
There currently is no automated process for updating the configuration file. We wouldn't want to dump stuff in the config a user has cleanly setup for himself. But the existing configuration files will keep working with new Alacritty versions unless mentioned otherwise in the change log.

So the recommended way of migrating the configuration file after an update is to take a look at the change log and if there are any interesting features you'd like to make use of, just adding the new configuration options to your config. All new configuration options should be documented in the `Added` section of the change log (similarly `Changed` and `Removed` are used for changes or removal of config sections).

Usually if your configuration file is in an invalid state because of updates, warnings/errors will be printed to stderr. So it shouldn't cause total havoc but allow you to make the required changes.

If there was a new git update, you'll likely have to recompile. The `make app` command should take care of that for you. You don't have to do anything other than `git pull && make app` to update Alacritty completely, unless there was a change to the `Alacritty.app`, terminfo, man or completion files. In that case you'll just have to copy over the altered files and you should be good to go.

**Comment by jonleopard** [comment]
Really appreciate you taking the time to answer my trivial questions! I will take note of all of this.
Alacritty has been serving as my primary driver for the past few months now and I really enjoy what you guys have made. If I ever manage to get Rust added to my toolbelt, I'd love to contribute in the future!

Feel free to close this 'issue', and thanks again!

**Comment by nixpulvis** [comment]
I'll also jump in here to say, A) tools like `yamldiff` might help you. I've gone down this path before. And B) if you have more questions perhaps IRC could be a good place for you to go. There's usually at least someone around.

**Comment by jonleopard** [comment]
@nixpulvis Thanks for suggesting `yamldiff`, I had no idea that existed. I just joined the IRC channel :)
