### ISSUE TITLE
New build crashes with default config

### ISSUE THREAD

**Issue by haadr** [jwilm/alacritty#1632]
OS: Linux, debian stretch (mostly)
X11

I just did a fresh clone of the repository, then used the following to get a deb file built:
```
cargo install cargo-deb
cargo deb --install
```
I've previously used alacritty via `~/.cargo/bin`, so I had an old config file in `~/.config/alacritty/alacritty.yml`.

Even with no config file/the default one contained in the repo, I get the following output and crash:
```
problem with config: env: invalid type: unit value, expected a map at line 17 column 1; Using default value
thread 'main' panicked at 'font offset is too small', src/display.rs:247:13
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: __libc_start_main
   9: <unknown>
```
When I try to manually adjust the offset.x value to something other than 0 alacritty starts, but the font spacing is messed up. Having it at something like 10 makes them readable, but for some letters the spacing seems different than for others.

Let me know if I can do anything else to help debug this. 

PS: I first wanted to ask whether I had just made some silly mistake before submitting an issue ticket, but I kept getting kicked from #alacritty on freenode via matrix with "err_needreggednick" even after registering. Maybe it's because of the [m] added on the name when using matrix.

**Comment by chrisduerr** [comment]
Regarding the #alacritty IRC channel, you need to be registered to join, because there recently were some spam attacks on freenode.

Regarding the issue itself, this is because either `font.offset.x` or `font.offset.y` is so small, that the computed cell width or height is lower than 1 pixel.

Usually this happens when the offset is set to something like `-30`, effectively leading to all characters disappearing. However with your issue it looks like it's present even at bigger sizes?

Usually the idea of the font offset is to start with 0 and then add/substract 1 until the spacing looks correct. Does Alacritty crash even with the default configuration file (so an offset of 0)? I your old config is unmodified, I recommend deleting it and allowing Alacritty to create a new one.

**Comment by haadr** [comment]
Thank you for the quick reply. I understand being required to register, I think there are just some issues around being recognized as registered with the nickname you get when you join via matrix, but that's probably matrix's problem.

Anyways, the weird thing is I assume alacritty tries using the default value (`Using default value` is printed in the output), but it still fails. I get the above output with the default config file, as well as with no config file at all. I will also attach a screenshot of what the fonts look like using the default config file and setting the offset to 10.
![screenshot](https://user-images.githubusercontent.com/16254070/46571605-027ff980-c978-11e8-8fba-6311900f3d9b.png)

**Comment by chrisduerr** [comment]
That seems to be a proportional font, instead of a monospace one. Changing your font to a monospace font should resolve this issue.

**Comment by haadr** [comment]
That set me on the right path... I had configured my `~/.config/fontconfig/fonts.conf` according to https://victor.kropp.name/blog/emoji-on-linux/ a while back. Removing that file and running `fc-cache -f -v` fixed alacritty for me. Thanks for the follow up!
