### ISSUE TITLE
[Feature] Add setting to hide titlebar

### ISSUE THREAD

**Issue by rafi** [jwilm/alacritty#168]
Like iTerm2 allows (_Profile -> Window -> Style: No Title Bar_), please add an option to hide the titlebar.

<img width="512" alt="alacritty" src="https://cloud.githubusercontent.com/assets/147918/21741005/df17ec46-d4d2-11e6-94f1-2fcf806beb94.png">

**Comment by holygeek** [comment]
See also: #161

**Comment by jwilm** [comment]
Should be easy to do

**Comment by rafi** [comment]
Any rustier up for the challenge? 😬

**Comment by will118** [comment]
I hacked together a solution to this a while ago, but I don't think it's a merge-able solution.

The change is in `cocoa-rs`, which is a dependency of `glutin`, which is in turn a dependency of `alacritty`.

The diff is here: https://github.com/servo/cocoa-rs/compare/ac2eaf83482d38...will118:wb-borderless-window

Essentially I compile in an subclass of NSWindow, so there's a couple of changes to compile and link in the objective-c into the Rust. I'm not sure of a better way of solving this.

p.s. I initially tried swizzling the NSWindow that was being created but I didn't have much luck creating an `IMP` in Rust (I have no Rust knowledge).

**Comment by k0nserv** [comment]
Related I've been experimenting with a borderless version for macOS

![borderless](https://user-images.githubusercontent.com/1333960/31861052-5f554cb4-b71d-11e7-9383-efff2d40e6f7.png)

**Comment by asilvadesigns** [comment]
Oooo

**Comment by Sachka** [comment]
@k0nserv Impressive! I wasn’t expecting an approach like this. It looks nice!

**Comment by OJFord** [comment]
@k0nserv That mockup has a title bar though, it's just styled to be the same as your background?

For me at least, 'no title bar' means:
1. No title (in your mockup: '4:4:work Hugo-macbook.local')
2. No window buttons (in your mockup: standard mac traffic lights)
3. No unused strip along the top (in your mockup: coloured as background, but not used as a terminal row)

**Comment by k0nserv** [comment]
Yeah, it's not without title bar that's true.

**Comment by monouser7dig** [comment]
![marta](https://marta.yanex.org/data/images/kon.png)
@OJFord ..still think this looks much better than the default grey.

The iTerm title bar color is actually a [bit of a hack](https://codematters.blog/custom-iterm2-titlebar-background-colors-a088c6f2ec60) not a real setting.
So alacrity could offer a real setting/ native implementation.

**Comment by kutsan** [comment]
@monouser7dig What is this app?

**Comment by sodiumjoe** [comment]
iterm2 has a native option to hide the title bar now:

![2017-11-26 at 1 22 pm](https://user-images.githubusercontent.com/845857/33244493-21357d18-d2ad-11e7-84df-0c067f007122.png)

![2017-11-26 at 1 25 pm](https://user-images.githubusercontent.com/845857/33244505-571a7d98-d2ad-11e7-84b5-123c3bb498d7.png)


As well as a dark title bar option:

![2017-11-26 at 1 24 pm](https://user-images.githubusercontent.com/845857/33244500-38e70e86-d2ad-11e7-9f6f-23c62b61f69d.png)

![2017-11-26 at 1 25 pm](https://user-images.githubusercontent.com/845857/33244502-444ab052-d2ad-11e7-8c99-65dd1eaef753.png)

**Comment by robertgzr** [comment]
I opened a PR with some of the groundwork in https://github.com/tomaka/winit/pull/389

**Comment by will118** [comment]
I've been running this daily on all my machines for over a year now with no issues:

<img width="1440" alt="screen shot 2018-02-01 at 19 24 15" src="https://user-images.githubusercontent.com/4598326/35698620-8ac60902-0785-11e8-99dd-873d0bbb7e4b.png">

99.9% of the time it's fullscreen (not that awful single-app macOS "fullscreen"), and looks like this:

<img width="1440" alt="screen shot 2018-02-01 at 19 25 26" src="https://user-images.githubusercontent.com/4598326/35698667-ad331444-0785-11e8-89f2-9995349f1d9e.png">

From the complete lack of interest here I guess it was deemed too hacky or complicated which I can appreciate 😄

I was under the impression if you set `NSBorderlessWindowMask` you need to return `YES` from `canBecomeKeyWindow` (a readonly property, hence my objc subclass). Without this, the window won't receive input events.

I saw there's a PR against `winit` so I guess I'm wrong, it's been a few years since I've done any real Cocoa development. I look forward to trying it out when it's merged.

**Comment by robertgzr** [comment]
@will118 

Yeah the `canBecomeKeyWindow` thing is the reason why you can't resize the window if you run alacritty with `decorations: false` on macOS (https://github.com/tomaka/winit/issues/368)

And I'm not sure if the winit folks want more mac specific code, especially if it's going to involve a lot of `cocoa-rs` fiddling - if it is even possible to subclass NSWindow without making changes to that😓

For this issue I like [this approach](https://github.com/jwilm/alacritty/pull/947#issuecomment-360908642) because it looks nice with the rest of the OS.
I do think winit should have this "fake" fullscreen feature though.

**Comment by monouser7dig** [comment]
> I've been running this daily on all my machines for over a year now with no issues:

...the issue for some is that you can't properly resize/ move anymore using the mouse 

> (not that awful single-app macOS "fullscreen"),

...which is completely subjective, e.g. I prefer the other fullscreen it just depends...


so are those 
> For this issue I like [this approach because](https://github.com/jwilm/alacritty/pull/947#issuecomment-360908642)

> [I opened a PR with some of the groundwork for this in tomaka/winit#389](https://github.com/tomaka/winit/pull/389)

going to get merged some time sooner than later 😃

**Comment by rafi** [comment]
PR #947 has been merged 2 months ago, hiding the title-bar is now possible via:
```yml
window:
  decorations: false
```

**Comment by kutsan** [comment]
@rafi I am on HEAD and it doesn't work. What is the thing that I am doing wrong?

**Comment by mwcm** [comment]
setting decorations: false breaks Spectacle window management for me too, can't resize or move Alacritty window around using spectacleapp.com

**Comment by robertgzr** [comment]
@mwcm 

yes that's a problem on macOS, see the [discussion here](https://github.com/jwilm/alacritty/pull/947#issuecomment-352350723)...

Unfortunately the problem lies with `winit` and while the fix for moving windows (at least using the mouse) is rather easy, making borderless windows behave as users would expect requires substantial changes to how `winit` handles them on macOS.

**Comment by sodiumjoe** [comment]
@paulrouget thanks for the pointer, I just built with a local version of winit with the subclassing code from that link copy-pasted in and it works great! I'll work on a pull request into winit as soon as I get some time.

**Comment by sodiumjoe** [comment]
winit PR: https://github.com/tomaka/winit/pull/408

**Comment by i-oliva** [comment]
It's

```
window:
  decorations: false
```
now :)

**Comment by ryuta69** [comment]
It's 

```
window:
  decorations: "none"
```

now

**Comment by gavvvr** [comment]
I see the current version with `decorations: none` works with Spectacle. But I am used to use similar app from AppStore called Magnet and it stops working after turning off decorations. Can I fix it somehow?

**Comment by OJFord** [comment]
@gavvvr Ask Magnet's developers, not here. Sounds like it's assuming the title bar exists and somehow using it though - maybe it uses AppleScript to 'click' on it and 'drag' it into position - so you're probably out of luck unless they're willing to change how it works.

**Comment by hexpwn** [comment]
> PR #947 has been merged 2 months ago, hiding the title-bar is now possible via:
> 
> ```yaml
> window:
>   decorations: false
> ```
I've looked at the documentation in the config file and searched for feature requests but didn't figure this out.. 

Is it possible to hide titlebar but NOT the border?

Thanks

**Comment by chrisduerr** [comment]
It is not.

**Comment by thiagowfx** [comment]
The current setting is `decorations: none` or `decorations: full`. There's no `decorations: false`.

**Comment by shendypratamaa** [comment]
![Screenshot 2021-12-27 at 07 05 53](https://user-images.githubusercontent.com/76093597/147423061-f3be5c1d-2786-4979-832b-e23c6bc781b0.png)

window:
decorations : Tranparent,

**Comment by xbladesub** [comment]
So how to remove title bar finally?

**Comment by xbladesub** [comment]
> So how to remove title bar? decorations: none doesn't work - no effect at all

finally worked with: 
```yml
window:
  decorations: None
```

**Comment by faruzzy** [comment]
I made it work with
```
window:
  decorations: "Buttonless"
```

**Comment by heeh** [comment]
They even added log
```
[ERROR] [alacritty_config_derive] Config error: decorations: invalid type: boolean `false`, 
expected one of `Full`, `Transparent`, `Buttonless`, `None`
```
