### ISSUE TITLE
add retro effect ( just because it's cool :) )

### ISSUE THREAD

**Issue by 257** [jwilm/alacritty#1682]
something akin to this:
https://github.com/Swordfish90/cool-retro-term

**Comment by chrisduerr** [comment]
I don't think this is within scope of this project, since the goal of Alacritty is to stay on the simple side rather than getting every feature possible in.

Not only would this feature be expensive to develop for how useful it is, but it would also introduce additional maintenance burdens for a 'gimmick' which isn't expected to be used on a regular basis.

There might be some trickery possible with the shader files, however I do not think that the full effects of the 'cool-retro-term' application are possible just using those.

I would recommend making use of the cool-retro-term when you're in the mood for a bit of retro term fun, while sticking to Alacritty when the goal is simplicity and speed. That way both terminal emulators can stick to what they do best.
