### ISSUE TITLE
Appveyor script can pass even if tests fail

### ISSUE THREAD

**Issue by zacps** [jwilm/alacritty#1724]
See https://github.com/jwilm/alacritty/pull/1723

**Comment by chrisduerr** [comment]
Windows support on Travis has been pretty good recently. I'm open to testing out going with changing the stable Windows build on Travis to fail the build.

**Comment by zacps** [comment]
Yeah it should be fine to take it out of allowed failures, I'll try get this fix done anyway though.

**Comment by chrisduerr** [comment]
Note there's one thing I've noticed which regularly leads to failure of the Window test on Travis: The winpty test.

It seems like this takes so long to run without any output, that travis stops it on a regular basis. I believe the cut-off point is 10 minutes for that. Seems to be right on the border since it sometimes does work and sometimes doesn't. That should probably be resolved before making the decision to leave appveyor behind.

**Comment by chrisduerr** [comment]
I believe this has been fixed.
