### ISSUE TITLE
Accept only limited number of protocols for URL launching

### ISSUE THREAD

**Issue by matthiaskrgr** [jwilm/alacritty#1727]
The new clickable-url detection thinks that strings like `std::marker::Send` are a link and can be opened with a browser. This seems like a false positive to me.

Is there some regex that can be tightened up a bit?

**Comment by jedahan** [comment]
So `std::marker` should be a valid IPv6 url, but I think `std::marker::Send` is not, because having two `::` makes their positioning unclear. I'll see if I can open a bug for the crate, though it won't fix all the false positives it should help with some.

**Comment by jedahan** [comment]
Another alternative: safelist known protocols. Perhaps manually to start (with http/https/git/mailto/ftp), and then maybe through some xdg utils.

**Comment by chrisduerr** [comment]
Looking at the regex which URxvt uses, I'd probably also recommend `news://`, `file://` and `www.` as valid URL starts. The only problem with this is that `www.` is not a valid URL.

The complete regex can be found here:
https://github.com/exg/rxvt-unicode/blob/0767fe71f667f5be4e8967ca6ea27e2b14c19daf/src/perl/matcher#L95

Maybe using the URL crate to verify links is not necessary? I'm sure we could try going without, otherwise we'd probably have to either prepend `http(s)://` when the potential URL starts with `www.` or just ignore `www.alacritty.io` as a valid URL.

The more I think about this, the more I like the idea of just accepting a limited amount of protocols. I think we've already got a fairly big collection in this issue, so I doubt people would run into a lot of problems. And we could always expand that when users run into problems. I'd recommend against making these a configuration option though.

**Comment by chrisduerr** [comment]
Note that I just saw that even stuff like `event:` is a valid URL. Which is fair, because it is. But I don't think it should ever be accepted. So before a point release, I'd like to refine the URL clicking behavior.

**Comment by jedahan** [comment]
Using `Url::parse` makes it easy for us to check if a a protocol is in a vec of safelisted ones with a small change [to src/term](https://github.com/jwilm/alacritty/blob/master/src/term/mod.rs#L140). Dropping the dependency on `url` to do something like `if buf.starts_with('http://') || buf.starts_with('https://') || buf.starts_with('mailto://')...` or something similar would work too, but once we start parsing parts / adding a regex I'd err on re-using the work done on url. Everything after that first line in the rxvt regex makes me feel :/

Its easy to add protocols, harder to remove. How about we start with a small number and be open to new contributions for more? Another benefit is that it would be low hanging fruit for new contributors to add more protocols.

* http
* https
* mailto
* news
* file
* git
* ssh
* ftp

Could we make the 'www.' matching discussion a separate issue? It feels like it opens a can of worms regarding `[:word:].[:tld]` matching for convenience and I'd rather be conservative for now.

**Comment by chrisduerr** [comment]
@jedahan Everything you said seems sound and sane to me. I fully support taking that approach.

Adding support for `www.` could potentially be done with a heuristic (if starts with www => add http(s)), but since it's not actually a URL protocol, that seems better fit for a separate issue.
