### ISSUE TITLE
Not properly working on Arch Linux

### ISSUE THREAD

**Issue by philk982** [jwilm/alacritty#1742]
This issue occurs on a freshly installed Arch Linux in a VirtualBox VM. I'm using X11 and installed alacritty through `pacman -S alacritty`. When running alacritty I get the following error:

```
$ alacritty
problem with config: env: invalid type: unit value, expected a map at line 17 column 1; Using default value
thread 'main' panicked at 'Failed to initialize any backend!
    Wayland status: NoCompositorListening
    X11 status: LibraryOpenError(
    OpenError {
        kind: Library,
        detail: "opening library failed (libXcursor.so.1: cannot open shared object file: No such file or directory); opening library failed (libXcursor.so: cannot open shared object file: No such file or directory)"
    }
)
', /build/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.15.1/src/platform/linux/mod.rs:428:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Maybe #275 is somehow related..

Let me know if any additional information would be helpful.

**Comment by chrisduerr** [comment]
Could you provide some more information about what system you're running?

Are you running Wayland?

Are you running X11 without a compositor?

**Comment by philk982** [comment]
I'm running 4.18.16-arch1-1-ARCH in a VirtualBox VM with X11 and bspwm without a display manager. As far as I know I'm running X11 without a compositor.

**Comment by dnkl** [comment]
Is `libxcursor` installed?

**Comment by philk982** [comment]
Nevermind. Had to install `libxcursor` and `libxi` manually and now it works.

**Comment by chrisduerr** [comment]
Seems like it's possible to install Alacritty without having all required dependencies on Archlinux. This is probably uncommon, since `libxcursor` is required by `ffmpeg` and `gtk3`, but the package dependencies probably should still be updated.

I've added a comment to the package, hopefully that should resolve the issue in the future.

**Comment by shibumi** [comment]
Hi alacritty arch linux maintainer here. I will add `libxcursor` and `libxi` as dependencies. Just one question to the devs: Has alacritty native wayland support? so are these packages needed for running alacritty on wayland via xwayland and libxcursor? Because if not, I would add the dependencies as optional.

**Comment by chrisduerr** [comment]
@shibumi Alacritty does have native Wayland support in theory, however it has some problems so I believe that running it through XWayland is pretty common.

I'd probably recommend just adding them as fixed dependencies.
