### ISSUE TITLE
Crashes on startup in MacOS Mojave

### ISSUE THREAD

**Issue by ColdSauce** [jwilm/alacritty#1749]
Which operating system does the issue occur on?

MacOS Mojave 10.14

I downloaded both the `Alactritty-binaries.dmg` as well as the `Alactritty.dmg` files. Both of them closed after startup. Not sure how to find out more about what happened since I'm not super familiar with how MacOS `.dmg` files work.

Going to install from source in the meantime and see if that works.

**Comment by ColdSauce** [comment]
Building with `make app` failed with the following:

**Comment by chrisduerr** [comment]
@ColdSauce When building from source, please make sure you're using the latest stable compiler.

I'm not a macOS user and because of that I don't know anything about macOS, but .DMG seems to be a common container format for app distribution on macOS. Since it's a container, you probably can't execute it directly.

I'd recommend following available online instructions on how to make use of these files. Here's one picked at random which looks promising:
http://www.ofzenandcomputing.com/how-to-install-dmg-files-mac/

**Comment by ColdSauce** [comment]
@chrisduerr Thanks for the quick response!

I am familiar with installing .DMG files, however the released DMG file did not execute properly so I thought if I ran it with the command line, I would get an error message in order to make debugging easier. Just wanted to report that the released .dmg did not run correctly.

**Comment by chrisduerr** [comment]
What do you mean by `did not run correctly`? A .dmg should not be run, it should be mounted and extracted. I'm not quite sure how it is 'run'.

**Comment by ColdSauce** [comment]
Sorry, I mean I extracted the .app file and ran that file. It started, and quit right away.

**Comment by ColdSauce** [comment]
Update -- I managed to get it to not crash right away by starting it from another terminal: 

`open -a Alacritty`

Starting from Finder made it crash, starting from terminal was just fine. Strange.

**Comment by chrisduerr** [comment]
If starting it from finder makes it crash, but starting it from another terminal works just fine, I'd assume that the problem is with your PATH.

Try changing the shell to add the parameter `--login` or use the `/usr/bin/login` program as shell. This should help set the correct PATH.

It works when starting from a different terminal emulator, since it's probably inheriting the environment variables.

**Comment by ColdSauce** [comment]
That was it! 

For potential future viewers: 

Added the following to my `alacritty.yml` file, for me, located it in `~/.config/alacritty/alacritty.yml`

```
shell:
  program: login
  args: ["-fp", "USERNAMEHERE"]
```

Thanks for the help 😄
