### ISSUE TITLE
Allow cursor to be overdrawn outside glyph box

### ISSUE THREAD

**Issue by tokyovigilante** [jwilm/alacritty#1759]
Which operating system does the issue occur on?
macOS

In Sublime Text, the height of beam cursor is such that it is rendered slightly outside the glyph bounding box as shown. This is good for visibility, particularly on HiDPI screens.
<img width="468" alt="st3 beam cursor" src="https://user-images.githubusercontent.com/12971/48193514-8562ee00-e342-11e8-95bb-55faed92b57d.png">
I have been trying to achieve the same thing in alacritty, however while I can increase the height and thickness of the cursor, I do not seem to be able to move the top of the glyph box above the zero position, so while the bar is as long as I would like, it is not in the correct position:
<img width="518" alt="alacritty enlarged beam cursor" src="https://user-images.githubusercontent.com/12971/48193791-3b2e3c80-e343-11e8-97bf-c22650ea7999.png">

It would be good if alacritty was able to render the cursor slightly outside the glyph bounding box as shown.

Code I am currently using:
```rust
@@ -263,15 +264,16 @@ pub fn get_beam_cursor_glyph(
     width: i32,
 ) -> Result<RasterizedGlyph, Error> {
     // Create a new rectangle that is at least one pixel wide
-    let beam_width = cmp::max(width * CURSOR_WIDTH_PERCENTAGE / 100, 1);
-    let buf = vec![255u8; (beam_width * height * 3) as usize];
+    let beam_width = cmp::max(width * CURSOR_IBEAM_WIDTH_PERCENTAGE / 100, 1);
+    let overdraw = 3;//CURSOR_IBEAM_VERTICAL_OVERDRAW/100*height;
+    let buf = vec![255u8; (beam_width * (height + overdraw * 2) * 3) as usize];

     // Create a custom glyph with the rectangle data attached to it
     Ok(RasterizedGlyph {
         c: BEAM_CURSOR_CHAR,
-        top: ascent,
+        top: ascent - overdraw,
         left: 0,
-        height,
+        height: height + (overdraw * 2),
         width: beam_width,
         buf,
     })
```

**Comment by chrisduerr** [comment]
This issue has been open for quite a while and it looks like I must have missed it since it has neither tags nor any comments, so sorry for that.

I'll be direct here, this is something I'd pretty clearly consider unfit for Alacritty. Not only do I question how a slightly bigger cursor would make it easier to find (if you have troubles with confusing it with |, l or I, that's kind of a font issue), I also think that even if we would implement it, it would never get used much and it would bloat the configuration file.

Because of that, I'm going to close this issue. This is not necessarily a definite 'no', since things might always change in the future, so if people are interested in this feature leaving a comment here would be useful, but it does mean that it's not going to be implemented at the moment and pull requests which implement it will not be accepted, just to make sure nobody wastes their time.

**Comment by tokyovigilante** [comment]
That’s fine, thanks for your feedback. I still like it and would be prepared to maintain my own small patch if it’s not widely applicable. 

However I’m also finding it necessary to increase the thickness of the cursor independent of it’s height on a HIDPI screen. I’m getting my new ThinkPad next week which has a 14” 4K display that i’d run at a 2x multiple. I’ll see how the cursor looks with the standard width there. 

Would you consider a patch to add an option just to scale the cursor width with a HIDPI scaling factor? Or maybe I should just get new glasses...

**Comment by chrisduerr** [comment]
> Would you consider a patch to add an option just to scale the cursor width with a HIDPI scaling factor? Or maybe I should just get new glasses...

The cursor size is scaled. It is not a fixed width single pixel cursor.
