### ISSUE TITLE
Feature request: Tiling

### ISSUE THREAD

**Issue by hastebrot** [jwilm/alacritty#178]
Layout terminals in any fashion by splitting them horizontally or vertically.

This feature is supported in some terminals, e.g. [Terminology](https://github.com/billiob/terminology) and [Terminix](https://github.com/gnunn1/terminix).

I know according to the blog Alacritty strives for simplicity and `tmux` could be used, but this is really a useful feature to have directly in the terminal.

Example key-bindings (taken from Terminology):

- `Ctrl+PgUp` &mdash; switch focus to previous terminal inside a window
- `Ctrl+PgDn` &mdash; switch focus to next terminal inside a window
- `Ctrl+Shift+PgUp` &mdash; split terminal horizontally (1 term above the other)
- `Ctrl+Shift+PgDn` &mdash; split terminal vertically (1 term to the left of the other)

**Comment by hastebrot** [comment]
Also: If this feature is considered to much bloat, at least a paragraph how to use `tmux` for simple tiling could be added to the `README.md`.

**Comment by Gonzih** [comment]
Just use tmux.

**Comment by ton** [comment]
Or a tiling WM.

**Comment by hastebrot** [comment]
@Gonzih @ton 

>tiling window manager

What if I want to use Unity on Linux or I want to use macOS/Windows?

>tmux

What if I don't want to learn/configure/install `tmux`? Sometimes `tmux` could be consided as a "hack".

**Comment by topaxi** [comment]
> `vim` / `nvim` behave differently.

vim has native tiling builtin, nvim even supports starting a terminal in vim-windows.

I personally avoid terminals with too much functionality builtin, especially if its already solved in several different ways.

**Comment by lukaslueg** [comment]
I hope not. Tiling and scrolling are in fact done much better within the terminal than by the terminal.

**Comment by Gonzih** [comment]
@hasterbrot problem tha you are describing is being solved by tmux, vim, terminator, awesome, xmonad and etc. I don't think there is also need to solve this proble in every possible terminal emulator. Unecessary feature for sure.

**Comment by hastebrot** [comment]
>Tiling and scrolling are in fact done much better within the terminal than by the terminal.

@lukaslueg Maybe I configured `tmux` not correct, but selecting text and changing panes with the mouse does not work good enough.

**Comment by hastebrot** [comment]
So, as initially mentioned, something like tiling probably doesn't fit into the idea of simplicity for this project. I'll close this issue, if there is no big interest.

My arguments are, that there are use-cases, where someone doesn't want to use tiling window managers or terminal multiplexers. Having basic functionality like horizonal/vertical split panes and switching to next/previous pane could be easy to implement.

If someone wants to implement this feature in a separate feature fork, questions like

- How to start multiple terminal/shell sessions?
- How to restrict one shell to a certain window area?
- How to add the key-bindings into a configuration file (no settings dialog needed)?

need to be answered.

**Comment by jwilm** [comment]
I appreciate your thoughtful comments here, but there's no way such a feature is making it into Alacritty.

As you pointed out yourself, there are plenty of terminal emulators to choose from that offer this feature.

**Comment by freshtonic** [comment]
I became interested in Alacritty because it's fast. However, tmux on a mac is not fast. It even says so in the Alacritty FAQ. So until either Alacritty provides native tabs & panes or a wrapper app is written around the core of Alacritty that provides native tabs/panes I'm pretty much alienated.

**Comment by chrisduerr** [comment]
@freshtonic Pretty much everything you've mentioned is definitely planned. There's #1544 for tabs on macOS, which might need a bit of work, but doesn't require any additional rendering complexity.

The #1023 PR also lays the initial foundations for extracting Alacritty's core into a library to allow others to extend it.

These changes will probably take some time until they land, but hopefully they'll make Alacritty available to a broader audience without sacrificing any of its goals.

**Comment by freshtonic** [comment]
@chrisduerr that's fantastic news. Thanks for the update!

**Comment by hgkamath** [comment]
Just penning a '2 cents'. 
I was searching for a cross platform terminal that does cross-platform tiling, for uniform experience reasons.
My understanding is limited, you folks know more, please disregard if not relevant.
I am also new to trying out alacritty and other terminals
This seems like a way to abstract out 
 "tiling/split window/split pane/resizing events", 
 "terminal multiplexing/tty sharing (GNU-screen/tmux/et etc) ",
  and "re-connection, session maintenance by server with a logged-in/tty with shell open"

https://github.com/MisterTea/hyper-htm
A javascript plugin for another terminal app hyper.js, which talks over the network to the 'et'

https://github.com/MisterTea/EternalTerminal
et: eternal-terminal Re-Connectable secure remote shell 
The et opens a local-tty and maintains the connection with the terminal app via the tiling plugin.

It seems like an attempt at making a standard protocol to negotiate tiling

( terminal-app -> tiling-plugin )    --n/w->  ( terminal-session-manager => tty-by-OS )

So when the tile boundaries are changed even a remote terminal can also adapt to it. 

This bug is closed, but didn't know where to note this. So referencing
[]  tmux doesn't recognize alacritty (#2487)
[]  Support multiple windows (#607) 
[]  Default to ConPTY instead of WinPTY #2890 
[]  Feature request: Tiling (#178) 
[] Add support for the new native ConPTY API in Windows 10 (#1661)

**Comment by alexherbo2** [comment]
For tabs, there is [tab].  It does not provide multiplexing, but provides facilities to switch between contexts.  The sole shortcut is `Ctrl-t`.

[tab]: https://github.com/austinjones/tab-rs

There is also [Pueue] which can be nice when you don’t need a terminal.

[Pueue]: https://github.com/Nukesor/pueue

**Comment by s-at-ik** [comment]
PR #1023, mentioned by @chrisduerr, has been abandoned. Is there still an ongoing effort to "librify" allacritty? And if so is there anywhere one can follow the general progress?

I believe there are arguments to be made in favor of tiling support directly in the terminal emulator (I guess I wouldn't stumble upon a 7 years old issue otherwise :stuck_out_tongue: ):

- window manager tiling is not cross-platform (this is especially relevant to Alacritty as many other terminal emulators are tailored to a specific OS/environment any way)
- window manager tiling can be cumbersome (e.g. switching between tiles, or alternating between tiles and full screen application)
- window manager tiling is overkill when you only need tiling for the terminal
- tmux tiling offers abysmal performances in comparison to any higher level tiling I've used

**Comment by kchibisov** [comment]
you can use `alacritty_terminal` crate, it's already used by some editors written in rust to provide a terminal, and also there's a terminal based on alacritty called `rio`.
