### ISSUE TITLE
crash on suspend-resume cycle with 0.2.3

### ISSUE THREAD

**Issue by chutz** [jwilm/alacritty#1789]
Which operating system does the issue occur on?
Linux
If on linux, are you using X11 or Wayland?
X11

Crash after suspending and resuming my laptop, this is 100% reproducible.
```
thread 'main' panicked at '[winit] Failed to find any monitors using XRandR.', libcore/option.rs:989:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
Setting RUST_BACKTRACE=1 does not produce anything meaningful, I would probably need debugging symbols in my system C libraries.

**Comment by chrisduerr** [comment]
Can you check if this is reproducible with the winit example? It's available here: https://github.com/tomaka/winit.

You should be able to test it by running the following command:
`git clone https://github.com/tomaka/winit && cd winit && cargo run --example window`

If this can be reproduced with just the winit example, this should probably be reported upstream in the winit issue tracker. Feel free to open an issue yourself if you can reproduce it, otherwise I'll create one.

**Comment by chutz** [comment]
The same thing happens with the winit example, this is at least somewhat recently added. I know I have been able to suspend/resume with alacritty running before.

**Comment by chutz** [comment]
I filed a but upstream at winit:
https://github.com/tomaka/winit/issues/705

**Comment by jonpas** [comment]
https://github.com/rust-windowing/winit/pull/1158 was merged, which should in turn fix this alacritty crash.

**Comment by chrisduerr** [comment]
This will be fixed with https://github.com/jwilm/alacritty/pull/2438.

**Comment by hazeled** [comment]
This still happens on my machine

**Comment by matthewcm** [comment]
This also happens on my machine every morning, alacritty just hangs, but can see a cursor on the top left, but thats it. When the pc suspends for just an hours, alacritty usually just takes a few minutes to redraw.
