### ISSUE TITLE
Reloading config file should trigger a redraw

### ISSUE THREAD

**Issue by jwilm** [jwilm/alacritty#18]
Filing as a bug since it appears broken when colors don't refresh immediately.

**Comment by jwilm** [comment]
This was fixed a while ago

**Comment by krishicks** [comment]
I've seen this work and also not work. A few days ago I switched colors around and noticed them changing immediately. Today I've done the same and noticed them not change unless I open a new instance of alacritty.

**Comment by jwilm** [comment]
There was a patch recently that fixed an issue with colors reloading after OSCs had modified them. Could you try with the latest master?

Commit with fix: 6495ab34d2043440f138242cf58d39e687e6c02e

**Comment by krishicks** [comment]
I pre-emptively did just that and am seeing the expected behavior: instantaneous change on save. However, it also worked a few days ago after a fresh reboot.

I'll return to this after a few days to see if it still functions.

**Comment by srjefers** [comment]
Existing way to manually **reload** the config file?

Now I have this problem too, sometimes it just works with font-size

**Comment by chrisduerr** [comment]
There are certain parts of the config file which do not support live reload. For example the font family.

For most other settings automatic font reload is supported and should take effect, if you want to 'manually' reload a certain setting, you need to restart Alacritty. Since the settings that don't automatically reload often aren't enabled to do so because there's too much complexity involved.
