### ISSUE TITLE
ubuntu:  failed to load source for a dependency on `winpty-sys`

### ISSUE THREAD

**Issue by mirza-s** [jwilm/alacritty#1848]
Which operating system does the issue occur on?

```
Ubuntu 18.04.1 LTS
```

If on linux, are you using X11 or Wayland?

```
X11
```

Using v0.2.3:
```
cargo build --release
    Updating git repository `https://github.com/zacps/winpty`
error: failed to load source for a dependency on `winpty-sys`

Caused by:
  Unable to update https://github.com/zacps/winpty?branch=rust#9ccec645

Caused by:
  revspec '9ccec6459c2c8b7555846910c12ba697b688f44d' not found; class=Reference (4); code=NotFound (-3)
```

**Comment by Ace4896** [comment]
I got this error as well for 0.2.2, this was changed in 6f4ad9bb4f82bfdc4d8aac883a65ddd8c6acd45d (after 0.2.3 was released) where the `winpty-sys` crate is used instead of the git repository. Master compiled fine for me because of this change.

If you go to the `winpty/Cargo.toml` and change the line for the `winpty` dependency to be:

`winpty-sys = "0.4.3"`

the crate can be used instead and allows you to get around that error.

**Comment by chrisduerr** [comment]
Yeah, this is unfortunately due to a change which @zacps has made to the winpty-sys crate. The issue is already resolved on the latest master, but it will create problems when building previous versions.

**Comment by robertgzr** [comment]
Wouldn't something like this warrant a new patch release... I'm trying to package alacritty for Solus and this forces me to do some ugly patching :/

**Comment by chrisduerr** [comment]
@robertgzr That's a good point, thanks for the heads-up. Though I believe it should still be buildable without having to apply any patches. I think just running `cargo update` would work.

Based on the current master, I've been planning to release a new version today or tomorrow though. So either way that should be resolved soon.
