### ISSUE TITLE
Crash on macOS while cat-ing a binary file.

### ISSUE THREAD

**Issue by fernandezpablo85** [jwilm/alacritty#190]
Steps to reproduce:

- install alacritty
- go to `target/release` directory
- run `./alacritty`
- on the terminal, `cat libalacritty.rlib`
- the program will crash.

Running it with RUST_BACKTRACE=1 yields:
```
thread 'pty reader' panicked at 'cursor fell off grid', src/term/mod.rs:634
stack backtrace:
   1:        0x10d6c8e8a - std::sys::imp::backtrace::tracing::imp::write::h1461f67be4bf68a9
   2:        0x10d6cb06f - std::panicking::default_hook::{{closure}}::h6dba65b2b498d274
   3:        0x10d6cad17 - std::panicking::default_hook::ha8ecbcff1f59e805
   4:        0x10d6cb536 - std::panicking::rust_panic_with_hook::h5ceed7bd7aef311a
   5:        0x10d60ba54 - std::panicking::begin_panic::hac4cfc1999155f3b
   6:        0x10d625cb2 - <alacritty::ansi::Performer<'a, H, W> as vte::Perform>::print::h5f86d9cf613035bb
   7:        0x10d61dc8e - <alacritty::event_loop::EventLoop<Io>>::spawn::{{closure}}::hd6fb5177d4ce92b7
   8:        0x10d60ba9b - std::panicking::try::do_call::h0094239def3a34ee
   9:        0x10d6cc40a - __rust_maybe_catch_panic
  10:        0x10d61bb7a - <F as alloc::boxed::FnBox<A>>::call_box::h854e414bff848aff
  11:        0x10d6ca744 - std::sys::imp::thread::Thread::new::thread_start::haeb202749da670ee
  12:     0x7fffdf0feaaa - _pthread_body
  13:     0x7fffdf0fe9f6 - _pthread_start
child finished with error '256'
```

**Comment by Zenexer** [comment]
Not sure if this is a separate issue, but if I only print part of a binary file that causes it to crash (in this case, `head -c 10000`), `6c` is sent repeatedly to my shell as if I'd typed it.  The more characters I print, the more times `6c` is repeated.

I've also attached [a 480-byte binary snippet](https://github.com/jwilm/alacritty/files/691649/crash.bin.zip) that causes the crash originally mentioned, but only with the default window size.  (It's compressed as a ZIP because that's the only way GitHub would allow me to upload it.)  Removing the first or last byte will prevent it from crashing.  Interestingly, both bytes translate to printable ASCII chars (`x` and `B`, respectively).

**Comment by mrkev** [comment]
looks like another one for https://github.com/jwilm/alacritty/issues/134

**Comment by jwilm** [comment]
Closing in favor of #63.

@Zenexer maybe a separate issue? Also maybe related to #72
