### ISSUE TITLE
Add an installer for Windows

### ISSUE THREAD

**Issue by zacps** [jwilm/alacritty#1900]
Because Windows has no dedicated package manager, unlike Linux/OSX, the main method used for installing Windows programs is through the `.msi` format.

I started investigating using `cargo wix` for generating an installer, this could potentially be used with [self_update](https://crates.io/crates/self_update) for automatic updates.

Initial work at [zacps/alacritty#cargo-wix](https://github.com/zacps/alacritty/tree/cargo-wix).

**Comment by chrisduerr** [comment]
> Because Windows has no dedicated package manager, unlike Linux/OSX

I've recently merged a PR with install instructions for scoop, I believe there's also another package manager with a name closed to chocolate. So while a linux-like package manager doesn't exist, a macOS-like third party addon does.

I still think it would be a good idea to have a way to install on Windows without these package managers though, since I don't think they're commonly used. The user would still have to update manually, but maybe the `watch releases` option on github is sufficient to resolve that problem for now.

**Comment by zacps** [comment]
Yeah, there are a couple of them, but they're very much a minority.

What do you think about using that crate for updates? I can see why you'd want to keep packaging/updates separate from the main binary, but it does seem like the simplest solution to me.

**Comment by chrisduerr** [comment]
As long as the code is clean and I am never bothered by it on Linux, I'd be fine with it. Though I'm not a huge fan, but there's little that can be done since it's just due to Windows' awful package management.

I'd be very concerned with the UX of updating though. We aren't gonna add any UI options, since Alacritty doesn't do that kinda stuff, so the only option seems to be to automatically update at startup. That might not only affect startup times significantly, it could also lead to a forced update situation which might prevent users from running older builds, when the latest stable breaks stuff. Both of these seem like deal-breakers to me.

If there's a decent way to do it, sure. I just don't know how I would go about doing it. There's a good reason why this is done by external applications on most operating systems. Patching it into Alacritty itself is just not going to work out extremely well.

Just showing an update notice with the text display we use for warnings/errors might be an option. But at that point there's no reason why we'd need to depend on a crate to update things. Combining that with an external script for updates is of course an option, but I think we're already distributing enough files on Windows, that's just going to make things way too complicated for the user.

If you have any ideas how this could work out well, I'm all ears. But it doesn't seem like we can just pull in the crate and we're good to go.

**Comment by zacps** [comment]
My idea is to have a configuration option (default or not can be bikesheded) which enables automatic updates. If it's on, when Alacritty starts an update would be downloaded in background. Then when it's ready we could show a 'Restart to apply updates' notice.

That makes it relatively easy to stay on a particular version and relatively undisruptive otherwise.

**Comment by prabirshrestha** [comment]
Please no `.msi`. It is very slow. Takes forever to install nodejs which is around 20mb. I personally prefer vim's MUI2 installer and hate all MSI installers. MUI2 is very fast. https://github.com/vim/vim-win32-installer. It auto removes the old vim and preserves the old settings when installing.

Also would love to have an option for `Open in Alacritty Here` and `Open in Alacritty Here (admin)` when installing.

Or event better if the setup was similar to [clink](https://mridgers.github.io/clink/). Let alacritty.exe have it's own installer i.e. all it needs to do is copy it to appdata and add modify some registry so it shows up in control panel remove programs, add shortcut to desktop and start menu, add explorer menu. It is both portable as well as installable.

```
alacritty --install
```

You could then have `-i` or `--interactive` mode for asking few questions in CLI or `--gui` for interactive gui. Or even other flags that tells not to add desktop shortcut and so on.

**Comment by zacps** [comment]
The vim installer is not a library, so obviously not an option.

MSI, while it may not be perfect, is the canonical solution. There is something to be said for uniformity in the instillation experience.

I'd also like to have an 'Open Alacritty here' option, and is one of the main motivators for an installer for me.

Alacritty having its own installer is problematic. We need an external binary (`winpty-agent`), and writing binaries out of `.text` is generally frowned upon by virus software. To be honest I don't think packaging/installation code has any place in the main binary anyway.

**Comment by eberkund** [comment]
I wouldn't mind working on this, MSI/Wix is definitely the way to go.

What functionality should the installer have? So far I can think of:

- Copy alaritty.exe and winpty-agent.exe to Program Files
- Copy the default config file to `%APPDATA%`
- Add a context menu shortcut to open alacritty in the current directory
- Add the Program Files folder to `$PATH`

Is there anything else? Ideally once this is done it can be submitted to [chocolatey](https://chocolatey.org/) and the installation process will be really smooth.

**Comment by chrisduerr** [comment]
I'm not very familiar with Windows, but that sounds pretty good to me @eberkund.

**Comment by prabirshrestha** [comment]
As for context menu it would be good to have “open alacritty in admin mode”

**Comment by eberkund** [comment]
Is Appveyor CI integration working? Because to build Windows installers with Wix you need a Windows environment.

**Comment by chrisduerr** [comment]
@eberkund We've replaced Appveyor with Travis' new Windows CI. As you can see in the releases, this allows us to build Windows binaries and will likely work with Wix too.

**Comment by chrisduerr** [comment]
It might be nice to somehow make context menu entries optional, I'm not representative of an average Windows user at all, but I could imagine that some people would get bothered by this.

This could be done with either a feature flag, or the context menu shortcut could be added at runtime with an Alacritty CLI flag, I'm not quite sure about that myself (I'm also not familiar with MSI/Wix, so I don't know what options we have there).

**Comment by eberkund** [comment]
Oh great, I didn't know Travis had Windows CI.

With MSI that can be an optional feature that is installed, if the user is installing with the MSI GUI then they can uncheck that feature or set with a command line flag if installing with say chocolatey.

**Comment by Starz0r** [comment]
@eberkund [Chocolatey](https://chocolatey.org/packages/alacritty) support for Alacritty got added by me already via this [PR](https://github.com/jwilm/alacritty/pull/2130) and this [image](https://github.com/Starz0r/alacritty-choco) for packaging the application.

However, MSIs would make the install and uninstall process a lot more "official", and a lot less time-consuming to manage. I'm probably going to need some migration process, since currently the Chocolatey package installs at `C:\tools\alacritty`, which is standard in Chocolatey, but the standard MSI install location is `C:\Program Files\Alacritty`. So I'm going to have to figure out how to handle this for users who have installed previous packages.
