### ISSUE TITLE
Linux: copy paste with ctrl-c/v

### ISSUE THREAD

**Issue by talal** [jwilm/alacritty#1919]
Which operating system does the issue occur on?
Elementary OS 5 (Ubuntu based distro)

If on linux, are you using X11 or Wayland?
X11

Alacritty: compiled latest from master.

I understand that Alacritty uses `ctrl-shift-c/v` but is that just preference or is there some technical limitations for this? 

I am asking because the default terminal app on Elementary OS (as one example) allows copy with `ctrl-c` when text is selected and acts as `SIGINT` when nothing is selected.

I am not sure how other terminal apps do it.

**Comment by nixpulvis** [comment]
As long as ctrl-c also clears the selection so a repeated press will send the `SIGINT` I could see this being a UX win.

**Comment by talal** [comment]
@nixpulvis I recently switched from macOS to Linux as my daily driver and until I switched to Alacritty, this didn't even cross my mind because like I mentioned the default terminal app in the distro uses `ctrl+c` which was very familiar to `cmd+c` of macOS.

P.S. the default app in question does not clear selection on `ctrl+c`.

**Comment by chrisduerr** [comment]
I think this is a really bad idea and there are a couple of reasons that play together why I think it is.

My first issue is mostly about element of least surprise. Would Alacritty configure Ctrl+C as the default for copy/pasting inside the terminal, then a lot of people used to terminal emulators could get really, really confused. This could of course be fixed by not setting it as a default, but then there's a need to document it so people actually know about it.

Now Alacritty does support a scrollback buffer though. So there's no reason why a selection would have to be visible for Ctrl+C not to work. If you ask me that's a UX nightmare. An invisible selection thousands of lines away in the scrollback buffer could be the sole reason why copy/pasting isn't working anymore. And if you set it up so it only works when the selection is visible, then users will get confused again.

So this isn't straight-forward and I do not think there are any good ways to handle it. Building it into Alacritty will always require some special workaround which might affect users unrelated to this feature and it could contribute to a lot of 'weird' heuristics thrown around the codebase. But thinking about the benefits, there doesn't seem to be enough to support this change. People are used to ctrl+shift+c, it works, if you want a key less, you can bind ctrl+copy and ctrl+paste. I feel like this wouldn't solve an issue that doesn't exist.

If there's any better idea to handle this cleanly without running into any of the issues I've mentioned, please let me know. But as far as I'm concerned there doesn't seem to be a good way to implement this and it seems like a shallow UX improvement that would actually make things worse if you actually look more into it.

**Comment by nixpulvis** [comment]
I agree with you about the added complexity probably not being worth it, and I personally prefer simplicity to backward-compatibility or even consistency, in some cases. Here the only "heuristic" I could think of that might help users is the clearing selection on copy thing I mentioned in my last comment, but I too fear it'll be a bit jarring to users.

The primary users who are upset by this are macOS users converting to Linux. They are the users who the current functionality is breaking the principle of least surprise currently. I went through this transition with Alacritty as my primary terminal on macOS and Linux. Re-learning to copy and paste has definitely been a pain point for me, but I'm understanding since I know that ctrl-c is sigint. Hopefully most users are at least somewhat understanding too.

**Comment by talal** [comment]
@chrisduerr with macOS `SIGINT` is never sent (or overlaps with copy) since mac has a special key called `cmd` (similar to the `windows` key on windows) and `cmd+c` is used for copying rather than  `ctrl+c`.

On macOS's default terminal app when the selected text is out of visible region and `cmd+c` is pressed, it is copied and the selection is cleared. However on the iTerm app (a famous terminal emulator on Mac), the selection is not cleared and consecutive `cmd+c` presses simply register as a copy action.

On Elementary OS's default terminal app, the behavior is similar to iTerm: selection is not cleared on copy and copy action is done on consecutive `ctrl+c` presses.

**Comment by chrisduerr** [comment]
Well the `cmd` key is more like `super`, rather than control, right? Nobody's stopping you from mapping copy to super on linux and mapping copy to command should work just as well.

**Comment by talal** [comment]
@chrisduerr yeah, you are right, but it differs in the way that in order to have consistency, I would have to map it globally, not just in the app.

I am aware of the mapping solution and that is what I intend to do in the end, my reason for opening this issue was just to get your thoughts on the pros/cons of the current structure vs `ctrl+c` 😄

**Comment by AlansCodeLog** [comment]
So found this issue because I have started to move to linux from windows and I've been trying different terminal emulators but I hadn't really found any yet that support ctrl+c for copy _and_ terminating commands like Windows has the option to (am trying the elementary terminal now, didn't know it had that). Found this issue searching for if alacritty could, since apart from this, I liked it.

In windows it works similar to the elementary terminal except when something is running it pauses when you select and you can change the selection, then when you hit ctrl+c it clears the selection and continues running. Even without that pausing behavior, I like that first ctrl+c copies, and any subsequent ones terminate.

Actually I just tried the Window's version of alacritty out of curiosity, and it seems to handle things more how I want, but still different then either windows or linux. ctrl+c copies if nothing is running (no new lines on subsequent presses though), otherwise it terminates the running command. That's kind of what I would like in linux, except, subsequent presses should add a new line.

It doesn't have to be the default, but an option to have it work like in windows would be nice, or some way to make the commands context sensitive? Like:
```
 - { key: C, mods: Control, action: Copy when: !was_last_press && not_running}
 - { key: C, mods: Control, action: Terminate when: was_last_press || running } 
```

Also, I can't really find how to set the shortcut to terminate to something else (it autosets it to ctrl+shift+c?). Maybe I missed it but I didn't see it in the list of actions.

**Comment by dtheodor** [comment]
Windows terminals also work like that, in particular WSL. It's not a UX nightmare, on the contrary. It's perfect.

You should expand your worldview and get the good stuff from non-linux terminals and the GUI world in general. Unlearning that copy is "ctrl-shift-c" in the terminal and "ctrl-c" everywhere else, and instead having "ctrl-c" being copy *everywhere*, that was a huge win in my experience. I've used linux terminals for years and the amount of times I killed the running process instead of copying text has not been negligible, because of accidental "ctrl-c" instead of "ctrl-shift-c". And there's the constant mental overhead of having to be aware of which is the right copy shortcut at any given time. On the contrary, being on WSL for a couple of years, it feels liberating. Accidentally killing something just doesn't happen. And if I want to kill the process I'm looking at and "ctrl-c" isn't killing, all I have to do is click on the command line right in front of me (thus unselecting) and "ctrl-c" again. (this is also exactly what you do in another common error when working in windowed GUIs, which is that you think you've selected the terminal window, but some other window is actually selected, so you're trying to do something in the terminal, you see it unresponsive, so you click it thus making it the active window and try again. this process becomes second nature)

> Now Alacritty does support a scrollback buffer though. So there's no reason why a selection would have to be visible for Ctrl+C not to work. If you ask me that's a UX nightmare. An invisible selection thousands of lines away in the scrollback buffer could be the sole reason why copy/pasting isn't working anymore. 

I'm not sure you thought this through. If there's an invisible selection thousands of lines away, everything keeps working just fine. "Ctrl-v", you paste it. select something else and "ctrl-c", you copy something else. "ctrl-c" intended as a SIGINT, and not working? click right in front of you, "ctrl-c" again, it's working.

**Comment by kchibisov** [comment]
On Linux(X11, mostly all Wayland compositors). You can select with mouse without even pressing `Ctrl + C`/`Ctrl + V`, just select the thing and then press your mouse wheel to paste content. We even have `save_to_clipboard` option so you can just select with mouse and it'll be in your clipboard buffer(`Ctrl + V` one), so I don't see a reason on supporting on speculating on `Copy` shortcut, knowing that you can remap it, etc.

**Comment by chrisduerr** [comment]
> Windows terminals also work like that, in particular WSL. It's not a UX nightmare, on the contrary. It's perfect.

Ah, right. The only platform that has ever had problems with ctrl+c not working.

> you're trying to do something in the terminal, you see it unresponsive, so you click it thus making it the active window and try again. this process becomes second nature)

Trying things over and over again without good user feedback until it somehow manages to do what you want doesn't really sound like the pinnacle of UX to me.

**Comment by MattSturgeon** [comment]
The two main arguments against this seem to be

1. It would be confusing if set as default
2. It could be confusing if text is selected without the user realising

The counter argument would be

3. It is confusing if a user manually sets the copy keybind to `Ctrl+C` but they can no-longer send `SIGTERM`, having used other terminals where this works as they expect.

I'd propose that

1. This shouldn't be default. For better or worse on linux, `Ctrl+Shift+C` is the standard for copying in a terminal.
2. Copying should (optionally?) remove a selection. This way if you type `Ctrl+C` twice you are guaranteed to send a `SIGTERM`. If this is optional, perhaps note that this is recommended wherever the dual action `Ctrl+C` ends up being documented.
3. Either document that this is or isn't possible.

Personally, I really like this behaviour having discovered it while using Windows. I like how I don't have to remember to use a different keybind exclusively in terminal emulators. Right now this is the only thing keeping me from using alacritty.

I don't think this has to be particularly intrusive or obnoxious to those who don't want it, but it would be really handy and would work well for those who do.

**Comment by mitar** [comment]
I have made an alternative solution to this in https://github.com/alacritty/alacritty/pull/4195 PR. The idea is that one can use ctrl-c for copy, while using super key for terminal ctrl key. (You can then remap those keys using xkb the way you want, to behave like it behaves on Mac.)

**Comment by mixmastamyk** [comment]
If a selection being off-screen turns out to be a real problem that causes confusion, there could be a temporary popup window of some sort that says "kill action unavailable until selection cleared. Click or press ESC to clear it."  

Perhaps worded differently/better, but that's the idea in a nutshell.

**Comment by nixpulvis** [comment]
Selections which go off the screen are something we explicitly want to support, how else do you copy more than a single page height of text at a time?

> temporary popup window of some sort

This seems like the wrong solution for something like this in general. Popup windows are **very** intrusive. If this was really a concern, which I don't think it is in general, perhaps just a small notice near a potential scrollbar would suffice.

My original concern was that a user who overloaded ctrl-c when a selection was active wouldn't know if that action would be taken or the SIGINT would be fired if the selection was off the screen. But our position is that this kind of overloading is a bad idea.

**Comment by terax6669** [comment]
For the love of everything open source... **do I really have to build a fork to get this feature working?** I know I'm gonna sound... demanding and aggressive and whatever but I'm really upset at this SILLY issue! I hope to be the voice of reason, as clearly my predecessors have failed.

You are the authors and maintainers of one of the best terminal emulators out there. Could you please pull your collective heads out of your collective butts and just GIVE PEOPLE WHAT THEY WANT instead of saying things like "there is no desire to implement this"? There. **clearly. IS.** From THE USERS. This is now the only terminal that I (want to) use that doesn't support this!

I've only glanced at the documentation but IIRC there even are special flags to tell when a keybinding should be active so you can even support special cases like an open text editor if needed (right now ctrl+c works perfectly in Micro so there's no need as far as I can tell).

You don't like it. It's fine. Don't use it. Don't even set it as default. Just give us the OPTION! That's all we're asking! It'll take you an hour merge the existing PR and test it, maybe another hour to fix a stupid bug down the line. Everybody wins. Please.

**Comment by TheSimpleZ** [comment]
@chrisduerr Could you please consider re-opening this issue? Based on the number of upvotes on this issue, a number of duplicate issues, and the fact that there is [a fork](https://github.com/ambiso/alacritty) being maintained that implements this feature, this is something that users want. 

Whether the proposed solution is the correct one or not is up for discussion, but it would be appreciated if you could keep an open mind toward this.

**Comment by chrisduerr** [comment]
This is pretty much the last issue I'd ever consider implementing upstream.

**Comment by TheSimpleZ** [comment]
It's really unfortunate that you have such a strong stance against an opt-in feature. Especially since there are [those who consider this a dealbreaker](https://news.ycombinator.com/item?id=24017440) with Alacritty. 

The implementation could just be something simple, similar to what I have in my fork. And I think you'd gain a lot of love from users.  
Anyone who doesn't want the smart copy behavior can simply go about their day. This wouldn't affect them.

But I guess the only viable solution for us is to find ourselves another terminal that will do the job. 

For those who end up here through google like me: The link above lists a few alternative terminals with this feature. 

Thanks for your time.

**Comment by mitar** [comment]
In meantime, I made a patch for [Gnome VTE](https://gitlab.gnome.org/GNOME/vte/-/issues/276) which enables one to use super key for ctrl, while keeping ctrl as shortcut key.

**Comment by rpbaptist** [comment]
So I'm moving to Wayland and Sway and wanted to use Alacritty. Then I find this issue. It's sad that the author holds a dogmatic stance against user friendliness regarding this simple issue.

Tilix implements this feature just fine without any SIGTERM issues.

@TheSimpleZ Thank you for referencing kitty.

**Comment by Pbotsaris** [comment]
+1 for implementing this feature 👍

**Comment by MichaelThessel** [comment]
+1, this is the only reason I cannot switch to alacritty.

**Comment by f1she3** [comment]
+1

**Comment by melandur** [comment]
+1

**Comment by frabjous** [comment]
I realize +1s are annoying, but this is an absolute dealbreaker, and the arguments against it are completely asinine. I've used this feature on kitty for years now and not once has Ctrl-C done something I wasn't expecting it to do. Think it would be confusing to set it as default? Fine, don't set it as default. Just provide an option. I don't understand at all what your reservations are.

**Comment by ukutaht** [comment]
Same here. I understand and respect the default, but I really love smart copy & paste and I'm planning to only use terminals that support it. At the moment this seems to include just the Mac ecosystem, pantheon-terminal and kitty. I would happily use Alacritty as my main daily driver if it supported smart copy paste.

**Comment by Notarin** [comment]
I know my input is probably unneeded, but i feel the need to say it anyways, I've been using alacritty for awhile, and enjoyed it for the most part, its simplicity was to kill for, however I found myself often accidentally killing programs trying to copy output. This is only a minor inconvenience, but it builds up, eventually It became a deal-breaker. I can no longer use alacritty until this feature is implemented. I know that come certain developers may feel some....way.... about this feature, but I hope we can move past this blunder and just do what we can to make alacritty the best terminal it can be. I understand how it feels to disagree with a user base on a subject and how aggravating it can be, especially when you get backlash for it, but I think I speak for most when I say we just want to implement this feature and move on. So I will reiterate, can we please implement the feature to "smart" copy using Ctrl+c then clear the selection. I really think @nixpulvis really understood the assignment in his first comment.
> As long as ctrl-c also clears the selection so a repeated press will send the SIGINT I could see this being a UX win.

I know I'm being a broken record when I keep saying this, but, I'm aware that this issue has become tense and may have acquired bad-blood, but I'd like to ask everyone to just clear their head, step back, and think about this again with a clean perspective.
I just want alacritty to be the best terminal emulator it can be.

**Comment by kchibisov** [comment]
>killing programs trying to copy output

You know that after you've selected text you don't have to press anything to get it copied? Since it's already in the selection buffer which is on middle mouse button. Alternatively you can yank to clipboard on select, so you can use ctrl + v in other apps.

**Comment by Notarin** [comment]
Yes, I'm aware that this is possible, however I have three issues with this,

1. Force of habit, I am not intending to press Ctrl+c, it just do it out of habit.
2. Matter of preference
3. And lastly, while it usually does, it does not always play nice with browsers/web-pages.

> Alternatively you can yank to clipboard on select, so you can use ctrl + v in other apps.

No clue how to do this. Personally I wouldn't be satisfied with this, but if you could, would you explain this for the other future users who read this thread?

**Comment by kchibisov** [comment]
>> Alternatively you can yank to clipboard on select, so you can use ctrl + v in other apps.

>No clue how to do this. Personally I wouldn't be satisfied with this, but if you could, would you explain this for the other future users who read this thread?

https://github.com/alacritty/alacritty/blob/5c51d528ea8ded63b127a4f17ee6136653db09b9/alacritty.yml#L382

**Comment by Notarin** [comment]
Many thanks.

**Comment by terax6669** [comment]
This is NOT a replacement. I hate it when the terminal accidentally overwrites my clipboard.

Sometimes it happens because I've missclicked. Sometimes it happens when I just want to mark text as I'm reading. Sometimes it happens when I'm trying to highlight something when talking with a co-worker. It just does happen.

Ctrl+c expresses a clear intent.

**Comment by Notarin** [comment]
>  I hate it when the terminal accidentally overwrites my clipboard.

While I agree with you that we need ctrl+c, selecting text by default does not overwrite the clipboard, it instead writes to the buffer, think of it like a second clipboard.

**Comment by terax6669** [comment]
Sorry, I misunderstood. Still I'm gonna argue that half the time I'm copying something from the terminal my intent is to paste it outside. ¯\_(ツ)_/¯

**Comment by Notarin** [comment]
You can, by middle clicking.

**Comment by terax6669** [comment]
But that'd only work on Linux. My goal with Alacritty is to have the same terminal everywhere (home Windows/work Linux).

**Comment by vietvudanh** [comment]
Wow, I didn't think this would cause this much problem. I moved from MacOS to Linux recently and yes, Ctrl+C is confusing and caused a lot of mistakes.

**Comment by Notarin** [comment]
Hello, I'd like to bring attention to this issue again, following my comment/plea for reconsideration we've received no input on the matter from the developers. So to reiterate what I've said before, I plea for everyone, especially the developers, to please consider this feature again with a clean slate perspective. I have long since moved to kitty [as it simply provides this feature as opt-in behavior](https://sw.kovidgoyal.net/kitty/actions/#action-copy_and_clear_or_interrupt). Please @chrisduerr , could you try and look at this issue with a new perspective? I understand that this issue has acquired some feelings, but if we could simply forget I really think this would be a great feature that would make alacritty, an already great terminal, an even better terminal.

**Comment by chrisduerr** [comment]
There's no new perspective to be taken when looking at this issue. Nothing has changed and that also applies to my stance on adding this.

**Comment by Terraphice** [comment]
It's pretty unfortunate that there's no opt-in for this. Better terminals do this, and it holds back Alacritty.

**Comment by frabjous** [comment]
> There's no new perspective to be taken when looking at this issue. Nothing has changed and that also applies to my stance on adding this.

I think people were just hoping you'd reconsider, since your stance is so unreasonable. Why the paternalism? No one is asking for this to be default.

**Comment by Notarin** [comment]
@chrisduerr 
Your intransigence and refusal to entertain this matter is highly disappointing and unbecoming. Your obstinate and paternalistic attitude is antithetical to the collaborative environment that is necessary for finding mutually beneficial solutions to complex problems. Please engage in some self-reflection in order to reassess your position on this issue.

**Comment by FunctionDJ** [comment]
I find it sad to see that Alacritty will never have smart copy with `Ctrl + C`.
I switched over from OSes and Terminal emulators that have always supported `Ctrl + C` to copy in some form, so to me Alacritty feels like the first application to break that muscle memory - the opposite of the principle of least surprise, which is basically the reason that was given *against* implementing this.

*If anyone knows of a different performant terminal emulator that supports Windows, please let me know (via [Twitter](https://twitter.com/functiongermany) as to not hijack this issue thread)*

**Comment by Strus** [comment]
> Would Alacritty configure Ctrl+C as the default for copy/pasting inside the terminal, then a lot of people used to terminal emulators could get really, really confused.

It's exactly the opposite, as most (if not all) modern terminal emulators support "smart copy/paste" with `Ctrl+C` / `Ctrl+V`. But what's even worse about current implementation is that in `tmux` I need to hold Shift to select text, to be able to later copy it with `Ctrl + Shift + C` - where in other emulators I used (ITerm2 / Gnome Terminal / Windows Terminal) I can just select text without any additional keypresses.

**Comment by kchibisov** [comment]
>It's exactly the opposite, as most (if not all) modern terminal emulators support "smart copy/paste" with Ctrl+C / Ctrl+V. But what's even worse about current implementation is that in tmux I need to hold Shift to select text, to be able to later copy it with Ctrl + Shift + C - where in other emulators I used (ITerm2 / Gnome Terminal / Windows Terminal) I can just select text without any additional keypresses.

You can use `save_to_clipboard`, so you'll copy on select, like you can automatically on Linux, will still require `shift` for mouse mode applications though. One more thing is that you can copy from the tmux.

And given that you mention mac, you binding is `Cmd + C`, not the `Ctrl + Shift + C`.

**Comment by Strus** [comment]
> You can use save_to_clipboard,

`save_to_clipboard` still requires holding `Shift` while selecting text if you are using `tmux`. At least on Windows, when `tmux` is run under WSL.

> And given that you mention mac, you binding is Cmd + C, not the Ctrl + Shift + C.

I use `alacritty` only on Windows.

**Comment by kchibisov** [comment]
>save_to_clipboard still requires holding Shift while selecting text if you are using tmux. At least on Windows, when tmux is run under WSL.

Yes, because tmux is capturing your mouse. You can disable mouse mode in tmux if you don't want to, but selecting in mouse mode doesn't make any sense, since selection and other stuff is done by the application, not alacritty.

**Comment by Strus** [comment]
> Yes, because tmux is capturing your mouse

Probably. But other terminal emulators handle that without issues.

**Comment by kchibisov** [comment]
All terminals I'm aware of require `Shift` for mouse mode and don't select. If you've used tmux without a mouse mode before that's not a comparison. You can simply disable mouse mode in tmux and you won't need `Shift` anymore.

**Comment by Strus** [comment]
I use the same tmux.conf everywhere. I have mouse mode enabled and I do not need to press `Shift` on select in Windows Terminal, iTerm2 or Gnome Terminal. I just select text and it is copied automatically, or I can copy it with `Ctrl + C`. All of it is a basic functionality in any modern terminal emulator.

**Comment by Strus** [comment]
This discussion gave me an idea for a workaround using AutoHotKey:
```
#IfWinActive ahk_exe alacritty.exe
#c::Send, ^C
#v::Send, ^V
#x::Send, ^X
```

This script will map `Win + c/v/x` to `Ctrl + Shift + c/v/x` when Alacritty windows is focused. I you also want `Win + c/v/x` to work as `Ctrl + c/v/x` everywhere else, you can use this:
```
#c::Send, ^c
#v::Send, ^v
#x::Send, ^x

#IfWinActive ahk_exe alacritty.exe
#c::Send, ^C
#v::Send, ^V
#x::Send, ^X
```

**Comment by MagicMarvel** [comment]
I found the settings in config file, and changed it to the following:
```yml
key_bindings:
    - { key: V, mods: Control, mode: ~Vi, action: Paste }
    - { key: C, mods: Control, action: Copy }
```
It works for me! (OS: WSL in window)

**Comment by Notarin** [comment]
> This discussion gave me an idea for a workaround on Windows using AutoHotKey:
> 
> ```
> #IfWinActive ahk_exe alacritty.exe
> #c::Send, ^C
> #v::Send, ^V
> #x::Send, ^X
> ```
> 
> This script will map `Win + c/v/x` to `Ctrl + Shift + c/v/x` when Alacritty windows is focused. I you also want `Win + c/v/x` to work as `Ctrl + c/v/x` everywhere else, you can use this:
> 
> ```
> #c::Send, ^c
> #v::Send, ^v
> #x::Send, ^x
> 
> #IfWinActive ahk_exe alacritty.exe
> #c::Send, ^C
> #v::Send, ^V
> #x::Send, ^X
> ```
> 
> Same can be achived on Linux using any keypress-modifying software.

This can just be done in the terminal keybind settings.
correct me if I'm wrong.

**Comment by bluz71** [comment]
My current approach (for those interested):

```
key_bindings:
  - { key: C, mods: Control, action: Copy }
  - { key: K, mods: Control, chars: "\x03" }
```

`Control-C` for copy (as per usual for all standard Linux GUI apps).
`Control-K` for `SIGINT` / `cancel` / `kill` (I am using K for Kill mnemonic); my muscle memory is adapting to this (slowly). Note, some shells use `Control-K` for kill-line, but I simply never used that binding, so I don't care to lose that capability.

In my Alacritty setup I do **NOT** define `Control-V` for paste, I don't need to do so since my new preferred Shell, [Fish Shell](https://fishshell.com), already defines `Control-V` for Paste (`fish_clipboard_paste` binding); this seems to work great inside and outside of tmux (with no deleterious effects that I have encountered, it just works). I also define a Neovim insert mode paste mapping for `Control-V` as `inoremap <C-v> <C-r>+`.

Nothing seems to have broken.
Nothing I care about seems to be inaccessible to me (`Control-v` block mode selection in Neovim/Vim still works fine, for example).

I am glad to junk `Control-Shift-C` and `Control-Shift-V` to the dustbin of my keyboard history (after all these years, even going back to my Xterm days stretching back decades).

**Comment by sigurdo** [comment]
I just got sick of pressing shift, and discovered that [ambiso's fork](https://github.com/ambiso/alacritty) is out of date, so I re-implemented it in [my own fork](https://github.com/sigurdo/alacritty-smart-copy). Will be interesting to see how often I'll bother updating it.

Since I chose to base it on the `master` branch, you have to migrate your config to TOML to get rid of a deprecation warning, which can be done automatically with `alacritty migrate`. Then the TOML config you need to add to be able to copy and paste with `ctrl+c`/`ctrl+v` is

```toml
[[keyboard.bindings]]
key = "V"
mods = "Control"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control"
action = "CopyDynamic"
```

**Comment by terax6669** [comment]
@sigurdo are you going to provide a release?

**Comment by sigurdo** [comment]
@terax6669 , thanks for the suggestion! It is actually quite easy, thanks to the github workflow. I didn't think about that. I provided a release just now. I think it makes sense to keep releases synced with officially stable Alacritty releases and not the master branch, so if you download the latest release [v0.12.2](https://github.com/sigurdo/alacritty-smart-copy/releases/tag/v0.12.2), you need the following YAML config to copy and paste with `ctrl+c`/`ctrl+v`:

```yaml
key_bindings:
  - { key: V,        mods: Control, action: Paste            }
  - { key: C,        mods: Control, action: CopyDynamic      }
```

**Comment by Notarin** [comment]
@sigurdo doing gods work!!! Thank you for your awesome work!

**Comment by nixpulvis** [comment]
Mind if I ask what exactly `CopyDynamic` does exactly? I know this is an old issue that was unresolved and one that I never truly championed, but I'd be curious how things are developing now.

**Comment by Notarin** [comment]
@nixpulvis The question may not have been directed towards me but I believe I both understand this well enough and have been involved in the issue enough to answer. `CopyDynamic` does the following based on the two following states of the terminal:
 - No text is selected:
   - The normal Ctrl-C SIGINT is sent to the shell
 - Text is selected:
   - The selected text is applied to the clipboard
   - The selected text is deselected
 
This behavior is identical to the windows terminal, the windows console host, Kitty (when configured), and a few select other terminals (second-hand anecdote).
I really appreciate you revisiting this issue.

**Comment by sigurdo** [comment]
@Notarin, that is indeed a correct description. Alternatively phrased, quoting the [readme](https://github.com/sigurdo/alacritty-smart-copy/blob/master/README.md) in my own fork:

This fork of Alacritty lets you copy and paste with `ctrl+c` and `ctrl+v`, like in most modern Windows and Linux software. If no text is selected, `ctrl+c` sends `SIGINT` like usual. The selection is cleared when you copy with `ctrl+c`. In this way, pressing `ctrl+c` twice will always send minimum one `SIGINT`.

**Comment by Notarin** [comment]
I'm especially glad we now have an up to date model showcasing our request. Even if the communication breaks down we now have code explaining the requested behavior.

**Comment by Notarin** [comment]
I was actually wondering how normal of a feature this is so I took some time sifting through some terminal emulators to see how common or uncommon support is for this. If anyone has any addition I'd love to add them.

| Terminal Emulator | Support for smart copy |
| --- | --- |
| Alacritty | ❌\* |
| Kitty | ✅ |
| Tilix | ✅ |
| Terminator | ✅ |
| Gnome Terminal | ✅ |
| Xterm | ❌ |
| Windows Terminal | ✅ |
| Windows Console Host | ✅ |
| Konsole | ❓\*\* |

If any of this is wrong please inform me, if you know of another terminal and are aware of its support for this also, please let me know and I shall add it.

\*Alacritty has a fork with this feature enabled by configuration.

\*\*Konsole devs have indicated approval and closed the [issue](https://invent.kde.org/utilities/konsole/-/issues/27) requesting this feature, however, there is also an open [merge request](https://invent.kde.org/utilities/konsole/-/merge_requests/520) that is related to this, so I'm unsure without further exploration. If someone checks before me, please let me know.

**Comment by bluz71** [comment]
I believe [WezTerm](https://wezfurlong.org/wezterm) also supports `SmartCopy` as noted in [this closed issue](https://github.com/wez/wezterm/issues/1900).

@Notarin, can you add *WezTerm* to your table with a tick.

Personally, I am now in the camp that would like like this option (disabled by default).

**Comment by Notarin** [comment]
I as well do not want this to be enabled by default. While I personally don't really see how this would surprise anyone or ever act in an unintended manner, I still do not want to modify such a cemented linux norm. While I love bleeding edge changes and always exploring new concepts, the more conservative and older crowd are the backbone of linux, and I respect their workflow and would never want to project changes to it.

**Comment by frabjous** [comment]
I'm definitely in the older crowd of linux users -- I've been using linux since the early 90s, and used unix before that -- and would still very much like this feature. Sure, don't make it default, but support it at least.

**Comment by Terraphice** [comment]
The strange stubborn and juvenile behavior presented in this issue is exactly why I lead people to other options when the discussion of choosing a terminal emulator comes up.

**Comment by berisap** [comment]
> My current approach (for those interested):
> 
> ```
> key_bindings:
>   - { key: C, mods: Control, action: Copy }
>   - { key: K, mods: Control, chars: "\x03" }
> ```
> 
> `Control-C` for copy (as per usual for all standard Linux GUI apps). `Control-K` for `SIGINT` / `cancel` / `kill` (I am using K for Kill mnemonic); my muscle memory is adapting to this (slowly). Note, some shells use `Control-K` for kill-line, but I simply never used that binding, so I don't care to lose that capability.
> 
> In my Alacritty setup I do **NOT** define `Control-V` for paste, I don't need to do so since my new preferred Shell, [Fish Shell](https://fishshell.com), already defines `Control-V` for Paste (`fish_clipboard_paste` binding); this seems to work great inside and outside of tmux (with no deleterious effects that I have encountered, it just works). I also define a Neovim insert mode paste mapping for `Control-V` as `inoremap <C-v> <C-r>+`.
> 
> Nothing seems to have broken. Nothing I care about seems to be inaccessible to me (`Control-v` block mode selection in Neovim/Vim still works fine, for example).
> 
> I am glad to junk `Control-Shift-C` and `Control-Shift-V` to the dustbin of my keyboard history (after all these years, even going back to my Xterm days stretching back decades).

I saw this approach and I looked good enough for my case. I wanted to try it but then noticed that alacritty switched to a TOML based configuration. Of course it wouldn't accept "\x03" since it is a YAML specific thing I spend a good few hours to make it work with TOML. I want to spare you guys the same effort and show you how it is done in TOML:

[keyboard]
bindings = [
{ key = "C", mods = "Control", action = "Copy" },
{ key = "K", mods = "Control", chars = "\u0003"}
]

Also I don't see a reason why not to integrate the "CopyDynamic" feature into the software but since it is an open source project we should be thankful for the effort of the devs and live with it.

**Comment by mcarans** [comment]
Given that smart CTRL-C is the norm on Windows and Alacritty supports Windows, I don't understand the rationale for not having this as an option on all supported platforms.

Sadly, no terminal emulator seems to be fully cross platform, supporting smart CTRL-C for copy/interrupt and mouse click to position cursor in bash.

**Comment by chakibchemso** [comment]
- This is just insanity ngl. oh and +1 for this to be implemented or at least merged as is. Thank you.

- Its all in the first few words of the README:

### Why smart copy?
1. Cuz its part of "extensive configuration"
2. The users wants it. (as an option that is, and a working implementation is ready anyway)
> Alacritty is a modern terminal emulator that comes with sensible defaults, but allows for extensive [configuration](https://github.com/alacritty/alacritty#configuration). 

3. The next sentence doesn't apply, as smart copy cant be achieved by any combination of current features or even external ones.
> By integrating with other applications, rather than re-implementing their functionality, it manages to provide a flexible set of [features](https://github.com/alacritty/alacritty/blob/master/docs/features.md) with high performance.

3. This is the default behavior in windows and macos. This one only is a deal breaker. I cant imagine the horror of switching between windows terminal, vscode terminal, intellij terminal... and alacritty! you see the problem, hopefully.
> The supported platforms currently consist of BSD, Linux, macOS and Windows.
