### ISSUE TITLE
Delete key not working

### ISSUE THREAD

**Issue by SirAiedail** [jwilm/alacritty#192]
The `Delete` key is not recognized on Fedora 25 with a fresh install of alacritty and default configuration file.

**Comment by dbrgn** [comment]
Same thing here. Arch Linux, `sg` (Swiss German) keyboard layout.

`xbindkeys -k` output for the delete key:

> m:0x10 + c:119
> Mod2 + Delete

**Comment by colinclement** [comment]
Same issue. Ubuntu 16.04 with bash 4.3. 

I fixed it by changing the binding in the default alacritty.yml file:
Original (line 176) `  - { key: Delete,                  chars: "\x1b[P",   mode: ~AppKeypad  } `
Changed to `  - { key: Delete,                  chars: "\x1b[3~",   mode: ~AppKeypad  }`

Can someone clarify what `mode: ~AppKeypad` means? If I simply swap the chars in the Delete binding lines, then delete works in the command line but not correctly in vim (it inserts 'o'). Binding both Delete lines to "\x1b[3~" gives the expected behavior as far as I can tell.

**Comment by snuderl** [comment]
I can confirm the same problem on a slovene keyboard (si layout)

**Comment by jonhoo** [comment]
I can't seem to find any documentation mentioning the `\e[P` escape anywhere. `\e[3~` seems to be [the standard delete binding](http://www.ibb.net/~anne/keyboard/keyboard.html#prob). I'd suggest making them both `\x1b[3~` unless there's a good reason not to?

**Comment by KoBruhh** [comment]
I can still reproduce this issue in arch linux using my turkish keyboard
