### ISSUE TITLE
Starts umaintained 'cmd' shell on Windows

### ISSUE THREAD

**Issue by mikemaccana** [jwilm/alacritty#1928]
Alacritty 0.24 on Windows 10.0.17763.0 will start `cmd` by default. The default shell (see Win+X) on Windows is powershell and cmd is no longer maintained by Microsoft. 

Alacritty should start powershell by default, which is actively maintained by Microsoft and supports modern features like key bindings, readline, arrays, objects, and functions, and separates content from presentation avoiding the need for regex scraping. 

Ideally, Alacritty should do what Terminus does and start `pwsh` (Powershell 6) if installed, then fall back to `powershell`

**Comment by zacps** [comment]
Do you have a source for cmd's EOL? Haven't heard it was out of maintenance before.

**Comment by mikemaccana** [comment]
See Microsoft's comments in: https://github.com/Microsoft/console/issues/217

**Comment by chrisduerr** [comment]
Note that even Windows 7 should support powershell. So backwards-compatibility shouldn't be an issue. I don't think officially supporting anything before Win 7 is reasonable.

**Comment by zacps** [comment]
Given that issue I'm happy to move to powershell as the default. 

I'm not convinced that adding fallbacks for this is reasonable/worth it, but I would be happy to accept a pr to change the default to `powershell`.

**Comment by bitcrazed** [comment]
Hey all. Just to clarify here - as I wrote [in this post](https://blogs.msdn.microsoft.com/commandline/2017/01/04/rumors-of-cmds-death-have-been-greatly-exaggerated/), Cmd is currently supported and maintained, and will likely remain supported and maintained until there is no more Windows desktop OS, which itself is unimaginably unlikely.

However, @mikemaccana is correct in saying that we can only _change_ Cmd in limited ways because it (and the Cmd ecosystem) are so very fragile. In addition, because Cmd lacks many of the features of modern CLI shells, and because it's so difficult to change, we cannot add any significant new features to it.

This is one of the key reasons we created PowerShell, and why PowerShell should be considered the future of the Windows CLI. PowerShell is massively more powerful, capable, feature-rich, and expansible, supportable than Cmd, and now runs across Windows, *NIX, and beyond! It should be every Windows user's default interactive CLI shell environment. 

It is 2019, after all! ;)

**Comment by mikemaccana** [comment]
@bitcrazed It would be super cool if you could do another blog post mentioning that (as you and Mike @miniksa have previously mentioned at https://github.com/Microsoft/console/issues/217) new command line tools should use powershell. Windows is starting to get a lot of attention from non-traditional (node, go, etc) folk who often have no idea about powershell and cmd, and a blog post with:

# Making something for the Windows command line in 2019? Use powershell!

Would be *waaay* better than having to point people to some comments on a GitHub link.

**Comment by bitcrazed** [comment]
Great suggestion Mike - I'll write a post in a week or two after I get back to work :)

Thanks everyone for your support & great work ;)

**Comment by mikemaccana** [comment]
@bitcrazed Did this post ever come out? I'll get the word out among node community folk.

**Comment by bitcrazed** [comment]
Alas, no. I've been at 120% capacity for about 8 months now, but am hoping to get some breathing room after Build 2019. DEFINITELY want to write that post though - PowerShell is da bomb!

**Comment by Chaitanyabsprip** [comment]
how can I change default shell to pwsh?

**Comment by adigitoleo** [comment]
@Chaitanyabsprip

In `alacritty.yml`:

```
shell:
    program: pwsh
```

**Comment by 237dmitry** [comment]
It does not work:

```
[2021-04-19 17:22:16.511117200] [ERROR] [alacritty_config_derive] Config error: shell: data did not match any variant of untagged enum Program
```

**Comment by adigitoleo** [comment]
@237dmitry Hmm, worked for me. Make sure to spell `program` in lowercase. Otherwise I'm not sure, I only use windows occasionally.

**Comment by stellarsu** [comment]
this worked for me

```
shell:
    program: C:\Program Files\PowerShell\7\pwsh
```
