### ISSUE TITLE
Add UTF-8 mouse report support

### ISSUE THREAD

**Issue by DarkDefender** [jwilm/alacritty#1934]
> Which operating system does the issue occur on?
Linux

> If on linux, are you using X11 or Wayland?
X11

In weechat, mouse gestures (click and drag) and clicks do not register after a certain horizontal point in alacritty. This works in urxvt and xterm.

![ala_mouse](https://user-images.githubusercontent.com/312503/50513544-c224a900-0a98-11e9-9f81-8c436d2dabaf.png)

If I resize the terminal window to be smaller (so it is smaller than the red line area) mouse clicks and motions now work again at the far right again.

So I'm guessing something funky is happening with mouse actions on large cell count positions.

This is a bit of a problem for me as the nick list is located on the right for me and I can't scroll the nick list or click on names to message them unless I resize the window as it is now.

**Comment by chrisduerr** [comment]
This is related to https://github.com/jwilm/alacritty/issues/698.

If I had to take a guess, weechat is probably using the normal mouse reports in Alacritty, but using sgr mouse reports in other terminal emulators. Normal mouse reports do not support anything past column 223 iirc, so that would lead to issues.

Does changing the `TERM` to something like `xterm-256color` resolve this issue? Then maybe there's some code in weechat which sets the mouse mode based on the terminfo string, rather than terminal capabilities.

**Comment by DarkDefender** [comment]
I forgot to mention that I have tried with both `TERM` set to alacirtty and xterm. Both have the same problem.

**Comment by chrisduerr** [comment]
Interesting, that means that both should be using the same mouse report mode. It would probably be worth investigating which mouse mode exactly is set by weechat. There's potentially some more issues with the SGR mouse mode? If the normal mouse mode is requested, then this is the intended behavior afaik.

**Comment by chrisduerr** [comment]
I can't reproduce this issue. Is this still present for you @DarkDefender?

**Comment by DarkDefender** [comment]
I can still reproduce this with 0.3.3. Has anything changed in the regard with master?

**Comment by DarkDefender** [comment]
@chrisduerr also how many cells is the width of your terminal? You might need to use a very small font to trigger this

**Comment by chrisduerr** [comment]
I can repro on my 1440p display. However haven't looked into the cause of this at all yet. I wouldn't expect this to be too difficult though.

**Comment by kchibisov** [comment]
This issue is caused by a limitation of a normal mouse mode lines/cols to be less then `223`, so clicks after a certain point are just filtered out. See the following line.

https://github.com/jwilm/alacritty/blob/93e87eb0f1858138113d4ecdfaa8bfac3c127a39/alacritty/src/input.rs#L372

This behavior is intended according to [xterm manual](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-Mouse-Tracking). So, I'm not sure what we should do here now (we can wrap, but I don't think that it's a right thing to do). @chrisduerr, What do you think?

**Comment by DarkDefender** [comment]
IIRC, other terminals like urxvt and gnome terminal removed this limitation a while back. But I'm not totally sure. At least that would explain why it work with those terminals and not alacritty.

**Comment by kchibisov** [comment]
The issue was identified and verified. We should add UTF-8(1005) encoding support https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-Mouse-Tracking to resolve it, since weechat is using it.
