### ISSUE TITLE
More specific messaging for macOS permissions

### ISSUE THREAD

**Issue by jedahan** [jwilm/alacritty#1964]
Thanks to #1760, I recently saw some application within Alacritty trying to access my Contacts and Calendar. I was wondering if there are programmatic ways to share information about the process that tried to access said permissions - pid, process name, etc. This would be great in helping allay concerns.

**Comment by chrisduerr** [comment]
@jedahan I don't think there is. If you take a look at #1760, I'm sure you can see that Alacritty is doing absolutely nothing itself. It's just specified in the configuration file that it is allowed to ask for permissions. Then subprocesses spawned by the shell do the requesting.

I think it would be great to do this if it's easily possible without some crazy hacks, but I simply do not think it is possible.

I'm going to close this as wontfix because I'm not aware of anything that Alacritty can do. If you have any ideas, feel free to let me know how Alacritty could resolve this.
