### ISSUE TITLE
Window launch fails with "MSVCP140.dll was not found"

### ISSUE THREAD

**Issue by JJJollyjim** [jwilm/alacritty#1972]
On what is effectively a fresh install of Windows 10 Education 1809 (save for Nvidia drivers, one game, and Firefox, plus a few reboots worth of windows updates), I installed alacritty from scoop-extras.

Launching alacritty from the start menu fails with "The code execution cannot proceed because `MSVCP140.dll` was not found. Reinstalling the program may fix this problem.", followed by an identical issue regarding `VCRUNTIME140.dll`.

Searching my system, I appear to have DLLs for versions up of MSVCP up to 120 in `Windows\System32` and `Windows\SysWOW64`. Firefox and OneDrive both seem to package their own copies of `MSVCP140.dll` - is this something that `scoop` should be able to handle, and it just needs to be made an explicit dependency?

![Unnecessary screenshot](https://user-images.githubusercontent.com/691552/50682640-68157c00-1074-11e9-95ad-9b2262fab57e.png)

(Possibly relevant, the machine is a VM running under KVM/qemu/libvirt on Linux)

**Comment by chrisduerr** [comment]
To troubleshoot if scoop is at fault here or if Alacritty can do something about it, I'd recommend downloading the latest `.exe` from the [github releases](https://github.com/jwilm/alacritty/releases).

If the `.exe` from the releases works fine, but the scoop version does not, this needs to be fixed by whoever maintains the Alacritty scoop package.

**Comment by JJJollyjim** [comment]
@zacps I thought the idea with the redistributable packages was that they get packaged with apps, not installed by the user system-wide - can the scoop package not handle it?

**Comment by JJJollyjim** [comment]
(I actually can't find an official download for it, just Visual Studio addons for working with it -- I've never really done windows development stuff so let me know if I'm misunderstanding things)

**Comment by JJJollyjim** [comment]
Actually, it looks like scoop doesn't have a great mechanism for this: https://github.com/lukesampson/scoop/issues/763

**Comment by zacps** [comment]
Scoop is not written or maintained by anyone from the Alacritty project. I do not use it myself, and have no knowledge of it.

**Comment by Tset-Noitamotua** [comment]
just ran into this issue
Fresh Windows 10, Fresh Scoop … 

```
MSVC140.dll nicht gefunden
```


MSVCP140.dll not found

**Comment by chrisduerr** [comment]
> Fresh Windows 10, Fresh Scoop …

> On Windows, Alacritty also requires Microsoft's VC++ redistributable to work properly.

See https://github.com/jwilm/alacritty#other.

**Comment by Tset-Noitamotua** [comment]
>See https://github.com/jwilm/alacritty#other.
Thank you for quick response. 

I did the following steps (without success) while trying to install with `scoop`
1. find and download MSVC140.dll
2. start Windows Explorer as Administrator 
3. copy the .dll to "C:\Windows\System32"
4. open run dialog ( [Win] + [R] ) and type  `regsvr32 msvcp140.dll` and press [Enter]
5. got another error

I give up trying to install this on Windows. I just wanted to give it a guick shot and thought `scoop install ...` would allow to do exactly that. Will try another day on Linux :)

I'd suggest to remove the `scoop install` option from the readme or at least put it further down so that people don't jump on it first :)
I have not tried chocolatey but it may have same issues because of VC++ dependency

**Comment by chrisduerr** [comment]
> I'd suggest to remove the scoop install option from the readme or at least put it further down so that people don't jump on it first :)

That's perfectly fine though. You just need to install the VC++ redistributable, which is available for install and download from the microsoft website. Not download the DLL, but the VC++ redistributable.

This is likely already installed on many systems, though installing it yourself shouldn't be a problem.

**Comment by RoyiAvital** [comment]
Currently even the portable installer fails due to `VCRUNTIME140.dll`:

![image](https://user-images.githubusercontent.com/7347975/204472775-7830ec7d-4698-4e5c-aaa8-ea044f902956.png)

Is there a way to make the project compatible with the libraries supplied in modern Windows (Windows 10, Windows 11)?
