### ISSUE TITLE
macOS keyboard-related performance can be vastly improved by changing system key repeat values

### ISSUE THREAD

**Issue by lachlantula** [jwilm/alacritty#1992]
After reading [this article](https://andrewbrookins.com/tech/slow-scrolling-in-vim-and-macvim-on-os-x-increase-key-repeat-settings/) I was curious to see how the suggest changes could affect Alacritty, which describes in its `README.md` about how the poor tmux/vim performance is not really the program's fault.

Running the following commands *vastly* improved my performance (you may need to log out and back in to see changes):

```
defaults write -g InitialKeyRepeat -int 10
defaults write -g KeyRepeat -int 1
```

[Here's a webm comparing Alacritty and iTerm 2 following the changes (Alacritty left, iTerm right).](https://gfycat.com/GiganticDifferentBellfrog) Alacritty still noticeably comes out on top, but scrolling is significantly smoother than before. Similar performance boosts can be seen in other emulators such as Terminus, Hyper, and Terminal.app (the effectiveness of the change varies, however).

It turns out this has been a [known issue for a while.](https://github.com/tmux/tmux/issues/353#issuecomment-419286706) I think it would be a good idea to mention this on the README.

It is worth considering the following factors that may have affected my performance:

- I tested this on a new user account.
- I am using the default Alacritty configuration.
- I did not test Neovim.
- [You can view my Vim config here.](https://github.com/lachlantula/dots/blob/master/.vimrc%23%23Darwin)

Curious to see if this affects anyone else.

**Comment by chrisduerr** [comment]
Scrolling to the bottom of vim is not a benchmark and doesn't provide any useful performance insights. Keyboard repeat rate is unrelated to performance, the issue mentioned in the README is about an actual performance problem afaik.

While this is probably helpful information to many people that are interested in increasing their keyboard repeat rate, it seems very unrelated to Alacritty itself.

As a result of this, I don't think it would be appropriate to document this in Alacritty's README, since it's a system configuration for macOS which mainly affects applications running *inside* of Alacritty that use a single key to scroll.
