### ISSUE TITLE
Font size is doubled, even with no dpi ratio

### ISSUE THREAD

**Issue by redg3ar** [jwilm/alacritty#1999]
Which operating system does the issue occur on?
Arch Linux
If on linux, are you using X11 or Wayland?
X11

X11 dpi scaling is very broken for me until tomaka/winit#606 is merged. 

To get around this, I set the environment variable to "1". I prefer a bitmap font in size 12, and I see the 16 point font is chosen instead.
I still see the size being multiplied somewhere in the debug output.
![image](https://user-images.githubusercontent.com/8226605/50989249-d7f48e00-14dc-11e9-9dbb-10569c5f289d.png)

It is using the 16 point font instead of the 12 point font I want. For it to be 12 point I must use a font size that is smaller then the intended size. I thought it could maybe be https://github.com/jwilm/alacritty/blob/04707cbba630e3e4ad6b4200bef8ae7888c49e3b/font/src/ft/mod.rs#L375 this lines multiplication but I unsure.

**Comment by chrisduerr** [comment]
The log only prints a value of `24` because it is doubled to improve precision while using full integer numbers. This allows changing the font size in .5 increments without having to support floating point numbers. The font size does not actually get doubled.

It should also be noted that point size and pixel size is different. Since you're talking about bitmap fonts, I'd assume you're looking for the font with a pixel size of 12, rather than a point size.

If you take a look at the [official freetype documentation](https://www.freetype.org/freetype2/docs/glyphs/glyphs-2.html), you can see that the pixel size is calculated exactly how it is done in the code snippet you've posted.

If you want to use a font with a pixel size of 16, you'll have to adjust for the conversion from point size to pixel size.

I hope I've understood your problem correctly, but this doesn't sound like an issue with Alacritty. Even though I haven't written that code, comparing it to the official documentation looks like it should be correct and the configuration file explicitly states that the size is in points, not pixels. If there are any other issues, please let me know.
