### ISSUE TITLE
Konsole is faster than Alacritty with more tabs open (edit: in some cases) 

### ISSUE THREAD

**Issue by happysmash27** [jwilm/alacritty#2003]
Which operating system does the issue occur on?

Gentoo Linux

If on linux, are you using X11 or Wayland?

X11

I made a small C program that can print an arbitrary number of lines with ascending numbers. 

In Konsole, the time output is: 

`~/Code/largeprint 65536  0,04s user 0,10s system 99% cpu 0,141 total`

In Alacritty, the time, after a reset, is:

`~/Code/largeprint 65536  0,05s user 0,13s system 99% cpu 0,173 total`

In addition, Alacritty uses 113M of memory, while Konsole uses only 110, despite having 4 tabs open at the same time and much less resets. 

Oh, I just found VTEBench! 

Testing with VTEBench, it seems faster. Strange... In order to find an explanation, I ran my largeprint program at a smaller line size: 

Konsole: 

`~/Code/largeprint 16384  0,01s user 0,03s system 99% cpu 0,046 total`

Alacritty: 

`~/Code/largeprint 16384  0,01s user 0,03s system 99% cpu 0,041 total`

So, it appears that this has something to do with very large amounts of output, which would explain why vtebench gets such better benchmarks with a small amount of output. 

Wati, no. Strangely enough, the scrolling benchmark as opposed to the alt-screen-random-write benchmark gives much worst results in Konsole, despite it being seemingly very similar to my program. 

Code of my program for reference: 

```
#include <stdio.h>
#include <stdlib.h>


int main(int argc, char **argv) {
  if (argc!=2){
    fprintf(stderr, "Eraro: bezonas nur 1 argumenton\n");
    exit(EXIT_FAILURE);
  }

  char *erarnumbro;

  long linioj = strtol (argv[1], &erarnumbro, 10);

  if (*erarnumbro != '\0'){
    fprintf(stderr, "Eraro: argumento ne estas numbro\n");
  }
  
  for (long i = 0; i<linioj; i++){
    fprintf(stdout, "%ld\n", i);
  }
  exit(EXIT_SUCCESS);
}
```

Going to /dev/null, it takes about 0.003 for 16384 and and 0.008 for 65536. 

So at least in some cases, but not all, it seems to go slower.

**Comment by chrisduerr** [comment]
A loop printing for every line of text is not a very good benchmark because that's extremely slow. Vtebench bypasses this by using a buffer that is written in one go, instead of line-by-line which removes that bottleneck.

The problem here is not with Alacritty or Konsole, the issue is the benchmark which is being used. It is not a reliable method to benchmark terminal emulators.

Usually the best way to write benchmarks is just to write all the text and escape sequences to a file and then output this file in the terminal. This automatically creates a nice buffer which should not be a bottleneck anywhere. Running it a few times to fill up filesystem caches first is usually a good idea.

If you find a way to reproduce this issue by running it through a file as a buffer, please let me know and I'll re-open.
