### ISSUE TITLE
Question: open file urls?

### ISSUE THREAD

**Issue by artemave** [jwilm/alacritty#2051]
Hello!

I'd like to be able to click-open files from a stack trace (file urls with line:colon gubbins appended) in an editor of choice.

A similar (albeit limited) feature is present in iTerm2: With the help of a script, I am able to open files from window 1, in the vim that is opened in window 2.

Is this possible in alacritty?

Thanks!

**Comment by artemave** [comment]
Thank you for the quick reply!

I guess my case would be closed, If the following could be expressed in `alacritty.yml`:

Given the modifier M is pressed, when a text under cursor matches pattern X, pass the matched text to a command Y

I setup a similar (but limited to absolute file urls only) experience in iterm - [details here](https://gist.github.com/artemave/e68aa6e367f2c65aece6300f44aacb5a)

**Comment by nixpulvis** [comment]
I think I've used a terminal like this before, but as @artemave just mentioned it would only perform the actions on a modifier click. I think the best way to implement this would be to decorate (underline) each clickable thing (web url, file, etc). I'm not 100% sure how the modifier and keybindings would look in our config, since the modifier for decorating would need to be the same as the modifier for clicking.

As for the file:line format, it's common enough that some level of support would be worth looking into IMO. It might require ugly configuration however, which is a tradeoff.

**Comment by artemave** [comment]
I could personally live without decorated urls in the terminal. As an MVP :)

**Comment by Lythenas** [comment]
Just implementing this (at least as a start) would be great:

> Given the modifier M is pressed, when a text under cursor matches pattern X, pass the matched text to a command Y

I can imagine e.g.
- making a timestamp clickable and opening a calendar app
- when clicking on an email open your mail program
- when clicking on a hash (or branch) inside a git project checkout that commit
- ...

I think this is a great opportunity for customization.

**Comment by nixpulvis** [comment]
@Lythenas oof, yea there's a lot of fun we could have. I think the idea of parsing some common date formats (conservatively) could be interesting, though I'm not personally 100% sure what I'd do with them generally.

Clicking git hashes or branches seems like it's more in the realm of a user implemented feature if/when we ever get scripting in Alacritty (related to #600).

**Comment by Lythenas** [comment]
@nixpulvis in my opinion all this custom behavior (even the url clicking) and should be provided by the user or at least from outside alacritty. Alacritty could also provide some useful scripts that are commonly used. Like the url clicking.

I honestly don't know what osc52 is but regarding the hash/branch clicking I would probably just call the git commands to check if it is a valid hash/branch.

Supporting decorations through scripts is probably not that hard, if that the decorations only appear when the user presses some key. You would just need to call the script once.

**Comment by Lythenas** [comment]
@nixpulvis Yes I guess you should make it as hard as possible for the user to slow down Alacritty. The speed is only relevant for decorators, correct? Maybe running the scripts asynchronously is already enough. Or (instead of executable scripts) you could only allow the user to specify regexes or something even simpler.

Even disregarding the idea of decorators I think it would be helpful to simply call a script that only gets the word under the cursor (or line or screen content with click position). That would mean matching the text happens entirely outside of Alacritty.

If I define all the click handlers myself I don't necessarily need to see decorations. Although they would be nice.

**Comment by DanielHeath** [comment]
What if the decorations are not applied synchronously? 

That is, new text first displayed, then passed to the decorator script (off-thread), then decorated once the script marks it as such.

**Comment by chrisduerr** [comment]
That would not provide a sufficient user-experience in my opinion.

Alacritty's goal is performance, that means things shouldn't update only every third frame because they're too slow to run synchronously. Either they are fast enough to be feasible in real time or they shouldn't be included in that form.

**Comment by DanielHeath** [comment]
I'm suggesting a non-blocking API for extensions, not for core code.
 
If you allow extension hooks (IMO a desirable quality), your options are to do make them blocking or non-blocking.

If you make them block, a slow extension breaks everything else. If you make it non-blocking, a slow extension only breaks itself.

Not only is the latter approach better for performance (everything else remains responsive), it typically makes it obvious which extension is slowing things down.

**Comment by chrisduerr** [comment]
> I'm suggesting a non-blocking API for extensions, not for core code.

An extension which is used by enough people becomes core code. Because of that, an asynchronous operation is absolutely not an option.

**Comment by DanielHeath** [comment]
To reframe the question, then: If extension hooks exist, what should happen when someone writes an extension and it runs slowly on a given machine. 

For instance, if an extension checks whether a given file exists (plausibly useful), that's a syscall which is typically extremely fast, but on eg a network FS might block for 30 seconds.

Should it be impossible to make blocking syscalls from an extension? That would restrict the kinds of extension quite unreasonably IMO.

**Comment by chrisduerr** [comment]
That's why there currently are no extensions. If something makes sense as a feature in Alacritty, it should be included into Alacritty directly where its performance and quality can easily be controlled.

**Comment by DanielHeath** [comment]
Right - would I be correct in summarizing your argument as 'use a fork, not an extension, and try to get it merged into core where it can be maintained'?

**Comment by chrisduerr** [comment]
That sound correct, yes. Though maintenance is not an issue as long as someone is willing to write the initial PR and adjust for suggested changes.

**Comment by DanielHeath** [comment]
That makes sense to me, and I'd be interested in contributing the feature (in time).

**Comment by sts10** [comment]
Just reviving this thread, because I found that, while `file:///home/user/path` used to be clickable in v0.3.0, but isn't in v0.4.0 or v0.4.1-dev for me on MacOS. Maybe there's a config setting for this I can enable?

**Comment by artemave** [comment]
I found an alternative. [Kitty](https://sw.kovidgoyal.net/kitty) is an all around great terminal emulator and the project maintainer quickly responded with necessary changes.

See details https://github.com/kovidgoyal/kitty/issues/2124

**Comment by chrisduerr** [comment]
The file URLs should work, if they're in the format `file:<PATH>`. There's a bug with `file:///` and `file:/` since the scheme separator is usually 0 or 2 `/`s, but that's better tracked in a different issue.

The string `file:testing.rs:53` highlights perfectly fine, so there really shouldn't be any issue.

If you need differentiation between what should be opened when, you can always define a custom URL launcher, so this should work in Alacritty today with paths that don't start with `/`.

**Comment by sts10** [comment]
Hm, `file:<PATH>` does indeed become "highlighted" (underlined) when I hover over it with my mouse, but nothing happens when I click or control+click. 

I have the following in my `alacritty/yml`:
```yaml
  url:
      # URL launcher
      #
      # This program is executed when clicking on a text which is recognized as a URL.
      # The URL is always added to the command as the last parameter.
      launcher:  
        program: open
```

It kind of makes sense that nothing happens when I click, because, separately, running `open file:<PATH>` results in a "Not Found" error. 

Any hints/tips?

**Comment by chrisduerr** [comment]
The relative path is not from where your shell is at, so that's probably causing it to not work.

That's why https://github.com/jwilm/alacritty/issues/3034 is required to make this really helpful, but that should be a simple fix.

In theory, the path would need to be relative to where you launched Alacritty from. Since that's likely your home directory, clicking on `file:test` should work if `test`'s path is `~/test`.

**Comment by sts10** [comment]
OK, thanks. Though FYI `file:~/absolute/path` isn't working for me either, which checks out because running `open file:~/absolute/path` results in an error.

**Comment by chrisduerr** [comment]
The `~` is commonly misunderstood on unix, but it is not a valid path. Your shell expands the symbol `~` to the correct path, but applications cannot just access a file with it. That's why `echo '~/absolute/path'` probably doesn't work either. Application need to explicitly support this expansion.

So that's why it doesn't work. `~/absolute/path` is not a valid path, it's a shorthand for `/home/user/absolute/path`, which is the valid path.

However you can probably just omit it and do `file:absolute/path`, assuming that Alacritty is started in the home directory and that should work. Since Alacritty's working directory is in home and relative paths are valid.

**Comment by gregoryholder** [comment]
If you're still interested, I've played around with adding a custom hint for "file:line:column" links and opens them in VSCode:
```yaml
hints:
 # [...]
  enabled:
  - regex: "[a-zA-Z/\\-_\\.]+(:\\d+)(:\\d*)?"
    command: 
      program: code
      args: 
        - "--goto"
    post_processing: true
    mouse:
      enabled: true
      mods: None
 # [...]
```
```
test_dir/test_file:3:4 -> matches
----------------------

test_dir/test_file:3   -> matches
--------------------

test_dir/test_file     -> doesn't match
```

**Comment by artemave** [comment]
Dang. Here we are five years later. I've since moved onto [another solution](https://github.com/artemave/tmux_super_fingers) to this problem. The good news is that it's terminal agnostic, the bad news is that you must use tmux.
