### ISSUE TITLE
sway, font is 30pt or so

### ISSUE THREAD

**Issue by soloturn** [jwilm/alacritty#2064]
Which operating system does the issue occur on?
arch linux

If on linux, are you using X11 or Wayland?
sway, wayland

the font in sway is much bigger than the default font. the window size seems to go out of the window available .

**Comment by soloturn** [comment]
![image](https://user-images.githubusercontent.com/825568/52167698-86c46c80-271f-11e9-8b57-14fefbffa6a4.png)

**Comment by chrisduerr** [comment]
Since you seem to describe this like a font issue, this might be related to DPI scaling and xfce-terminal might not be scaling the font size based on DPI.

What output do you get on startup when running `alacritty -v`?

> the window size seems to go out of the window

This seems a bit odd to me. Could you go into more detail? It seems like there might be more to this issue than just font size.

**Comment by soloturn** [comment]
i did install sway from git now:
```
yay -S sway-git
```
and the issue is not there any more. closing. sorry for bothering.

**Comment by chrisduerr** [comment]
Thanks for keeping us updated, glad it could be resolved in sway.
