### ISSUE TITLE
Direct binary launch spawn extra terminal/command-line

### ISSUE THREAD

**Issue by non-descriptive** [jwilm/alacritty#2082]
On MacOS (High Sierra, Mojave) when I try launch binary directly from folder/launchpad or pinned to Dock app it spawns terminal and then launches instance of alacritty. Currently I made script that i and directly from terminal 
`nohup alacritty >/dev/null 2>&1 &` 
and then close terminal 

On Windows when i try direct launch from folder or via "Run as" (Win+R) command it also spawn extra command line. I also tried to start it via `cmd /c start alacritty` but that also made extra command line. Not really succeeded to spawn alacritty without extra windows.

**Comment by nixpulvis** [comment]
Seems related to #1137 and #607. Though I'm not sure I'd call this a dup.

**Comment by chrisduerr** [comment]
I'm not exactly sure what the issue here is. When executing the binary twice, two windows should be launched. That is the intended behavior.

If you're talking about the issue with macOS that multiple instances aren't tracked as the same binary, then #607 is what you're looking for.

**Comment by non-descriptive** [comment]
It's not two binary executions. If you try to run alacrititty directly from Finder/Explorer it will open terminal/command line first and only then launch window instance of alacritty.

**Comment by non-descriptive** [comment]
https://youtu.be/6v8iG6PhHec
made a demo for windows

**Comment by chrisduerr** [comment]
Thanks for demonstrating the issue @non-descriptive. Though I haven't seen something like that before.

Do you have the latest version of Alacritty and the winpty agent installed? Also it looks like you have an `alacritty.ps1` file in that forder, that looks very very suspicious to me. If you have Rust installed, I'd recommend just compiling from source, I wouldn't be surprised if that worked.

Otherwise, please try downloading the binary built by travis from the github releases and try running that in a directory which contains only alacritty and the winpty agent.

@zacps might this be related to winpty-agent?

**Comment by non-descriptive** [comment]
Version in demo installed via `scoop` so scripts and winpty-agent came up with it. 
Github releases version launches fine.

On mac I've installed latest version via `cargo install --git `. Not sure what exact version it was. I think the one before windows support came out. Will check latest github releases version.

**Comment by chrisduerr** [comment]
>  Github releases version launches fine.

Then this is an issue with scoop and not Alacritty. I'm not aware of who's maintaining scoop, but contacting them would likely be the best choice.

**Comment by avarun42** [comment]
> Then this is an issue with scoop and not Alacritty. I'm not aware of who's maintaining scoop, but contacting them would likely be the best choice.

I want to note that installing via `scoop` is recommended on the official Alacritty README, so by the transitive property this is an issue with Alacritty as well.

**Comment by non-descriptive** [comment]
https://monosnap.com/file/C4p2G0QGShLkOqj5PR3JU72yn7xS6I
And MacOS version behaviour.

**Comment by chrisduerr** [comment]
@avarun42 I'd like to mention that this is by no means explicitly mentioned as the recommended installation method for Windows, it's just the only one which allows you to directly install the binary and keep it up to date.

If you're familiar with scoop, and this applies to brew and all linux package managers too, you should be aware that it's not the project itself which is managing these binaries. Which of course doesn't mean that they aren't the best way to install it. It just means that responsibility might be on someone else.

If it should turn out that scoop is unusable and provides broken or extremely outdated versions of Alacritty, we'd of course remove that from the readme, but that seems unlikely to me. So I'd rather give them the benefit of the doubt and guide you torwards reporting this to the scoop maintainer.

Now with linux, there's usually straight-forward ways to contact all package maintainers, I'm not familiar with how this works on scoop. Based on a few seconds of research, it looks like [this](https://github.com/lukesampson/scoop-extras) is where Alacritty's definition is tracked, so I'd recommend opening an issue there.

If you should decide to open an issue there, I'd appreciate it if you could link it here, that way other people would find out about it too.

**Comment by chrisduerr** [comment]
Also note that the macOS behavior you're demonstrating @non-descriptive is just that you're launching a blocking process from the CLI, so it'll keep the CLI open until the process exits.

This is the intended behavior, though it might be resolved with the issue I've linked previously, since that only spawns a new window. However you should never rely on a graphical application automatically starting in daemon mode, there's tools like `nohup` or `disown` which will take care of that for you.
