### ISSUE TITLE
Windows build panicks on `unwrap()`

### ISSUE THREAD

**Issue by panstromek** [jwilm/alacritty#2085]
Windows 10. 

Latest (0.2.7) prebuilt .exe file I downloaded from the releases page. 

Error:
![image](https://user-images.githubusercontent.com/25121817/52396727-1f0d7900-2ab3-11e9-966f-395a3d066574.png)

**Comment by JDTX** [comment]
@panstromek You are missing the winpty-agent from the releases page as the error indicates.
https://github.com/jwilm/alacritty/releases

Put the winpty executable in the same directory and it should run normally.  

Alternatively, if you're using Windows 10 version 1803+, you can try setting `enable_experimental_conpty_backend` to `true` to use the Windows conPTY instead of winpty-agent. This feature is experimental as the value indicates, so beware.

**Comment by panstromek** [comment]
Oh - thanks a lot, I missed that  ;) works now.

btw. is there a way to embed the window into IntelliJ terminal window? If I set it in intelliJ it always opens a new window.
