### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by bemeurer** [jwilm/alacritty#2086]
Since Wayland window name functionality was just added, which is the only thing keeping me from using Alacritty for everything, I'd like to ask for a release to be cut so it can show up downstream.

PS. Show up on IRC @chrisduerr !

**Comment by chrisduerr** [comment]
A new release is planned either this weekend or next weekend, depending on how the latest features behave. Since the #2045 PR changed quite a bit of things, I might hold off with a release until next week. Though I will consider your specific issue.

Also note that I should be reachable in #alacritty on freenode 24/7 and I usually am also around in the #rust/#rust-beginners channels on mozilla.

**Comment by bemeurer** [comment]
Thanks @chrisduerr!
