### ISSUE TITLE
Inaccurate claim

### ISSUE THREAD

**Issue by jcayzac** [jwilm/alacritty#2087]
Hi,

> Alacritty is the fastest terminal emulator in existence. Using the GPU for rendering enables optimizations that simply aren't possible in other emulators.

This is a bit misleading. [iTerm2 for instance has had GPU rendering since version 3.2.0](https://gitlab.com/gnachman/iterm2/wikis/Metal-Renderer).

**Comment by nixpulvis** [comment]
Maybe we can simply add "in most other emulators."

I don't have strong feelings about this, and I'm not a marketing person really.

**Comment by chrisduerr** [comment]
I think that's the least inaccurate claim made in the README.

`other emulators` here implies other terminal emulators that do not use GPU rendering, otherwise the statement about the GPU rendering would be pretty pointless anyways.

Discussions about reworking the readme a bit have been made before, however I see no rush to jump to action here. It's likely things will get reworded in the future though, taking out the `alpha` is another thing worth considering (at least switch it to beta, it's by far not as unpolished anymore as it was when it was first put there).
