### ISSUE TITLE
Display issue with 2 monitors on MacOS after update to 0.2.8

### ISSUE THREAD

**Issue by timorunge** [jwilm/alacritty#2098]
> Which operating system does the issue occur on?
MacOS 10.14.3.

After the update from 0.2.7 to 0.2.8 Alacritty has a problem with different monitors and different display resolutions. In my case I'm using the default monitor of a MBP (1680x1050) + an external 24" Monitor (1200x1920 correct value).

Using just one monitor is working perfectly fine. 

Starting Alacritty on the MBP looks good: 
<img width="1140" alt="screenshot 2019-02-11 at 11 40 16" src="https://user-images.githubusercontent.com/1560363/52558463-bdbb1200-2df2-11e9-8044-850393063360.png">

Moving Alacritty to the external monitor: 
![screenshot 2019-02-11 at 11 40 36](https://user-images.githubusercontent.com/1560363/52558476-cad80100-2df2-11e9-8cde-c7715524fe33.png)

And moving it back to the MBP one:
<img width="1140" alt="screenshot 2019-02-11 at 11 40 48" src="https://user-images.githubusercontent.com/1560363/52558492-d62b2c80-2df2-11e9-8bd8-cbd3de8a2828.png">

**Comment by chrisduerr** [comment]
This was caused by https://github.com/jwilm/alacritty/commit/b55e219bc4a5378caa9e0070cdf59a9be7ec48d1 and affects all platforms.

Might qualify for another release since the impact is pretty high.

**Comment by jshap70** [comment]
Can confirm that I am seeing this on Arch Linux as well after upgrading to `0.2.8`. I similarly have 2 monitors w/ different dpi's, however alacritty looks not good on both of them now. 

screenshot from starting on external monitor (1920x1200):
![image](https://user-images.githubusercontent.com/9045475/52592659-94a77b00-2e0c-11e9-92f1-a839634951ff.png)

moving back to laptop display (3840x2160 downscaled to 1920x1080 because X scaling _grumble grumble_): 
![image](https://user-images.githubusercontent.com/9045475/52592646-8c4f4000-2e0c-11e9-8fd7-bb82b57dea9c.png)
