### ISSUE TITLE
Use $XDG_CONFIG_HOME on windows

### ISSUE THREAD

**Issue by dakom** [jwilm/alacritty#2108]
On Windows, would be nice if Alacritty could first check for `XDG_CONFIG_HOME` in the environment vars, rather than always using `%APPDATA%\alacritty\alacritty.yml`

**Comment by chrisduerr** [comment]
`XDG_CONFIG_HOME` is a Linux-specific variable that has been created specifically for X.Org and which has now been inherited by Wayland. This is not a specification which is followed by Windows at all, so I don't think we should query it to decide where the config file should be read from.

I think Alacritty currently reads the `APPDATA` environment variable. Which is Windows specific and allows Alacritty to properly fit into the system. I'm unsure if it's possible to change this without breaking Windows, but even if it's not, the `--config-file` flag might still help out.

I'm not completely opposed to read from other environment variables if they are standardized for the Windows platform. However the `XDG_CONFIG_HOME` mentioned in this issue is definitely not something that should be followed on Windows as far as I can tell.
