### ISSUE TITLE
Feature request: different padding for top and bottom

### ISSUE THREAD

**Issue by ston1x** [jwilm/alacritty#2121]
I like the `transparent` decoration a lot but I have to set padding by `y` so that the buttons would not overlap the content.  
As the padding by `y` increases, it increases in both top and bottom sides of the window so there is some free unused space at the bottom.  
It would be convenient to set top and bottom padding independently.

<img width="773" alt="screenshot 2019-02-18 at 11 16 44" src="https://user-images.githubusercontent.com/13198813/52940227-b2c22d80-336e-11e9-85a7-b5d183f7df23.png">

**Comment by chrisduerr** [comment]
This is one possible solution to the problem. Among others it has been discussed in https://github.com/jwilm/alacritty/issues/1671.

**Comment by Lambdaphile** [comment]
@ston1x Did you find a way to achieve padding top only? I'm currently facing the same problem. @chrisduerr IMO, transparent decoration should only make the window bar take theme's background, not make it part of the "editable area", because it makes setting useless, since the close/min/max buttons overlap with the text area. This is what I mean:
<img width="173" alt="Screen Shot 2023-07-07 at 22 22 44" src="https://github.com/alacritty/alacritty/assets/5767281/bf8c677d-4b97-4a74-9239-ac33fdc910ec">

**Comment by elzii** [comment]
Biggity Biggity bump.
