### ISSUE TITLE
Package as rpm for Fedora

### ISSUE THREAD

**Issue by Limero** [jwilm/alacritty#2126]
It would be cool if the releases were also offered as rpms for Fedora. Currently, the only Linux package format offered is .deb.

**Comment by chrisduerr** [comment]
Note that the tarfile should work on Fedora based on my testing.

However it seems reasonable to provide an rpm package since we already have .debs.

**Comment by eberkund** [comment]
Won't snaps be good enough for all Linux platforms?

**Comment by chrisduerr** [comment]
While snaps, flatpak and the like are an option, they're very subpar. Afaik an Alacritty snap already exists too, I'm not sure about flatpak.

In general, Alacritty shouldn't really have to provide many Linux packages, since the source is available and plenty of distributions are capable of maintaining Alacritty and already do. However there are some very commonly used distros which unfortunately are very slow at adapting new packages (namely Ubuntu, Fedora and Debian). Providing RPMs and DEBs would allow us to fully support these platforms natively, without punishing the user for their distro choice.

Of course this isn't a great solution and comes with plenty of problems (DEBs in general only work with one specific version for example), however it seems to be the only option to work around slow maintainers without putting users at a disadvantage.

**Comment by eberkund** [comment]
What makes you say snaps are very subpar? My experience with them (as a user and developer) has been nothing but positive and it's my preferred method of installing software when it is available.

**Comment by chrisduerr** [comment]
This isn't the right place to get into the advantages and disadvantages of different ways to distribute software, but snap/flatpak undermine a lot of the advantages that package managers offer and sacrifice user experience for convenience of developers.

**Comment by The-Loeki** [comment]
As a user I actually rather like the FlatPak approach

**Comment by xliiv** [comment]
Could anyone outline what steps should be done to make it happen? Or which other project already implement it from which it could be copied?

**Comment by chrisduerr** [comment]
The main thing is that we would need a fedora container to run all of this with everything necessary bundled in.

**Comment by xliiv** [comment]
Can anyone share `Dockerfile` for `undeadleech/alacritty-ubuntu`?

**Comment by chrisduerr** [comment]
All the dockerfiles are in the repository:
https://github.com/jwilm/alacritty/blob/master/ci/x86_64/Dockerfile

**Comment by pschyska** [comment]
Just a heads-up, I added a specfile template in#2506 because I'm trying to build in COPR. This would allow using the Fedora infrastructure to build and host RPMs, and probably make it easier for official Fedora inclusion down the line.

**Comment by dankamongmen** [comment]
I've got a few packages in Fedora, and am going to look at getting this packaged up for Fedora Core, unless any upstream developers object.

**Comment by chrisduerr** [comment]
> if for no other reason than I currently have to reset my TERM when ssh'ing to a Fedora machine

This should already be fixed by updating to the latest version of ncurses. Since they ship our terminfo.

> unless any upstream developers object

We do not. :)

**Comment by dankamongmen** [comment]
Fedora 33 ships ncurses-6.2-1.20200222, but I don't see the alacritty terminfo file in `ncurses-base`. I'll file a bug (and patch) against the package, as it looks like the alacritty terminfo file was added in 20181027 (and updated in 20190803 and 20200118). If the maintainer refuses it because alacritty isn't yet in Fedora, well, that'll change soon =]. I'll ensure the terminfo file is provided by `ncurses-base` either way; thanks for the reply, @chrisduerr. https://bugzilla.redhat.com/show_bug.cgi?id=1849974

**Comment by kchibisov** [comment]
It has nothing to do whether alacritty is available as package or not. You should handle the use case of ssh with `TERM=alacritty` somehow from other machine, which has alacritty terminfo. If they remove terminfo that is in 6.2 release for some abstract reason, it's just sad.

**Comment by dankamongmen** [comment]
@kchibisov indeed; I misspoke above; I scp'd the Debian alacritty terminfo onto my Fedora machine last week. It turns out that the terminfo file is present in `ncurses-term`, just not `ncurses-base`. I've asked for it to be moved into `ncurses-base`, but we'll see. Either way, it's there. Packaging alacritty is proceeding, and I'll post that today for inclusion in Fedora Core.

**Comment by pschyska** [comment]
@dankamongmen Thanks for your effort!

I have to admit I fell behind pushing new builds up to COPR because I stopped using Fedora. I suggest to remove the corresponding files in this repo as soon as alacritty is packaged officially.
Just out of interest, did you already post the inclusion request? I'd like to check it out.

Cheers!

**Comment by dankamongmen** [comment]
@pschyska I made my own specfile, being unaware of yours, but I'll go take a look at yours before submitting it (which I plan to do tonight). In other news, I can report that the newest build of `ncurses-base` has the alacritty terminfo description, freshly moved out of the optional `ncurses-term`.

**Comment by dankamongmen** [comment]
Alas, it looks like this isn't currently possible without work of the kind described in #357. If alacritty requires modified versions of crates present in Fedora, that simply won't fly (`servo-freetype-sys` was mentioned 2019-12). Anything which it's bringing in which *isn't* in Fedora will need be packaged up and submitted, or (circumstances willing) defined as a subpackage `Provides`. I'm looking through this now, and doing the tedious work of converting cargo deps into `BuildRequires`, but if that `servo-freetype-sys` still needs patching, I'm going to abort for the time being. What I have thus far can be seen at https://github.com/dankamongmen/fedora-mmmmlady/blob/master/alacritty.spec.

**Comment by kchibisov** [comment]
We're not using `servo-freetype-sys`. I'm not sure what are you talking about.

**Comment by chrisduerr** [comment]
> We're not using servo-freetype-sys. I'm not sure what are you talking about.

The latest release still is. This will be changed with the next release @dankamongmen.

**Comment by kchibisov** [comment]
>The latest release still is.

Oh, indeed. I guess I forget to include it in `v0.4.3` for some reason, since I've thought that I've done that. In any case, waiting for `v0.5.0` makes the most sense here, since we move a lot of things to `crates.io` for the first time.

**Comment by myroslav** [comment]
@dankamongmen, 0.5.0 was released. Will you have a chance to look at packaging this newer version, please?

**Comment by dankamongmen** [comment]
Absolutely! I'll get to it in the front half of this week.

**Comment by pschyska** [comment]
@dankamongmen  Just a heads-up, a COPR user notified me of an unowned file in my .spec,
`/usr/share/alacritty`. This directory remains when alacritty is uninstalled. He suggested to add:
```
# under %files
%dir %{_datadir}/alacritty/
```

(see https://github.com/zenofile/rpm-rust-alacritty/blob/a2ba2af7f56ded1251094b6ec8ad9b7b61e527d5/alacritty.spec#L60).
I feel that his specfile is generally better crafted than mine (e.g. shell-specific triggers for completion), so I suggest you take a look there too.

**Comment by dankamongmen** [comment]
> @dankamongmen Just a heads-up, a COPR user notified me of an unowned file in my .spec,
> `/usr/share/alacritty`. This directory remains when alacritty is uninstalled. He suggested to add:
> 
> ```
> # under %files
> %dir %{_datadir}/alacritty/
> ```
> 
> (see https://github.com/zenofile/rpm-rust-alacritty/blob/a2ba2af7f56ded1251094b6ec8ad9b7b61e527d5/alacritty.spec#L60).
> I feel that his specfile is generally better crafted than mine (e.g. shell-specific triggers for completion), so I suggest you take a look there too.

thanks for the heads-up; i'll do exactly that. planning on getting to this tonight.

**Comment by dankamongmen** [comment]
I'm having difficulties at the moment due to the following not being available as RPMs in Fedora Core:

* crossfont (any version)

I'll look around to see if anyone's packaging it. If not, I might be able to.

**Comment by dankamongmen** [comment]
> I'm having difficulties at the moment due to the following not being available as RPMs in Fedora Core:
> 
> * crossfont (any version)
> 
> I'll look around to see if anyone's packaging it. If not, I might be able to.

ahh, it looks like crossfont is part of alacritty. i doubt anyone's bothered to package it in that case. i guess i'll be getting to it!

here's my specfile thus far: https://github.com/dankamongmen/fedora-mmmmlady/blob/master/alacritty.spec

**Comment by starvsion** [comment]
```
sudo dnf install alacritty-0.5.0-1.x86_64
Last metadata expiration check: 0:10:05 ago on Tue 29 Sep 2020 06:36:14 PM.
Error: 
 Problem: conflicting requests
  - nothing provides ncurses-extraterms needed by alacritty-0.5.0-1.x86_64
(try to add '--skip-broken' to skip uninstallable packages)
```
Looks like the one from rpmsphere is having some issue ...

**Comment by pschyska** [comment]
@starvsion I don't know who is behind the rpmsphere package, but I recently fixed a terminfo issue (which I assume is why it requests ncurses-extraterms) in [copr](https://copr.fedorainfracloud.org/coprs/pschyska/alacritty/), and 0.5.0 could be build for Fedora 33 and earlier versions.
You could try that package if you like.
