### ISSUE TITLE
terminfo details missing on macOS

### ISSUE THREAD

**Issue by JeanMertz** [jwilm/alacritty#2131]
The [installation instructions](https://github.com/jwilm/alacritty/blob/8d5e1226d500579692128439abd9c991ba9a72d3/INSTALL.md#terminfo) mention running:

```
sudo tic -e alacritty,alacritty-direct alacritty.info
```

to install the Alacritty specific terminfo definitions.

However, this does not (always) seem to be enough to get cursor style support to work, [specifically in tmux](https://github.com/jwilm/alacritty/issues/1630#issuecomment-467360764).

The solution for me was to add the `-x` flag to `tic`:

```
  -x         treat unknown capabilities as user-defined
```

However, it appears this is not the final solution, as it apparently [changes the behavior of Alacritty](https://github.com/jwilm/alacritty/pull/1877#pullrequestreview-182701932).

This is happening with the following software versions:

* Alacritty (8d5e122)
* Tmux (2.8)
* macOS (10.14)

**Comment by chrisduerr** [comment]
Some prior discussion was made in https://github.com/jwilm/alacritty/issues/1630.

Checking quickly through everything, it almost looks to me like the capabilities that are not included without the `-x` flag are just ignored completely, but it has been a while since I've taken a look at terminfo.

If this would be the case, chances are that applications like `htop` might break because of the additional escape sequences, not because one might be missing. In that case the escape which causes these issues should probably be narrowed down and fixed or removed.

Taking a look at the build files for Termite in the Archlinux repository, you can see that this does indeed use the `-x` flag (https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/termite#n65). The Alacritty package here does not use them, likely because they were following our install instructions. Taking this into account, I'm pretty certain at this point that I was wrong in the past and the `-x` flag is something we should strive to get working.

**Comment by JeanMertz** [comment]
> If this would be the case, chances are that applications like `htop` might break because of the additional escape sequences

FYI: on my machine, I don't see any (obvious) breakage of the `htop` output. Anything specific that looks off on your end?

**Comment by chrisduerr** [comment]
This has been a long time ago, but I believe the issues were likely related to clicking of the columns to sort them and clicking on different rows to select them.

With the current terminfo this should work great (it does on my machine), but iirc it broke with the `-x` option. If this works for you, please let me know and I'll look into it again.

**Comment by JeanMertz** [comment]
Ah, yes, you are correct, it does break (in interesting ways, I might add 😄).

**Comment by chrisduerr** [comment]
Well, using the `tmux-256color` terminfo likely doesn't have this problem because it's unrelated to the Alacritty terminfo.

**Comment by JeanMertz** [comment]
@chrisduerr true, but what I found interesting about that is that the cursor style changing still works as expected.

So: using `-x` was required, but `$TERM` can still remain on `tmux-256color`, and things are now working as expected (regarding my original issue of the cursor style not changing when doing `echo -e "\e[6 q"`)

**Comment by chrisduerr** [comment]
The problem with Neovim's cursor style is not Alacritty's support for it. If any program ever sends the right escapes, Alacritty will parse them properly and apply them. The problem is that these escapes are never sent if the terminfo is incorrect.

So keeping the `TERM` on something other than `alacritty` is kinda pointless, because you're just completely circumventing the issue.

**Comment by chrisduerr** [comment]
@JeanMertz Would you mind testing if you can find any issues with the new terminfo file provided in #2134?

**Comment by kernel-panic96** [comment]
I can confirm that it does work on MacOS, my version is Mojave 10.14.4, just a heads up if someone follow these instructions and it still does not work.

Make sure your `.tmux.conf` does not have extra `terminal-overrides` without the '-a' (append, don't overwrite) option.
I had one  `set -g terminal-overrides 'xterm*:smcup@:rmcup@'` deep inside the conf file and spend 3 hours wondering why it's not working.
