### ISSUE TITLE
macOS: Can't quit by pressing Cmd-Q

### ISSUE THREAD

**Issue by johannesl** [jwilm/alacritty#218]
On macOS any application can be terminated by pressing Cmd-Q. Not allowing this can be very confusing for newcomers. Plus it slows down restart time when you need to move your fingers to the trackpad / mouse.

**Comment by garyemerson** [comment]
In the meantime, exiting the shell process seems to be a good mouse-free alternative to Cmd-Q (e.g. `exit` in bash).

**Comment by jwilm** [comment]
Or equivalently, Control-D (sends EOF)

**Comment by dannydulai** [comment]
this issue is the same as #119

**Comment by johannesl** [comment]
Ah, sorry.. Missed issue #119.

The problem for me with EOF or Ctrl-D is that it doesn't work when the shell / process you run has hanged or you accidentially hit ~ again on your Swedish keyboard.

**Comment by brandur** [comment]
Just a small additional comment: it would also be nice if other "standard" Mac OS shortcuts worked as well like Cmd-W for close window (and hopefully Cmd-N to open one eventually too!).

I'm interested in trying to tackle a bug like this one which seems like it should be relatively tractable. Can anyone with decent knowledge of the project comment as to whether there are any pitfalls or other background here? Is the feature missing only because it hasn't been implemented yet? Thanks!

**Comment by jwilm** [comment]
>  Is the feature missing only because it hasn't been implemented yet?

That is indeed the reason for _most_ missing features at this point.

Cmd-W is essentially going to be equivalent to Cmd-Q at this point since each Alacritty is a process leader. Cmd-N I was planning to implement very generally -- just making it possible through config. One `Action` that we would like to have is the ability to exec another process. You can imagine then that CmdN would just exec another Alacritty.

**Comment by brandur** [comment]
> Cmd-W is essentially going to be equivalent to Cmd-Q at this point since each Alacritty is a process leader.

I think that would be fine until there are actually windows to be closed individually.

> Cmd-N I was planning to implement very generally -- just making it possible through config. One Action that we would like to have is the ability to exec another process. You can imagine then that CmdN would just exec another Alacritty.

Yep, that makes perfect sense. My bar is low, and I'd just like to (eventually) see it behave roughly like other common windowed applications on Mac OS like Finder, iTerm2, or Chrome.

I've taken a shot at a basic fix for this one in #393.
