### ISSUE TITLE
Are the hardware accelleration claims a bit of an oversell since this feature exists in SDL as well?" Your writing about the project seems to seems to make theclaim that OpenGL alone can hardware accelerate.

### ISSUE THREAD

**Issue by wade-welles** [jwilm/alacritty#2197]
> "Yes, SDL supports 3D acceleration: ... Alternatively, you can use SDL's 2D accelerated render API using SDL_Texture for pure 2D graphics which itself uses either OpenGL or Direct3D for acceleration (but it is easier to use than OpenGL/Direct3D directly and you get support for both for free)." - [libSDL FAQ](https://wiki.libsdl.org/FAQDevelopment)

> "Would I be truthful if I were to describe to users of my API that the  Cairo implementation is hardware accelerated?" 
> "Yes. cairo supports a number of backends, which it uses is under your
control....On the Linux desktop, both Nvidia and Intel have very good XRender
drivers which are much faster than trying to feed cairo through OpenGL."- [Cairo Developer responding to mailing list question](https://lists.cairographics.org/archives/cairo/2012-October/023609.html)

And Intel put out LibVA a long time ago to make getting access to the hardware acceleration functionality from GPU to CPUI available. 

**If this interpretation is correct**... the it would appear hardware acceleration as a selling point is quite misleading, and you would actually get a performance boost by ensuring your rendering was vector rather than pixel based. It would also support scaling better. 

So for example, Cairo2 which is capable of vector/raster graphics rendering can also do hardware acceleration, even partially through OpenGL (being it supports multiple backends). 

* **cairo-gl:** use OpenGL for GPU compositing and some rasterisation, depends
upon driver quality
* **cairo-xlib:** use XRender to send commands to X which uses the GPU for
compositing and some rasterization, depends upon driver quality

**So whats the deal? If I'm failing to understand something I would appreciate any information that would make it clear how attracity rendering is special. This is important to me because I'm also a developer interested in this subject and I'm trying to better understand this subject, and me bringing this up is mostly about setting the record straight to improve my knowledge on the subject and have this be a resource for other developers.**

It would seem to me any modern implementation of a graphical user interface using

**Comment by krixano** [comment]
So because SDL is accelerated, that means Alacritty isn't. Or are you saying that means alacritty isn't anything "special" - in which case, you are comparing software of different purposes. The more important question is if Alacritty is the only *terminal emulator* that uses OpenGL.

Additionally, correct me if I'm wrong (I very well could be), isn't using OpenGL more performant than not using it?

**Comment by chrisduerr** [comment]
There already are a few other issues which discuss this, so I'm going to keep it short, but there are a few differences between Alacritty and a terminal emulator which uses something like Cairo.

While Cairo does support hardware acceleration, it's a completely different story to render completely using OpenGL. Hardware acceleration certainly already helps a lot, but you still only have limited control over the smaller details.

However Alacritty is not *just* a terminal emulator which uses OpenGL exclusively to render to the screen. There are a lot of things that go into making a terminal emulator fast and rendering is just a small part of it. Having a renderer that is incredibly fast at going from grid in memory to grid on screen allows us to do other things that you might not be able to do if your renderer was slower.

So if you just pick a random terminal emulator and strap an OpenGL frontend on top of it, you likely won't gain a lot.

However using 'pure' OpenGL to render is not a common thing for terminal emulators. It comes with certain advantages and disadvantages and a lot of people are familiar with what OpenGL is fundamentally. Because of that it makes sense to point it out explicitly because it's a simple and specific thing that is part of why Alacritty is so fast.

> The more important question is if Alacritty is the only terminal emulator that uses OpenGL.

I believe Kitty (not the Windows one) is also a terminal emulator which uses OpenGL for rendering. But that's the only other example I'm aware of. And Kitty too (rightfully) advertises this. Since these are the only two I'm aware of, it makes sense to point out that things work differently here.

If you have any more questions, feel free to let me know. But there's also a lot of information on Alacritty and how it works out there already (including one talk by the author). So if you're really curious it might be worth taking a look at that.
