### ISSUE TITLE
Ctrl-L should at least optionally not remove contents from the scrollback buffer

### ISSUE THREAD

**Issue by pedrocr** [jwilm/alacritty#2199]
Which operating system does the issue occur on? Ubuntu 18.04
If on linux, are you using X11 or Wayland? X11

I will often clear my terminal screen just so I can start issuing commands with a fully empty page. I like however to maintain the full screen history just the same. gnome-terminal reacts to Ctrl-L by actually adding empty lines in the scrollback. alacritty will remove the lines cleared from the screen from the scrollback. Apparently both are valid behaviors:

https://github.com/kovidgoyal/kitty/issues/268#issuecomment-355764257

Ideally I'd like a third behavior where just the position in the buffer changes and Ctrl-L is just like a scroll down past the current point so the rest of the terminal below the current position is still empty.

**Comment by nixpulvis** [comment]
OK, I want to tackle this issue... but I also want to adress the fact that another valid expectation is that <kbd>ctrl-L</kbd> would clear everything, also not what we do today. We currently clear the visible region and leave the history, which is I think an incorrect mix of these two desired options.

Am I understanding this correctly. The proposal is to add an option to the configuration for how to handle `ClearMode::All`, either clearing everything from history, or simply shifting everything into the history buffer, either way leaving the user (as it is today) with a clear visible region.

Either way it's not quite right at the moment I'd argue.

**Comment by chrisduerr** [comment]
> which is I think an incorrect mix of these two desired options

I don't think `incorrect` is completely accurate here since we do provide the user with a new and clean page. As far as I can tell all three described options are 'correct', though our option right now is not very practical and potentially confusing.

I feel like it's also important to note that URxvt behaves the same way that Alacritty does today. While it's hardly modern and focused on being simple to use, it is one of the biggest terminal emulators out there. Kitty behaves the same way.

> The proposal is to add an option to the configuration for how to handle `ClearMode::All`

I don't think this is necessary. I don't recall anyone explicitly requesting XTerm's behavior and it would be simple to recreate yourself with escape sequences if you *really* wanted that. So I'd keep the config clean and just shift everything up.

> It sounds like a VTE behavior, so maybe it should be the default.

I don't think only because VTE behaves a certain way, it should be the default option, when evidently a lot of other terminal emulators behave differently. However, I think in this case VTE has made the best choice for the users so following that lead makes sense to me.

The only disadvantage to my proposed solution would be that it will be impossible to remove everything currently visible from the history forever without also clearing the full history. But I think that's fine and unlikely to be desired.

**Comment by pedrocr** [comment]
> However, I think in this case VTE has made the best choice for the users so following that lead makes sense to me.

Note that VTE does something weird as well. It adds to the history a bunch of empty space instead of simply scrolling the history out of the way. What I'm suggesting is actually a third behavior that goes a bit further that what VTE has done and that at least to me seems ideal for the user.

**Comment by nixpulvis** [comment]
I recall being some discussion around this back when 72495172c25e00799f29eb2e79fe40ddfa189866 was implemented.

**Comment by nixpulvis** [comment]
@pedrocr unfortunately we seem to receiving a `CSI 0; 0 H` before the `CSI 2 J` (I think), and this makes it hard because it removes our knowledge of the current cursor position. If I'm understanding your third option, I agree that'd be ideal, but seems hard to achieve. I don't really want to track cursor positions across escape codes, and it's unclear exactly how that could even work.

Am I missing something?

**Comment by pedrocr** [comment]
Maybe this is only possible if the shell cooperates? I guess having to configure the shell as well is fine. But somehow VTE knows enough to end up with a scroll buffer with everything in it and some extra space that was cleared. Since it knows where it was before wouldn't it be possible to remove those extra lines from the scrollback at the end of the process?

**Comment by aneutron** [comment]
Alacritty absolutely destroys all the other candidates I have tried for a main term, and only falls short in this regard _(especially when doing sysadmin work ...)_, I can't wait when this is implemented and I can use it as my main and exclusive term.

**Comment by pedrocr** [comment]
Yay! Thanks
