### ISSUE TITLE
URLs containing unescaped unicode are not recognized

### ISSUE THREAD

**Issue by awused** [jwilm/alacritty#2216]
Alacritty does not recognize URLs containing unescaped unicode characters.

https://はじめよう.みんな/index.html is recognized as a valid URL by modern browsers and most programs. Passing it to xdg-open results in the expected behaviour.

**Comment by enizor** [comment]
Alacritty should recognize unicode characters in URLs, try http://bücher.com
For me, Alacritty only recognizes the first Unicode character.
I think this URL uses double-width characters, since upgrading to latest master fixed it (thanks to #2203).
Could you confirm this bug on the latest version of Alacritty?

**Comment by chrisduerr** [comment]
This has been fixed in the latest master but is not released yet.

**Comment by awused** [comment]
Confirming this is fixed at the current head.
