### ISSUE TITLE
alacritty produces misaligned output without tmux when using column

### ISSUE THREAD

**Issue by ratorx** [jwilm/alacritty#2228]
## Environment
OS: Arch Linux (X11)
Version: alacritty-git from AUR (commit https://github.com/jwilm/alacritty/commit/8654a09f73c1fc63dae8f7ba7ab91999498852c2)
$TERM without Tmux: alacritty or xterm-256color
$TERM with Tmux: screen-256color

## Steps to reproduce
* Run a command which produces a lot of output (e.g. list all installed packages)
* Pipe result through `column`

## Expected behaviour
columns of output which are nicely aligned

## Current behaviour
misaligned output

This is an issue only when using `alacritty`, but not when using `alacritty` + `tmux`. The latter has the desired behaviour.

![Image showing issue](https://user-images.githubusercontent.com/10564044/55201271-2b13de00-51ba-11e9-8ea1-28bf0909b1b6.png)

Left is `alacritty`, right is `alacritty` + `tmux`

[Link to current config](https://pastebin.com/rncCDyPd)

**Comment by chrisduerr** [comment]
Are you using a different terminfo or did you change the number of tabs in the Alacritty config?

This works on my machine, using the `alacritty` terminfo with the default config.

**Comment by ratorx** [comment]
Changing tabspaces to 8 fixed this; any way to use tabspaces = 2 and have this work?

**Comment by chrisduerr** [comment]
Tmux likely works because it overwrites Alacritty's tabspace settings. It is also using a different terminfo but I doubt 2 is the default there.

Both terminfo and tabs in Alacritty need to be in sync, since many applications actually use tabs for rendering and performance optimization.

Tmux is pretty much a terminal emulator running inside a terminal emulator, so not everything set in Alacritty will necessarily take effect in tmux.
