### ISSUE TITLE
[Question] does it have a performance hit for other GPU intensive apps?

### ISSUE THREAD

**Issue by Trollwut** [jwilm/alacritty#2266]
Hey folks!

This may be a stupid question. I love the concept of this terminal, so I gotta ask if this is for me.

I use to game - and also have some terminals open (e.g. `htop`, `vim` and some other small stuff). As it uses GPU, will this have a performance hit on my games?

I understand that `alacritty` won't use 100% GPU, but maybe there is something like "some other app also uses the GPU, so don't give the game everything it needs".

**Comment by chrisduerr** [comment]
In a way this question could be asked for the CPU too, since games often require a lot of CPU horsepower too (even though they're often not bottlenecked by it directly), but you'll likely not find your performance impacted severely unless you're going hard at the CPU with another program.

On macOS/Windows, you also have video acceleration that uses the GPU. So that might be a better comparison. Usually when watching a youtube video at the same time, your performance shouldn't drop significantly (at least in my experience).

Of course when sharing resources you'll always have some impact from one application to another. So I can't guarantee you that opening Alacritty will not drop your games by 1 or 2 FPS. But I'd be seriously surprised to see a significant impact, since Alacritty should be relatively tame on the GPU compared to games.

Also note that while Alacritty is not updating, it will not redraw. So unless you're running `yes` while gaming, the impact should be even lower (probably 0).

I've never actually looked into this myself though, so if you want to give it a test yourself that's probably the best way to learn about how things work. Regarding a system that would share resources 50/50 instead of based on demand, I'm not aware of any OS which does that and it would likely cause a ton of issues, so that's definitely not the case.

I hope that answered your questions. If you have any more, just let me know.

**Comment by Trollwut** [comment]
Thanks for that information! Yes I know about the resource stuff. I'm just unsure how graphic performance is being distributed.

> Also note that while Alacritty is not updating, it will not redraw. So unless you're running yes while gaming, the impact should be even lower (probably 0).

I guess that's the crucial part for now for me. When running `gotop` or `htop`, it uses much more CPU in my VM setting right now. 

- gotop in urxvt: 0.5%
- gotop in alacritty: even less!
- 3x alacritty open with gotop: alacritty 4.3% + gotop 0.9%

The gotop processes seem to scale with their number running, so that's fine. Is there something I need to know about these extra 3% from the alacritty process?

I fear that if I have some alacritties open, it will consume even more CPU and that will then be a performance hit on games.

I also can't reproduce these CPU consuming with `vim` opened (well, which doesn't redraw if not needed). So might this be a problem with htop/gotop?

**Comment by chrisduerr** [comment]
I'm not sure about how `gotop` works but Alacritty sits at a consistent 0% CPU for me with htop. It really depends on what the process does though, so the more it updates, the more Alacritty will have to process obviously.

**Comment by Trollwut** [comment]
So I guess this has to do with my VM setup. For example that it simply doesn't have the GPU power that's necessary. I will double-check that when being home.

Thanks for the information!

**Comment by Trollwut** [comment]
Yo I'm back and yesterday I had some time doing benchmarks. They won't say everything, but for me it was enough.

What I tested:

- running the benchmarkk (unigine heaven) twice (once to get "warm", once to measure)
- open a buttload (5) instances of alacritty and run the benchmark again
- open alacritty 5x and open `gotop`/`htop` in each of them and running benchmark again

Biggest difference was about 0.5-1.0%, so this may not even be an impact, but rather just error in measurement.

This is *not* a real objective test, but for this means, that alacritty doesn't have an impact on GPU intensive games at all (at least not any you can feel).

I blame my VM and most likely a bad graphics driver for the VM for my problem.

Hope that may help some future readers. :)
