### ISSUE TITLE
Alacritty v0.3.0-rc3 crashes with fontconfig 2.13 its:rules

### ISSUE THREAD

**Issue by HakateyamaYuki** [jwilm/alacritty#2267]
Which operating system does the issue occur on?
Arch Linux
Linux 5.0.6-arch1-1-ARCH

If on linux, are you using X11 or Wayland?
X11

Alacritty doesn't run with _its:rules_ set in fontconfig .conf files.
error log: https://p.teknik.io/hNFaY

relevant commit: https://cgit.freedesktop.org/fontconfig/commit/?id=9a0fcb948fe7346f6c68028b2e54ab600a2a2a6f

**Comment by chrisduerr** [comment]
Did you download the precompiled binary? If so, this does not work on Arch. You'll have to either use the official package or compile it from source.

**Comment by HakateyamaYuki** [comment]
Yes, indeed I downloaded precompiled binary. Thank you for replying. Shouldn't it be mentioned somewhere in README? This would help other users in future.

**Comment by chrisduerr** [comment]
Well it's impossible to provide a single executable on multiple different distros when dynamic linking is used (which we have to do since X and Fontconfig and Freetype and all that stuff).

So I'd think that it shouldn't be much of a surprise usually.

I've considered removing precompiled binaries on Linux completely in favor of letting maintainers handle this, so this is mostly just a 'better than nothing' effort.
