### ISSUE TITLE
Some key bindings stopped working on 0.30

### ISSUE THREAD

**Issue by pbgc** [jwilm/alacritty#2280]
Which operating system does the issue occur on? macOS Mojave 

To use some needed keys on my MBP Portuguese Keyboard, I had to add this to alacritty.yaml:

  - { key: Key8,        mods: Alt|Shift,      chars: "\x7B"            }   # {
  - { key: Key9,        mods: Alt|Shift,      chars: "\x7D"            }   # }
  - { key: Key8,        mods: Alt,            chars: "\x5B"              }   # [
  - { key: Key9,        mods: Alt,            chars: "\x5D"              }   # ]
  - { key: Key2,        mods: Alt,            chars: "\x40"              }   # @

This always worked ... but stopped working with 0.30 . Can't understand why ... but they don't work at all or do strange things.

EDIT: From the above the only one that works is:
- { key: Key2,        mods: Alt,            chars: "\x40"              }   # @

**Comment by timorunge** [comment]
I've a similar issue on a German keyboard layout on MacOS 10.14.4.
"[" is just getting typed after entering a second character (e.g. space) or hitting it twice. Also re-adding the key mappings is not sorting the issue.

**Comment by chrisduerr** [comment]
Is `alt_send_esc` option enabled or disabled? Could you try toggling it to see if that fixes the issue?

**Comment by pbgc** [comment]
@chrisduerr turning it to false (it was true) seems to fix it!

**Comment by timorunge** [comment]
@chrisduerr it was enabled (like the default) for me. Disabling helped in my case. Thanks a lot.

**Comment by chrisduerr** [comment]
This is due to escape sequences getting send to the terminal by default when pressing alt. That is the intended behavior for terminal emulators and there's no way around this. Which is what this option is there for.

Hopefully that resolves the issue. In regards to german layouts, treating `AltGr` differently than `Alt` is tracked upstream and will probably land in the future, so once that lands it shouldn't be necessary to use that option for AltGr anymore.
