### ISSUE TITLE
10.13 macOS kernel panic

### ISSUE THREAD

**Issue by sandersantema** [jwilm/alacritty#2309]
Which operating system does the issue occur on?
macOS 10.13.6 
Alacritty: I can't exactly remember if I've got the pre-release installed or if I've compiled the latest HEAD myself. If it's HEAD the latest commit would be [this one](https://github.com/jwilm/alacritty/commit/aac62ce5acd2ef4d05a54bc13b7cf30c30f129b2)

Yesterday I got a kernel panic while using newsboat in alacritty (rss feed reader). 

Mac OS came up with the following log after my computer rebooted:
https://gist.github.com/sandersantema/bed51062fda62420ba2206d8e10849f7

I think  alacritty was what caused this kernel panic, atleast that's what I can deduct from the error log. However I was using virtualbox at the time too, which has some low level kernel extensions (as reported in the log).

I suppose you would need more information but I wouldn't know where to find the crashlogs etc. if this is serious and indeed caused by alacritty could someone more knowledgeable provide me the commands to get a crashlog and/or path where to find the crashlogs? Thanks in advance.

**Comment by chrisduerr** [comment]
While this bug showed up while running Alacritty, it seems to be pretty clear that the kernel panic itself came from the graphics drivers.

Since there's no graphics operation that should just allow an application to kill the kernel, I'd recommend reporting it there, since there's nothing Alacritty can do about a driver bug.
