### ISSUE TITLE
[Question] Can I bind vim command on shift+cmd+[ ? 

### ISSUE THREAD

**Issue by karambaq** [jwilm/alacritty#2313]
MacOS Mojave 10.14.3

Is it possible to bind `:bprevious\n` on `shift+cmd+[`? If yes, how can I do it? 
In iTerm2 I was able to do something like that: 
<img width="544" alt="Снимок экрана 2019-04-14 в 14 12 58" src="https://user-images.githubusercontent.com/14233969/56092021-6f43f580-5ebf-11e9-807c-066f64990547.png">

**Comment by chrisduerr** [comment]
So I never even considered doing something like this since you can actually set keybindings in Vim, which would be the proper way to do this, but it's possible in Alacritty too.

The following should work:
```
key_bindings:
  - { key: T, mods: Control, chars: ":wq\n" }
```

I've got space-h/l mapped to :bp and :bn in vim, for this you'd add something like this to your config:
```
nnoremap <silent> <Leader>l :bn<CR>
nnoremap <silent> <Leader>h :bp<CR>
```

That would probably be the 'proper' way to do this.

**Comment by karambaq** [comment]
This keybind is impossible to set in vim. 
https://stackoverflow.com/questions/38269078/how-to-map-cmd-shift-to-switch-tabs-in-vim
Thanks but I asked about specific keybind `shift+cmd+[`, hope someone will help me.
