### ISSUE TITLE
Render cells with the same foreground & background color differently when selected

### ISSUE THREAD

**Issue by ddevault** [jwilm/alacritty#2315]
Some terminal emulators (e.g. urxvt) do this. This allows you to read the text in the cell by selecting that cell, even if the foreground/background are the same. In practice this is useful for writing spoilers into social chats in terminal-based IRC channels.

**Comment by chrisduerr** [comment]
IIRC Alacritty actually followed URxvt in some combinations while following VTE in other combinations of the hidden flag and I've streamlined it to be identical to VTE's behavior since it seemed most consistent.

However I haven't considered using this as a spoiler tag and I'm not sure how much sense this makes.

In general I'd say that if something is hidden, it's supposed to be hidden and not visible so it should stay hidden and not be visible only when the text is selected. It's also inconsistent and would be a special case.

On the other hand, there's no point in printing invisible text if there's not at least *some* way to use that text and make it visible again.

The implementation itself would be trivial, so this is mostly a question of whether this is desired or not. I wouldn't be opposed to putting this behind a configuration flag either, since it seems like a nifty little feature, but even then the default would have to be considered and I'm not sure if people are interested in changing it once a default has been decided upon (what reason would there be to disable showing hidden text on selection for example?).

I'm curious how other people feel about this, maybe @nixpulvis has an opinion? I think in general I'm inclined more pro than con, since it seems mostly like an advantage without disadvantages (other than potentially surprising the user), but I don't really care either way personally.

**Comment by dnkl** [comment]
> On the other hand, there's no point in printing invisible text if there's not at least some way to use that text and make it visible again.

This alone is enough reason I think. I can't think of a practical use case where it isn't true.

**Comment by chrisduerr** [comment]
I've also talked to a few more people in IRC and I think this would be a good addition. So I think the primary question now would be how to implement it. So which color should be used.

URxvt acts like same color fg and bg is the default text background on default text foreground when inversed. So the foreground is the default bg and the bg is the default foreground.

It would be possible to just reset one of the colors back to the default, however in those cases there would still always be a scenario where the text would be invisible. I think using the default bg as fg and the default fg as bg is the only way to reliably make same-color text and background visible.

URxvt applies this behavior both when selected **and** when the inversion escape is used (so `echo -e "\e[7;31;41mTEST"` will result to be the same as selecting same-color fg and bg). And if this is inverted again using the selection the visible colors are not inverted but it's inverted back to the same bg on same fg colors. So Reverse and Selection do the same thing and are XORed together to check whether they should be applied. I think this makes sense and is what would be expected.

URxvt does not seem to implement the hidden escape sequence (`echo -e "\e[8mHIDDEN"`), so I'm not sure what we should do here. There's two choices, either we act like it's same fg on same bg and make it visible during selection, or we say that when things are hidden they'll stay hidden no matter what. XTerm does not show same bg/fg during selection and Termite (VTE) and Kitty both seem to have fixed selection fg/bg colors without supporting inversion (the reverse escape escape does not have special handling) and Kitty also does not support the hidden escape. According to some helpful people on IRC Konsole does not support inverting during selection either when bg/fg is the same.

So as far as I can tell, we'd be the first to make a decision about this and I'm unsure which decision would be "correct" here. In a way, it might be better to keep text which is intended to be hidden, hidden. So a stray inverting escape sequence can't accidentally expose passwords etc. On the other hand it would probably be more consistent to always show hidden text during selection, no matter what caused that text to be hidden.

Since this issue seems to suggest that same bg/fg is mainly used for spoilers and not the hidden escape sequence, which means I'm not aware of any advantage to show the hidden text, I'd be for keeping hidden text hidden. However I'd be very curious what other people think about it. If the sequence is used to hide passwords, the selection could be used as a "show password text" kinda thing similar to what is sometimes available with password fields in GUIs too.

**Comment by ddevault** [comment]
Hiding passwords with the same fg/bg is a very stupid idea and should not be supported. If you, for example, record your terminal with asciinema under these circumstances, you're going to expose your passwords. Alacritty wouldn't be the first terminal to expose that kind of fuck-up. I don't know of any software that does this rather than disabling echo.

In terms of the specific behavior to use, using the default colors inverted seems like the correct approach to me.

**Comment by nixpulvis** [comment]
Password I put should ideally output the Unicode Character 'BLACK CIRCLE' (U+25CF) IMO.

**Comment by chrisduerr** [comment]
I also do not believe that's a great idea, however I do think that this is (at least part of) the intended purpose of the "hidden" escape sequence. However it is not a `password input` escape sequence, but a `Hidden`/`Conceal`/`Invisible` escape. So text should just not be visible (however it should still be printed and copy/paste-able).

Alacritty can't control how this escape is used, however I wanted to mention that it might be used for passwords since it could be. I'm not aware of any application which makes use of this escape though so it's difficult to tell what people use it for in practice and Wikipedia also lists it as uncommon.

So we still need to make a decision about what colors should be chosen here when hidden text is inversed.

**Comment by nixpulvis** [comment]
Not saying it's worth the complexity in the rendering, but I wanted to propose this anyway since it's somewhat novel. We could style the text somewhat differently.

![](https://imgur.com/a/gqpeVGV)

**Comment by chrisduerr** [comment]
Note that as I've mentioned, the hidden escape sequence is ***not*** a password input escape sequence. It might be used for secrety stuff, but it's a general-purpose escape sequence intended to hide text from plain view.

So the question is *not* how to display passwords, but if the hidden escape sequence should be treated like background color text rendered on top of the background, which would mean inverting it makes the text visible, or if it should always stay invisible only allowing it to be selected and copy-pasted.

These are the only two options available. Everything else doesn't make sense in this context and is not following the purpose of these escape sequences.

**Comment by dnkl** [comment]
I'd like hidden text to be visible when selected. As has already been agreed, it is not for passwords and other security related things. As such, I think it makes sense to treat it as the same-background/foreground case.

That said, I'm not aware of any applications that make use of the hidden attribute, which makes it difficult to make a strong case.

Though I guess this can be said: if support for the hidden escape is unusual (in terminal emulators), and if I as an application developer wanted to use it, I'd use same bg/fg as fallback.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by chrisduerr** [comment]
Since there does not seem to be a clear solution to this problem, I'd like to bring up that currently hidden cells are just not rendered at all. They're replaced as empty cells during rendering (so selection and copying still works), instead of hiding them by using the background color as foreground.

As such,  an implementation completely ignoring the existence of the hidden flag would keep hidden cells hidden, even if same bg/fg are made visible.

Making the hidden cell visible on selection would also not allow to print any text that wouldn't be visible during selection, while both options would exist when the cell stays hidden (one could just use same bg/fg if it's desired). In my opinion this is probably the strongest argument for keeping them hidden.

It's also noteworthy that they are called hidden/invisible/concealed, so their name would suggest to the users their content can never be seen.

Because of these points, I'd propose just ignoring hidden cells for the implementation and keeping them hidden even though the text is revealed when foreground and background is identical. If this should ever turn out to be a mistake, we can still easily adjust in the future.

**Comment by nixpulvis** [comment]
I guess my only remaining question is if we don't display it, should we really copy it?

**Comment by ddevault** [comment]
Try copying things in general first :wink: 

I'd suggest copying same-colored text, but not hidden text.

**Comment by chrisduerr** [comment]
> should we really copy it?

This is an escape sequence aimed at changing the styling of text, so I would still copy it to the clipboard since the text still exists. Otherwise there wouldn't be any reason to use the sequence over just not printing text.

This would also allow us to have all the functionality available in all combinations. So text can be visible on selection (when same bg/fg), it can be invisible on selection but still copy-able (hidden escape) and it can be completely gone (don't print any text).

**Comment by chrisduerr** [comment]
This behavior should be changed in https://github.com/jwilm/alacritty/pull/2349.

I think I've captured all variations to behave consistently.

**Comment by ddevault** [comment]
Thanks!

**Comment by ddevault** [comment]
Thanks!
