### ISSUE TITLE
Allow transparent background colors

### ISSUE THREAD

**Issue by mfrischknecht** [jwilm/alacritty#232]
As far as feature requests go, is only a minor visual nitpick ;-)

I'm currently using [termite](https://github.com/thestinger/termite) as a daily driver, and the only obvious thing I'm missing so far is the option to specify a semi-transparent background. I'm not aware on how easily this is done using OpenGL - there is a [Stackoverflow thread](http://stackoverflow.com/questions/4052940/how-to-make-an-opengl-rendering-context-with-transparent-background/9215724#9215724) with some useful hints, but all answers seem to be platform-dependent.

**Comment by mystal** [comment]
I'm working on this. I got transparency working on OS X and am adding an option to alacritty.yml. Will post a PR soon.

**Comment by Rukenshia** [comment]
any update on this? I'd really appreciate it

**Comment by anxiousmodernman** [comment]
Isn't this closable? Transparency is available via this config option now: https://github.com/jwilm/alacritty/blob/master/src/config.rs#L250

**Comment by jwilm** [comment]
Ah, yes. Thanks @anxiousmodernman!

**Comment by Fandekasp** [comment]
@anxiousmodernman please share commit links rather than pointing to a line on a master head file. The link currently doesn't make sense.

Can someone enlighten me on the config to handle for transparency (also missing the rgba option from termite) ?  Maybe a mention in the README would be great for future adopters :)
