### ISSUE TITLE
Request "Full Disk Access" permission to run Applescript

### ISSUE THREAD

**Issue by zackhsi** [jwilm/alacritty#2337]
OS: MacOS High Sierra.

When running `osascript`, Alacritty does not prompt for the "Full Disk Access" permission and silently fails to detect if applications are running. This can be manually worked around by entering System Preferences.

See: https://gitlab.com/gnachman/iterm2/issues/6977.

**Comment by chrisduerr** [comment]
I'm unsure how exactly iTerm has fixed this since their gitlab/github mixture isn't exactly simple to follow, but I've got a patch for the Info.plist file which might help:

```diff
diff --git a/extra/osx/Alacritty.app/Contents/Info.plist b/extra/osx/Alacritty.app/Contents/Info.plist
index da1aea7..08b7eec 100644
--- a/extra/osx/Alacritty.app/Contents/Info.plist
+++ b/extra/osx/Alacritty.app/Contents/Info.plist
@@ -52,5 +52,7 @@
     <string>An application in Alacritty would like to access your microphone.</string>
     <key>NSRemindersUsageDescription</key>
     <string>An application in Alacritty would like to access your reminders.</string>
+    <key>NSSystemAdministrationUsageDescription</key>
+	<string>The operation being performed by a program in Alacritty requires elevated permission.</string>
 </dict>
 </plist>
```

This seems to be the only Info.plist thing even remotely close to requesting elevated storage access, so hopefully that does it. I believe iTerm originally did this through source code, but they've removed that and go through the Info.plist now.
