### ISSUE TITLE
Installing Alacritty via Git on Windows is missing winpty-agent.exe

### ISSUE THREAD

**Issue by LPGhatguy** [jwilm/alacritty#2352]
Hi! Exciting to see Windows support on Alacritty.

I've installed Alacritty from Git with Cargo:

```sh
cargo install --git https://github.com/jwilm/alacritty.git
```

...but when I run it, it looks like it's looking for `winpty-agent.exe` in my Cargo bin directory and not finding it:

```
panicked at 'called `Result::unwrap()` on an `Err` value:
Err { ptr: winpty_error_s { _unused: [] }, code: 4, message: "agent executable does not
exist: \'C:\\Users\\lucien\\.cargo\\bin\\winpty-agent.exe\'" }', src\libcore\result.rs:997:5
```

```
$ rustc --version
rustc 1.34.0 (91856ed52 2019-04-10)
```

**Comment by chrisduerr** [comment]
Since the `winpty-agent.exe` is a separate distributable, it's not possible for Alacritty to ship it when using `cargo install --git <REPO>`.

You either have to download the agent manually from the releases page, use the installer from the releases or use the ConPTY backend, which does not require the agent.

**Comment by LPGhatguy** [comment]
Can we update documentation to mention this? I followed the [guide to install Alacritty through Cargo](https://github.com/jwilm/alacritty/blob/master/INSTALL.md#cargo) which didn't mention that it would be missing `winpty-agent.exe` if I chose that route.

I can make a PR, I'm just not super sure how to phrase it! 😄
