### ISSUE TITLE
draw_bold_text_with_bright_colors does not seem to cause any effect

### ISSUE THREAD

**Issue by rumpelsepp** [jwilm/alacritty#2381]
Which operating system does the issue occur on?
arch linux; alacritty-git

If on linux, are you using X11 or Wayland?

wayland

The `draw_bold_text_with_bright_colors` setting does not seem to cause any effect with the default alacritty config/theme. Can anybody confirm this? I see the same colors on bold text with either enabled or disabled `draw_bold_text_with_bright_colors`.

**Comment by chrisduerr** [comment]
The default configuration file is definitely using the bright colors to draw bold text on my system. Since you're also using Linux I'd be surprised if that's not the case.

What are you using to draw bold text? The command `echo -e "\e[1;31mTEST"` should do the job.

If that doesn't work for you, I'd be interested in which shell you're using.

**Comment by rumpelsepp** [comment]
I made screenshots and by doing so I noticed, that the difference is so marginal on my screen that I assumed something is broken. In fact it looks almost the same, but there is indeed a difference. Thus the feature seems to work. Sorry.
