### ISSUE TITLE
Windows displays `?[1minfo: ?[0m`

### ISSUE THREAD

**Issue by steveklabnik** [jwilm/alacritty#2382]
At some point, rustup started spewing this:

![image](https://user-images.githubusercontent.com/27786/56907137-8276c980-6a58-11e9-942e-c1c2175c8794.png)

I am setting up a new computer, so it's not like the version of alacritty stayed the same and this changed; I think this is an issue in a newer version, possibly.

As you can see, cmd and powershell both display this properly.

I'm using `alacritty 0.3.2`.

**Comment by chrisduerr** [comment]
I'm pretty sure this is because of WinPTY. I think there is another issue like this which confirmed that the ConPTY backend fixes it. The `use_experimental_conpty_backend` setting in the config should be able to toggle that assuming you've got at least version 1809 of Windows 10.

Related issue:
https://github.com/jwilm/alacritty/issues/2284

Interestingly enough, both this issue and the other one use rustup as the 'faulty' tool, I'm not sure if it might be detecting terminal capabilities incorrectly here. But using ConPTY should definitely resolve this and is recommended at this point when supported.

That being said though, it might make sense to switch to the ConPTY backend by default when available, I'll open another issue about that in a second. In my experience it works a lot better than WinPTY.

As a sidenode, the `alacritty -v` output will show if WinPTY or ConPTY is used.
