### ISSUE TITLE
Reflow on resize duplicates prompt line

### ISSUE THREAD

**Issue by usommerl** [jwilm/alacritty#2408]
Which operating system does the issue occur on? `Linux 5.0.10-arch1-1-ARCH`

If on linux, are you using X11 or Wayland? `X11`

alacritty version: `0.3.2`

![anim](https://user-images.githubusercontent.com/4050763/57158266-4e4a3280-6de3-11e9-8c12-5227e1b8e647.gif)

**Comment by chrisduerr** [comment]
This is done by the shell, since it's redrawing itself and Alacritty keeps pulling from the redrawn content trying to shrink/grow it.

There's nothing Alacritty can do about it and it's just one disadvantage of having reflow in a terminal when it's not completely standardized.

I've tested this with every terminal emulator supporting reflow myself and there is not a single one which was able to solve this problem. So there's nothing we can do.

In general I can just recommend not to resize the terminal smaller than the prompt, but it should never be destructive, it just generates a bit of a mess.

**Comment by usommerl** [comment]
@chrisduerr I wasn't aware that the shell is redrawing itself. Thanks!

I was able to mitigate this issue by changing my shell configuration. I have been using the new configuration for a week now and the problem disappeared almost entirely.

If anyone is interested in what I've changed: I've removed the right prompt and updated a  plugin I'm using. See ([932f6a6](https://github.com/usommerl/configuration-zsh/commit/932f6a660bddf2e10b411120c34d565722d44603) and [5c94412](https://github.com/usommerl/configuration-zsh/commit/5c9441265d953ddf9b7cb883651845a787f91ec9))

![anim](https://user-images.githubusercontent.com/4050763/57570072-6252ed00-73fe-11e9-8089-939fa2b0da8c.gif)
