### ISSUE TITLE
Add Appstream data

### ISSUE THREAD

**Issue by derpmatt** [jwilm/alacritty#2412]
Which operating system does the issue occur on?
Linux

If on linux, are you using X11 or Wayland?
N/A

The addition of this Appstream data will facilitate the generation of the appropriate files for Alacritty to appear in distro "software shops". Attached is a XML file that you could include for the purpose, and I'm happy to submit a PR, but I'm not sure how to properly handle the build process. 

```
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright 2016-2019 Joe Wilm, The Alacritty Project Contributors -->
<component type="desktop-application">
  <id>alacritty.desktop</id>
  <name>Alacritty</name>
  <project_license>APACHE-2.0</project_license>
  <metadata_license>APACHE-3.0</metadata_license>
  <summary>A cross-platform, GPU enhanced terminal emulator</summary>
  <description>
    <p>Alacritty is the fastest terminal emulator in existence. Using the GPU for rendering enables optimizations that simply aren't possible without it.</p>
    <p>Alacritty currently supports macOS, Linux, BSD, and Windows.</p>
  </description>
  <screenshots>
    <screenshot type="default">
      <image>https://cloud.githubusercontent.com/assets/4285147/21585004/2ebd0288-d06c-11e6-95d3-4a2889dbbd6f.png</image>
      <caption>Alacritty is a terminal emulator with a strong focus on simplicity and performance</caption>
    </screenshot>
  </screenshots>
  <keywords>
    <keyword>terminal emulator</keyword>
    <keyword>GPU</keyword>
  </keywords>
  <url type="homepage">https://github.com/jwilm/alacritty</url>
  <url type="bugtracker">https://github.com/jwilm/alacritty/blob/master/CONTRIBUTING.md#bug-reports</url>
  <releases>
    <release version="0.3.2" date="19.04.24" unix_timestamp="1556145865"/>
  </releases>
  <update_contact>https://github.com/jwilm/alacritty/blob/master/CONTRIBUTING.md#contact</update_contact>
  <developer_name>Joe Wilm</developer_name> 
</component>
```

**Comment by chrisduerr** [comment]
> The addition of this Appstream data will facilitate the generation of the appropriate files for Alacritty to appear in distro "software shops".

Which distro shops are you talking about and why should this be maintained in-tree rather than by the maintainers of the "software shop" which requires this information?

**Comment by mmstick** [comment]
@chrisduerr All software centers on Linux (incl. GNOME Software, KDE Discover, & elementary appcenter) require [AppStream metadata](https://www.freedesktop.org/wiki/Distributions/AppStream/), a Freedesktop.org specification and standard, in order to display as installable items. It's up to application authors to provide this metadata with their software if they want it to appear in any software center on Linux.

Software centers do not come with any metadata themselves -- they gather this metadata from available repository sources when they construct their database of available app ids. In the case of a debian platform, they'd pull appstream metadata from the apt repositories, flatpak repositories, and maybe even Canonical's Snap repositories, too. Repositories won't be able to provide that metadata if the metadata is not being distributed with the software.

It is also a requirement for the creation of a [Flatpak](https://flatpak.org) (another Freedesktop.org standard), which is increasingly becoming the preferred format of packaging and distribution by desktop and application authors alike on Linux. Getting your application on a Flatpak repository like [Flathub](https://flathub.org/) ensures that any user, of any Linux distribution, with a software center that supports Flatpak, can install your software without adding any third party repositories, or having that software packaged natively for their platform. They can get releases directly from the applications, which optionally may run in a confined sandbox with varying restrictions (similar to Android's permission system).

Although I have Alacritty packaged in the Pop!_OS repositories, it does not appear in the "Pop! Shop" because it lacks the appstream metadata responsible for providing the metadata that the software center requires.

**Comment by chrisduerr** [comment]
I personally try to stay away from software centers and "universal" package managers, so I'm not really familiar with any of them, but if this is a standardized manifest, it would probably make sense to include it with the rest of our packaging data.

All the information should already be present in the manpage and the other documentation files, so a PR would be welcome if someone is interested in getting this into the Alacritty repository.

**Comment by mmstick** [comment]
@chrisduerr Once this is in the repository, I could submit an Alacritty Flatpak to the Flathub repository, but would need permission to do so, [as per Flathub rules](https://github.com/flathub/flathub/wiki/App-Submission#someone-else-has-put-my-app-on-flathubwhat-do-i-do), since this is usually done by the application authors. This would make Alacritty installable on all Linux distributions, in all software centers.

**Comment by derpmatt** [comment]
@chrisduerr To complete the PR I would like to ask for your preferred RDNN (reverse domain name notation)? A couple of suggestions would be either `org.alacritty.Alacritty` if you plan to have the organization behind Alacritty, or `io.github.jwilm.Alacritty` if you intend to make GitHub the one true origin source.

**Comment by chrisduerr** [comment]
We do own the `alacritty.io` domain, so that would probably be a good choice.

**Comment by chrisduerr** [comment]
@mmstick If you're willing to package Alacritty as a flatpak, I'd be totally fine with that. In general I think that separating developers from packagers is a good thing to strive for anyways, so if the capacity to keep that updated is present, go for it.

However I do want to make it absolutely clear that this shouldn't be promoted as the recommended installation method (I'm not saying that you claimed that), but generally it should be preferred to use the native packages for each distribution when available.

However if the user desires a flatpak/snap/appimage/etc, I don't see much reason why we would stop them. Especially if we can offer these separated from Alacritty's upstream.

Thanks for the willingness to cooperate on this! Always happy to improve the support for Ubuntu/Debian/Fedora, which is currently a bit lacking for a reasonably popular program with an open source.

**Comment by mmstick** [comment]
Most distributions seem to be moving away from native packaging for applications. Fedora Silverblue has done away with native RPM packaging entirely, using a combination of ostree and flatpak instead. It's good to have a Flatpak as an option, even if native packages exist, as it is much more likely to be updated compared to the native package, outside of the usual benefits of application sandboxing (which won't benefit this type of application).

I'll use @derpmatt's appstream metadata for flathub packaging soon. May also create an Alacritty PPA soon, as well.

**Comment by chrisduerr** [comment]
> Most distributions seem to be moving away from native packaging for applications.

Which is extremely unfortunate.

> I'll use @derpmatt's appstream metadata for flathub packaging soon. May also create an Alacritty PPA soon, as well.

That sounds like a good idea. I'll try to check out the PR tomorrow, hopefully we can get this merged relatively quickly.

**Comment by Peque** [comment]
@mmstick Did you finally got to work on this? :innocent:

**Comment by mmstick** [comment]
I have not, though I recently learned how to make a Flatpak, and it should be easy to accomplish. I think only one change would be necessary for the terminal, which would be to spawn the shell with `flatpak-spawn --host $SHELL` so that the shell from the host environment is used.

**Comment by Peque** [comment]
@mmstick Good to know it should be easy. :blush:

I opened https://github.com/jwilm/alacritty/issues/2571 to try to keep track of any advancements in that respect.
