### ISSUE TITLE
"gl function was not loaded" on Windows 10 via Remote Desktop

### ISSUE THREAD

**Issue by AdamVig** [jwilm/alacritty#2428]
Which operating system does the issue occur on?
Windows 10 build 17763

```
panicked at 'gl function was not loaded', C:\Users\travis\build\jwilm\alacritty\target\release\build\alacritty-318c734c9ae4bff8\out/gl_bindings.rs:20624:13
```

Same error as #2276, but I think the situation is different. I'm trying to use Alacritty via Microsoft Remote Desktop on macOS, which apparently doesn't have OpenGL support.

I'm mainly making this issue as a reference for others who run into the same issue, but I do think that the error message could be made friendlier.

**Comment by agocke** [comment]
I looked into this and wanted to add some more information: the problem is likely that you have a graphics card that doesn't support OpenGL hardware acceleration over RDP. I've found that the Nvidia consumer line (GeForce) does not support this, but their professional (Quadro) line does. It also looks like Intel supports it.

Long term, it may be worth supporting Direct X for these platforms. It seems like a lot of work, but RDP support is pretty important for some people.
