### ISSUE TITLE
Certain characters are invisible on Windows with DirectWrite

### ISSUE THREAD

**Issue by tarkah** [jwilm/alacritty#2433]
Which operating system does the issue occur on?

Windows 1809 17763.107

~~If on linux, are you using X11 or Wayland?~~

Overview:
- Built from source from [commit](https://github.com/jwilm/alacritty/commit/7738c52ed4eb177ead9f43d14207ecb129cfe617)
- Same issue exists using either Winpty or Conpty
- Powerline glyphs are invisible and have gaps between each character
- Tmux pane separators and other characters are invisible
- Characters used in GoTop for graphs are invisible
- Using `Noto Mono for Powerline` font

From left to right:
- Latest release without DirectWrite
- Built from HEAD with DirectWrite
- Mintty
![mintty_2019-05-09_17-17-28](https://user-images.githubusercontent.com/10239377/57494513-796ad100-727e-11e9-8d63-c3a50e741a9a.png)

If I highlight where the glyph should be, you can see the color of it. I can copy it out and it'll paste ✘
![alacritty_2019-05-09_17-17-39](https://user-images.githubusercontent.com/10239377/57494512-78d23a80-727e-11e9-9fd1-e8c4f4487c86.png)

Here you can see in tmux and gotop, latest build vs Mintty, the pane separators and characters don't show up 
![mintty_2019-05-09_17-28-40](https://user-images.githubusercontent.com/10239377/57495120-7e7d4f80-7281-11e9-8ad0-143162c310bf.png)

![mintty_2019-05-09_17-30-38](https://user-images.githubusercontent.com/10239377/57494863-37db2580-7280-11e9-96f2-c0a1ef4a4cee.png)

**Comment by chrisduerr** [comment]
I'm unsure about the exact issue here. Clearly the character is rendered, otherwise you wouldn't get the `>` you have but just a straight line or a missing glyph.

The issue just seems to be that the glyph dimensions don't match up. This is simply an issue with your font and one of the reasons why powerline is so incredibly unreliable. The powerline font where the glyphs are pulled from, just don't match up with the rest of your font, there's nothing Alacritty can do about that.
