### ISSUE TITLE
[v0.3.2] Doesn't render italic font for any font on Ubuntu 19 

### ISSUE THREAD

**Issue by kraythen** [jwilm/alacritty#2436]
I have tried over a dozen fonts and italics wont render. I have been testing with this string. 

echo -e "\e[3m is this italics? \e[23m"

Which operating system does the issue occur on?
Ubuntu 19+

If on linux, are you using X11 or Wayland?
X11

**Comment by kchibisov** [comment]
What's your `TERM` variable and also could you share your font configuration in `alacritty`?

**Comment by chrisduerr** [comment]
Alacritty will look for the italic version of the font you've specified (unless a separate italic font is set). If the closest match to an italic version for your font is the normal version of your font, then it will not show any italics.

**Comment by rsimmonsjr** [comment]
I have tried several fonts and none of them work in alacrity. I've tried using italic in font name and that didnt work wither.

**Comment by kchibisov** [comment]
@rsimmonsjr What's your `$TERM` variable and whats output from `infocmp`?

**Comment by kraythen** [comment]
19:51:20 ➜  ~ ➜  echo $TERM
xterm-256color
19:51:24 ➜  ~ ➜ infocmp > infocmp.txt
SEE ATTACHED
[infocmp.txt](https://github.com/jwilm/alacritty/files/3180337/infocmp.txt)

**Comment by kchibisov** [comment]
Your `infocmp` looks fine. Could you share one of your fonts?

**Comment by rsimmonsjr** [comment]
I have tried Deja vu sans mono, Inconsolata, Fira Code (my preferred font) and they all fail. I have tried specifying the italic face in config, i.e. Fira Code Italic, as well as leaving the italic in a style element and just using Fira Code for family. None of these work. The fonts do render italic in gnome terminal and tilix.

**Comment by kchibisov** [comment]
I've just tried `DejaVu Sans Mono` and it's working fine for me ( look at comments in my vim ). Maybe these screenshots can help you.
![Screenshot-Wed_15_May_2019_30](https://user-images.githubusercontent.com/27620401/57785328-373c0680-773a-11e9-81dd-9be850bb6ce8.png)
![Screenshot-Wed_15_May_2019_33](https://user-images.githubusercontent.com/27620401/57785332-3905ca00-773a-11e9-990f-fea9a0dcbfdf.png)

**Comment by kraythen** [comment]
As you can see in the screenshots below Tilix renders the italics but Alacritty does not. Shame because I like alacritty better. Again its on a Razer Advanced RTX-1080 running in a VMWare virtual machine and the latest Ubuntu 19.x. 

![alacritty-italics](https://user-images.githubusercontent.com/7327836/57792328-b9153b00-770c-11e9-94f1-e9022ae9f64f.png)
![tilix-italix](https://user-images.githubusercontent.com/7327836/57792329-b9153b00-770c-11e9-803a-68e6aba89795.png)

**Comment by chrisduerr** [comment]
Alacritty will make use of fontconfig system preferences, so please make sure you have not setup anything in fontconfig that would make Alacritty choose a different font when you pick `DejaVu Sans Mono Oblique`.

I have tested the same font and was able to successfully get Alacritty to render italic fonts without any issues. Would you mind sharing which WM/Compositor you are using?

Also please try reproducing this issue with the following minimal Alacritty config:
```yml
font:
  italic:
    family: DejaVu Sans Mono
    style: Oblique
```

You can save that to any file and then run Alacritty using `alacritty --config-file <PATH/TO/THAT/FILE>`.

Please also make sure you've tested the `alacritty` terminfo, since Alacritty is not 100% compatible with `xterm-256color` and it is not officially supported. If you could let me know which shell you're using that might also help.

**Comment by rsimmonsjr** [comment]
I tried it with that config. A contributor above verified my terminfo was correct. the font config is already there. Please read previous messages.

**Comment by chrisduerr** [comment]
xterm-256color is not an officially supported terminfo, no matter what another contributor might say.

It also makes a big difference if you're using a minimal config or one with additional keys, since this makes absolutely sure that it's not an error with your configuration file or the location its getting loaded from.

Alacritty will absolutely load the italic font if it is properly specified and fontconfig is configured properly. So if it does not do that, chances are your fontconfig might be altered.

This is also why I recommended changing the italic font to a completely different font, to check if the issue is with the escape sequence or the font loading.

**Comment by rsimmonsjr** [comment]
Look at the above discussion. All of this is answered along with the attached terminfo. Additionally all of these configurations have been tried. It works in other terminals, not in Alacritty. And if Alacritty doesnt support the single most common TERM environment var on purpose then it has a LONG LONG way to go. I am of the belief that this is something else. I am not going to go over AGAIN with you the exact same things I went over before. Your comments seem to indicate you haven't looked at the screen shots or any of the other information posted.

**Comment by chrisduerr** [comment]
This is a configuration issue on your end and I would have been happy to help and troubleshoot it. But I guess this works too.
