### ISSUE TITLE
No instructions for adding Alacritty to the dock in OS X

### ISSUE THREAD

**Issue by spease** [jwilm/alacritty#2462]
Not sure where to put this.

I installed Alacritty with nix using

`nix env -i alacritty`

This worked, but if I try to pin the icon to the dock via the right-click menu, the resulting link just looks like a white empty file icon, and it launches the regular terminal. I searched some for the 'expected' way to add Alacritty to the dock, but couldn't find it. Thanks.

**Comment by chrisduerr** [comment]
The recommended installation methods for macOS are either the prebuilt package or installing through brew. I'm not familiar with how nix works on macOS myself so I can't really say anything about how it performs on macOS and what additional steps are required.

However there are some issues with Alacritty on macOS since it spawns separate windows instead of launching everything through one application, more regarding that can be found here:
https://github.com/jwilm/alacritty/issues/607
