### ISSUE TITLE
Alacritty doesn't perform color correction.

### ISSUE THREAD

**Issue by xfbs** [jwilm/alacritty#2468]
Which operating system does the issue occur on?

* macOS 10.14

When using a colorscheme, it looks different in Terminal.app compared to Alacritty, despite both of them being set to exactly the same colors. See [srcery-vim #12](https://github.com/srcery-colors/srcery-terminal/issues/12). 

Terminal.app interprets the colors as sRGB, performing color correction and using the color-corrected values. Alacritty uses the RGBs directly. 

Terminal.app:
<img width="682" alt="terminal" src="https://user-images.githubusercontent.com/786420/58109577-2eda4480-7bee-11e9-8788-1f82d73bd709.png">

Alacritty:
<img width="682" alt="alacritty" src="https://user-images.githubusercontent.com/786420/58109572-2c77ea80-7bee-11e9-8f5a-5551839fa4b0.png">

For the red color, Terminal.app is set to `#EF2F27`, and Alacritty is set to `0xEF2F27`. So that should be identical. But it's not. 

Terminal.app renders Generic RGB 239, 47, 39.
<img width="486" alt="alacritty_color" src="https://user-images.githubusercontent.com/786420/58109735-719c1c80-7bee-11e9-9342-4c88bbc3a2c2.png">

Alacritty renders Display Native Value 239, 47, 39.
<img width="486" alt="terminal_color" src="https://user-images.githubusercontent.com/786420/58109725-6e089580-7bee-11e9-9a24-c6bfbe52672d.png">

I'm guessing that Alacritty doesn't perform color correction. Is this something that should be looked into? Or is this a bug in Terminal.app?

**Comment by chrisduerr** [comment]
> I'm guessing that Alacritty doesn't perform color correction. Is this something that should be looked into?

That is correct and Alacritty will not change this behavior. In fact the first time I've seen this in the macOS terminal I was convinced this was a bug, because it seems so crazy to me that an application would just override the user's colors like that.

I also do not think there's any value in adding this behind a configuration option. If you want a color to be different than what it is, you should change the color, instead of hoping that Alacritty will guess which color you might want.

**Comment by smcallis** [comment]
I don't think this is the correct behavior.  You need to gamma correct the colors before displaying so that when the OS/gpu re-applies gamma you end up with an accurate color.   If you don't do that, the displayed colors will never match what users's get out of a color picker.  

If you look at the attached file you'll see the Polar Night 0 from the Nord color scheme on the right, and the color that Alacritty displays on the left.  Very different. 
![example](https://user-images.githubusercontent.com/804394/106045920-d46dd880-609e-11eb-95c0-46e5ac078170.png)
