### ISSUE TITLE
All 3 icons are broken

### ISSUE THREAD

**Issue by prk3** [jwilm/alacritty#2469]
Which operating system does the issue occur on?
Fedora 30, KDE
If on linux, are you using X11 or Wayland?
X11

Icons from /extra/logo have a white triangle on top of "A". It looks like the light effect, which should be applied on the blue part of the icon, has no alpha layer. The icons look right when I open them in Inskscape. Maybe they are saved in some weird svg dialect?

![image](https://user-images.githubusercontent.com/16927151/58203944-899d9a00-7cdb-11e9-8e24-b292024faa5f.png)
![image](https://user-images.githubusercontent.com/16927151/58203960-95895c00-7cdb-11e9-9a52-1b7c8f67fbdd.png)
![image](https://user-images.githubusercontent.com/16927151/58203992-a20db480-7cdb-11e9-8c3b-7daee7029b5b.png)

**Comment by chrisduerr** [comment]
This is actually a bug in KDE. I'm not sure if there has been an issue of this before or if this has been discussed on IRC only, but the KDE SVG renderer does not properly support clipping paths.

You can probably fix this by converting these logos to PNGs with imagemagick though, since that does properly support SVGs.

**Comment by prk3** [comment]
Thanks for the info. Here are links to QT issues related to this problem, for anyone interested.
https://bugreports.qt.io/browse/QTBUG-28636
https://bugreports.qt.io/browse/QTBUG-23200
I'm closing this issue, there is nothing wrong with svgs.
