### ISSUE TITLE
Sponsorship

### ISSUE THREAD

**Issue by ChadTaljaardt** [jwilm/alacritty#2494]
Hello, 

I use Alacritty as my daily terminal and would like to give back!

Are you able to create a GitHub sponsorship so myself and other can donate?

Thanks for creating Alacritty!

**Comment by chrisduerr** [comment]
First of all, thanks a lot for the positive feedback and the proposal to make it possible to donate to the Alacritty project.

Regarding the direct GitHub sponsorship that people need to apply for, I personally think that it poses a lot of dangers for platform lock-in so I think it wouldn't be the best solution for financial support. However since GitHub allows adding external links that should not be an issue.

This leaves setting up an external service like patreon and linking to it in the GitHub repository. While I think in general this approach is a good idea, this would require some work to setup. Alacritty itself also doesn't have any direct expenses at this point, so the only thing that would need coverage is the free time contributors put into it and distributing fairly to all contributors is tough.

Because of these reasons, I think it makes sense to skip donations/sponsorships for now. However I'll keep the interest in mind so maybe this will change in the future.

**Comment by nixpulvis** [comment]
I think we'd be pretty open to facilitating bug/feature bounties for big issues or new features.

**Comment by jonhoo** [comment]
Just a gentle bump to keep this idea alive. I think there are many of us out there who would like to support those who work on alacritty if it were possible :)

**Comment by chrisduerr** [comment]
I really appreciate the support, though I personally do not see a way to accept financial contributions at the moment that would not negatively impact Alacritty's development. Especially where I'm from the maintenance overhead and cost associated with setting it up would just exceed the money people would contribute.
