### ISSUE TITLE
Implement multiple dynamic color code escape sequences

### ISSUE THREAD

**Issue by rbong** [jwilm/alacritty#2497]
Xterm escape codes allow setting/requesting both the foreground and background color at once:

>Because more than one pair of color number and specification can be given in one control sequence, xterm can make more than one reply.

Related to #2495

**Comment by chrisduerr** [comment]
Based on my quick first look, this should actually be fairly easy to implement and would make a great first issue because of that.

If anyone is interested in working on this, but needs some help, please let me know.

The relevant code can be found here:
https://github.com/jwilm/alacritty/blob/dbd8538762ef8968a493e1bf996e8693479ca783/alacritty_terminal/src/ansi.rs#L791-L811

**Comment by Coder-256** [comment]
This is fixed.

**Comment by rbong** [comment]
The fix changes the RGB response to `rgb:xxxx/xxxx/xxxx` instead of `rgb:xx/xx/xx`. The rgb response should be in the same format as setting colors according to the xterm docs, and this format is not currently supported. This will be fixed in #2504
