### ISSUE TITLE
hieroglyphics and other non-ascii chars are very small

### ISSUE THREAD

**Issue by ngortheone** [jwilm/alacritty#2508]
I am on Archlinux, X11

Non-ascii chars look very small, and I am not sure where to dig.

cat file in alacritty:
![Lowe-Leopard](https://user-images.githubusercontent.com/18271144/58925338-210bdf80-8715-11e9-89b5-35b1e8d8f6aa.png)

same file in Emacs/Idea/Any other non-terminal app:
![Lowe-Leopard-normal](https://user-images.githubusercontent.com/18271144/58925339-210bdf80-8715-11e9-8fbf-05774f74fa2a.png)

Same with emacs minor mode icons. `emacs -nw`:
![emacs-nw](https://user-images.githubusercontent.com/18271144/58925337-210bdf80-8715-11e9-92dc-5c87d0a6e2fb.png)

vs GUI Emacs
![emacs-normal](https://user-images.githubusercontent.com/18271144/58925336-20734900-8715-11e9-8195-460f275e18d4.png)

**Comment by kchibisov** [comment]
It seems like problem in your `fontconfig` configuration. For me everything works fine ( I'm on Linux with X11).
![Screenshot-Wed_05_Jun_2019_58](https://user-images.githubusercontent.com/27620401/58925881-d2c90180-8751-11e9-9b76-9c39b16e4899.png)

**Comment by ngortheone** [comment]
@kchibisov 
`gnome-terminal` shows everything correctly.

![Screenshot from 2019-06-04 23-23-08](https://user-images.githubusercontent.com/18271144/58928297-e8bdce80-871f-11e9-985d-9e6abafe7816.png)

sorry for poor screenshot..
gnome-terminal on the left (white background)
alacritty on the right

**Comment by ngortheone** [comment]
It seems that gnome is doing some magic. I tried other terminal emulators and got same problem as alacritty.

**Comment by ngortheone** [comment]
Also happens in `kitty` which is also GPU-accelerated, but not in `terminator`

**Comment by ngortheone** [comment]
also opened https://gitlab.freedesktop.org/fontconfig/fontconfig/issues/157

**Comment by ngortheone** [comment]
also opened https://gitlab.freedesktop.org/fontconfig/fontconfig/issues/157

**Comment by kchibisov** [comment]
@ngortheone `Alacritty` uses `fontconfig` for it's fonts on Linux ( I'm not aware of `kitty`). I think it's problem of your configuration/font, rather then `fontconfigs` fault, since you are probably dealing with font fallback and some metrics may go wrong. `gnome-terminal`, also uses `fontconfig`, but they are probably doing something with it. You can check your global fontconfig configuration in `/etc/fonts/` and local in `~/.config/fontconfig` (FYI).

 P.S. your string look fine on my system.
![Screenshot-Wed_05_Jun_2019_19](https://user-images.githubusercontent.com/27620401/58929841-98fff700-8761-11e9-916f-61ceecfe426d.png)

**Comment by ngortheone** [comment]
@kchibisov thanks, I will take a look at my fontconfig.

Another interesting observation is that 老虎 symbols always stay of the same size, no matter how big the font is..

**Comment by ngortheone** [comment]
I tried removing all system-wide and local fontconfig files, but the issue remains.

Guys from fontconfig say that this might be a problem in a "rendering library" since some apps do display correctly - this is not a fontconfig issue
https://gitlab.freedesktop.org/fontconfig/fontconfig/issues/157 f

**Comment by ngortheone** [comment]
After I grabbed /etc/fonts folder from ubuntu machine and replaced mine with it I got it fixed. It was `fontconfig` configuration after all...

**Comment by nixpulvis** [comment]
Glad your issue was resolved :D

**Comment by chrisduerr** [comment]
I'd just like to point out that the fallback in Alacritty which was broken was a bitmap font, which is often handled a bit differently and likely the reason why it was so small since it scales differently.

You can see in the "Emacs/Idea/Any other non-terminal app" screenshot that it doesn't use a bitmap font, but the vector font instead. I'd assume that the fixed version of Alacritty now likely uses a vector font too.
