### ISSUE TITLE
Support primary selection clipboard on Wayland

### ISSUE THREAD

**Issue by chrisduerr** [jwilm/alacritty#2510]
Currently the native Wayland clipboard only supports the 'normal' clipboard, however it does not support the very commonly used primary selection clipboard, which stores the last selection made.

This requires making some changes to the smithay-clipboard crate first. @trimental do you know how much work this would be approximately? I'm not sure what exactly needs to be done to extend the existing code to also support this.

**Comment by trimental** [comment]
Technically I’ve already implemented primary selection in the https://github.com/Smithay/smithay-clipboard/commits/primary branch.

I just need to do a bit more testing and api review and then hopefully that will make its way to a new release. Since you’re using the api in your rust-clipboard fork I’d happily take on board any suggestions on how the primary and secondary selection api should look. Hopefully I can do this in the next few days :)
