### ISSUE TITLE
feature request: Power Mode

### ISSUE THREAD

**Issue by kvark** [jwilm/alacritty#2526]
I wish we could do something like [textreme](https://le-von.itch.io/textreme) within Alacritty, given that GPU is already utilized. We have a potential for a much lighter and robust app, comparing to Textreme that is based on Godot.

**Comment by chrisduerr** [comment]
Which part exactly are you looking for? There are various text editors for terminals out there already, what exactly is missing from them that textreme has?

If this is only about fancy visual effects while editing, I don't think there's much Alacritty does that would help there. It explicitly sticks to a much simpler layout and grid to improve performance whenever possible. Being flashy is going into a bit of a different direction than that.

**Comment by kvark** [comment]
Yeah, this is about visual effects, nothing more. It would be good if Alacritty had at least a way to write this logic in a plugin.
This is just a wish, feel free to close if there is no interest.

**Comment by chrisduerr** [comment]
> It would be good if Alacritty had at least a way to write this logic in a plugin.

I've addressed this in a few different issues before, but plugin systems are kinda problematic for performance. If we expect them to respond synchronously, they'll likely tank Alacritty's performance. If they're handled completely asynchronously, they'll likely operate at a lower framerate than Alacritty.

Fundamentally, whenever a plugin lives up to the performance constraints of Alacritty and is popular enough to be desired as a public plugin, it's probably something that could be included into Alacritty directly, where Alacritty has direct control over its performance and interactions with other components and updates.

> Yeah, this is about visual effects, nothing more.

While this would likely be some fun for a few minutes to play around with it, I think it pretty clearly falls into the realm of feature creep/bloat. Based on the screenshots I've seen looking at textreme, I don't think anyone would run that as their daily text editor, since it's just a touch too much. Terminal emulators also aren't just text editors, so this would probably run into some limitations.
