### ISSUE TITLE
Windows - multiline rendering

### ISSUE THREAD

**Issue by ark0f** [jwilm/alacritty#2592]
Which operating system does the issue occur on?
Windows 10 64bit version 1903

If on linux, are you using X11 or Wayland?

Alacritty version: 0.3.3
[alacritty.yml](https://gist.github.com/ark0f/4ac606c003109565c14de5400277bf3e)

![Demo](https://i.imgur.com/v8XxDPj.gif)

Also I tried in PowerShell. Result is the same

**Comment by chrisduerr** [comment]
Is this on WinPTY or ConPTY?

**Comment by ark0f** [comment]
ConPTY on video. I checked WinPTY and got the same result, too.

**Comment by chrisduerr** [comment]
Can you reproduce this with an empty Alacritty config? It looks like you've got some MingW setup going, is there a chance that's messing with things?

I'd be curious if this works correctly with default config, if other programs like `vim` produce the same issue and if WSL works properly instead of MingW.

**Comment by ark0f** [comment]
I can reproduce this with empty config. I don't think it's MinGW's problem, because I can't reproduce bug in Windows Terminal and ConEmu.

I found that Windows Terminal sets `TERM` environment variable to `cygwin`, when Alacritty and ConEmu set it to `xterm-256color`.

Here is table with different cases:

|     | Windows Terminal | ConEmu | Alacritty | Alacritty | Alacritty WSL | Note |
| --- | -------------------- | --------- | --------- | --------- | ------------- | ---- |
| `TERM` | `cygwin` | `xterm-256color` | `cygwin` (set manually) | `xterm-256color` | `xterm-256color` |
| `nano` | ✔ | ✔ | ✔ | ❌ | ✔ |
| `winpty nano` | 🟨 | ✔ | ✔ | ✔ | - | Some cursor artifacts in Windows Terminal |
| `vim` | ✔ | ✔ | ✔ | ✔ | ✔ |
| `micro` | ✔ | 🟨 | ✔ | 🟨 | ✔ | Editor works with `TERM=""` or `TERM=cygwin` </br> No view in ConEmu  |
| `winpty micro` | ✔ | ✔ | ✔ | ✔ | - |

As I understand, It actually isn't Alacritty's problem, it's problem of `terminfo` crate.

**Comment by chrisduerr** [comment]
The `cygwin` terminfo is not accurate for Alacritty, so in general `alacritty` should be used. I've never tried using nano with Alacritty (neither on Linux or Windows), but it seems like it might be a problem of `nano` when vim seems to work perfectly fine?

Seems like nano's just having a few problems with Windows WinPTY/ConPTY. I'm not aware of what `micro` is.

**Comment by ark0f** [comment]
I found that `clear` doesn't clear terminal, but return carriage with WinPTY:
![](https://i.imgur.com/yMoqt9N.gif)
Also I tested other programs (see below). Because of this I don't think it's problem of `nano`.

WinPTY:

| `TERM` | `alacritty` | `cygwin` | `xterm-256color` |
| --- | --- | --- | --- |
| `nano` | ❌ | ✔ | ❌ |
| `clear` | ❌ | ✔ | ❌ | 
| `emacs` | ❌ | ✔ | ❌ |
| `hexcurse` | ❌ | ✔ | ❌ |

ConPTY:

| `TERM` | `alacritty` | `cygwin` | `xterm-256color` |
| --- | --- | --- | --- |
| `nano` | ❌ | ✔ | ❌ |
| `clear` | ✔ | ✔ | ✔ | 
| `emacs` | ❌ | ✔ | ❌ |
| `hexcurse` | ❌ | ✔ | ❌ | 

It's look like programs using `ncurses` would be work incorrectly without `TERM=cygwin`. Also I get same results in Windows Terminal, but not in ConEmu (because of MSYS2 connector probably).

[What micro is](https://github.com/zyedidia/micro).

**Comment by chrisduerr** [comment]
Are you on the latest Windows 10 version and does `alacritty -v` actually output that you're running ConPTY?

I don't think I've encountered issues with `clear` before, though I currently don't have any Windows system handy for testing.

**Comment by ark0f** [comment]
`alacritty -v`:
<details>

    Created log file at "C:\\Users\\ark0f\\AppData\\Local\\Temp\\Alacritty-7104.log"
    [2019-06-26 23:24] [INFO] Welcome to Alacritty
    [2019-06-26 23:24] [INFO] Configuration loaded from "C:\\Users\\ark0f\\AppData\\Roaming\\alacritty\\alacritty.yml"
    [2019-06-26 23:24] [INFO] Device pixel ratio: 1
    [2019-06-26 23:24] [INFO] Initializing glyph cache...
    [2019-06-26 23:24] [INFO] ... finished initializing glyph cache in 0.0060771s
    [2019-06-26 23:24] [INFO] Width: 1024, Height: 768
    [2019-06-26 23:24] [INFO] Cell Size: 8 x 21
    [2019-06-26 23:24] [INFO] Padding: 2 x 2
    [2019-06-26 23:24] [INFO] PTY Dimensions: Line(36) x Column(127)
    [2019-06-26 23:24] [INFO] Using Conpty agent
    [2019-06-26 23:24] [INFO] Initialisation complete
</details>
Yes, it does.

**Comment by chrisduerr** [comment]
I don't think I'll get around to testing on a Windows machine until this weekend. If anyone else can confirm these issues, it would be much appreciated. Otherwise I'll try to look into this myself when I've got some time to setup Windows 10 things again.

**Comment by ark0f** [comment]
I see that developers and users of other terminal emulators encountered with similar problems.

ConEmu:
* Maximus5/ConEmu#382
* [Cygwin Connector](https://conemu.github.io/en/CygwinMsys.html#cygwin-connector)

Windows Terminal:
* https://github.com/microsoft/terminal/issues/57#issuecomment-371462051

Hyper:
* zeit/hyper#1559
* https://github.com/zeit/hyper/issues/2316#issuecomment-341871609
* zeit/hyper#3142
* zeit/hyper#3391

**Comment by JDTX** [comment]
I cannot replicate this whatsoever. I'm using an identical version of Windows (1903) with Alacritty 0.3.3 and ConPTY

Steps I've tried:
1) Installed MSYS2 from here: https://www.msys2.org/
2) Imported your alacitty.yml config, exact one.
3) Launched alacritty, installed nano using pacman
4) nano works as expected, clear works as expected.

Here's what mine looked like:
![cnr](https://user-images.githubusercontent.com/24833917/60380363-1ee22b80-9a0a-11e9-81ac-74a4940ee22c.gif)

Furthermore, I was not able to replicate this in Cygwin, or MINGW w/ MSYS.

I'm not sure what could contribute to your issues, but maybe some package is interfering, or you've made some customizations to bashrc?  I'd recommend installing MSYS fresh to another location, and setting your shell to spawn there. See if it still happens then.

**Comment by ark0f** [comment]
I can scroll without any bugs too, but it's not about new lines and <kbd>Page Up</kbd>, <kbd>Page Down</kbd>.

I made new installation of MSYS2, also tested on another computer with `Windows 10 64bit version 1803` and I still get same results.

**Comment by chrisduerr** [comment]
@JDTX / @ark0f which shells are you running? Maybe that's where the difference is?

Also if loads of stuff is breaking when using the `alacritty` terminfo, I'd assume that might be because the terminfo hasn't been installed properly? Confirming that it's in the correct  location might be worth it.

Additionally it might be worth testing if the `cygwin` terminfo *name*, or the terminfo file itself fix these issues. So renaming the `cygwin` terminfo to something else or Alacritty's to `cygwin` might give some additional insights. If it turs out it's about the actual terminfo definition, comparing the properties might give a hint for a potential solution.

**Comment by ark0f** [comment]
I'm running the latest version of MSYS2 bash `4.4.23(1)-release (x86_64-pc-msys)`.

I noticed that `TERM` is set to `cygwin` if run bash in Windows Terminal, PowerShell and Command Prompt (but not in ConEmu, because it uses its own connector). If set `TERM` to `xterm-256color` I get even worse results in PowerShell and Command Prompt (but not in Windows Terminal, it uses some kind of connector probably, too).

It seems to me that it can be problem of Cygwin and Alacritty has nothing to do with that.

**Comment by chrisduerr** [comment]
@ark0f Since I don't really use Windows, it's hard for me to grasp the complete situation, but do you think there's anything specific Alacritty should do to fix this issue?

Should we set `cygwin` by default on all instances when running on Windows? Or does it only really help with mysys, if so, is there a way to detect it?

Also are you familiar with the behavior of any other terminal emulators? Maybe we can take a page of their book.

In general, I think it makes some sense to tweak terminfo on Windows, since the database files aren't going to be present. But I'm not entirely confident what the best solution is either without playing around with things a little bit.

**Comment by ark0f** [comment]
`cygwin` should be set only on Cygwin-like shells, because this environment variable can be invalid for another shells.

Windows doesn't have native terminfo support, we can introduce `TERMINFO` environment variable to tweak it as possibly solution.

I try to search solution for detection or even fixing behavior of Cygwin-like shells. There are possibly solutions:
* [Windows Terminal](https://github.com/microsoft/terminal/blob/9b92986b49bed8cc41fde4d6ef080921c41e6d9e/src/interactivity/base/InteractivityFactory.cpp#L337) - create pseudo window, but where it use? Is this reason why `TERM=cygwin` is in bash in PowerShell, Command Prompt and Windows Terminal?
* Check pipe name of bash. When bash is running you can see name like `msys-XXXXXXXXXXXXXXX-PROCESS_ID-sigwait`, but I still search needed place in Alacritty code.
We can also list files in `\\.\pipe\` and search it by process ID.

**Comment by chrisduerr** [comment]
I don't think checking for the shell is ever a good idea. If a shell requires special handling, that should be done in the shell.

That's why I was curious about other terminal emulators. If they just always set the `TERM` to something specific like `cygwin`, that might be a possible solution. Otherwise we'd just leave this up to user config.

**Comment by ark0f** [comment]
I failed to find more solutions and explore Windows Terminal source code (it's too sophisticated for me). As I can understand, issue can be closed.
