### ISSUE TITLE
Window separators (line chars) printed as "x" and "q" in tmux

### ISSUE THREAD

**Issue by davesque** [jwilm/alacritty#263]
![screen shot 2017-01-09 at 11 51 25 am](https://cloud.githubusercontent.com/assets/791437/21779080/421897d2-d663-11e6-803c-ed29fb0aa140.png)

Launching tmux with `tmux -u` seems to fix the problem but suggests that alacritty maybe isn't reporting its features correctly to tmux?  Don't really know enough about the nuts and bolts of terminal emulation to tell if it's a problem with alacritty or tmux.

**Comment by d3rrial** [comment]
What font do you use? What operating system?

Tmux draws separators properly for me on Arch with Ubuntu Mono font

**Comment by mbrumlow** [comment]
@davesque what do you have your TERM set to inside and outside of tmux?

**Comment by davesque** [comment]
@mbrumlow I set the `TERM` environment variable as follows in `~/.bash_profile`:

```bash
export TERM="xterm-256color"
test -n "$TMUX" && export TERM="screen-256color"
```

Is this proper?

**Comment by davesque** [comment]
@d3rrial I use OS X 10.11 with the Menlo font.  However, I don't think it's an issue with the font.  I get the same problem with the Monaco font as well.  Curiously, I wasn't having this problem yesterday with either font.  Maybe a patch was introduced that led to the problem?

**Comment by okuuva** [comment]
This seems to be somewhat related to the font in use, I get boxes when I use Inconsolata, FiraCode works just fine.

**Comment by davesque** [comment]
@okuuva I'm not sure though.  For one, the issue can be worked around by launching with forced UTF-8: `tmux -u`.  So the font definitely has the line-separators.  I've also never had this problem with iTerm using the same fonts.  Furthermore, the same issue appears to pop up in other contexts where the font doesn't seem relevant: http://stackoverflow.com/questions/8483798/tmux-borders-displayed-as-x-q-instead-of-lines

**Comment by wmiller848** [comment]
I'm not sure what triggered it but something has started making my tmux now do the same thing. Using Menlo font.

MacOS Sierra 10.12.1

**Comment by jwilm** [comment]
This bug is due to Alacritty's lack of support for changing character sets. In other terminals, a lookup table is used when in graphics mode. The character `x` and `q` map to horizontal and vertical bars in that table.

**Comment by mosconv** [comment]
> What font do you use? What operating system?
> 
> Tmux draws separators properly for me on Arch with Ubuntu Mono font
> 
> ![seps](https://cloud.githubusercontent.com/assets/3718129/21780258/2f2ff780-d6ab-11e6-9e7a-6fe0af83a24f.png)

How you did that?

**Comment by diedummydie** [comment]
I was experiencing this problem (borders drawn with `x`, and `q`, plus `j`, `k`, and `l` for some parts) using [npyscreen](https://npyscreen.readthedocs.io) to make some terminal gui forms in python.  

**It worked with no issues in Alacritty.**  

Terminal.app was fine too. iTerm2 had the problem. I don't mean to clutter your issues with unrelated software, but this was a top search result. No result anywhere else had exactly the situation and answer I needed, but what you (@jwilm) said here finally helped:  

> In other terminals, a lookup table is used when in graphics mode.  

iTerm2 started drawing tui borders correctly when I enabled Preferences > Adanced > Experimental Features > Detect base unicode characters with lookup table.  

Alacritty is the fastest, most cpu efficient, and lowest latency terminal emulator on every platform. Thank you for creating and sharing it.

**Comment by jaclu** [comment]
It is not font-related at all, since | and - are in virtually any font. The problem is related to UTF-8, the simplest solution is to set a UTF-8 LANG, this will also help in other cases to make sure your terminal uses UTF-8
here is something I keep in my .tmux.conf as a reminder:

#
# If you get pane borders drawn as x and q, you need to set a UTF-8 LANG
# sample: export LANG=en_US.UTF-8
# You should also be able to solve it by starting tmux with param -u
# Finally here is an in tmux hack to solve the pane border issue
# set-option -ga terminal-overrides ',*:enacs@:smacs@:rmacs@:acsc@'
#

**Comment by jaclu** [comment]
Another thing to remember is that your env might differ if you ssh in and then run tmux, vs connecting via mosh for example.
In the mosh scenario at first an ssh connection is done, seen as an interactive login, so the normally expected shell init scripts are run before starting mosh. However once mosh is started in server mode on the remote end, and mosh client on client-side connects directly to the mosh server running tmux from the mosh-server, this connection is not an interactive shell, thus not running the "normal interactive" shell init scripts. It varies per shell, and there are more than one way to set up shell init, so let's just say it is complicated :)  In the case of zsh, the simplest case is that an interactive shell uses .zshrc and a non-interactive uses .zshenv

This means that in the typical case  you need to assure that the env variables that should be present when tmux is started, needs to be set also to non-interactive shells
This would include
EDITOR - otherwise tmux will always use vi since it is the default, if that's ok for you then this one is not needed.
LANG et al
and if during tmux init you need something not in the basic path for example you would also need to modify the PATH variable.

It can be quite a pain to find a good overview when it comes to what init scripts are run and in what order, I found this summary to be quite helpful.
https://blog.flowblok.id.au/2013-02/shell-startup-scripts.html

**Comment by jaclu** [comment]
> export LANG=en_US.UTF-8; export TERM=ansi

There are of course exceptions, but in general, TERM should never ever be set in an init script. It is much better to let the terminal define how it can communicate, otherwise sooner or later you might connect with a different terminal app and get all kinds of screen glitches.

So should normally be hardcoded into your physical terminal (ok joking)
Or set in your terminal app, most terminals give you a list of options they can emulate. Your initial shell and any hops getting you to where you intend to use terminal features can be assumed to keep track of TERM, so in the vast majority of cases where something goes wrong, it is somewhere in the connection path from your term app to your furtherest session some script hardcoded a TERM setting.

Of course, sometimes it takes too long to figure it out and then a quick solution is to set TERM, but doing that in an init script is actually worsening the problem instead of fixing it, since now its permanent and in 5 mins time you have forgotten about it.
If I run into TERM issues and am in a hurry, I would rather do it as: TERM=ansi tmux
ie set it manually for that session as a prefix on the command line, thus remembering to sort out the glitch when I have more time, if I still don't have time to fix it next time I just scroll back to the last tmux in my history to find the workaround.

There are a few valid cases to override the TERM setting, for example with tmux since it normally expects you to use the xterm family of terminals. If you use some ancient vt100 terminal, the workaround is to use TERM=screen
with that you dumb down the screen handling parts of tmux to a so low level that virtually any terminal can handle it.
But even that should in most cases not be done in an init script.
