### ISSUE TITLE
Does alacritty ignore `embeddedbitmap` fontconfig setting?

### ISSUE THREAD

**Issue by roman-holovin** [jwilm/alacritty#2655]
Which operating system does the issue occur on?
Linux

If on linux, are you using X11 or Wayland?
X11

**Prerequisites**: 
I have a font [http://apl385.com/fonts/index.htm](APL385) (public domain, feel free to test it out), it has embedded bitmaps, I've disabled then globally using fontconfig configuration (snippet below) and made sure that this configuration is properly loaded

```xml
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
  <match target="font">
    <edit name="embeddedbitmap" mode="assign">
      <bool>false</bool>
    </edit>
  </match>
</fontconfig>
``` 

After that Firefox does not render embedded bitmaps for this font anymore, but Alacritty does.

**Comment by chrisduerr** [comment]
I've never tested this and Alacritty does not have its own fontconfig bindings, so there's little I've done directly with fontconfig and most things just work very well out of the box. However, Alacritty is not doing any font layout and instead just reads each glyph separately. It's possible that this has to be explicitly checked before loading every glyph.

Could you test if this works when disabling embedded bitmaps for the specific font, instead of disabling it for all fonts?

**Comment by roman-holovin** [comment]
So I've tested with disabling for this font only

```xml
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
  <match target="font">
    <test qual="any" name="family">
      <string>APL385 Unicode</string>
    </test>
    <edit name="embeddedbitmap" mode="assign">
      <bool>false</bool>
    </edit>
  </match>
</fontconfig>
```
Both Firefox and Termite (VTE-based teminal emulator) reacting appropriately to configuration changes (I've tried also to intentionally make a mistake in configuration to see, if they would react to that), but Alacritty still renders embedded bitmaps regardless of configuration.

**Comment by chrisduerr** [comment]
Sounds like there's additional work required by Alacritty then, thanks for the report.
