### ISSUE TITLE
Underline starting in last line not rendered when scrolled up

### ISSUE THREAD

**Issue by chrisduerr** [jwilm/alacritty#2680]
If an underline is started in the last line while scrolled up in the terminal, the underline is not rendered correctly.

This applies both for underlines printed using the escape sequence and for underlines created for URL highlighting.

Quick investigation shows this might be caused by the `update_lines` method or some other step in the rendering process. It seems like the cells have the underline flag set correctly, or at least some flags have an underline flag set, I haven't checked if they're the correct cells yet.

**Comment by kchibisov** [comment]
Seems like `strikethrough` is also affected. However selecting any cell (even empty) on line with underline + strikethrough shows both underline and strikethrough correctly.

**Comment by chrisduerr** [comment]
Since strikeout and underline are handled pretty much exactly the same way, this does make sense.

Good catch on the selection though. I'd expect this to be relatively easy to resolve once the cause is found, however I was caught up with finishing up my PR for moving Alacritty to rfind_url.

**Comment by kchibisov** [comment]
@chrisduerr I guess, I've found a starting point and it seems like something is super weird here. The code, which is seems to be responsible for it is [here](https://github.com/jwilm/alacritty/blob/54dca06bfbac50da0adb33c928e376b5c7986c4a/alacritty_terminal/src/renderer/rects.rs#L78). This "if" condition is **always** false and the cell.column, cell.line values are super odd. Also I've never seen `cell.line == size_info.lines()`.

```diff
diff --git a/alacritty_terminal/src/renderer/rects.rs b/alacritty_terminal/src/renderer/rects.rs
index b4f8a01..95f4028 100644
--- a/alacritty_terminal/src/renderer/rects.rs
+++ b/alacritty_terminal/src/renderer/rects.rs
@@ -17,6 +17,7 @@ use crate::index::Point;
 use crate::term::cell::Flags;
 use crate::term::color::Rgb;
 use crate::term::{RenderableCell, SizeInfo};
+use std::process;

 #[derive(Debug, Copy, Clone)]
 pub struct Rect<T> {
@@ -66,6 +67,10 @@ impl<'a> Rects<'a> {
     /// Update the stored lines with the next cell info.
     pub fn update_lines(&mut self, size_info: &SizeInfo, cell: &RenderableCell) {
         for line in self.active_lines.iter_mut() {
+            if size_info.lines() == cell.line {
+                process::exit(127);
+            }
+
             match line.range {
                 // Check for end if line is present
                 Some((ref mut start, ref mut end)) => {
@@ -75,8 +80,11 @@ impl<'a> Rects<'a> {
                         && cell.fg == start.fg
                         && cell.column == end.col + 1
                     {
+                        println!("SizeInfo(cols: {:?}, lines: {:?})", size_info.cols(), size_info.lines());
+                        println!("RenderableCell(cols: {:?}, lines: {:?})", cell.column, cell.line);
                         if size_info.cols() == cell.column && size_info.lines() == cell.line {
-                            // Add the last rect if we've reached the end of the terminal
+                            // add the last rect if we've reached the end of the terminal
+                            process::exit(127);
                             self.inner.push(create_rect(
                                 &start,
                                 cell.into(),
```

You're probably have more ideas on what's going on here, since I'm not very familiar with rendering code atm. I'll continue watching into this to learn about rendering, but waiting for your feedback on this one.

**Comment by kchibisov** [comment]
The issue was caused by this rework 6716c81c08c10477d2370d7e1ca56e31348a7fa3. The `cell.lines` seems correct on the commit before rework I've mentioned(they're counted from zero, but values looks fine, since they can reach size_info.lines()).

**Comment by chrisduerr** [comment]
I'll take a look at the code later, but `cell.line == size_info.lines()` looks like an off-by-one error to me. I'd assume `cell.line` is zero based. However I don't understand why it would have worked previously. Same with the columns.

**Comment by kchibisov** [comment]
> I'll take a look at the code later, but cell.line == size_info.lines() looks like an off-by-one error to me.

For me, they it's off by 7(random number) in case I create underline on the last line.

**Comment by kchibisov** [comment]
Just an update to the issue.
The issue is presented only with the last underline in the last line
![Screenshot_Tue 30 Jul 2019 11:58:34 PM MSK](https://user-images.githubusercontent.com/27620401/62165193-92879900-b326-11e9-9d85-b571c394a944.png)

This is also presented when underlining on a prompt regardless of the position, but your cursor should be to the left to underlined text. Just move a cursor across the url to get the broken behavior.
