### ISSUE TITLE
Live reload font config

### ISSUE THREAD

**Issue by rgtk** [jwilm/alacritty#2737]
Changes to color scheme in config are reflected in all windows without need for restarts. Would it be possible to have the same for font size change?

I jump between displays with different DPI throughout the day. In one 11 size looks good, on the other it's too big. I would love to amend alacritty.yml when computer detects screen change to appropriate font size.

I know it is possible to change font dynamically with `C-+`/`C--` but I with many windows in use, it's very tiresome.

**Comment by chrisduerr** [comment]
This has been on my roadmap for a while actually, I've just never gotten around to create the issue itself.

There's no reason why we would keep it to just the font size either. We should also be able to live reload the font family and style.

**Comment by chrisduerr** [comment]
> This would presumably override the current font size set by the user of a running terminal (set using the *FontSize actions). This seems fine to me, but if people are trying to use the live config feature to update visuals on the fly, I wouldn't want my font sizes resetting.

We should be able to just compare if the current font size is equal to the original font size and reset it only if that is the case.

> Generally live updating configurations that can be changed at runtime seems hard. How do we handle this with any other configs today?

I don't think any other option where this is possible comes to mind.

**Comment by waynr** [comment]
Has anyone begun working on this? It's kind of a personal itch that I'd like to scratch and I am looking for a good [hacktoberfest](https://hacktoberfest.digitalocean.com/details) challenge.

**Comment by chrisduerr** [comment]
@waynr As far as I know, nobody is working on this right now and it would be a very welcome addition.

If you have any questions about how to approach this, please let me know.

These are some of the relevant places for this issue:
 - [This is the config update handler closest to where our font is cached](https://github.com/jwilm/alacritty/blob/master/alacritty_terminal/src/display.rs#L129-L131)
 - [Our font cache is created here](https://github.com/jwilm/alacritty/blob/master/alacritty_terminal/src/display.rs#L308-L309)

As far as I can tell, the following steps should be taken:
 - Check if font has changed
 - Evict existing glyph cache
 - Fill new glyph cache
 - Update our cell metrics

This is of course just necessary if we want to go all the way and enable live reloading for the font. If we just want to live update the default font size, things get much easier.

The font size update code can just be handled in the [terminal's config update handler](https://github.com/jwilm/alacritty/blob/master/alacritty_terminal/src/term/mod.rs#L926-L941) and we'd just need to check if the current font size is equal to the old default font size and if that's the case we can change it to the new font size.

Since these two issues are so different in complexity, it probably makes sense to split them if someone is interested in going for the font size change. So handling them in separate PRs is no problem. If someone is doing the style reloading anyways, the size change shouldn't be much more complicated though.

**Comment by waynr** [comment]
@chrisduerr thanks for the excellent guidance! I am stuck in an airport so I'm gonna start looking into this now but not sure when I'll have any PRs up.

I'll probably do as you suggest and make the default font size change in a separate PR to start with since it sounds like a good way to get started.
