### ISSUE TITLE
Patch to make alacritty work on gru-kevin-coreboot rk3399 w/ Mali860 GPU under sway

### ISSUE THREAD

**Issue by a-m-joseph** [jwilm/alacritty#2773]
Which operating system does the issue occur on? Linux

If on linux, are you using X11 or Wayland? Wayland

**Are you including a patch that fixes the issue? Why yes in fact I am glad you asked**

Hi, after much suffering I managed to get alacritty (under sway)
working on the Samsung Chromebook Plus (aka gru-kevin) using its the
Mali 860 GPU, which is OpenGLES 3.2-only, so I had to backport the
shaders.  The new ones work on GLES 3.0 and later.

Below are the patches to alacritty.  They're ugly and definitely not
suitable for upstreaming as-is, but they should be useful to other
people with the same laptop/GPU.

There are four patches:

  1. glutin-0.21.0-alacritty-rk3399-patch.txt is a patch to
     glutin-0.21.0.  For some reason glutin misinterprets libMali's
     advertisement of what GLES versions it supports; this ugly patch
     hardwires the fact that libMali does GLES3.2.  Maybe glutin could
     offer an environment variable to override the advertised GLES
     support level reported by the driver in cases like this?

  2. 0001-use-kludged-version-of-glutin-0.21.0.patch is a patch to
     alacritty to use an in-tree local version of glutin with the
     patch above.

  3. 0003-shader-hacks.patch backports the shaders to OpenGL ES 3.0.
     I really wish the theory of operation on the shaders was
     better-documented in the code; I still can't figure out what a
     "rect shader" does or why on earth the text shader uses
     multisample blending.  Ultimately I just started poking at things
     until I found a combination that works, but I don't understand
     why it works.  Please document the meaning of the two shader
     outputs and why they are separate (color+alpha) instead of a
     single vec4.

  4. When you run alacritty under sway on rk3399 hardware each
     individual character will render upside-down.  If you use weston
     on rk3399 this doesn't happen.  If you use sway on ATI/AMD this
     doesn't happen.  It's a very weird bug.  I don't know what's
     going on here, but 0002-vertical-flip-hack-for-mali-opengl.patch
     clobbers it into working by simply flipping each character again.
     Don't ask me why this is needed, I don't understand it either.

I found that alacritty will freeze up randomly unless sway is launched
with -Dnoatomic. Unfortunately the libMali blob is very, very
unforgiving, and the freezing is due to it crapping all over the call
stack when it gets in a bad mood.

Performance is excellent.  Without GPU support alacritty is unusable on this hardware; with it alacritty-wayland is, _by far_, the fastest terminal emulator for the rk3399.  However startup time is still annoyingly long, several hundred milliseconds to perhaps even half a second.  Is there some way for a single alacritty process to be shared by all the terminal windows a user opens, like Terminal.app and urxvt?  Rust binaries are fast but monomorphization makes them big; part of the (wise) tradeoff chosen by Rust and MLton means their binaries will always start a bit slower in order to run much much faster.

The patches to sway can be found in this issue: https://github.com/swaywm/wlroots/issues/1812

[glutin-0.21.0-alacritty-rk3399-patch.txt](https://github.com/jwilm/alacritty/files/3568509/glutin-0.21.0-alacritty-rk3399-patch.txt)

[0001-use-kludged-version-of-glutin-0.21.0.patch.txt](https://github.com/jwilm/alacritty/files/3568510/0001-use-kludged-version-of-glutin-0.21.0.patch.txt)

[0002-vertical-flip-hack-for-mali-opengl.patch.txt](https://github.com/jwilm/alacritty/files/3568511/0002-vertical-flip-hack-for-mali-opengl.patch.txt)

[0003-shader-hacks.patch.txt](https://github.com/jwilm/alacritty/files/3568512/0003-shader-hacks.patch.txt)

**Comment by chrisduerr** [comment]
First of all, thanks a lot for looking into this. I'll try to address all the points you've made, but if I miss something, please let me know.

### General

> For some reason glutin misinterprets libMali's advertisement of what GLES versions it supports

This would probably be best reported to glutin directly, but I'm curious why your patch and solution aim to override the support response instead of fixing what glutin does wrong. You said that "glutin misinterprets libMali's advertisement of what GLES versions it supports", which sounds like something that should be fixable, without requiring a workaround, right?

> When you run alacritty under sway on rk3399 hardware each individual character will render upside-down

This sounds like an extremely strange bug, but if weston works and sway does not, maybe this is something that needs to be fixed in the compositor?

> Is there some way for a single alacritty process to be shared by all the terminal windows a user opens, like Terminal.app and urxvt

This is tracked in issues like https://github.com/jwilm/alacritty/issues/607 or https://github.com/jwilm/alacritty/issues/241.

It should be noted though that often the first start takes more time than all following initializations because of what seems to be driver initialization, though more research could certainly be done in that area (see https://github.com/jwilm/alacritty/issues/2303 and https://github.com/jwilm/alacritty/issues/782). I don't think we can blame Rust for this one since drivers/OpenGL might have a significant impact here.

### OpenGL Shaders

I'd like to go into a bit more detail here since I think the work on the OpenGL shaders could potentially be upstreamed. There has been a long standing issue (https://github.com/jwilm/alacritty/issues/128) about supporting lower OpenGL versions and I think it might be very beneficial to support at least a few more years of old GPUs. That should hopefully help with bringing Alacritty to a few more people out there and reduce the barrier that OpenGL imposes.

> I still can't figure out what a "rect shader" does

The rect shader is used for drawing rectangles like the message bar background, underlines, strikeout and the visual bell.

> why on earth the text shader uses multisample blending

I did not write this code so I can only take guesses why multisampling is enabled. But I'd assume that this was done to improve glyph outlines. However in my testing I can't make out any concrete differences. Why is this relevant to your changes though?

The commit which introduced this (eac9747a78fb3fe2eb6563ea95c2847eb0ec9f0a) doesn't shed a lot of light on things, though it's very very old.

> why they are separate (color+alpha) instead of a single vec4

Are you talking about the `alphaMask` output of the text fragment shader?

This is the original commit message:

> Correct sub-pixel font rendering with OpenGL
>
> Uses the GL_ARB_blend_func_extended to get single-pass, per-channel alpha blending. gl_generator is now used instead of gl to enable the extension.
>
> The background color is removed since that presumably needs to run in a separate pass.

I'm not very familiar with OpenGL myself and haven't written this code, but it seems like this separate alpha blend mask is necessary for the OpenGL blend function extension in use by Alacritty.

If you take a look at c70acbac0b721ea2f1b1442898c22aee0f360ef2, you'll see that previously something more similar to what you might have expected is used, however here you can see that the alpha value is constant and it's blended in the shader. It seems like what we currently have allows us to have a blend map with a custom blend factor for each individual channel.

If the goal is purely to share these patches, I think this issue can be closed. However I'm very open to upstream as many things as possible for improved platform support as long as it doesn't significantly impact existing systems.

I think support for earlier OpenGL and GLSL versions should be tracked in https://github.com/jwilm/alacritty/issues/128 though, so all further comments on that are likely better posted on this more specific issue.

**Comment by a-m-joseph** [comment]
> You said that "glutin misinterprets libMali's advertisement of what GLES versions it supports"

Good point, you're right.  I will figure out why glutin is parsing libMali's response as None instead of Some(3,2) and submit a patch to glutin.

> >  When you run alacritty under sway on rk3399 hardware each individual character will render upside-down

> if weston works and sway does not, maybe this is something that needs to be fixed in the compositor?

Quite possible.  To be clear I did not mean to assign blame on this issue.  The behavior is strange enough that fault could lie with any of the participants!  I just wanted to document what I'd noticed.

> If the goal is purely to share these patches, I think this issue can be closed.

Ok, no problem, you can close this issue.

> I think support for earlier OpenGL and GLSL versions should be tracked in #128 though, so all further comments on that are likely better posted on this more specific issue.

I will post the rest of my reply there.

**Comment by chrisduerr** [comment]
Oh, just an idea to increase visibility, you could also document this in the wiki, however I'm not quite sure how much sense that makes in the current state of patches required.
