### ISSUE TITLE
Make font bolder, macOS-ish font rendering?

### ISSUE THREAD

**Issue by nvmnghia** [jwilm/alacritty#2806]
I want the font to be bolder, like the font rendering of Mac, but not as blurry as Windows's MacType.

I'm using Kubuntu 19.04. The yml setting has a `thin stroke` option reserved for macOS, can we have a `bold-stroke` option on other platforms too?

I do find mac's font rendering pleasing. Maybe I'm the silent minority mentioned [here](https://pandasauce.org/post/linux-fonts/).

Thanks for considering my request.

**Comment by kchibisov** [comment]
If you want a bolder font, you can always use Medium/Bold style for your normal font. The option on macOS is because the system expose such thing. If you want to make your font bolder, what's the purpose of Medium/Bold variants then?

**Comment by nvmnghia** [comment]
> If you want a bolder font, you can always use Medium/Bold style for your normal font. The option on macOS is because the system expose such thing. If you want to make your font bolder, what's the purpose of Medium/Bold variants then?

It is **slightly** bolder, and there's a separated bold variant. I would describe the current font rendering in Windows and Linux as thin. Medium would be awesome (no system modification), however most fonts only come in Regular or Bold, no medium rare or anything.

**Comment by chrisduerr** [comment]
You're free to choose whatever thin or bold font you want on Linux. Even on macOS the `use_thin_strokes` variable is questionable and there's at least the argument of default fonts there. With Linux I don't think there's any point in not letting this be a system configuration.

Chances are just looking around at a few alternative fonts might already provide very insightful. I personally don't like very thin fonts either, which is why I'm running Fira Mono Medium myself. So it's not a bold font either, it's just slightly bolder. That's exactly what it's made for and I know a lot of monospace programming fonts support a dedicated font for this (I've used the slightly bold variation of source code pro before).
