### ISSUE TITLE
Elevated ram/memory usage not solved by #1584

### ISSUE THREAD

**Issue by codesections** [jwilm/alacritty#2853]
Issue #977 (in 2018) involved the fact that Alacritty uses significantly more RAM than other terminal emulators (in percentage terms, though still a low amount overall).  At the time, the consensus was that this higher RAM use was caused by the scrollback buffer being initialized with empty lines.  Based on that assumption,  the issue was closed when #1584 was merged, since it addressed the scrollback issue.

However, as reflected in the screenshot below, Alacritty's memory usage is still about double that of xterm—about the same difference noted in #977.  

![alacritty](https://user-images.githubusercontent.com/35405463/66249394-a2de3a80-e700-11e9-81be-cb97812e504d.png)

I recognize that the difference between 8.5 MBs of RAM (for xterm) and 19.4 MBs (for Alacritty) is not enough for many people to get worked up over (though it does significantly increase my personal RAM use!).  But I thought I'd bring this issue to the community's attention, especially given that we believed the scollback fix would resolve the discrepancy. 

> Which operating system does the issue occur on?

Void Linux (Linux kernel 5.2.18)

> If on linux, are you using X11 or Wayland?

X11

> What version of Alacritty are you using?

0.3.3

**Comment by chrisduerr** [comment]
> especially given that we believed the scollback fix would resolve the discrepancy

This statement is actually incorrect. The scrollback fix worked exactly as intended and saved a good chunk of memory for terminals which would never reach a significant amount of scrollback buffer especially when running with 100_000 lines of scrollback.

However, due to the nature of Alacritty, it's impossible to match the memory usage of terminal emulators like XTerm.

This is because we use OpenGL for rendering, which requires drivers to be loaded. If you run even a very basic OpenGL program like glxgears, you'll notice that doing anything OpenGL comes with a good chunk of memory overhead.

If there's any astronomical difference which is caused by Alacritty, that's of course a bug. But this issue seems to be mostly about the memory differences due to rendering, so I don't think there's anything Alacritty can or should do.
