### ISSUE TITLE
Non-native window decorations on Gnome on Wayland

### ISSUE THREAD

**Issue by marekdedic** [jwilm/alacritty#2860]
I'm on Debian testing, using Gnome on Wayland.

If I set my window decorations to `full`, I'd expect the decorations to match the style of other apps on Gnome. However, this is not the case - Alacritty decorations look very out of place.

Obviously this isn't an issue that would make Alacritty unusable or something like that, but it would still be nice to have the window match the DE.

**Comment by kchibisov** [comment]
@marekdedic Would you mind to share screenshot on how our decorations look like on you system?

**Comment by marekdedic** [comment]
![Screenshot from 2019-10-09 12-18-07](https://user-images.githubusercontent.com/3134692/66473252-285e4380-ea8f-11e9-8f65-5f751dc0cf0b.png)

I've added gedit on the right - that's what I would imagine "native" decorations to look like...

**Comment by chrisduerr** [comment]
What you describe as `decorations to match the style of other apps on Gnome` likely means just GTK decorations. These all look the same because they are drawn with the same toolkit.

If server side decorations are rendered, we will not draw our own decorations. However, GNOME thought it's a good idea not to support server side decorations, which means you end up with Applications that all have decorations that look completely differently.

My recommendation is to not use GNOME. There might be a way to get some kind of server side decorations working with GNOME, but that's a GNOME issue really. Other Wayland compositors should just work, if they do not we can discuss that in a separate issue. Sorry for the disappointment.

**Comment by coshsinh** [comment]
This is really a GNOME thing here, client-side decorations are now supported for all apps, the GNOME look is just enforced by the GTK theme, but as mentioned in this [post](https://blogs.gnome.org/fmuellner/2015/01/30/a-small-note-on-window-decorations/), server-side decorations can also be negotiated and should use the default GTK theme by default.

The same problem was also mentioned for KDE Qt apps running on GNOME shell, the GTK look can be obtained with several third-party themes though.
