### ISSUE TITLE
Unable to resize window in latest nightly

### ISSUE THREAD

**Issue by dead10ck** [jwilm/alacritty#2893]
I'm running Fedora Linux under GNOME Wayland. On the latest nightly (a75e9493449d90b54a140b76f6a96b684784a059), when hovering the mouse over the borders of the window, the resize icon never shows up, so it is impossible to resize the window.

**Comment by chrisduerr** [comment]
Can you pinpoint which version exactly broke this?

**Comment by dead10ck** [comment]
I can try to bisect next week

**Comment by andreasgrv** [comment]
I have also run into this, I cloned the repository today and built alacritty on Debian and could not resize the window. I noticed after a while that when hovering exactly over a corner of the window, I occasionally get a resize icon and can resize it, but it is quite hard to achieve.

**Comment by chrisduerr** [comment]
Would be interesting to see if this can be reproduced with the examples of glutin in https://github.com/rust-windowing/glutin.

The examples can be run with `cargo run --example window`.

**Comment by andreasgrv** [comment]
Yes, the window that shows up is resizeable but no resize icon shows up when hovering over the border.

**Comment by chrisduerr** [comment]
Reported upstream in https://github.com/rust-windowing/winit/issues/1236. Thanks for testing.

**Comment by kchibisov** [comment]
I think you can resize, just no icon is showing. I was able to repro issue on GNOME and I'm not sure what is going on, however after click on a border everything is correct.

**Comment by andreasgrv** [comment]
Moreover, the hovering issue is definitely specific to GNOME Wayland, I logged into GNOME/X11 now and hovering works fine.

```
echo $XDG_SESSION_TYPE
x11
```

**Comment by kchibisov** [comment]
I know that its specific to Wayland. I can't repro on sway 1.2, I have a feeling that we should manually set resize cursor etc, since QT/Gtk set a different one on Wayland for the same thing, so when I'm hovering over window border QT sets cursor to horizontal resize on however, and to e.g. left resize on press, but GTK sets cursor to e.g. left resize directly.

Previously we didn't set cursor at all, so it was able to disappear on GNOME in some cases.
