### ISSUE TITLE
Is there anyway to make alacritty modes(with decoration/none/full) be toggled with the keyboard?

### ISSUE THREAD

**Issue by cata0309** [jwilm/alacritty#2900]
Linux Solus 4 Fortitude
X11

**Comment by kchibisov** [comment]
No, and I don't think that its a good idea to add something like that, generally some wm provides a way to change window decorations during runtime, I'm not sure that we want something like that, since its some exotic feature, which will likely be rarely used(idk if it's to implement something like that on all supported platforms though).

**Comment by cata0309** [comment]
I understand
