### ISSUE TITLE
Doesn't always use full window to render

### ISSUE THREAD

**Issue by cubetastic33** [jwilm/alacritty#2916]
Which operating system does the issue occur on?
Arch Linux
If on linux, are you using X11 or Wayland?
X11

Alacritty sometimes isn't using the full screen to render. I'm using Arch with i3, and here are some screenshots:
This is how the bottom right edge looks in a regular-sized window running neovim:
![image](https://user-images.githubusercontent.com/33519300/67558171-1d184280-f734-11e9-9fdf-a3d6fb2e950d.png)
When I go to full screen:
![image](https://user-images.githubusercontent.com/33519300/67558254-43d67900-f734-11e9-801c-280d5b2fcdad.png)
If I reduce it to half the width:
![image](https://user-images.githubusercontent.com/33519300/67558293-5486ef00-f734-11e9-8535-77f2b7a91be0.png)
This doesn't just happen in neovim - it's always there. What could be causing this issue? I did try using kitty, and it renders properly.

**Comment by chrisduerr** [comment]
I'm not quite sure I understand the issue here. It seems like the full screen is used to render, judging by the airline you have. So putting text probably works too in every line/column?

I'd assume the issue you talk about is with the "line" at the right side of your second screenshot, right?

Do you have any kind of transparency enabled? Also have you tried the latest master or are you running the version of Alacritty in the repos?

**Comment by cubetastic33** [comment]
I'm talking about the black space around the gray in the screenshots. Here's a screenshot of kitty to compare:
![image](https://user-images.githubusercontent.com/33519300/67583400-24a60e80-f769-11e9-9199-ec7a34847628.png)
As you can see, there's not as much of a black border. However, with alacritty, there's a black margin, and its size changes when I resize the window. I use compton as my compositor, but I don't think I've set transparency options for alacritty. I'm using alacritty from the repos.

**Comment by cubetastic33** [comment]
@kchibisov why does this not happen in kitty, then?

**Comment by kchibisov** [comment]
@cubetastic33 It depends on your font size and terminal size, you could be just like in kitty, since it also uses padding (all terminals are using it).

P.s.
Screenshot from kitty with the same behavior
![Screenshot_Fri 25 Oct 2019 06:30:53 PM MSK](https://user-images.githubusercontent.com/27620401/67584205-c6236500-f755-11e9-8351-c7952f4cd9b5.png)

**Comment by cubetastic33** [comment]
So how do I make my alacritty use hardly-noticeable padding like kitty is?

**Comment by kchibisov** [comment]
change font size, try dynamic_padding setting in a config(this is what kitty does by default), char spacing, etc.

**Comment by cubetastic33** [comment]
Ooh, that's awesome - `dynamic_padding` did it!! What's this feature for though? Why is `dynamic_padding` disabled by default in alacritty?

**Comment by chrisduerr** [comment]
> Why is dynamic_padding disabled by default in alacritty?

I'm running with dynamic_padding myself and in my initial PR it was enabled by default. However after discussing it with a few other people it seems like the majority of people do not like that. One issue with dynamic padding is that when resizing, the prompt "jumps" around a bit since the padding on the top left changes dynamically.

> Is there any disadvantage to setting the padding to 0?

None I'm aware of. It's purely a stylistic preference as far as I'm concerned.
