### ISSUE TITLE
Alacritty extremely slow in Sway with Nvidia

### ISSUE THREAD

**Issue by n8henrie** [jwilm/alacritty#2932]
I have Sway running fairly well on a computer with a 1080Ti running Arch; I use CUDA so I have to launch it with the [`--my-next-gpu-wont-be-nvidia` flag](https://github.com/swaywm/sway/blob/master/sway/main.c#L101), but otherwise it seems to work fairly well.

With my setup, alacritty is extremely slow -- each keypress has a visible lag, and even moving the mouse over the alacritty window lags (as opposed to a urxvt window on the other half of the screen -- with both running simultaneously, it continues to be snappy and has no mouse lag).

I initially posted this [on r/alacritty](https://www.reddit.com/r/Alacritty/comments/dlywol/alacritty_extremely_slow_in_sway/) but was suggest to make an issue. [As noted there](https://www.reddit.com/r/Alacritty/comments/dlywol/alacritty_extremely_slow_in_sway/f5jch12/) this isn't particularly *surprising* given that Sway explicity does not support Nvidia; mostly I was posting to see if anyone with a similar setup was *not* experiencing lag, in which case I would continue trying to hunt down an issue with my configuration.

**Comment by kchibisov** [comment]
Would you mind to try nouveau, just for the testing purposes?

**Comment by dnkl** [comment]
AFAIK, sway doesn't support the Nvidia blob _at all_. `--my-next-gpu-wont-be-nvidia` is needed because sway bails out if the nvidia driver **is loaded**.

So, you're either running Sway on nouveau, or maybe on an integrated Intel GPU? You should be able to see which card sway is using by enabling logging (`sway -d 2> ~/sway.log`, then exit again and check the output).

If it's nouveau, then it might be that the card is stuck at boot clock frequencies. These would be the lowest performing, power saving frequencies and would explain why Alacritty is slow.

If it's the integrated GPU, then things should be ok, except if alacritty, for some reason, is rendering on the nvidia card. The rendered surfaces would then have to be copied over to the integrated GPU to be displayed. This is slow.

**Comment by chrisduerr** [comment]
> AFAIK, sway doesn't support the Nvidia blob at all

This was what I thought too, so I was a bit surprised by that flag. So if it is just to make sure it doesn't bail even if it shouldn't be using the nvidia blob, that would make sense.

**Comment by n8henrie** [comment]
Sorry, it took me way longer than I expected to get nouveau running.

You're correct, alacritty runs excellently under sway with nouveau.

Sway seems to run fairly well under Nvidia with the `--my-next-gpu-wont-be-nvidia` flag, but I'll remember to do a rew `rmmod` and `modprobe`s if I want to use alacritty!

Thanks to all for the input.
