### ISSUE TITLE
Missing packages on Arch Linux

### ISSUE THREAD

**Issue by burgerdev** [jwilm/alacritty#294]
On a pretty fresh arch installation, I found the following packages to be missing:

  * `make`
  * `pkg-config`

**Comment by jwilm** [comment]
Thanks for the report

**Comment by N-006** [comment]
Those packages are in `Core` repository and should be installed by default.

**Comment by polyzen** [comment]
They are part of the `base-devel` group which is [expected to be installed](https://wiki.archlinux.org/index.php/Makepkg#Usage).

**Comment by burgerdev** [comment]
Would it still make sense to add `base-devel` to the readme? The wiki page only mentions that `base` is assumed to be installed on all systems while `base-devel` *has to be installed* for using `makepkg` (which is itself an optional package, although admittedly very common).

**Comment by polyzen** [comment]
My mistake, you're absolutely right.

@jwilm, since there's a package for Arch, perhaps the readme should just point users to that. There will also be one to follow releases once those are available.

**Comment by MoSal** [comment]
@burgerdev 
`makepkg` is not an optional package. It's the official build tool. And it's shipped with `pacman`(the package).

`base` is assumed installed in all cases.  
`base-devel` is assumed installed if you want to build software.

**Comment by burgerdev** [comment]
@MoSal You are totally right, `makepkg` is part of `pacman` but can't be used unless `base-devel` is installed - which is fair to assume on a machine compiling sources. It might not hurt to mention it, but the odds of someone else compiling alacritty on a vanilla OS seem pretty small. I'd consider this issue solved.

**Comment by jwilm** [comment]
> since there's a package for Arch, perhaps the readme should just point users to that

This sounds ideal. Would someone familiar with arch mind updating the instructions?

**Comment by munyari** [comment]
@MoSal I think it might be useful to make a note that `base-devel` is assumed if you need to build software (I didn't even know that, or at least it never occurred to me). I think there are two possibilities for the Arch Linux instructions:
1. Show how to build from source. In that case, I think it makes sense to say that you need `base-devel`
2. Point people to the AUR package. In that case, make no mention of `base-devel`, [since it is assumed](https://wiki.archlinux.org/index.php/Arch_User_Repository#Getting_started)
