### ISSUE TITLE
[Feature] Hide title bar when maximized

### ISSUE THREAD

**Issue by agriffis** [jwilm/alacritty#2965]
Linux - Wayland

I've looked for existing feature requests here and in winit and haven't found something. I'd be surprised if this isn't duplicate, though, so apologies in advance if so.

I'd like to have a title bar normally, but hide it when the window is maximized. On X11 with SSD this can be done in the window manager. On Wayland with CSD I think this needs to be handled by the application.

**Comment by kchibisov** [comment]
fyi Wayland has SSD, if your compositor doesn't support it then ask them to add it, I assume you're using GNOME, since I don't know any other compositor without SSD.

Anyway, I don't think that we should handle such things, since it's much a user preference about having a title bar when window is maximized and should be handled by compositor/wm in my opinion. I personally don't want such behavior, so this mean, that we should add a toggle for it. We have a fullscreen mode without title bar though.

**Comment by agriffis** [comment]
@kchibisov I agree that it should be configurable, sorry I neglected to say that. I know that CSD versus SSD is an ongoing debate and that GNOME has staked their position. To both sides the answer seems obvious and I don't really want to argue it. Since alacritty already has CSD that can be hidden when fullscreen, my hope is that it would be reasonable to extend that to maximized mode as well.

**Comment by chrisduerr** [comment]
@agriffis Have you tried using `Fullscreen` instead of `Maximized`? Usually maximized means the bar is still showing and fullscreen means it is not.

**Comment by agriffis** [comment]
@chrisduerr Yes I've used both. The effect I wanted was: title bar on normal window, no title bar on maximized window. Then the top of the alacritty window content bumps up directly against the GNOME top bar.

I use KDE on one of my systems so I'm aware of how that behaves differently. Funny thing is that isn't much easier, but at least it's possible. There's no configuration in the GUI for hiding SSD title bars on maximized windows. You have to issue a command `kwriteconfig5 --file ~/.config/kwinrc --group Windows --key BorderlessMaximizedWindows true` and then reload kwin with `qdbus org.kde.KWin /KWin reconfigure`.

My thinking is that if it were easy to provide a configurable for hiding the CSD title bar when maximized, it would make integration in a GNOME desktop nicer, but honestly I'm not too hung up on this. The situation with alacritty is already better than kitty, which doesn't provide any CSD and refuses to start on GNOME without an override!

**Comment by chrisduerr** [comment]
@agriffis So fullscreen mode does indeed do what you want, however it takes up the whole screen instead of going up to the titlebar, correct?

And maximized does what you want with going up to the title bar, however it does still show the window decorations?

From what I can tell that's exactly how decorations are supposed to behave on both Wayland and X11, so it's a tough argument to make for changing this. If a change is desired, I'd see a patch for such special behavior in the DE using SSDs, rather than asking every client application for a patch to support this special case.

I can understand it of course if people are looking for solutions to work around the gnome CDS/SSD issue, however fundamentally this is an issue imposed by gnome and I don't think it should be the problem of any other application to fix the mistakes they've made.

**Comment by mmoya** [comment]
FTR  I end up here looking for 'no title bar when maximized' but [#168's solution](https://github.com/alacritty/alacritty/issues/168#issuecomment-1236052344) is acceptable for me.
