### ISSUE TITLE
Sublime theme support

### ISSUE THREAD

**Issue by fdcds** [jwilm/alacritty#2977]
It would be great if alacritty would support customisable colour themes.

[bat](https://github.com/sharkdp/bat) uses Sublime themes (*.tmTheme):
* https://github.com/sharkdp/bat#adding-new-themes
* https://www.sublimetext.com/docs/3/color_schemes_tmtheme.html

If alacritty would support the same theme format, I could use the exact same theme in both and everything would always be readable and consistent. :)

**Comment by kchibisov** [comment]
We want our configuration to be simple and portable, and the most important, **simple** and readable for humans. So using xml for our config is not an option (and also creating multiple themes). Oh, and why should we even consider a format of some proprietary app? I could same let's use simplified `.vim` and it will sound to me like your proposal.

**Comment by fdcds** [comment]
> I could say let's use simplified `.vim` and it will sound to me like your proposal.

Nice idea. That format could then also be used in the shell, the prompt and the pager. The important part is that there is one format that I can use in all of them to make them look well together.

> P.s. And I'm completely ignoring the fact, that this format doesn't even map to terminal emulators.

It defines a bunch of colours for things that I would think could be mapped to things a terminal emulator would use.

**Comment by kchibisov** [comment]
>Nice idea. That format could then also be used in the shell, the prompt and the pager. The important part is that there is one format that I can use in all of them to make them look well together.

This was a joke and it's a terrible idea.

>It defines a bunch of colours for things that I would think could be mapped to things a terminal emulator would use.

It defines a bunch of colors for things that a suitable for text editors, so at this point you're just suggesting to use `xml` for colorschemes instead of `yml`, which is not an option, since we're using `yml` for a very long time.

>That format could then also be used in the shell, the prompt and the pager.

No, it's not. Terminal emulator defines the colors for all the thing you've mentioned. So changing colors in alacritty, affects every app (unless they are using truecolor).

You're probably understanding the coloring a bit wrong, since it's not like in GUI's. We're just rendering whatever thing was requested. So if app requested a color `#00ff00`, we're rendering it without any changes (truecolor mode). However there're also `indexed` colors(1-256 iirc), for which colors are provided by user (`colors` section in a config). This user defined usually called a colorscheme (you can change all of them with escape sequences during runtime though).

**Comment by chrisduerr** [comment]
Most things have been said by @kchibisov already, though there are applications like `terminal.sexy` that support converting between different colorschemes.

There's absolutely no reason for Alacritty to read different formats, instead they should be converted to what Alacritty understands. One might be able to make an argument for .XResources, but even that is already more work than what it's worth.
