### ISSUE TITLE
Question - How to add a native session or "tab" feature (no tmux)

### ISSUE THREAD

**Issue by chichid** [jwilm/alacritty#2987]
I'm trying to get deep into rust and chose this project to do some experiments. I want to add a "tab" feature to the terminal. Something similar to the "SpawnNewInstance" command but would be more like "SpawnNewTab"

For now, I'm not interested in the GUI aspect of this, and I know it can be done with other solutions such as tmux (I'm actually interested in implementing the feature and comparing performance with tmux).

I wanted to approach the problem in the most performant ways (ex. one display that handles many terminals and share as much as possible).

What would be the best way to achieve this in this project from a design point of view?

**Comment by chrisduerr** [comment]
Would probably be best to look at other issues like #241 or #607. Those are foundational things that would probably need to be supported for Alacritty to make it possible to implement Tabs. These are also things that we want to include in Alacritty anyways, since it is required for proper platform support on systems like macOS.

Beyond that would mostly be the GUI work, though I want to make it clear that we have no desire to merge that upstream. But if you want to work on it for personal reasons, that's perfectly fine of course.

If you have any more questions, just let me know. If you're interested in working on the multi-window issue yourself, it would probably make sense to ask questions there though.

**Comment by kchibisov** [comment]
In addition to @chrisduerr , if it happens to be that you're on macOS, we would probably be interested in macOS tabs, since they're likely will be very easy to add and maintain after the issues mentioned above will be solved, take a look at #1544 also.

**Comment by chichid** [comment]
Thanks for the replies! For now I'm just working on this as an experiment on what happens if we try to refactor a core concepts within a big Rust project and this is a perfect candidate! 

Of course when I have the necessary knowledge, then it'll be my pleasure to contribute!

**Comment by chichid** [comment]
@kchibisov @jwilm I was able to make a functional implement tab feature without a GUI using chrome-like keyboard shortcuts (you can spawn new tabs using ctrl+T, delete tabs using ctrl+W, and select the first tabs uisng ctrl+1, ctrl+2). 

I think I'm going to add a native GUI aspect to this next, as I don't think it'll be hard to add even if I implement the tab control using native APIs for each platform, it would be a standalone tab_control, it wouldn't own the opengl renderer and it'll dispatch the necessary actions and present the state of term_collection I created to do all this stuff. 

If you're interested here in a review here is my fork: https://github.com/chichid/alacritty, I put the tabs in the branch: feature/tabs

I'm interested Feedback from Rust practices point of view as I'm still learning it part time :)!

**Comment by nixpulvis** [comment]
@chichid I just skimmed over your branch, and would need to read through more carefully and play with running it myself to really be much help, but I'm curious how you see this work eventually working together with something like #241.

I'm also curious if the design of this can avoid a wrapper for the `Term`. I'm not eactly sure if this makes sense or not yet. Clearly something like a collection struct is needed, but otherwise I'm unsure.

Food for thought maybe.
