### ISSUE TITLE
Control opacity with a bash script 

### ISSUE THREAD

**Issue by xircon** [jwilm/alacritty#2997]
This is not a bug report, I thought I would share a couple of scripts:

Assign to two keyboard shortcuts in your desktop (KDE here).  First script reduces opacity by 0.1, second increase by 0.1. I use super+Numpad plus & super+Numpad minus.

```bash
#!/bin/bash
Str=$(grep -i background_opacity ~/.config/alacritty/alacritty.yml)
Str=${Str:20:5}

num=$(awk "BEGIN {print $Str-0.1; exit}")

if (( $(echo "$num < 0" |bc -l) )); then
        num=0.0
fi

echo $num #debug

sed -i "/background_opacity:.*/c\background_opacity: $num" ~/.config/alacritty/alacritty.yml
touch ~/.config/alacritty/alacritty.yml
```
```bash
#!/bin/bash
Str=$(grep -i background_opacity ~/.config/alacritty/alacritty.yml)
Str=${Str:20:5}

num=$(awk "BEGIN {print $Str+0.10; exit}")

if (( $(echo "$num > 1" |bc -l) )); then
        num=1.0
fi

echo $num #debug

sed -i "/background_opacity:.*/c\background_opacity: $num" ~/.config/alacritty/alacritty.yml
touch ~/.config/alacritty/alacritty.yml
```

**Comment by chrisduerr** [comment]
Unfortunately I don't think we have any place where we can highlight user-scripts like this, but hopefully having it in an issue will make it possible to link to it and help others searching for it.

Our wiki could probably use some rework to clean everything up a bit, structure it more clearly and allow for a clearer "user-contributed" section, which would include things like this, but for now this issue will hopefully work.

Thanks for sharing!

**Comment by nixpulvis** [comment]
I've taken the liberty to create a [s(cripts page on the Wiki](https://github.com/jwilm/alacritty/wiki/Scripts). Was meaning to post this script I had at some point anyway.

**Comment by chrisduerr** [comment]
While that might be a good temporary solution, it's certainly not maintainable in this structure in the long term. So we'll probably have to look into either restructuring the wiki, or providing an alternative platform (like an Alacritty website). Though I personally think keeping everything on github is nice, as long as it doesn't require some proprietary storage format (wikis are just git, so that works well).

**Comment by nixpulvis** [comment]
I'm against an alacritty website in general I think. But I agree this won't scale well... Maybe something as simple as wrapping the code in a `<details>` tag would work for now?

**Comment by nixpulvis** [comment]
I'm against an alacritty website in general I think (haven't really considered it much myself). However, I agree this wiki with scripts won't scale. I suppose we could have each script be a page, and have links to them on the page I created. I don't much care how it looks TBH.

**Comment by chrisduerr** [comment]
> I'm against an alacritty website in general I think

I think a really simple general website that boils down to what is already in the readme can be very helpful, especially for guiding people from search engines.

While our primary audience might be rather tech savvy, I can see how some people can be overwhelmed when getting thrown straight at github when looking for just a TL;DR on what a specific piece of software does.

In the long term, this would also make it easier to have a place to publish release notes with some extra gifs or other graphical support. So I think there are several advantages that would make this worth pursuing long-term.

**Comment by nixpulvis** [comment]
fair enough, a static site is fine. I just don't want to depend on severs. GitHub pages is great while we use GitHub.

**Comment by chrisduerr** [comment]
> I just don't want to depend on severs

Why not? I love servers.

**Comment by shivanshu-semwal** [comment]
I modified the script to only change the line beginning with `background_opacity` and not something like comment `# background_opacity`

```sh
#!/bin/bash

Str=$(grep -i ^background_opacity ~/.config/alacritty/alacritty.yml)
echo "$Str" # debug
Str=${Str:20:5}
echo "$Str" # debug

case $1 in
"-dec")
    echo "Increasing opacity"
    num=$(awk "BEGIN {print $Str-0.1; exit}")
    if (($(echo "$num < 0" | bc -l))); then
        num=0.0
    fi
    ;;
"-inc")
    num=$(awk "BEGIN {print $Str+0.10; exit}")
    if (($(echo "$num > 1" | bc -l))); then
        num=1.0
    fi
    ;;
*)
    echo "Invalid option, use -inc or -dec flag."
    ;;
esac

echo $num # debug

sed -i "/^background_opacity:.*/c\background_opacity: $num" ~/.config/alacritty/alacritty.yml
touch ~/.config/alacritty/alacritty.yml
```

**Comment by RichardBronosky** [comment]
> I've taken the liberty to create a [scripts page on the Wiki](https://github.com/jwilm/alacritty/wiki/Scripts). Was meaning to post this script I had at some point anyway.

I see that this wiki page has been removed. Would you be open to creating a `contrib` directory under https://github.com/alacritty/alacritty/tree/master/scripts so that users @xircon and @shivanshu-semwal (and myself) can collaborate on enhancements in public?

Note:
The `/contrib/` directory pattern is a thing in Open Source, not just something I made up:
https://docs.djangoproject.com/en/4.0/ref/contrib/
https://pypi.org/project/opencv-python/#:~:text=2%20-%20Full%20package%20(contains-,both%20main%20modules%20and%20contrib%2Fextra,-modules)%3A%20pip%20install%20opencv

**Comment by chrisduerr** [comment]
> Would you be open to creating a contrib directory under https://github.com/alacritty/alacritty/tree/master/scripts so that users @xircon and @shivanshu-semwal (and myself) can collaborate on enhancements in public?

I'm generally not a fan of having to review scripts in the wiki, which is why I've removed it. It's too much of a hack to be included in the official repository though.

There are solutions to this problem that I plan to work on in the future, so that will hopefully solve this issue in a more upstream-friendly fashion.

**Comment by RichardBronosky** [comment]
@xircon I ran with your idea. https://github.com/RichardBronosky/alacritty/blob/master/scripts/contrib/opacity-change.sh
