### ISSUE TITLE
Publish on deepin

### ISSUE THREAD

**Issue by GopherJ** [jwilm/alacritty#3001]
Which operating system does the issue occur on? deepin 15.5 SP2

If on linux, are you using X11 or Wayland?

x11

**Comment by kchibisov** [comment]
This should be solved by distro maintainers and not us, so ask them instead.

**Comment by GopherJ** [comment]
Hello @kchibisov , so is there a way to use `alacritty` on deepin, it's not published on crates.io, deepin.

**Comment by kchibisov** [comment]
Just clone the repository and use `cargo install` (see INSTALL.md for more information).
```
git clone https://github.com/jwilm/alacritty
cd alacritty
cargo install --path alacritty --locked
```
This approach doesn't differ from crates.io one (2 commands more though).

Also make sure you have all the required dependencies installed, take a look on INSTALL.md, you should get a clue on what is probably required based on other distros information, iirc correctly we don't have deepin).

P.s.
I'm not recommending `cargo install --git`, because it doesn't work with workspaces (cargo bug iirc).

**Comment by GopherJ** [comment]
Hello @kchibisov , I just installed it! But it seems there are many binaries installed, I need to learn how to use them, but thanks for the instructions.

**Comment by kchibisov** [comment]
It should install only on binary called `alacritty` into `$HOME/.cargo/bin/` everything else were just building dependencies (library crates). if you're about the output of `cargo install`.
