### ISSUE TITLE
Alacritty scroll warning

### ISSUE THREAD

**Issue by 0p3r4t0r** [jwilm/alacritty#3041]
**Which operating system does the issue occur on?**
Linux

**If on linux, are you using X11 or Wayland?**
X11

**Error message:**
[WARN] Config scrolling.faux_multiplier is depreciated; the alternate scroll escape can now be used to disable it and `scrolling multiplier` controls the number of scrolled lines.

**The Fix**
Go into ~/.config/alacritty/alacritty.yml and comment out the `faux_multiplier` setting (line 87 in the default config).

** Questions: **
Should the faux scrolling feature section of the yml file be removed entirely?

Does changing the lines in the config completely solve this issue, or should some part of the code be updated? If an update is needed I can give it a go if someone could point me in the right general direction.

**Comment by cole-h** [comment]
Your `faux_multiplier` section should be removed. It was removed from the repo's default alacritty.yml in https://github.com/jwilm/alacritty/commit/49380bffd24203f139dc32c7bdc9958e64d9dd4d and deprecated in favor of `scrolling.multiplier` (at least for changing the number of lines scrolled).

If you're ever unsure of whether or not a config option was removed, you can check the master alacritty.yml here: https://github.com/jwilm/alacritty/blob/master/alacritty.yml

**Comment by chrisduerr** [comment]
As @cole-h has pointed out, chances are you just want to remove it. If you have not modified this setting, the behavior will be identical to the last release.

If you have modified the `faux_multiplier` and set it to `0`, then you'll have to use the escape sequence to disable it now instead.

Generally if you want to cut down on errors and warnings with the configuration file in the future, I'd recommend removing all fields which you have not set yourself. Since all fields are optional, this will not cause any issues, but allow you to easily upgrade in the future without having to deal with any issues.
