### ISSUE TITLE
Font size aspect ratio is not preserved accross different screens

### ISSUE THREAD

**Issue by agjini** [jwilm/alacritty#3048]
Which operating system does the issue occur on?
I'm on linux manjaro i3. X11.

I have a font size of 10.0 configured.
I'm using two screens : my laptop and an external monitor.
Both screen have a resolution of 1920x1080.

My PC is a Dell latitude 7490.

But when I switching my alacritty window on my laptop or on the monitor, the font size does not appears with the same aspect ratio. The external monitor font seems to be smaller and more lines are displayed than my laptop screen.

Here are screenshot of the same window in each screen

![laptop](https://user-images.githubusercontent.com/1453217/69814787-40cc1e00-11f5-11ea-980b-ccf259f747cc.png)

![monitor](https://user-images.githubusercontent.com/1453217/69814790-4295e180-11f5-11ea-9bbe-2b738e388d13.png)

**Comment by chrisduerr** [comment]
When you open Alacritty on a bigger monitor at the same resolution, that means that more lines should fit on the monitor, since it is bigger. This is called DPI scaling and is computed automatically on X11 based on the monitor's physical size and resolution.

This is intended behavior and should result in similar (ideally identical) physical font sizes (measured with a ruler to the screen), instead of creating bigger fonts on bigger displays.

Since most X11 users are not used to this, since it is not possible in GTK and behind a feature flag on QT, we have the environment variable `WINIT_HIDPI_FACTOR` which can override the automatically computed DPI. Setting this variable to `1` will probably produce the behavior you're expecting. You can put it in the `env` section of the Alacritty configuration file to set this permanently.

Please let me know if I've understood you incorrectly or you have any further questions, but as far as I can tell, things are working as designed.

**Comment by agjini** [comment]
Yes the option works well ! And it produces the expected behavior !
thanks
