### ISSUE TITLE
Consider adding /Applications symlink into alacritty dmg

### ISSUE THREAD

**Issue by mikroskeem** [jwilm/alacritty#3072]
That would make installing Alacritty even quicker, as then you'd be able to simply drag Alacritty app in a single window to get it up and running.

Why? Everybody else seems to do that, and throwing in `ln -s /Applications Applications` into dmg generation shouldn't be an hard task :smile:

OS is MacOS, if someone could not figure out from the suggestion text yet.

**Comment by chrisduerr** [comment]
I don't have a macOS machine around to test this at the moment, but since we're talking about symlinks here, wouldn't that mean the source file is required to stay around?

I feel like that would just be annoying and something that always has to be removed anyways, usually you just want to copy it over properly, instead of keeping it around in some random folder.

**Comment by mikroskeem** [comment]
Not sure if you understood me correctly, but I mean something like this:

![image](https://user-images.githubusercontent.com/3490861/70358385-e4ff3600-1881-11ea-997f-db2236d26f14.png)

**Comment by chrisduerr** [comment]
Okay, so you're not necessarily talking about actually symlinking, but instead just want the .dmg to automatically install to the Applications folder?

I'd assume that would require some kind of installer to be packaged within the .dmg, at least that was the case for the few .dmgs I've installed manually (everything is installed through brew mostly).

It definitely seems like something that can be evaluated, we have an installer on Windows too after all. But it would probably depend on complexity if we actually want that. Since it's macOS specific it might also take a while, but I think we can definitely give it a shot.

**Comment by mikroskeem** [comment]
Not quite an automatic installer. But simply an symlink **inside** the dmg to avoid opening another Finder window.

I can try to PR this at some point.

**Comment by mikroskeem** [comment]
That's what I meant:

![image](https://user-images.githubusercontent.com/3490861/70359072-9f436d00-1883-11ea-86ba-78693c41bf7f.png)

Now I can simply drag and drop the Alacritty.app into /Applications folder

**Comment by chrisduerr** [comment]
Ah gotcha, that would significantly make things easier, yes. Should be a trivial change then and seems like it would make sense.

**Comment by chrisduerr** [comment]
Fixed in #3077.
