### ISSUE TITLE
Alacritty 0.4 in Ubuntu 16.04 possible?

### ISSUE THREAD

**Issue by ywpkwon** [jwilm/alacritty#3093]
I just realized that, on Ubuntu 18.04, updating packages makes Alacritty be 0.4. It's so exciting!!
I also have Ubuntu 16.04 machines. Is it possible to try Alacritty in Ubuntu 16.04?

**Comment by chrisduerr** [comment]
Have you tried it? The Ubuntu PPA is not provided by Alacritty, but instead by a maintainer of System76 (PoP_OS!).

I'm not sure if any 16.04 PPAs are available, since afaik I think 16.04 is older than PoP_OS! is. Generally with an OS almost 4 years old it would probably make sense to update to 18.04, which I think is the latest LTS?

But generally if the PPA is not available on 16.04, there's likely no interest from @mmstick to support it.

**Comment by ywpkwon** [comment]
Okay, it makes sense. I was just wondering if I can get it simply with something like `apt install alacritty`. It's okay even if not. I'm enjoying v0.4 in Ubuntu 18.04. (Since I had opacity bug with v0.3.3 in Ubuntu and was waiting for v0.4. It seems gone now! Nice and Thanks!)
