### ISSUE TITLE
Unicode \ue795 not rendering as expected

### ISSUE THREAD

**Issue by tuberry** [jwilm/alacritty#3099]
For bug reports, the following information can help speed up the process. Please describe the bug that you have found and what you would expect to happen instead.

### System

OS:Arch Linux
Version: 0.4.0
Linux/BSD: X11

### Logs

Font/Terminal size: Hack 16 / 75x100

### Steps to reproduce 
`echo \ue795` in alacritty:
![ala](https://user-images.githubusercontent.com/17917040/70836982-0bead880-1e3d-11ea-83dd-3c6507702108.png)

### Expectant result (gnome-terminal) 
![gt](https://user-images.githubusercontent.com/17917040/70837045-3b014a00-1e3d-11ea-85e8-ff98b29d1455.png)

**Comment by cole-h** [comment]
Most likely a font problem. Displays just fine for me.

![image](https://user-images.githubusercontent.com/28582702/70840663-a230e700-1dc8-11ea-82a2-5d081ebd0ead.png)

**Comment by chrisduerr** [comment]
As @cole-h has already pointed out, this is likely a font problem, since the glyph itself is very likely to be rendered correctly when the font is found.

If this works in other terminals, you might want to follow #1560, which aims to track down some differences with fontconfig fallback between Alacritty and other applications.

Generally playing with your fontconfig and setting the order of fonts up correctly will likely help in this case though.

**Comment by tuberry** [comment]
Hi, it works with a patched font(`DroidSansMono Nerd Font`) but not font fallback (`ttf-nerd-fonts-symbols`). Just in case if it can help.
