### ISSUE TITLE
Overlapping glyphs

### ISSUE THREAD

**Issue by tmccombs** [jwilm/alacritty#3172]
Some glyphs overlap other glyphs when rendered. I think these glyphs are coming from a fallback font that might not be monotype (I'm pretty sure it is coming from fontawesome free 5). I know alacritty "doesn't support' non-monospace fonts, but I think it could handle this situation better than it does. Specifically, I think it would be better if alacritty either:
1. Detected that the glyph was too wide, and rendered it in a double cell, similar to how it appears to handle some other characters, such as emoji (I'm guessing currently it is using the unicode range to determine this, and since the character is in the "private-use" range, it doesn't know it should be double-width).
2. Scale the glyph down so it fits inside a single cell.

For example:

![image](https://user-images.githubusercontent.com/2541726/72054182-b7911800-3285-11ea-8dff-454e1a1562ab.png)

There is a closing quote after the icon in the screenshot.

### System

OS: Linux
Version: alacritty 0.4.0
Linux/BSD: Wayland, sway

### Logs
Font/Terminal size: `alacritty -vv`
```
[2020-01-09 02:25] [DEBUG] Estimated DPR: 1
[2020-01-09 02:25] [DEBUG] Estimated Cell Size: 9 x 18
[2020-01-09 02:25] [DEBUG] Estimated Dimensions: None
[2020-01-09 02:25] [INFO] Device pixel ratio: 1
[2020-01-09 02:25] [INFO] Initializing glyph cache...
[2020-01-09 02:25] [INFO] ... finished initializing glyph cache in 0.061340881s
[2020-01-09 02:25] [INFO] Cell Size: 9 x 18
[2020-01-09 02:25] [INFO] Padding: 0 x 0
[2020-01-09 02:25] [INFO] Width: 800, Height: 600
[2020-01-09 02:25] [INFO] PTY Dimensions: Line(33) x Column(88)
[2020-01-09 02:25] [INFO] Initialisation complete
[2020-01-09 02:25] [DEBUG] New num_cols is 213 and num_lines is 63
[2020-01-09 02:25] [INFO] Width: 1920, Height: 1149
```

I'm happy to see the great progress alacritty has made. It's just a few little font rendering glitches like this that are preventing me from switching over to it completely.

**Comment by kchibisov** [comment]
>Some glyphs overlap other glyphs when rendered. I think these glyphs are coming from a fallback font that might not be monotype (I'm pretty sure it is coming from fontawesome free 5). I know alacritty "doesn't support' non-monospace fonts, but I think it could handle this situation better than it does. Specifically, I think it would be better if alacritty either:

They could be monospace, and the font you're showing is likely just full-width(which is fine), however such glyphs are likely have width 1 according to wcwidth, so alacritty must rendrer them as 1 cell-width glyphs, we can't do anything here and speculate chars width by ourself.

>Detected that the glyph was too wide, and rendered it in a double cell, similar to how it appears to handle some other characters, such as emoji (I'm guessing currently it is using the unicode range to determine this, and since the character is in the "private-use" range, it doesn't know it should be double-width).

**You are not allowed to do that as a terminal emulator**, you can't just change width of unicode characters by yourself. it'll break everything if we try to do that, so that is not an option and wont be implemented.


>Scale the glyph down so it fits inside a single cell.

This is the only option alacritty *can* do, however you'll have such glyphs extra small and barely visible. We've touched this question(and I've even implemented it, the glyphs just look bad tbh) at some point in the past and decided that overlapping is fine, since it's just a matter of time when wcwidth evolved and most terminal emulators, I'm aware of, a doing the same thing here as alacritty, so if alacritty decides to overlap a bit then the world wont break tbh and we're doing already for a long time.

I personally don't want to downsample glyphs for multiple reasons. 1 - it'll break some emojis (they will be too tiny and you really don't wont it), 2 - they'll be looking way worse than right now in general due to imperfect downsampling, 3 - You have an option to use a monospace font for such glyphs, so not a big deal.

If you want to see how downsampled glyphs looks like take a look on the thing windows terminal is doing [here](https://github.com/jwilm/alacritty/pull/3127#issuecomment-569405803). They also don't like it and want to remove the thing IIRC, however it could be other bug from their side, but downsampled glyphs will look like that (I don't have a screenshot from alacritty, since I was experimenting with it while implementing linux emojis).

P.s. 
If you really want to solve overlapping you can use a proper monospace font for such things instead of whatever you have. I mean there are monospace variants of font awesome in [nerd-fonts](https://github.com/ryanoasis/nerd-fonts/releases) for example.

**Comment by chrisduerr** [comment]
> I know alacritty "doesn't support' non-monospace fonts

Kchibisov has already pointed out many of the reasons *why* we do not support proportional fonts, but it seems like you're already aware that we don't.

This has not changed and the behavior you've been describing has been considered in that decision.

**Comment by nixpulvis** [comment]
I feel like this kind of issue is part of my motivation for being able to tell Alacritty to ignore fontconfig altogether. Unless there's a relatively straightforward way to configure it to **only** match, specific fonts I've explicitly added, and know to be monospace.

I personally would rather see a replacement character than something improperly overlapping.

**Comment by chrisduerr** [comment]
That sounds like an issue between you and fontconfig, rather than you and Alacritty though.

Patching Alacritty to work around problems with the system font configuration seems like a surefire way to create a big mess. If you dislike the default font configuration of a system, maybe you should consider addressing the issue on that level?

> On my system right now, fc-match -s "monospace" | wc -l shows 140 font matches!

It's 8 on mine. Maybe you're just making life unnecessarily hard on fontconfig?

**Comment by tmccombs** [comment]
> If you really want to solve overlapping you can use a proper monospace font for such things instead of whatever you have. I mean there are monospace variants of font awesome in nerd-fonts for example.

I tried using the Hack Nerd fonts. Fontawesome icons don't overlap as much, "⚙" still does overlap a little bit though, but I think that is still because it is falling back to another font, in this case DejaVu Sans, which is not a monospace font.  However, it appears that the font did scale down icons, so as @kchibisov  mentioned, they don't look great. Still, IMO better than overlapping, but not ideal.

For "⚙", I even tried  changing fontconfig to  fallback to another monospaced font that contained the glyph (DejaVu Sans Mono), but it still overlaps. I'm guessing because the font-width is different for the fallback font than the main font.  

> however such glyphs are likely have width 1 according to wcwidth

> You are not allowed to do that as a terminal emulator, you can't just change width of unicode characters by yourself. it'll break everything if we try to do that, so that is not an option and wont be implemented.

Ok, I guess that makes sense in general. But for the private use area, the result from wcwidth doesn't really make sense, since the width of the glyph is very much dependent on the font face (since it could be anything). Maybe in that case alacritty could use some heuristic to determine the column width? If that's more work than it's worth I totally understand, just throwing out ideas.

> Kchibisov has already pointed out many of the reasons why we do not support proportional fonts

Out of curiosity, where are these reasons stated?

Also, maybe it would be good to have an FAQ or something that explains why alacritty has these issues, and how to deal with them (using nerd fonts, fontconfig, etc.) I would be willing to help write such documentation.

**Comment by chrisduerr** [comment]
> Maybe in that case alacritty could use some heuristic to determine the column width?

There is exactly 0 freedom for picking column width. If you do not match wcwidth, you **will** break things. If you make a monospaced font that uses the private use area, you have to constrain yourself to its column width.

**Comment by kchibisov** [comment]
>Also, maybe it would be good to have an FAQ or something that explains why alacritty has these issues, and how to deal with them (using nerd fonts, fontconfig, etc.) I would be willing to help write such documentation.

FWIW it's not only alacritty, it's mostly all terminal emulators, and no one besides you complained about this so far, so I don't think that we should document a **common** behavior for terminal emulators.

**Comment by kchibisov** [comment]
>I tried using the Hack Nerd fonts. Fontawesome icons don't overlap as much, "⚙" still does overlap a little bit though, but I think that is still because it is falling back to another font, in this case DejaVu Sans, which is not a monospace font. However, it appears that the font did scale down icons, so as @kchibisov mentioned, they don't look great. Still, IMO better than overlapping, but not ideal.

This is a user preference, for me the thing you've linked is a `gear` emoji and I don't want to see it downscaled in alacritty to be 1 cell width. A screenshot from my alacritty.

![picture](https://user-images.githubusercontent.com/27620401/72156930-c253c600-33c7-11ea-927a-44bd6c1aa330.png)

**Comment by yech1990** [comment]
I am not sure whether it is bug that relative issue, noto-color-emoji fonts are shown in half-width instead of full-width, in Alacritty.

![image](https://user-images.githubusercontent.com/5415510/76141999-419e0700-60a4-11ea-8202-727b8567072d.png)

while full width fonts are rendered properly
![image](https://user-images.githubusercontent.com/5415510/76142041-d56fd300-60a4-11ea-9aa9-7473ac30d168.png)


```
$ uname -a
Linux YC-PC 5.5.8-arch1-1 #1 SMP PREEMPT Fri, 06 Mar 2020 00:57:33 +0000 x86_64 GNU/Linux
$ alacritty -V
alacritty 0.4.1
```

**Comment by tmccombs** [comment]
Well, in that case there is a space after it. If there is a closing double quote  after it, it is illegible.

**Comment by itsfarseen** [comment]
@tmccombs I experienced this issue using while Iosevka + Nerd Fonts installed. The fix was to switch to the "Fixed" or "Term" variant of Iosevka. 

They both resize all glyphs to fit in the monospaced cell.
The "Fixed" variant also remove all ligatures, while the "Term" variant has them. That's the only difference between them.

Not sure if this option is
 there for other fonts as well.

**Comment by qrockz** [comment]
2024 and still not fixed....

**Comment by qrockz** [comment]
> overlapping glyphs can't be fixed without cutting and no one wants their glyphs to be cut, because it doesn't make any sense, and also, no library/app does that.

Why does Kitty handle it better?

**Comment by kchibisov** [comment]
I mean you have option to make glyphs _smaller_ and try to _fit_ them into cell, they won't look consistent, but whatever. There's also builtin fonts which try to align things (we do have them for powerline, etc).
