### ISSUE TITLE
Inner Borders like rxvt-unicode

### ISSUE THREAD

**Issue by jlneder** [jwilm/alacritty#343]
I like to know if there is a way to add inner borders aka padding like in rxvt-unicode or vte terminals with gtk.css.

**Comment by jwilm** [comment]
This is something I've been thinking about myself actually. The text currently bumps up right to the edge of the window which can be undesirable. This would likely be done through some config options rather than a CSS file.

**Comment by aperezdc** [comment]
Indeed, configuration options in the existing `alacritty.yml` file should be perfectly fine. I guess @jlneder just mentioned that VTE-based terminals can be configured using GTK+'s CSS mechanism as an example :wink:

**Comment by brandur** [comment]
Just to throw an alternative out there: is it possible that rather than inner padding/borders, most people would probably just be satisfied with a good default? Looking at my main terminal (iTerm2), rather than support a padding concept it seems to just choose a padding that's proportional to my current font size. It looks great, and I wouldn't ever have to the desire to tweak it further.

Totally agreed that Alacritty's current behavior of bumping text right up to the edge isn't desirable, but a default padding proportional to your font size might be a "good enough" alternate solution that doesn't introduce more configuration overhead.

**Comment by jwilm** [comment]
> Just to throw an alternative out there ... satisfied with a good default?

I like this proposal. Any thoughts from the folks who filed the issue?

**Comment by CrashyBang** [comment]
How difficult would it be to have a sensible default that is also able to be overridden?

**Comment by jwilm** [comment]
Not hard at all, it's just more code

**Comment by OJFord** [comment]
I was about to open a semi-duplicate but as a bug report - on macOS and when full-screened, it's not just against the edge but actually clipped:

I've had this issue before, I think macOS does just blend apps into the edge of the bezel when full-screen...

I mention this here now because unfortunately (it suggests to me, at least) a good default may be less satisfying/good in all cases, since what looks good to someone typically using alacritty full-screen on a Mac will be different to what looks good not-full-screen on a Mac, or probably regardless of size on other platforms.

Otherwise, I'd have been 👍 for just have a good default; I think it's great that the project has that attitude in general.

**Comment by lord-re** [comment]
I also have the same issue of the last line being half offscreen on linux using i3.

**Comment by aperezdc** [comment]
Something that sounds reasonable as a good default is using *one third of the width of a character cell* for the inner padding, based on a bit of testing by modifying a screen capture in GIMP — note that there's a 2px blue border from the window manager:

![term-with-padding](https://cloud.githubusercontent.com/assets/723451/23631403/04cf862a-02c7-11e7-9f71-7d8915beed0d.png)

**Comment by OliverUv** [comment]
Please make this configurable. I absolutely prefer to conserve as much window real estate for content as possible. I assume many others also prefer this for laptops and other constrained environments.

Thanks.

**Comment by jwilm** [comment]
This feature was implemented a while ago. Configuration for padding is at the top level of the config file. Example:

```yaml
# Adds this many blank pixels of padding around the window
#
# Units are physical pixels; this is not DPI aware. Fractional pixels will be
# truncated.
padding:
  x: 3
  y: 3
```
