### ISSUE TITLE
FreeBSD is not linux

### ISSUE THREAD

**Issue by SoniEx2** [jwilm/alacritty#367]
Why's FreeBSD listed as a linux distro on the README?

**Comment by jwilm** [comment]
The README has grown pretty organically over time. I'm sure that when it was added, the section just wasn't renamed appropriately.

By the way, the tone in your issue comes across as confrontational. A simple "you might want to update the section header.." in the README would've sufficed.

Anyway, thanks for the heads up.

**Comment by SoniEx2** [comment]
Sorry, I originally intended this as a sort of joke issue.

It's kind of a meme to say FreeBSD is a linux distro - the "not linux" distro. Sorry for sounding confrontational.
