### ISSUE TITLE
Control D not exiting alacritty

### ISSUE THREAD

**Issue by michelboaventura** [jwilm/alacritty#422]
This seems to be a regression caused by https://github.com/jwilm/alacritty/pull/419. Before my PR I could type Control + D and alacritty would happily quit. Now it just hangs and waits for any event to quit. The event could be anything, like lose focus, key press, mouse click, etc.

**Comment by Elronnd** [comment]
I can reproduce.

**Comment by jwilm** [comment]
Getting this as well

**Comment by jwilm** [comment]
@michelboaventura Your Glutin patch included this:

```diff
diff --git a/src/api/x11/window.rs b/src/api/x11/window.rs
index 48c022f..45af18f 100644
--- a/src/api/x11/window.rs
+++ b/src/api/x11/window.rs
@@ -240,7 +240,7 @@ impl<'a> Iterator for PollEventsIterator<'a> {
                     return Some(Refresh);
                 },
-                ffi::KeyPress | ffi::KeyRelease => {
+                ffi::KeyPress => {
                     let mut event: &mut ffi::XKeyEvent = unsafe { mem::transmute(&mut xev) };
                     let events = self.window.input_handler.lock().unwrap().translate_key_event(&mut event);
                     for event in events {
```

This looks like it will prevent KeyRelease events from ever being sent. I think `translate_key_event` should still be called in this case, but is should just not attempt to run `Xutf8LookupString`. I've pushed [a patch]( https://github.com/jwilm/glutin/commit/cc64178d39a1fa06b2c5403117e5e0ef24deeac4) to my glutin fork which implements this. Would you mind checking that dead keys are still only printed once?

Incidentally, this doesn't actually fix the bug where the shell exiting doesn't immediately close Alacritty. The bug is worked around by receiving a KeyRelease event. In any case, I think this implementation might be more correct for glutin/winit.

**Comment by michelboaventura** [comment]
Dead keys still work. Thanks!

@jwilm, is there a way to compile alacritty faster? If i change a single line of code and run ``cargo build`` it takes 147 seconds to compile!
