### ISSUE TITLE
Numpad PgUp,PgDn,Home,End

### ISSUE THREAD

**Issue by E100Beta** [jwilm/alacritty#428]
Tried this terminal yesterday, immediately fell in love.
One usability issue I have is that some keys residing on numpad don't work in Alacritty (normal PgUp,PgDn,Home,End keys are farther away then numpad ones on my keyboard).
As I understand there is already code for it in, for example,
https://github.com/tomaka/winit/blob/9e404f2fe6572306f0e84c3fb7102e2206e66275/src/api/x11/events.rs#L76
that just needs uncommenting (and adding to enum) for these keys to start working.
Is there some issue with why these keys would be commented out, or is it okay if I propose it there?
I apologize if it's a trivial question, I am a newbie and not yet sure how things work around here.

**Edit:** Well, I compiled and briefly tried what I said above, and it seem to not return key release events, so maybe it's not _that_ easy.
I should've pobably asked in winit repo to begin with, sorry. Should I close this, or leave it open to later use it for tracking adding these keys to config after this is resolved in winit? If there are no other issues, of course.

**Comment by valff** [comment]
Any updates to this? My keyboard doesn't even have regular PgUp, PgDn, Home, End, only a numpad.

**Comment by Diagonactic** [comment]
Greetings!

I had/have the same problem, though, for me, the numpad keys only *really* work exactly as I expect them to in the default Konsole (I'm on OpenSUSE / KDE).  In my case, only Konsole from openSUSE behaved properly with regard to the keypad when NumLock was disabled, though, alacritty was the only terminal that simply ignored the keypresses -- the others would act as though I pressed a completely different key.

Bear with me - I'm niave when it comes to X -- my typical linux work involves SSH/terminal via Win/Mac.  Only recently did I start using openSUSE/KDE full time.

To fix the issue, I used `xmodmap` with an `.Xmodmap` file to remap the numpad keys to a working mapping.  Since I have *no clue* how to write a proper `.Xmodmap` file, I grabbed an ancient utility called `xkeycaps`, which gave me a GUI to assist in its generation.  Unfortunately, some of the keys I pressed weren't recognized by the program, but I was then able to edit the `.Xmodmap` file and it helpfully had lines with `KP_Home`, `KP_End` in the format of `keycode 0xXX = KP_End    KP_1    KP_End    KP_1`.  I simply removed the `KP_` from the `KP_End` in both cases (actually, for most I also replaced the first `KP_1` with `NoSymbol` and removed the last `KP_1` because I never use it with NumLock enabled on purpose).

After saving and manually tweaking the file, I created a script that called `xmodmap ~/.Xmodmap` which runs when I login (and added it to my `.zshrc` for good measure).  All is well in _every_ terminal, now.

If you're using openSUSE, `xkeycaps` is in the OSS repository for Tumbleweed so a simple `zypper in -y xkeycaps && xkeycaps` is all that's needed to install/launch.  Otherwise, check your distro's repos or get it [here](https://www.jwz.org/xkeycaps/).  

Or, if you actually know something about X, such as how to get the correct keycode for the key (I tried `showkey` for scan codes and key codes but when I looked at the records in the .Xmodmap file that I had for _working_ remappings, I didn't find any correlation between the output of `showkey` and the `keycode 0xXX ...` line; though I'll admit that I spent about a minute investigating that after a couple of days of running around wrapping presents and not getting enough sleep, so the possibility of a silly mistake having been made in those visual correlations is pretty high).

Here are the lines from my .Xmodmap file that relate to those keys (I'm not even slightly confident that you could take these lines and use this verbatim on anything other than the specific model of laptop -- with it's odd keyboard -- that I'm using, but I'm providing it here as an example in case you want to poke at it):

```
keycode 0x6E =  Home    NoSymbol        Home
keycode 0x4F =  Home    NoSymbol        Home
keycode 0x57 =  End     NoSymbol        End
keycode 0x73 =  End     NoSymbol        End
keycode 0x6F =  Up      NoSymbol        Up
keycode 0x50 =  Up      NoSymbol        Up
keycode 0x58 =  Down    NoSymbol        Down
keycode 0x74 =  Down    NoSymbol        Down
keycode 0x53 =  Left    NoSymbol        Left
keycode 0x55 =  Right   NoSymbol        Right
keycode 0x71 =  Left    NoSymbol        Left
keycode 0x70 =  Prior   NoSymbol        Prior
keycode 0x51 =  Prior   NoSymbol        Prior
keycode 0x59 =  Next    NoSymbol        Next
keycode 0x75 =  Next    NoSymbol        Next
```
(Prior/Next are PgUp/PgDn, evidently)

**Comment by michalrus** [comment]
Ahhhhhhhhhh, what a nice idea to remap `KpPrior→Prior` and similar. ♥ Thank you. So obvious rn!

**Comment by howdoicomputer** [comment]
huh

I'm experiencing the same issue. I might try the above work around sometime in the future.

**Comment by chrisduerr** [comment]
The remaining issues with this will be fixed by https://github.com/tomaka/winit/pull/805.

**Comment by Kinmarui** [comment]
since it's been merged there are there any plans to include this fix in next release?

**Comment by kchibisov** [comment]
This fix is included in `v0.3.3`

**Comment by Kinmarui** [comment]
I on `v0.3.3` and when I press `PgUp` error sound is player and for `PgDown` error sound is played and I'm getting ~~ signs written in console. Although I just discovered that both of then works in Alacritty when I'm holding `shift`

**Comment by chrisduerr** [comment]
@Kinmarui The PageUp and PageDown buttons are bound to send escape sequences to the applications running inside of Alacritty by default. If your shell (or whatever application you're running) does not currently allow scrolling or if the escape is not supported at all, the bell will be rung.

The shift bindings however aren't bound to send any escape sequences, instead they just scroll Alacritty's scrollback directly without a roundtrip to the application running inside of Alacritty, so they'll always work assuming that you have native scrollback available (opposed to something like tmux scrollback).

So that's why you're experiencing this and it sounds like things are working exactly as they're supposed to.

@kchibisov Thanks for the update, closing this issue as resolved.
