### ISSUE TITLE
Building on windows: servo-fontconfig-sys: file not found

### ISSUE THREAD

**Issue by TyOverby** [jwilm/alacritty#435]
```
$ cargo build
   Compiling servo-fontconfig-sys v2.11.3 (https://github.com/jwilm/libfontconfig#618a5297)
error: failed to run custom build command for `servo-fontconfig-sys v2.11.3 (https://github.com/jwilm/libfontconfig#618a5297)`
process didn't exit successfully: `C:\Users\tyoverby\workspace\alacritty\target\debug\build\servo-fontconfig-sys-68ad2970a58a11c5\build-script-build` (exit code: 101)
```

**Comment by jwilm** [comment]
Thanks for filing an issue!

Unfortunately, windows is not yet supported. Please subscribe to #28 for updates.

**Comment by TyOverby** [comment]
Sorry about that, I should have written a bit more in the issue.

I actually work at Microsoft and would really like to see alacritty working on Windows.  I filed these bugs so that I could start working on getting them working on my own box.

**Comment by jwilm** [comment]
Interesting! Since you seem interested in moving this forward, let me share a couple thoughts I've had about the subject with you.

* Alacritty will run as a native windows application outside the WSL. Will need to update the `font` crate to support `ClearType` and whatever the font locator system is on windows. The clipboard library `copypasta` will also need some attention.
* Alacritty should use bash.exe to start /bin/bash. Not sure how this will work; I don't know enough about it yet. Hopefully there's a way to get bash.exe to provide the raw escape sequences from /bin/bash.

Regarding the issues you filed,
* servo-fontconfig-sys not found. We shouldn't be trying to load this at all if we are using ClearType and the Windows font locator. Maybe using FreeType and fontconfig is a nice shortcut though.
* Glutin clear_context not implemented. We ended up not using this feature at all, and it could be removed from the fork. The missing part at this point would be support for modifier keys.

Please let me know if there's anything I can do to help you!

**Comment by TyOverby** [comment]
Why does alacritty maintain a glutin fork?

**Comment by jwilm** [comment]
Only because our changes haven't been upstreamed. There's a PR in progress for modifier keys, and there's an open issue for including characters with the KeyboardInput event. Hopefully we'll be able to switch back to the main tree at the next release of winit.

**Comment by TyOverby** [comment]
Would it be possible to swap out `servo-fontconfig` for the (`font_loader`)[https://docs.rs/font-loader/0.1.4/font_loader/] crate?  Looks like `servo-fontconfig` uses GDI on windows, `core-text` on OSX, and `fontconfig` on Linux.

**Comment by jwilm** [comment]
I'd rather not replace the font loading code we have already. That crate looks pretty young, and it can be a struggle to get patches accepted sometimes. The only advantage I see at the moment is it already wraps GDI.

**Comment by TyOverby** [comment]
My plan was to fork the library and contribute upstream when convenient.  Also, I was planning on using it just for font discovery rather than replacing the entire loading phase.

Yeah, the benefit of a library like this is that it exposes a single API that happens to be backed by multiple fairly-complex implementations.

**Comment by jwilm** [comment]
If you want to bring it in just for pathfinding on Windows, that's probably fine. The `font` crate we have internally is already a cross-platform API for loading/rasterizing fonts, and I don't intend to replace it with a third party component.

I would plan (not necessarily you, just generally) to add our own GDI bindings at some point in the future to remove the font_loader dependency.

**Comment by qmx** [comment]
@jwilm if you want to avoid adding font_loader, can't we just "lift" (with proper attribution, of course) the GDI code from there and implement on the font crate?
