### ISSUE TITLE
Alacritty is not associated to its .desktop-defined icon due to non-matching WM_CLASS

### ISSUE THREAD

**Issue by ronjouch** [jwilm/alacritty#455]
1. Build Alacritty under Ubuntu 16.04.2, and deploy the .desktop
2. Launch Alacritty
3. Alt-Tab

***Expected***: the icon defined in the `.desktop` file should show up in the switcher

***Actual***: the default "missing icon" Ubuntu-provided question mark shows up instead

## Cause

As [encountered by other apps](https://github.com/aseprite/aseprite/issues/846), this seems to be due to the fact that Alacritty's `WM_CLASS` is `Alacritty`, which totally freaks out whatever-piece-of-ubuntuware-doing-window-to-.desktop-matching, failing to match `alacritty`.

```bash
~ xprop
WM_NAME(STRING) = "ronj"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
                program specified size: 1024 by 768
WM_CLASS(STRING) = "Alacritty", "Alacritty"
_NET_FRAME_EXTENTS(CARDINAL) = 0, 0, 28, 0
WM_STATE(WM_STATE):
                window state: Normal
                icon window: 0x0
...
```

## Workaround

Add `StartupWMClass=Alacritty` to the `.desktop` file. Tested, working for me.

## Better solution?

Maybe make `WM_CLASS` equal to `alacritty` ? I'm not sure; was there a strong reason for the capitalization?

**Comment by brycefisher** [comment]
@ronjouch would this address #330 and #348 (partially)?

**Comment by jwilm** [comment]
I actually have a patch for setting wm_class separately, but I decided against it since it's already set by the title. Should we set wm_class independently? Seems like that workaround would be fine.

**Comment by ronjouch** [comment]
> would this address #330 and #348 (partially)?
>
> EDIT: Confirmed! Adding `StartupWMClass=Alacritty` to the end of my Alacritty.desktop file and saving it immediately fixes the icon issues mentioned in #330 without even restarting the process for me on Ubuntu 16.10. Commenting out that line and restarting alacritty #330 occurs again.

@brycefisher I confirm too it fixes #330 (just tested under Ubuntu 16.04.2). I doubt it fixes #348 though, as setting `StartupWMClass` has no impact on what `xprop` says about the Alacritty window (no x property of the window ends up mutated, it is only like a *read*-time level of indirection used by window matching logic).

> I actually have a patch for setting `wm_class separately`, but I decided against it since it's already set by the title. Should we set `wm_class` independently? Seems like that workaround would be fine.

@jwilm workaround sounds fine yeah; your call, you probably know more about me about this wm stuff to judge what's best.

**Comment by brycefisher** [comment]
@jwilm I'd vote to include `StartupWMClass=Alacritty` in the .desktop file for now and create an issue to refactor later (if desired). I'm happy to open a PR for that one line change.

**Comment by jwilm** [comment]
Sounds good @brycefisher. Thanks!

**Comment by Iambecomeroot** [comment]
I am still getting a blanc icon. Any suggestions?

**Comment by francesca64** [comment]
`.desktop` files will probably work more reliably once winit implements the [startup notification protocol](https://specifications.freedesktop.org/startup-notification-spec/startup-notification-0.1.txt), though I haven't been able to verify that yet.

**Comment by francesca64** [comment]
Okay, startup notification doesn't seem to make a difference. I did figure some other stuff out, though.

Tips:
- Always install `.desktop` files to `/usr/local/share/applications` rather than `~/.local/share/applications`, since the latter isn't always searched.
- Be sure to delete any existing `Alacritty.desktop` from `~/.local/share/applications`, since somehow it didn't work until after I did that.
- The `.desktop` filename should be the same as the binary filename, so `alacritty.desktop`.

Following that, the icon shows up correctly for me now.

**Comment by chrisduerr** [comment]
@francesca64 I don't use `.desktop` files, but do you think it would make sense to put these tips into the `README` maybe?

If you think it makes sense and have the time to open a PR, I'd welcome it very much. :)

**Comment by francesca64** [comment]
@chrisduerr yeah, I'll be able to do that, though I'm not done researching the problem yet. It's unfortunately tricky, since there are heuristics in place that make it hard to tell when we're doing something incorrectly.

I've got it working perfectly with my own application, but for some reason Alacritty only wants to show up in `latte-dock` and `cairo-dock`, and not in `plank`. It's not a big deal though, so I'll submit a PR even if I don't figure that out.

Installing `.desktop` files manually seems to be a bad idea. Detection worked more reliably once I switched to using the utils:
```bash
sudo desktop-file-install alacritty.desktop
sudo update-desktop-database
```
