### ISSUE TITLE
Some characters are skipped when alacritty is forced to redraw quickly

### ISSUE THREAD

**Issue by Flat** [jwilm/alacritty#546]
Alacritty sometimes misses drawing characters, and sometimes as the incorrect color.

Steps to reproduce:

1. launch ncmpcpp and play a track.
2. switch to the visualizer "frequency spectrum"

Video: https://my.mixtape.moe/yktkrn.webm
Top term is alacritty, bottom xfce4-terminal

alacritty also appears to incorrectly draw the seek bar.

**Comment by maximbaz** [comment]
I wonder if the root cause here is the same as in #540, which is currently assumed to be a race condition 🤔

**Comment by DarkDefender** [comment]
@Flat could you try to do `export NCURSES_NO_HARD_TABS=1` before running ncmpcpp and see if that helps?

**Comment by Flat** [comment]
@DarkDefender doesn't look like that affects it at all.

**Comment by DarkDefender** [comment]
@Flat Ok, I were just wondering because @Aaron1011 and I just hunted down an other drawing bug that was caused by alacritty using xterm terminfo: https://github.com/jwilm/alacritty/pull/620

I thought that it might have been the same.

The problem that pull fixes is that the xterm terminfo reports that it supports a few features that alacritty does not support. So when terminal programs tries to use those features, things go wrong.

You could try to switch around `$TERM` to something else than xterm (like rxvt, screen, tmux etc) and see if that fixes it. If you know your way around terminfo stuff, you could try to remove the suggested entries listed here and see if it helps:
https://github.com/gittup/ncurses/blob/5a58bcb99470378fbbb24d21cb5e54f08cb7d353/ncurses/tty/lib_mvcur.c#L65

If none of that helps, then I guess this might not be terminfo related.

**Comment by HorselessHorseman** [comment]
The same problem also occurs when running Catalysm-DDA, which uses ncurses. If you open crafting menu and switch tabs, almost nothing is redrawn.

**Comment by DarkDefender** [comment]
@HorselessHorseman Are you running mac?  I just tried Catalysm-DDA and it seem to work fine in the crafting menu for me. I'm running linux though...

This seems to be a hard issue to track down as not everyone seems to have this redraw problem.

**Comment by HorselessHorseman** [comment]
@DarkDefender Nope, it's Ubuntu Lts. I tried running it with DRI_PRIME=1 and the issue seems to be gone, but now there are some new less annoying artifacts.

**Comment by DarkDefender** [comment]
Maybe this will be solved by using a newer mesa version? I'm using radeonsi (AMD) mesa drivers. It could also be a intel specific problem...

**Comment by Flat** [comment]
Using the latest commit this seems to have been fixed for me at some point.

**Comment by HorselessHorseman** [comment]
I gave it a try a few days ago, and it's almost perfect.
