### ISSUE TITLE
support for background images

### ISSUE THREAD

**Issue by OliverLeitner** [jwilm/alacritty#565]
hi

id love to see background image support...

something like "rxvt*pixmap: /path/to/image.jpg"

is this in the plannings?

anyways, thanks for this great approach to a new generation of terminals=)

**Comment by jwilm** [comment]
Probably not going to support this, but we do have plans for making the window translucent.

**Comment by Radagan** [comment]
I wish you would reconsider this decision. It adds a lot to a terminal window and distinguishes it from the background in a way transparency does not.

**Comment by Catman155** [comment]
I would also like this feature

**Comment by ColdSauce** [comment]
I would really love this feature, as well.

**Comment by KhaimovMR** [comment]
Same. Please reconsider.

**Comment by i30817** [comment]
It'd be rad on a login shell ;)

**Comment by chrisduerr** [comment]
Adding a background image might be something that could be reconsidered, however playing videos in the background will definitely not be. That's just too much work for a feature which is not going to be used by anyone and hardly makes much sense for a terminal emulator.

Of course some crazy ideas are fun to play around and experiment with, however I don't see something like that ever landing in Alacritty. :)

**Comment by i30817** [comment]
Depressingly conservative, as is the unix tradition.

**Comment by nixpulvis** [comment]
I wouldn't say "depressingly conservative". If Alacritty was closed source maybe... but there's nothing stopping a motivated member from adding this feature to their own fork. Don't be depressed :D

As for the goals of this community and mainline project; we are more focused on performance and minimalism, while still being a feature complete, working terminal emulator.

If the community truly wants this, I'd expect to see prototypes and forks pop up long before they are merged into master here.

Just my 2 cents.

**Comment by pencil** [comment]
@chrisduerr Would a PR for this feature be accepted?

**Comment by chrisduerr** [comment]
Honestly, I think at this point there's no way to implement this in a nice way where I'd be inclined to accept it.

It's possible that when support for something like libsixel is implemented, that it would be so trivial to implement this that it wouldn't be a lot of work to maintain, which would make it fine for me.

But generally I don't want to introduce any additional codepaths and rendering modes to support this and Alacritty currently has no way to render anything other than glyphs and rectangles.

**Comment by Cyberlane** [comment]
I am experiencing ghosting when I have the `background_opacity` set, which is why I started to look for a way to set an image on the terminal itself.

**Comment by sinistersnare** [comment]
One of the reasons for the closing of #2798 was that there wasnt enough interest in the feature.

I would like to say that I am highly interested in this feature, enough that I accidentally made a duplicate issue (#3609) for it.

Are there plans for implementing something like libsixel in Alacritty? How can this be done in a way that will be easy to maintain?

**Comment by kchibisov** [comment]
libsixel has a separate issue #910

**Comment by luisiacc** [comment]
Please add this feature, it's very valuable for some people.

**Comment by hex1028** [comment]
Please add this feature, it's very valuable for some people.

**Comment by HTG-YT** [comment]
This feature is really nice to have. Not being able to set a background image would be a massive -1 from me migrating from Windows Terminal which has out of the box support for it - but does not support bold text styles.

**Comment by arnavr23** [comment]
+1 for the background image support, I would like it as well, please reconsider,

**Comment by s-kirby** [comment]
I wanted to throw in a vote here. Would love to see this added in the future!

**Comment by chrisduerr** [comment]
"Voting" is unnecessary, this is not going to be implemented.

**Comment by butla** [comment]
I guess it'd be good to focus on [the plugin system](https://github.com/alacritty/alacritty/issues/4844), so that people can have the option for easy inclusion of "controversial" features like the background image :)

If I ever finally have some time to tinker with Rust it might implement it.
I think it'd be a nice thing to have a more bit beauty in the workplace (without too much setup hustle with opacity and some window manager scripts) to ease the mind during a whole day of staring at a somewhat colorful blob of monospace font :)

Side note: loving this project and Rust in general, wanna get more into it. Not enough time, of course.

**Comment by chrisduerr** [comment]
There's **not** going to be a plugin system in Alacritty.

**Comment by butla** [comment]
> There's **not** going to be a plugin system in Alacritty.

Ok, I respect that decision. Then maybe there should be an Alacritty fork (staying close to upstream) that will introduce just one thing - a plugin system 🙂

I'm not saying I'm gonna write it, but if someone has time, energy and skin in the game, then that could come about.

**Comment by ninjarogue** [comment]
reconsider please..

**Comment by sz47** [comment]
Is there any progress in 2022? please

**Comment by arxra** [comment]
Transparency _almost_ covers this well, but for times where there is no background being rendered from the compositor it's way worse (looking at you, fullscreen MacOS spaces where the fixis to simpy not fullscreen Alacritty or set opacity to 1).

**Comment by CodeWithAnupam** [comment]
hello everyone 

alacritty terminal background image how to apply

**Comment by binarydigitz01** [comment]
@CodeWithAnupam If you will read the reply, the devs most likely won't implement background images. If you desperately want them, I would suggest kitty terminal emulator.

**Comment by solrankos** [comment]
damn ill have to choose kitty instead... i really need a background image lol

**Comment by afonsolage** [comment]
Any chance of reconsidering it?

**Comment by ChristophSonnleitner** [comment]
I wanted to migrate from iTerm2, but no background image is a deal-breaker unfortunately.
After reading the comments here I installed kitty and it's probably the best alternative out there.

**Comment by Mattlau04** [comment]
No background image support is a dealbreaker for me too, thanks for kitty suggestion

**Comment by ThatAnonyG** [comment]
Just installed Alacritty and started configuring it. Decided to google the "how to" for image bg and stumbled upon this thread. Now Alacritty takes the "fastest app deleted" on my books.

**Comment by ThatAnonyG** [comment]
> Adding a background image might be something that could be reconsidered, however playing videos in the background will definitely not be. That's just too much work for a feature which is not going to be used by anyone and hardly makes much sense for a terminal emulator.
> 
> Of course some crazy ideas are fun to play around and experiment with, however I don't see something like that ever landing in Alacritty. :)

A lot of people takes terminals way too personally and Alacritty supporting full on videos would make for a really unique feature and would have given you guys a repo for adding stuff like this on community requests. But alas.

**Comment by tshazar** [comment]
FYI... to those in the thread, desiring background images / looping video

on OSX I added

>     - { key: F,              mods: Command|Control|Alt,        action: ToggleSimpleFullscreen}


to the "key_bindings:" of the configuration file

>     ~/.config/alacritty/alacritty.yml


this got close to the desired effect noted in the duplicate issue's screenshot

>    https://github.com/alacritty/alacritty/issues/2446


when using the desktop background and an opacity flag in the "ToggleSimpleFullscreen" 

this uses the current desktop (and preserving the background image already on the desktop) instead of creating a new desktop while full screening. 

>    window:
>        opacity: 0.8


I have even combined this with a "Dynamic Wallpaper" application that will show a looping video of your choice 
(including self-created movies)

<img width="1518" alt="image" src="https://github.com/alacritty/alacritty/assets/5994486/7e70e0fd-b8f8-4df4-a476-0a710bec0d9c">

while not a physical part of this application there are ways of creating the atmosphere discussed in this thread with both background images as well as dynamic desktops.

however, a note to the devs, a native looping video / image layer under the text layer that could be muted using the opacity layer would be an amazing feature.

While I do enjoy the "keep it stupid simple" single-focus applications sometimes unseen before cool features can really set an application apart from the crowd and hook some "influential" users.

Maby someone will be inspired to make a fork

**Comment by ahmaddynugroho** [comment]
please support background image. i can't focus without my waifu in the background staring at me

**Comment by kchibisov** [comment]
>please support background image. i can't focus without my waifu in the background staring at me

With such desire I don't think having a background image will actually solve anything. It sounds like investing in 3d figures an putting one on the desk is the thing you really want, given that you can interact with it.

**Comment by kimjisena** [comment]
background images support when?

I'd like my Terminal to look like this...it's just perfect

<img width="1792" alt="Screen Shot 2024-01-18 at 7 59 09 PM" src="https://github.com/alacritty/alacritty/assets/73499939/81129e29-c387-4fd6-95ca-bd837a2448ab">

**Comment by Blezz-tech** [comment]
I hope to see this feature someday. I can wait...

**Comment by mostepunk** [comment]
Oh common! give us background image support!

**Comment by kimjisena** [comment]
> Oh common! give us background image support!

Just switched to kitty! Works pretty well.

**Comment by joshuadanpeterson** [comment]
No background image support is a dealbreaker for me. Too bad, because I just wasted the better part of two hours configuring my alacritty.toml file only to come to this realization.

**Comment by kimjisena** [comment]
> No background image support is a dealbreaker for me. Too bad, because I just wasted the better part of two hours configuring my alacritty.toml file only to come to this realization.

I feel you! Give [kitty](https://sw.kovidgoyal.net/kitty/) a try, haven't regretted since I permanently switched.

**Comment by Aritheme** [comment]
reconsider please..

**Comment by geraldaddey** [comment]
Please add a custom background feature.

**Comment by hendrikmi** [comment]
Just downloaded Alacritty to switch from Kitty, but the lack of a background image feature is a dealbreaker. I enjoy customizing my dev environment to be visually appealing. Uninstalled it again.

**Comment by djmittens** [comment]
i also came here for the waifu background, and lemme tell you, i find it ironic, that the issue was closed due to lack of popular demand, and yet i see consistent posts, getting close to a decade.

**Comment by chrisduerr** [comment]
@djmittens If there ever was a reason not to allow people to set background images, this is it.

**Comment by johan-weitner** [comment]
Text-based user interfaces does feel very 20th century, that's their nature. But I've found that a simple linear gradient background can make wonders for the feel of staring at a terminal. (Have a look at the Cyber Wave theme in the Warp terminal for example). Maybe off topic, maybe not - in CSS world they're kind of the same thing. Of course I understand that a CSS engine is not on the table. But as a concept I think it's a compromise that could go a long way. Except for the anime fans obviously. :)

Then again maybe opacity + blur accomplishes pretty much the same thing...

**Comment by erikLundstedt** [comment]
> please support background image. i can't focus without my waifu in the background staring at me
> 
> edit: for someone who still need background image. use wezterm and add this config
> 
> ```lua
> config.background = {
>     {
>         source = {
>             File = '/path/to/png'
>         },
>         hsb = { brightness = 0.02 }
>     }
> }
> ```

+1 for switching to a _**better**_ terminal overall

**Comment by paxperscientiam** [comment]
LMAO at the waifus and nsfw art

**Comment by tabuyos** [comment]
Is there any progress? I hope to see this feature.

**Comment by MoonDusk1996** [comment]
How can it have been so many years and we still don't have this? 😢

**Comment by dotintegral** [comment]
7 year later, still no support... Would love to have it though.

Truth be told, if people ask for a feature since 7 years and there is just "we do not plan to do it" as a reply, then it doesn't really gives us anything. At least tell us why, is it hard to do? You don't want to do it? Other reasons? Leaving cliffhanger like that is disheartening... 😢

**Comment by chrisduerr** [comment]
If only a maintainer had made multiple comments in the past outlining why this will **not** be implemented. :sob:

**Comment by dotintegral** [comment]
> If only a maintainer had made multiple comments in the past outlining why this will **not** be implemented. 😭

Thanks. When I saw the first post "no plans" then I kinda skimmed over other comments and did not picked up the reasoning 😅 My bad

**Comment by Obe1sance** [comment]
After 5 years I decided it was time to "upgrade" to a more modern terminal emulator. I'd been using Tilix for a long time because I loved the ability to split terminals and ofc, my terminal hosted background image with TRANSPARENCY, so I could adjust how bright/dark my background image dynamically. 

I really wanted to use Alacritty because I've heard so many good things about it; but it's just not worth sacrificing the customization features Tilix has to offer. I'm of the mind that if I'm going to stare at blue light all day burning my retinas into oblivion, it should at least be a pleasant experience to look at in doing so. 

Even though Tilix was built for X11, it works well under Wayland/Hyprland for those seeking a nice alternative. It's worth checking out.
