### ISSUE TITLE
Question: how to start alacritty from spotlight in osx?

### ISSUE THREAD

**Issue by yevhen-m** [jwilm/alacritty#584]
I can see alacritty app, but I can't start it. I see some flickering but terminal does not start.
<img width="687" alt="screen shot 2017-05-23 at 6 55 05 pm" src="https://cloud.githubusercontent.com/assets/10185058/26363362/78a0dacc-3fe9-11e7-9d5c-190aedced8e2.png">

**Comment by lpalmes** [comment]
I've had the same problem when starting, did you change the file `~/.config/alacritty/alacritty.yml`? When the file is not correct, it just open and closes given the config file is wrong.

From what i can tell you are not running the compiled app, the size is 68 kb in your screen, my alacritty terminal weighs about 3.6 mb, so maybe that's why.

You have to compile, make the app, and then copy it to your applications folder, so you can use it like a normal app. Follow this https://github.com/jwilm/alacritty/wiki/MacOS-application-bundle, and make sure you have rust compiler installed. If you need anything else let me know and i'll try to do my best to help.

**Comment by asilvadesigns** [comment]
well then... I definitely did it the hard way.
I just used Automator to call it from iTerm since I tend to use that as well.
See screenshot:
<img width="1440" alt="screen shot 2017-06-01 at 2 53 40 pm" src="https://cloud.githubusercontent.com/assets/7071307/26695819/440c7166-46da-11e7-85ba-78a50f80f283.png">

**Comment by rafi** [comment]
@yevhen-m Try setting your Alacritty config's `shell.program` and/or `shell.args`, for example mine is:
```
shell:
  program: /opt/local/bin/bash
  args:
    - --login
```

**Comment by snoblenet** [comment]
Check Spotlight is not finding the copy of the app in your build folder vs the copy that you copied to the Applications folder. This was preventing me from launching it using Alfred initially.

**Comment by evmorov** [comment]
What I usually do for updating the app:

- git checkout .
- git pull
- rustup update
- cargo build --release
- make app
- rm -rf /Applications/Alacritty.app 
- mv target/release/osx/Alacritty.app /Applications/Alacritty.app 
- rm -rf assets/osx/Alacritty.app

Spotlight and Alfred work with no problems.

**Comment by SidOfc** [comment]
I'm on macOS Mojave 10.14.2 and also faced this issue when I _symlinked_ the installation into `/Applications/Alacritty.app` instead of actually _copying_. When I removed the symlink `/Applications/Alacritty.app` and just copy the files directly, Spotlight works fine.

The homebrew formula actually instructs to use a symlink instead since a newly compiled build would replace the old one in the same location and thus the symlink would just use the new build, but it seems that symlinking into `/Applications` causes some breakage for the likes of Spotlight at least.

```plain
• ~ ❯ brew info alacritty
mscharley/homebrew/alacritty: stable 0.2.3, HEAD
A cross-platform, GPU-accelerated terminal emulator
https://github.com/jwilm/alacritty
/usr/local/Cellar/alacritty/HEAD-6b61e96 (12 files, 12.4MB) *
  Built from source on 2018-12-08 at 17:59:33
From: https://github.com/mscharley/homebrew-homebrew/blob/master/alacritty.rb
==> Dependencies
Build: cmake ✔
Required: fontconfig ✔
==> Options
--with-cache
        Use a cargo cache in /usr/local/var/cache during the build.
--HEAD
        Install HEAD version
==> Caveats
Although it is possible that the default configuration will work on your
system, you will probably end up wanting to customize it anyhow. You can
find a copy of the default configuration at:

  /usr/local/share/alacritty/alacritty_macos.yml

You can copy this file to ~/.alacritty.yml and edit as you please.

For the best experience, you should install/update alacritty's terminfo
file after each update. You can do so by running the following command:

  sudo tic -e alacritty,alacritty-direct /usr/local/share/alacritty/alacritty.info

WARNING: This formula can't install into /Applications, the application
has been installed to:

  /usr/local/Cellar/alacritty/0.2.3/Applications/Alacritty.app

This path is stable across upgrades, you can create your own symlink in
the global /Applications folder as follows:

  ln -s /usr/local/Cellar/alacritty/0.2.3/Applications/Alacritty.app /Applications/
```

So at the bottom here is the broken `ln -s` instruction. It would probably be better to clean up and just copy a new version by using `rm -rf /Applications/Alacritty.app` and then `cp -R /usr/local/Cellar/alacritty/[VERSION]/Applications/Alacritty.app /Applications/`.

In addition, what I always do before I open it using Spotlight is to actually go to the `/Applications` folder in _finder_ and launch the application from there once first.

Just my 2c for anyone who might run into this today :)
