### ISSUE TITLE
Alacritty website

### ISSUE THREAD

**Issue by asilvadesigns** [jwilm/alacritty#624]
@jwilm not sure if there are any plans for this, dev and design, but I would certainly love to join forces with anyone interested.

**Comment by EdenSG** [comment]
Same here - can contribute design and code, wherever it's needed.

**Comment by jwilm** [comment]
Love that you two are eager to contribute on that front! Getting a website up would be really great, and I would be immensely appreciative if anyone wanted to take charge of that. Since there's not been any discussion on the subject so far, we may as well make this the canonical thread for an Alacritty website.

Let me begin by sharing a few thoughts about it:

- I bought a domain, alacritty.io that can be used for the site
- Should probably use Jekyll so we can take advantage of GitHub pages
- Site should be static content and use JS only sparingly. It would be nice for the site to work on noscript browsers.
- Would be nice to get the project logo figured out before getting too much further. Work was started in #285 but it's halted.
- Need to figure out content. Initial thoughts, in no particular order:
    - Project overview
    - Contributors. I would really like a place to acknowledge everyone that has contributed to the project.
    - Configuration guide. Something that's more than just sticking in the default config file would go a long way, but that can evolve over time. For example, including a screenshot explaining a setting like `render_timer` would be very nice.
    - Pretty much everything that is in README but broken out (FAQ, how to build, etc)
    - In the future, links to builds for major platforms
    - Benchmarks, once we start publishing them
    - Version indicator at the top. I still consider the project alpha level software, and websites have a way of legitimizing things. Just want to keep user expectations reasonable.
- Design-wise, I would really enjoy a dark theme which pulls colors from the default color scheme.
- Would be nice to have all the content in a single page and just use anchors for navigation. I think Jekyll can even be configured to generate the GitHub-like link icons by each header on mouse over.
- Will probably want to add some media queries so it reads nicely on mobile and tablets.
- Should live in gh-pages branch of this repo

@asilvadesigns @EdenSG -
Are you still interested after my brain dump? :laughing: 

There's work to do on design, copy, and the actual implementation. I'd be incredibly thankful contributions on as much or as little of it as would interest you. I'm terrible at design, so would uber appreciate help there. Would also be appreciative of help on the implementation.

What do you think?

**Comment by lytedev** [comment]
I would just like to speak up for [Hugo][hugo] as the static site generator. Wicked fast, works with GitHub pages, and was a joy to work with for my use cases.


[hugo]: https://gohugo.io/

**Comment by asilvadesigns** [comment]
@jwilm sounds good! Jekyll is really nice, love working with it.

My mind immediately goes to a todo list and consequently a brain dump.
I image these items may need to get done, or should be considered:

- brainstorm
  - includes your content above.
  - links to sites or brands you're inspired by.
  - target audience
  - social medias, if any
- content
  - site-map
  - determine content/visual hierarchies etc
  - user flows... probably overkill here
- design
  - logo/brand etc
  - typography
  - imagery
  - ux/wireframing.. also probably overkill
- dev
  - cms, or best way to maintain long-term-ish.. perhaps overkill now
  - tabs vs spaces <-- joke joking just joking, joke. (cough, tabs as spaces)..
- miscellaneous
  - assuming github for dev n host, cname to domain..
  - content collabs on google doc or something?

As a priority, I can't help but desire a todo list, Google docs much...?

Okay I'll stop, just wanted to throw those out there for discussion.

**Comment by EdenSG** [comment]
@asilvadesigns yes, that all sounds good! Some thoughts:

- perhaps it'd be worth using a separate repo for the website, so that the issue tracker and project board don't have to be shared with the main project
- i don't *think* we need much in terms of a cms, unless you'd like to blog about alacritty or something 👀 
- it'd be nice to come up with a colour scheme to use... i can't say i'm a *huge* fan of tomorrow night bright, but i can work with it
- pages i was thinking might be useful to have:
  - **homepage**: would have a nice screenshot of alacritty (maybe a gif/silent repeating video?), basic info about what it is, build status and links to download binaries (if/when that happens) — more or less the about section of the current readme (and maybe an faq as well)
  - **download/install page**: links to builds, and info on building and installing manually
  - **docs**: info about the config files (perhaps the above page and this one could be integrated into a single page? idk). could also have the faq section from the readme
- design-wise i'm pretty flexible. i can sketch up some ideas, if you like

Google doc (or maybe trello?) does sound good haha... this could quickly get out of hand

**Comment by asilvadesigns** [comment]
@EdenSG awesome. I'll get to doodling as well.
@jwilm do you have a repo for this project?

Regarding color scheme, I think @jwilm mentioned he would like to use the original color palette, which I think is found in the alacritty.yml..?

Those pages to start sound good, let's setup the google docs, and put all the goodies in there, site-map included.

@jwilm do you mind creating a folder on Gdrive and adding us in there. That is unless you prefer a different way, I just don't want to assume anything by default, seems proper that you pave the way since you're the main dude.

pretty stoked for this.

**Comment by jwilm** [comment]
@asilvadesigns @EdenSG I've invited you both to a google docs folder and an alacritty.io project.

It probably makes sense to move this discussion over to the new project's issue tracker.

> pretty stoked for this.

 Me too :smile: 

> i don't think we need much in terms of a cms, unless you'd like to blog about alacritty or something

Jekyll is basically a CMS for static sites--should be more than sufficient.

> typography

Please use system fonts. I'm not a fan of having to pull in 1MB worth of font dependencies for every page load.

**Comment by EdenSG** [comment]
+1 for system fonts. Definitely the way to go. We can use the same font stack that Github uses.

**Comment by jwilm** [comment]
>  We can use the same font stack that Github uses.

:100:

**Comment by jwilm** [comment]
Going to close the issue; let's move discussion to the alacritty.io tracker.

**Comment by gmile** [comment]
@jwilm alacritty.io – a tracker for this is not public? otherwise could you share a link please?

**Comment by polyzen** [comment]
https://github.com/jwilm/alacritty.io
