### ISSUE TITLE
Update README regarding alpha-readiness

### ISSUE THREAD

**Issue by twe4ked** [jwilm/alacritty#636]
> This initial release should be considered to be pre-alpha software--it will have issues. Once Alacritty reaches an alpha level of readiness, precompiled binaries will be provided for supported operating systems.

Love where this project is going but as stated in the readme it's not quite ready yet. Can we have an issue to track when Alacritty is going to be considered Alpha? That way people (me) can subscribe to a single issue that will be updated when Alacritty is ready for alpha. Could be this issue. I suggest locking it to prevent noise.

Cheers!

**Comment by jwilm** [comment]
Hey @twe4ked, thanks for filing the issue!

I think it's fair to say it's reached an alpha level of quality. We've solved most of the stability and _urgent_ correctness issues filed since launch. There's still a way to go, but I think pre-alpha is unnecessarily conservative at this point.

That said, there's still bugs, and it's missing many features. It's reached a level though where many are using as a daily driver.

**Comment by twe4ked** [comment]
Oh cool, I guess this issue has served it's place! I'll give it another go. Thanks @jwilm :)

I'll leave this open as it's tracking the README change now.
