### ISSUE TITLE
Keystrokes dropped after nohup

### ISSUE THREAD

**Issue by brycefisher** [jwilm/alacritty#638]
## Steps to repro:

 1. Open alacritty
 2. `nohup $(ssh -L <remote IP:remote port>:<local IP:local Port>) &`
 3. Roughly half of all keystrokes are lost 

## Expected behavior:

all keystrokes would be handled by the terminal.

## Additonal Info:

 * OSX 10.12.4
 * Commit: b4a839aee9784a2d281be1bec87ac6f2ae4a79f0
 * rustc --version: rustc 1.18.0 (03fc9d622 2017-06-06)

**Comment by jwilm** [comment]
Getting an error with your SSH command `Bad local forwarding specification ':'`

**Comment by brycefisher** [comment]
@jwilm my bad! formatting error. The `<` and `>` were being silently hidden in my code sample. Can you try again? Thanks for the prompt investigation!!!

**Comment by jwilm** [comment]
What's the expected behavior with this command? Seems like you're want to substitute the output of your ssh command as arguments to nohup. Is this really the command you're having trouble with?

From what I understand, the best way to achieve a "background tunnel" is actually to use flags on `ssh`. Specifically, `-f` will background it until the command finishes, and this can be combined with `-N` to say "there's no command, just keep running".

**Comment by jwilm** [comment]
Anyway, I wasn't able to repro this.

**Comment by brycefisher** [comment]
Ah, yes! you're right, I want to `ssh -f ...` not `nohup $(ssh ...)`. Thanks!!
