### ISSUE TITLE
Make shader file path user configurable

### ISSUE THREAD

**Issue by ghost** [jwilm/alacritty#703]
Feel free to reject this if deemed unnecessary; 
I want to do some messing with shaders so it would be nice to be able to set the file path for the glsl shaders. 

In my case, specifically because NixOS makes packages immutable, and I would have to rebuild for every trivial change.

**Comment by chrisduerr** [comment]
I'm not opposed to implementing this and it seems like something which should be quite simple to support, but since the author of this issue doesn't seem to be around anymore, I'm going to close it for now.

If someone else is interested in this feature, or might even want to implement it (it should be trivial), feel free to comment here and I'll re-open the issue.
