### ISSUE TITLE
The code lacks documentation

### ISSUE THREAD

**Issue by vityafx** [jwilm/alacritty#707]
The code has no useful documentation in a lot of places. I have a lot of desire to participate in it, I have a lot of good ideas I would like to propose and implement by myself, but it is very difficult to understand the code. I would treat it as priority task because new developer must spend a lot of time to understand how the project works.

Also, I would suggest to write a separate developer documentation.

**Comment by myklv** [comment]
Code documentation often hurts more than it helps. Although I would agree documentation for external interfaces would be helpful.

**Comment by chrisduerr** [comment]
As someone who was a bit late to the party I have to say that I didn't really find the code poorly documented at all. Of course documentation could always be better, but I believe (especially since I've been part of it), documenation has been added whenever relevant changes have been made.

If anyone is interested in helping out and getting started, I would strongly recommend to just join the irc #alacritty on freenode or just open an issue. If there are any specific issues with understanding certain parts of the code, it's probably easiest to just explain them personally, and maybe the first little contribution can be adding the results of the discussion as documentation if the current documentation was lacking. :)

I can't speak for anyone else but I'm always ready to help with mentoring issues, it sometimes might just take a day or two until I've got the time to respond. So don't be afraid to open issues/ask questions in IRC!
