### ISSUE TITLE
Cursor flickering in Neovim

### ISSUE THREAD

**Issue by asilvadesigns** [jwilm/alacritty#711]
Hopefully this makes sense. But I've noticed the cursor flickers, especially when opening the completion menu, either for omni-complete or another completion plugin such as deoplete, youcompleteme, or nvim-completion-manager. 

Within tmux, it gets really bad, especially when entering visual line selection, the cursor visibly jumps to the end of the line, before returning to it's initial position when the visual line selection was invoked via hotkey.

These observations are constant:
- In Alacritty, In Neovim, no Tmux, there is minimal flicker.
- In Alacritty, In Neovim, in Tmux, much flickering, very noticeable.
- In iTerm, In Neovim, no flickering at all using tmux or not.

Is anyone else experiencing this?

**Comment by mhartington** [comment]
Im not seeing the cursor flicker, but a little bit of flickering from the completion menu, which is to be expected and is noted in deoplete.
![completion](https://user-images.githubusercontent.com/2835826/28999351-5c28e8aa-7a11-11e7-9289-f32cbb3c6cd7.gif)

**Comment by DarkDefender** [comment]
Flickering where the cursor jumps around when moving it, is a know problem. It is not alacritty specific.
There are a few pull requests like https://github.com/neovim/neovim/pull/6366 that tries to fix it. However the problem lies in that neovim (an vim) does not properly wait for the screen to be redrawn before sending a screen update.

This seems to be a tricky problem to solve as there doesn't seem to be a easy way to solve this.

**Comment by asilvadesigns** [comment]
Ah, word. Thanks for the link, closing!
