### ISSUE TITLE
Alacritty stopped working / does not start anymore

### ISSUE THREAD

**Issue by n0ah01** [jwilm/alacritty#732]
Hello all

I was trying to change the icon of Alacritty to the [official bash logo](https://github.com/odb/official-bash-logo) and when I wanted to start Alacritty, nothing happens. When I try to start it from Gnome Terminal i get this message:

`thread 'main' panicked at 'XOpenIM failed', /home/n0_ah/.cargo/git/checkouts/winit-5993d63686bf7f83/cc89d56/src/platform/linux/x11/mod.rs:680
note: Run with `RUST_BACKTRACE=1` for a backtrace.`

I reversed anything I've done for the icon and also build Alacritty from source without any luck.

I'm runing Ubuntu Gnome 17.04 and using the current version.
I'm sure it is something simple and easy to fix, but im to stupid to find anything...

Thank you in advance and thanks for such a great app! (it realy sucks to be back on Gnome Terminal...)

**Comment by jrupac** [comment]
I saw the same problem and realized that it was due to 4c4c2f5f5c81e6efb580e50ea993606160809469 (see #658). In my case, I was able to resolve it by starting up an input method (fcitx in my case) which I realized I wasn't running (I don't use CJK characters).

However, given that I don't get this error for any other program on my machine, is it expected that users should be using an input method framework always?

**Comment by quininer** [comment]
This seems to be due to the use of X11 does not support the locale caused, should fix it in winit.

**Comment by n0ah01** [comment]
Just started the Laptop up from sleepmode, works now.
@quininer yes it that could be the case, because i'm swiss...

Thanks for the help, even if it resolved itself

**Comment by nirfse** [comment]
I was unable to start recent versions of Alacritty on Ubuntu 17.04 for quite some weeks due to the same issue. I do also have several locales. @jrupac 's suggestion to run `fcitx` helped, thanks! Is there a reported issue/fix in `winit` repo to make sure others won't encounter the same problem in future?

**Comment by addobandre** [comment]
Also running into this in elementary OS 0.4.1 (based off Ubuntu 16.04.2 LTS) with i3. Starting the IBus daemon seems to also solve the issue. Maybe this should be added to the FAQ, or even better get a more descriptive error message (if possible)?
