### ISSUE TITLE
Invoking Paste/PasteSelection commands in editor (vim, nano) mangles pasted text with existing text

### ISSUE THREAD

**Issue by ronjouch** [jwilm/alacritty#733]
A screencast comparing gnome-terminal (left) to alacritty (right) will do better than words:

![alacritty-paste-in-editor-inserts](https://user-images.githubusercontent.com/522085/29365327-90b114c0-8264-11e7-9948-abfe3bc64387.gif)

The key_binding I invoked is visible on the screencast, it is:

```
- { key: V,        mods: Control|Shift,    action: Paste               }
```
... and I tried `PasteSelection`, with the same results. Am I doing something wrong or is it a bug?

This is alacritty master @ 4e9b1c590e8b0990f5f43fa9d7c53a31a92840a8 vs. gnome-terminal 3.18.3, no tmux, under Ubuntu 16.04.3 LTS.

**Comment by maximbaz** [comment]
Interesting bug, I wondered why I haven't seen it before, apparently I can reproduce it in `nano`, but not in `vi`, `vim` or `nvim`. Curious why...

**Comment by PSSGCSim** [comment]
I did some testing and if you have `\n` you get smashed lines, `\r\n` you get doubled lines, `\r` you get correct lines.

Demonstration
[![thumbnail](https://i9.ytimg.com/vi/b7vCdwta0Zo/default.jpg?sqp=CKDr5c8F&rs=AOn4CLASaFp_WmXuGwTk6VAL7SIbP9daRw)](https://youtu.be/b7vCdwta0Zo)

Not sure whether this info helps though.

**Comment by grinapo** [comment]
Same goes for other curses editors like _joe_. It also results linefeeds to be eaten, so multiple lines become One (like a coherent group of superheroes ;-)).

**Comment by grinapo** [comment]
On a brief observation what I see is that alacritty inserts **\n** within the paste buffer while xterm inserts **\r** there. I have the feeling that CR and LF is mixed up on pasting (both reading and writing side, possibly).

**Comment by giorgiga** [comment]
When pasting a single `\n`, `nano` behaves as if `^J` or `F4` (justify paragraph) had been pressed:

Before pasting:
<img width="420" alt="1" src="https://user-images.githubusercontent.com/471835/34537063-8286e39e-f0c7-11e7-84bc-e8eaac1167ba.png">

After pasting:
<img width="420" alt="2" src="https://user-images.githubusercontent.com/471835/34536915-0631fa86-f0c7-11e7-83d3-0f99f5a6a82f.png">

Pasting `before\nafter` seems to give the same results as typing `before<^J>after`:

<img width="420" alt="3" src="https://user-images.githubusercontent.com/471835/34537091-96b8bfb8-f0c7-11e7-94d2-7680e3d14b83.png">

**Comment by giorgiga** [comment]
Apparently, non-bracketed pasting *is* the issue here.

When the "enter" key is hit, a `CR` (`^M`) is generated (see http://invisible-island.net/xterm/ctlseqs/ctlseqs.html).

In non-bracketed mode, `LF`s (`^J`) in pasted data have to be replaced with `CR`s in order to simulate keypresses.

In non-bracketed mode, applications have no way of distinguishing if data comes from the keyboard or the clipboard, so it seems sensible that a terminal must simulate keypresses.

To me it is not 100% clear to what extent a terminal is supposed to do that (ie: whether octets corresponding to other control characters or maybe to bytes with the high bit set should be processed). Maybe data bytes should be interleaved with `^V`s? Or maybe bracketed mode is how pasting is supposed to work and applications that don't use it are at fault?

Anyhow, replacing `\r` with `\n` seems an improvement and it is what [jediterm](https://github.com/JetBrains/jediterm) does.
