### ISSUE TITLE
Can't type russian charts

### ISSUE THREAD

**Issue by Snuff** [jwilm/alacritty#793]
Which operating system does the issue occur on?
MacOs HighSierra

When I type in Alacrity in Russian it display Unicode bytes instead of Russian characters, however if I ask system to echo these bytes, it displays right characters, take a look below:

```
@MacB ➜  ~ rvm:(system)  echo '<00d0><009f><00d1><0080><00d0><00b8><00d0><00b2><00d0><00b5><00d1><0082>'
Привет
```

English works fine. Could someone help me?

**Comment by jwilm** [comment]
Does this happen in other terminals? Is your locale set properly when the shell is launched?

**Comment by Snuff** [comment]
Apple Terminal works well.

```
@MacB ➜  ~ rvm:(system)  echo $LANG
en_RU.UTF-8
@MacB ➜  ~ rvm:(system)  echo $LC_CTYPE
en_RU.UTF-8
```
Just changed locale to en_US and it helped, do you have any thoughts?

```
MacB ➜  ~ rvm:(system)  export LANG=en_US.UTF-8
@MacB ➜  ~ rvm:(system)  export LC_CTYPE=en_US.UTF-8
```

**Comment by jwilm** [comment]
Typically when the shell shows UTF-8 codepoints in byte form as you described, it's very intentional. Notice how when you delete one of these <byte> characters, it's actually clearing several grid cells. This indicates the shell knows it's only one codepoint and is intentionally showing you the bytes. This would not be the case though if it were instead Alacritty rendering the codepoints incorrectly.

I don't know exactly the reason for this, but as you've found out, the locale influences that behavior. The fact that it seems to work ok in Terminal.app but not Alacritty suggests a configuration or environmental difference between them.

**Comment by bikbah** [comment]
macOS High Sierra 10.13.2

I have the same problem - I cannot type any cyrillic letters 
```
-->Hello
bash: Hello: command not found
-->
-->:\237\321\320\320\320\321

-->locale
LANG="ru_RU.UTF-8"
LC_COLLATE="ru_RU.UTF-8"
LC_CTYPE="ru_RU.UTF-8"
LC_MESSAGES="ru_RU.UTF-8"
LC_MONETARY="ru_RU.UTF-8"
LC_NUMERIC="ru_RU.UTF-8"
LC_TIME="ru_RU.UTF-8"
LC_ALL=
```

`en_US.UTF-8` did not solve problem

**Comment by jwilm** [comment]
@bikbah does this work in _Terminal.app_? If so, please post `locale` output from there as well.

**Comment by bikbah** [comment]
Terminal.app (iTerm2 as well):
```
-->:~ $ locale
LANG="ru_RU.UTF-8"
LC_COLLATE="ru_RU.UTF-8"
LC_CTYPE="ru_RU.UTF-8"
LC_MESSAGES="ru_RU.UTF-8"
LC_MONETARY="ru_RU.UTF-8"
LC_NUMERIC="ru_RU.UTF-8"
LC_TIME="ru_RU.UTF-8"
LC_ALL=
```

Alacritty:
```
-->locale
LANG="en_RU.UTF-8"
LC_COLLATE="C"
LC_CTYPE="C"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

setting `ru_RU.UTF-8` env variables in `~/.bashrc` (which shows `locale` output as in Terminal.app) doesn`t help

**Comment by bikbah** [comment]
and yes, iTerm2 and Terminal.app work well with ru_RU.UTF-8
