### ISSUE TITLE
Right click doesn't work.

### ISSUE THREAD

**Issue by refacto** [jwilm/alacritty#839]
Which operating system does the issue occur on? Gentoo.

If on linux, are you using X11 or Wayland? Both.

I noticed that I can't right click to play songs in ncmpcpp. This works fine in st, and any other terminal emulator I've tried.

**Comment by refacto** [comment]
Hmm. This doesn't seem to be implemented at all in `input.rs`, I might have a stab at it.

**Comment by chrisduerr** [comment]
I believe this should work on the latest master @refacto. If it doesn't, please let me know and I will re-open this issue.

**Comment by mazulo** [comment]
I'm having the exact same problem. Using macos Mojave 10.14.6. Installed alacritty by cloning/building it.

**Comment by chrisduerr** [comment]
@mazulo Which terminfo do you use? And can you confirm the actual hash with `alacritty --version`?

**Comment by mazulo** [comment]
@chrisduerr I'm using the same terminfo as the install says [here](https://github.com/jwilm/alacritty/blob/master/INSTALL.md#terminfo). About the version: the command `alacritty --version` didn't work when I tried, I think because I installed it by cloning/building. The first time I installed with `brew cask install alacritty` but I removed because I thought it would worth a try to install directly from a build.

**Comment by chrisduerr** [comment]
You probably need to run `/Applications/Alacritty.app/Contents/MacOS/alacritty --version`, since macOS doesn't expose the application it installs in the path.

**Comment by mazulo** [comment]
@chrisduerr yep, it worked!
```bash
➜ /Applications/Alacritty.app/Contents/MacOS/alacritty --version
alacritty 0.3.3 (561063b)
```

**Comment by chrisduerr** [comment]
Ah, nice, so that confirms that you're running a pretty recent version. Would you mind testing if things work with `TERM=xterm-256color`?

If it doesn't, we can either open a separate issue or re-open this one.

**Comment by mazulo** [comment]
Just tested:

```bash
TERM=xterm-256color /Applications/Alacritty.app/Contents/MacOS/alacritty
Created log file at "/var/folders/ky/1mwq65xx6cj_tygdw6tn93400000gn/T/Alacritty-79561.log"
[2019-11-18 19:18] [WARN] Config scrolling.faux_multiplier is deprecated; the alternate scroll escape can now be used to disable it and `scrolling.multiplier` controls the number of scrolled lines
```

Still right click doesn't work. Also (not sure if it's expected) the menu at the top (the `Alacritty` in the screenshot below) that usually shows some options, doesn't show anything when I click:
<img width="318" alt="Screen Shot 2019-11-18 at 7 19 32 PM" src="https://user-images.githubusercontent.com/1661112/69099063-a02d6f80-0a38-11ea-8789-ba0a5db4ec5a.png">

**Comment by kchibisov** [comment]
@mazulo What are you expecting on right click to happen? Are you about `ncmpcpp` option to play song? In this case I can't repro this issue on the latest master.

**Comment by mazulo** [comment]
Sometimes yes, but I'm not a heavy `ncmcpp` user. I'm more interested in some options that I usually see in other terminals, like: clear buffer, copy/paste (to say the most common ones). If `alacritty` doesn't have this features and it is expected that the right click does nothing, maybe it was a misunderstood on my side.

@kchibisov what happens when you open `alacritty` and right click on it?

**Comment by kchibisov** [comment]
@mazulo I guess, you've misunderstood the issue. Alacritty never had a menu on right click, and I guess never will (due to lack of usefulness and complexity for an opengl terminal). The original issue is about terminal's mouse mode and sending proper escapes to an app.

>@kchibisov what happens when you open Alacritty and right click on it?

So, answering your question. Right click does nothing for me, when I'm clicking on alacritty, and it always was like that, unless you're in a terminals mouse mode, then it'll send an escape sequence to a running app.

We have key bindings for all actions you've mentioned though and you can bind mouse buttons to do specific actions, so I don't see how menu of 2/3 (copy/paste and clear) entries would help.

**Comment by chrisduerr** [comment]
Ctrl+L/`clear` will clear the screen, copy/paste is done with command+c/v. Should all work out of the box.

**Comment by mazulo** [comment]
That makes total sense! Sorry for the false alarm and thank you @chrisduerr and @kchibisov for the help and patience 😄
