### ISSUE TITLE
Font Rendering - Blurry letters

### ISSUE THREAD

**Issue by asilvadesigns** [jwilm/alacritty#844]
**Which operating system does the issue occur on?**
macOS

As reported by @weslly in https://github.com/jwilm/alacritty/commit/e8f5ab89ee0b6810649f76c6dbd15ee1105554e8.

![screen shot 2017-10-16 at 1 23 45 pm](https://user-images.githubusercontent.com/7071307/31625877-acf97186-b275-11e7-9000-1074a9012dd6.png)
![screen shot 2017-10-16 at 12 00 17 pm](https://user-images.githubusercontent.com/7071307/31625878-ad0889be-b275-11e7-9b5e-5efe36ad7a12.png)

**Comment by weslly** [comment]
8a0b1d9 looks and works fine for me, the bug was probably introduced at e8f5ab8

![image](https://user-images.githubusercontent.com/107672/31620467-1683a856-b276-11e7-9098-bb5653efa4dd.png)
![image](https://user-images.githubusercontent.com/107672/31620515-329ae3e2-b276-11e7-8c82-4c9beeb298aa.png)
![image](https://user-images.githubusercontent.com/107672/31620423-fb377c58-b275-11e7-8633-80653b12e2fb.png)

**Comment by asilvadesigns** [comment]
@weslly yups. works on https://github.com/jwilm/alacritty/commit/8a0b1d9c3f5a9ddb98469a340bbcd06374d4a24e.

**Comment by jwilm** [comment]
I was able to verify this isn't an issue with texture reuse. There must be some book keeping missing in e8f5ab8 which was previously handled.

**Comment by jwilm** [comment]
Should be fixed by #845; would you folks mind testing?

**Comment by weslly** [comment]
@jwilm #845 works for me, seems to be fixed now 👍

**Comment by asilvadesigns** [comment]
👍
