### ISSUE TITLE
Tmux not found, even though it's installed

### ISSUE THREAD

**Issue by magicalbanana** [jwilm/alacritty#870]
Which operating system does the issue occur on?
OSX High Sierra 10.13 (17A405)

So when opening alacritty, I get this error:
```
zsh tmux plugin: tmux not found. Please install tmux before using this plugin.
```
But I can still use tmux though.

**Comment by NickeZ** [comment]
Seems to be an  issue with a plugin to zsh and not alacritty. https://github.com/robbyrussell/oh-my-zsh/issues/2583

**Comment by jwilm** [comment]
I agree with @NickeZ. Feel free to reopen if you determine otherwise, @magicalbanana.

**Comment by a-eid** [comment]
having the same issue ohmyzsh/ohmyzsh#2583 did not help.

**Comment by Queopius** [comment]
i have the same problem.

**Comment by laudai** [comment]
@a-eid I search this issue from the Internet, and I didn't use this software at all. 


At the begin, I can' fix this issue by add the path, either.

After I deep dive on this issue as [ Marc Cornellà ](https://github.com/mcornella) point out in issue [#2583](https://github.com/ohmyzsh/ohmyzsh/issues/2583) . This issue was raised by the oh-my-zsh plugin named [tmux](https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/tmux/tmux.plugin.zsh). So as below code, we can see that the plugin will check the tmux when it load. So you need to add the path which tmux located before we source the `oh-my-zsh.sh`
```bash
if ! (( $+commands[tmux] )); then
  print "zsh tmux plugin: tmux not found. Please install tmux before using this plugin." >&2
  return 1
fi
```

So the suggestion is that
1. export and add the tmux located path to the PATH variable
2. make sure the tmux path was load before you source the `oh-my-zsh.sh`

Environment:
zsh 5.9 (x86_64-apple-darwin22.0)
Oh-My-ZSH with Tmux plugin verison: commit [f4dc8c5](https://github.com/ohmyzsh/ohmyzsh/commit/f4dc8c5be365668810783ced01a86ff8f251bfd7)

**Comment by farmer00317558** [comment]
If you install tmux via brew.
Place `eval "$(/opt/homebrew/bin/brew shellenv)"` in `~/.zprofile` instead of `~/.zshrc`

**Comment by nandanito** [comment]
@farmer00317558 Thanks! Solved issue for me as well.

The startup files loading order for zsh seems to be an issue as described [here](https://shreevatsa.wordpress.com/2008/03/30/zshbash-startup-files-loading-order-bashrc-zshrc-etc/).


```
+----------------+-----------+-----------+------+
|                |Interactive|Interactive|Script|
|                |login      |non-login  |      |
+----------------+-----------+-----------+------+
|/etc/zshenv     |    A      |    A      |  A   |
+----------------+-----------+-----------+------+
|~/.zshenv       |    B      |    B      |  B   |
+----------------+-----------+-----------+------+
|/etc/zprofile   |    C      |           |      |
+----------------+-----------+-----------+------+
|~/.zprofile     |    D      |           |      |
+----------------+-----------+-----------+------+
|/etc/zshrc      |    E      |    C      |      |
+----------------+-----------+-----------+------+
|~/.zshrc        |    F      |    D      |      |
+----------------+-----------+-----------+------+
|/etc/zlogin     |    G      |           |      |
+----------------+-----------+-----------+------+
|~/.zlogin       |    H      |           |      |
+----------------+-----------+-----------+------+
|                |           |           |      |
+----------------+-----------+-----------+------+
|                |           |           |      |
+----------------+-----------+-----------+------+
|~/.zlogout      |    I      |           |      |
+----------------+-----------+-----------+------+
|/etc/zlogout    |    J      |           |      |
+----------------+-----------+-----------+------+
``` 

*(Execution order alphabetical)
