### ISSUE TITLE
Scrolling broken in `ed` (OS X 10.11.6)

### ISSUE THREAD

**Issue by sterpe** [jwilm/alacritty#90]
Steps to reproduce:

- `ed [FILE]`
- `,n`
- Scroll either up or down with the trackpad

Result: See photo attached
Expected: The terminal scrolls up and down correctly

<img width="606" alt="screen shot 2017-01-06 at 11 59 30 am" src="https://cloud.githubusercontent.com/assets/678398/21731212/247407fa-d408-11e6-949e-ae34bc72606a.png">

Related bug: scrolling in general

Steps to reproduce:

- `cat [LONGFILE]`
- Scroll up with trackpad

<img width="610" alt="screen shot 2017-01-06 at 12 04 01 pm" src="https://cloud.githubusercontent.com/assets/678398/21731231/3b9770de-d408-11e6-826a-128790cab298.png">

**Comment by d3rrial** [comment]
alacritty doesn't have mousewheel support as far as I know. this should happen everywhere

**Comment by sterpe** [comment]
Is that a feature or a bug ;)

**Comment by d3rrial** [comment]
Input is pretty much completely broken in any but the most basic use cases. Non-us keyboard layouts don't work, key-codes are misinterpreted (Shift+Up for example is interpreted as "A"), etc., etc.

Some of this is because of glutin, some of it because the developer probably developed with too narrow parameters. We should see everything working sooner or later. I'd call it a bug, tho ;)

**Comment by sterpe** [comment]
Haha, wasn't sure if it was like a retro thing.  Do 80 cols and stop using the mouse, just pipe everything to `less` or `more`.  And use `ed` too.

**Comment by jwilm** [comment]
We've fixed some issues with scrolling; mind trying this out with a recent version of Alacritty?

**Comment by chrisduerr** [comment]
This issue has been resolved for a while now. Scrolling should work in `ed` and other terminal applications.
