### ISSUE TITLE
Alacritty crashes when scrolling through Unicode inside Neovim

### ISSUE THREAD

**Issue by rafi** [jwilm/alacritty#914]
Reproduce:
1. Run Alacritty and tmux 2.6
2. Download https://www.fsd.it/pragmatapro/All_chars.txt
3. Run Neovim and open All_chars.txt
4. Scroll through document
5. Alacritty crashes (see [crash dump](https://gist.github.com/rafi/b5c3367b9093ccb52ce3bcd7445c0f70))

[Using macOS High Sierra, tmux 2.6, latest greatest Neovim & Alacritty]

**Comment by Aaron1011** [comment]
I suspect that this is the same problem as https://github.com/jwilm/alacritty/issues/842#issuecomment-344752082, where a certain glyph is always unable to fit into an `Atlas`

**Comment by chrisduerr** [comment]
Would be interesting to know if you can repro this with #949. I wasn't able to make my instance crash by scrolling through the file, probably because I have a smaller number of those glyphs. And a smaller number of glyphs would mean that my atlas has more space in it. I'd assume that for you the atlas fills up with all available glyphs and then crashes. This should be fixed with my PR.

**Comment by rafi** [comment]
I can no longer reproduce this, thanks @chrisduerr.
