### ISSUE TITLE
Complete implementation of scrollback

### ISSUE THREAD

**Issue by shreve** [jwilm/alacritty#923]
Scrollback (#657) is nearly complete, but does still require some heavy lifting to get it merged into master.

Bountysource won't let me put a bounty on a pull request, so I've made this issue. 

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=52061265)](https://www.bountysource.com/issues/52061265-complete-implementation-of-scrollback?utm_source=52061265&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by buster** [comment]
👍 Added 15$. I really hope someone get's this merged, i don't need or want tmux in my local terminal.

**Comment by lancelet** [comment]
+$15 from me. I've been using alacritty for a while and would like to have scrollback too.

**Comment by ght** [comment]
As a workaround you could use a terminal multiplexer like [tmux](/tmux/tmux), which supports scrollback (you might need to `set-option -g mouse on`) and has several other advantages.

**Comment by buster** [comment]
I use that workaround and it's a major hazzle. I see the point of tmux and screen on remote and plain text systems but not at all in my desktop environment. I'm fine when other people like to use tmux all day but please don't try to sell it to me as "advantage". For you it may be, for me it is not. 

I'm aware that alacritty was supposed to be used with tmux from the beginning. I'd like to use it without tmux and put some money behind it. That's how painful using tmux is for me. I'm paying money whereas i could just use one of the gazillion other shells.

Still, i hope  someone will find the time to do that :)

**Comment by unphased** [comment]
I can't live without tmux! @buster, could you share some of your reasons why you prefer not to use tmux? I'm just really curious!

**Comment by lord-re** [comment]
For me tmux is excellent throught ssh, but i locally i prefer opening multiple terminals and arranging easily with my windows manager rather than learning how to arrange them in tmux. 
I also don't use tabs in my web browser for the exact same reason : i prefer managing them through the wm rather than learning how to move them in the browser… 
Idem for (neo)vi(m), i don't use multiple buffers but multiple terminals with multiple text editor…

**Comment by unphased** [comment]
vim -> windows/panes in one instance lets your search highlights work in all of the open files, copy & paste across them, etc. Also reduce process ram usage overhead.

tmux -> windows/panes are part of your workspace. your workspace gains flexibility of client/server, so I can juggle/upgrade my terminal emulator program without affecting my workspace, rather than the workspace itself being tied to ephemeral program state such as window positions or client machine tiling wm state. This leads to my workspace being persistent at the operating system level. Note my tmux server session survives even logging out of my user! Not to mention, all of these properties hold over SSH, so I routinely have hundreds of days persistent tmux sessions on my various linux servers and routinely connect to them from my windows rig, my many MacBooks, and my iPhone.

**Comment by shreve** [comment]
@unphased I use i3wm, which is a much better overall experience compared to just using tmux inside a terminal.

**Comment by unphased** [comment]
That’s great to hear! I’ve not found a Linux window manager I could stomach yet and i3 is on my short list of things to try.

**Comment by shreve** [comment]
@jwilm Sorry if this turns out to be a dumb hassle, but this bounty is yours for the taking.

**Comment by jwilm** [comment]
@shreve my hope was that the bounty could be granted to @neon64 who did all of the initial pathfinding work for scrollback in #657. Is that possible?

**Comment by shreve** [comment]
Anyone can go to the page and claim they earned it. If I see a claim from them, I'll approve it.

**Comment by l29ah** [comment]
Can i scroll it with keyboard?

**Comment by chrisduerr** [comment]
@l29ah Yes, yes you can. Go take a look at the configuration file to see how:
https://github.com/jwilm/alacritty/blob/master/alacritty.yml#L345-L358

It's currently not possible to scroll a specific amount of lines, only page up/down. If you want something beyond what is already possible, please open a feature request.

**Comment by neon64** [comment]
I've put in a claim. Is it possible for the bounty to be split amongst the contributors to the actual patch, though?

**Comment by chrisduerr** [comment]
@neon64 Since @jwilm did most of the work with the second scrollback implementation and he decided that it should be granted to you, I think it's fine.

However if you still want to give part of the bounty to other contributors, you could put it on other issues, I think bountysource only charges 10% on withdrawal.

If you don't care about Alacritty, you could of course also give it to anyone else or keep it, but these seem like the best options if you do not wish to do that.

I don't think it's possible to partially claim a bounty based on looking at the page myself. However I'm not super familiar with bountysource so I might be wrong there.
