### ISSUE TITLE
Prevent decreasing font size beyond the minimal value

### ISSUE THREAD

**Issue by maximbaz** [jwilm/alacritty#955]
Linux, X11.
Extracted from https://github.com/jwilm/alacritty/pull/949#issuecomment-353494090

-----

I played with holding <kbd>Ctrl +/-</kbd> and found a silly issue, posting just in case you can immediately think of a simple fix, otherwise I guess it's not worth looking into:

- Hold <kbd>Ctrl +</kbd>. The value reaches its maximum value (274 in my case) and stays there, pressing <kbd>Ctrl +</kbd> further has no effect. Pressing <kbd>Ctrl -</kbd> once reduces font size to 272.
- Now hold <kbd>Ctrl -</kbd>. The value reaches its minimum value (2 in my case), but further presses of <kbd>Ctrl -</kbd> change the value to 2, again and again. If I press <kbd>Ctrl -</kbd> 10 times after I already reached the minimal value of 2, then pressing <kbd>Ctrl +</kbd> once will have no effect - the font size will stay at 2. I have to press <kbd>Ctrl +</kbd> 10 times to compensate for my earlier actions, before further presses of <kbd>Ctrl +</kbd> begin to actually increase the font.

**Comment by lord-re** [comment]
I can confirm this too.

**Comment by Aaron1011** [comment]
I don't believe that #949 fixed this issue:

> The issue is with this call to Atlas#insert. If the font size is increased until it is too big to fit into a single atlas, Atlas#insert will always return an Err. This leads to load_glyph recursing infinitely, since inserting the glyph into an Atlas will never succeed.

**Comment by jwilm** [comment]
Thanks @Aaron1011. I reopened the other issue.

**Comment by chrisduerr** [comment]
@Aaron1011 It does actually fix the issue tho. The issue was never that the glyph was too big for a single atlas. Have you tested it out yourself? With #949 the crash doesn't happen anymore when increasing font size. The problem was that the atlas never changed, so there was never a new atlas that was created.

In theory you could run into problems with glyphs being too big for a single atlas, but I don't think that's even possible to happen because of gpu restrictions. I've played around with it a bit myself and the max font size goes up to a limit and then just stops. The worst thing I was able to reconstruct was that a few glyphs didn't show up anymore because my gpu driver was spouting errors about textures being too big. I don't think fitting a single glyph into an empty atlas has ever been the actual issue. Or can you still reproduce the issue after #949.

I did initially play with changing the recursion strategy, but it turned out for me that after I fixed the obvious problem, all the other issues were resolved too.
