### ISSUE TITLE
Zombie processes from key_bindings commands execution

### ISSUE THREAD

**Issue by monsterzz** [jwilm/alacritty#973]
Which operating system does the issue occur on?
**OS X 10.12.6 (16G29)**

My alacritty.yml configuration contains such strange thing:

    key_bindings:
      - { key: LBracket, mods: Command|Shift, command: { program: "/usr/local/bin/tmux", args: ["prev"] } }
      - { key: RBracket, mods: Command|Shift, command: { program: "/usr/local/bin/tmux", args: ["next"] } }

Each time I trigger command execution with Cmd+Shift+[ or ] I'm getting more and more zombie processes of tmux in my system. Unfortunately I have very small ulimit on processes (1000 hard) and after some time I'm hitting fork error in all shell windows. Re-launching alacritty works (all processes are collected by system on alacritty exit). Seems that alacritty doesn't wait for spawned processes.

If you need any additional information or debug logs, feel free to ping me here.

Thanks.

**Comment by yangliping** [comment]
I still have this issue. macOS High Sierra 10.13.4 (17E199) and latest alacritty from github.

**Comment by chrisduerr** [comment]
The fix from @jwilm was to run the process as a daemon, it might be possible that this is not supported on MacOS or has a different syntax.

Instead of setting up the command as a daemon, it should be possible to `wait` for the child, which will read the exit status and free the zombie process for reaping.
The method is documented here: https://doc.rust-lang.org/std/process/struct.Child.html#method.wait

The issue with this would be that alacritty has to keep track of the process and probably spawn a new thread for `wait`ing on the output. But if that works and daemon mode does not, it's probably an improvement.

**Comment by alisnic** [comment]
Not really a solution to the issue, but this can be worked around. Here's a small snippet from my config:

```
  - { key: Key1,     mods: Command,       chars: "\x01\x31" }
```

This makes pressing `Cmd-1` send `C-a 1`, which my tmux recognises (C-a is my tmux prefix). You can rewrite all your tmux bindings in alacritty config to send raw char data instead of invoking tmux processes.

To see character codes, you can use `xxd`:

```
$ xxd -psd
^A1
01310a
```

**Comment by chrisduerr** [comment]
I know that @zacps has added ignored the daemon mode in his Windows PR (only when built on Windows). So currently there's the Windows version (I think it's just spawned without awaiting), the Linux version where it's spawned as daemon and it works and the MacOS version where it's spawned as daemon and does not work.

As far as I know the `wait` call should be present on all platforms (correct me if I'm wrong please), so that might still be a good option. Alternatively it's probably possible to orphan the spawned process to allow init to `wait` for the process to exit.
